Resource
-

In [1]:
!pip install wandb==0.22.0

Collecting wandb==0.22.0
  Downloading wandb-0.22.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: click>=8.0.1 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (8.3.1)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (3.1.46)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (26.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (4.9.4)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (5.29.6)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (2.12.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (6.0.3)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (2.32.4)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (2.57.0)
Requirement already satisfied: typing-extensions<5,>=4.8 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (4.15.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb==0.22.0) (4.0.12)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb==0.22.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb==0.22.0) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb==0.22.0) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb==0.22.0) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb==0.22.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb==0.22.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb==0.22.0) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb==0.22.0) (5.0.3)
Downloading wandb-0.22.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.6/19.6 MB 27.1 MB/s eta 0:00:00
Installing collected packages: wandb
  Attempting uninstall: wandb
    Found existing installation: wandb 0.25.1
    Uninstalling wandb-0.25.1:
      Successfully uninstalled wandb-0.25.1
Successfully installed wandb-0.22.0

### Install kaleido for export pdf

In [2]:
!pip install plotly==6.4.0
!pip install kaleido==1.2.0
!pip install choreographer==1.2.1
!pip install pypdf
!apt update
!apt-get install libnss3 libatk-bridge2.0-0 libcups2 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libpango-1.0-0 libcairo2 libasound2

Collecting plotly==6.4.0
  Downloading plotly-6.4.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: narwhals>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from plotly==6.4.0) (2.18.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly==6.4.0) (26.0)
Downloading plotly-6.4.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 40.5 MB/s eta 0:00:00
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1
Successfully installed plotly-6.4.0
Collecting kaleido==1.2.0
  Downloading kaleido-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Collecting choreographer>=1.1.1 (from kaleido==1.2.0)
  Downloading choreographer-1.4.0-py3-none-any.whl.metadata (5.5 kB)
Collecting logistro>=1.0.8 (from kaleido==1.2.0)
  Downloading logistro-2.0.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: orjson>=3.10.15 in /usr/local/lib/python3.12/dist-packages (from kaleido==1.2.0) (3.11.8)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaleido==1.2.0) (26.0)
Collecting pytest-timeout>=2.4.0 (from kaleido==1.2.0)
  Downloading pytest_timeout-2.4.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: platformdirs>=4.3.6 in /usr/local/lib/python3.12/dist-packages (from choreographer>=1.1.1->kaleido==1.2.0) (4.9.4)
Requirement already satisfied: simplejson>=3.19.3 in /usr/local/lib/python3.12/dist-packages (from choreographer>=1.1.1->kaleido==1.2.0) (3.20.2)
Requirement already satisfied: pytest>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from pytest-timeout>=2.4.0->kaleido==1.2.0) (8.4.2)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido==1.2.0) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido==1.2.0) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido==1.2.0) (2.20.0)
Downloading kaleido-1.2.0-py3-none-any.whl (68 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 4.2 MB/s eta 0:00:00
Downloading choreographer-1.4.0-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.0/58.0 kB 6.8 MB/s eta 0:00:00
Downloading logistro-2.0.1-py3-none-any.whl (8.6 kB)
Downloading pytest_timeout-2.4.0-py3-none-any.whl (14 kB)
Installing collected packages: logistro, pytest-timeout, choreographer, kaleido
Successfully installed choreographer-1.4.0 kaleido-1.2.0 logistro-2.0.1 pytest-timeout-2.4.0
Collecting choreographer==1.2.1
  Downloading choreographer-1.2.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: logistro>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from choreographer==1.2.1) (2.0.1)
Requirement already satisfied: simplejson>=3.19.3 in /usr/local/lib/python3.12/dist-packages (from choreographer==1.2.1) (3.20.2)
Downloading choreographer-1.2.1-py3-none-any.whl (49 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 2.2 MB/s eta 0:00:00
Installing collected packages: choreographer
  Attempting uninstall: choreographer
    Found existing installation: choreographer 1.4.0
    Uninstalling choreographer-1.4.0:
      Successfully uninstalled choreographer-1.4.0
Successfully installed choreographer-1.2.1
Collecting pypdf
  Downloading pypdf-6.19.0-py3-none-any.whl.metadata (7.5 kB)
Downloading pypdf-6.19.0-py3-none-any.whl (395 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.5/395.5 kB 8.2 MB/s eta 0:00:00
Installing collected packages: pypdf
Successfully installed pypdf-6.19.0
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 https://cli.github.com/packages stable InRelease [3,917 B]
Get:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Err:3 https://cli.github.com/packages stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5612B36462313325
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:10 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [114 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [93.2 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,623 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [8,152 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,718 kB]
Get:15 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,254 kB]
Get:16 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [11.0 MB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.6 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [82.9 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [4,372 kB]
Get:20 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,321 kB]
Get:21 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [49.0 kB]
Get:22 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [84.6 kB]
Get:23 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,843 kB]
Fetched 43.2 MB in 6s (7,229 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
246 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://cli.github.com/packages stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5612B36462313325
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
W: Failed to fetch https://cli.github.com/packages/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5612B36462313325
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxdamage1 set to manually installed.
libxfixes3 is already the newest version (1:6.0.0-1).
libxfixes3 set to manually installed.
libxkbcommon0 is already the newest version (1.4.0-1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libcairo2 is already the newest version (1.16.0-5ubuntu2.1).
libcairo2 set to manually installed.
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpango-1.0-0 set to manually installed.
The following additional packages will be installed:
  at-spi2-core gsettings-desktop-schemas libasound2-data libatk1.0-0
  libatk1.0-data libatspi2.0-0 libegl-mesa0 libgl1-mesa-dri libglapi-mesa
  libglx-mesa0 libxtst6 session-migration
Suggested packages:
  libasound2-plugins alsa-utils cups-common
Recommended packages:
  alsa-ucm-conf alsa-topology-conf libgl1-amber-dri
The following NEW packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0 libatk1.0-0
  libatk1.0-data libatspi2.0-0 libxcomposite1 libxtst6 session-migration
The following packages will be upgraded:
  libasound2 libasound2-data libcups2 libegl-mesa0 libgbm1 libgl1-mesa-dri
  libglapi-mesa libglx-mesa0 libnss3
9 upgraded, 9 newly installed, 0 to remove and 237 not upgraded.
Need to get 11.5 MB of archives.
After this operation, 1,502 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libasound2 amd64 1.2.6.1-1ubuntu1.2 [391 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libasound2-data all 1.2.6.1-1ubuntu1.2 [19.3 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcups2 amd64 2.4.1op1-1ubuntu4.21 [266 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libegl-mesa0 amd64 23.2.1-1ubuntu3.1~22.04.4 [118 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgbm1 amd64 23.2.1-1ubuntu3.1~22.04.4 [33.7 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgl1-mesa-dri amd64 23.2.1-1ubuntu3.1~22.04.4 [8,860 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglx-mesa0 amd64 23.2.1-1ubuntu3.1~22.04.4 [158 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglapi-mesa amd64 23.2.1-1ubuntu3.1~22.04.4 [35.6 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libnss3 amd64 2:3.98-0ubuntu0.22.04.4 [1,347 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Fetched 11.5 MB in 1s (19.6 MB/s)
Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 118194 files and directories currently installed.)
Preparing to unpack .../00-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../01-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../02-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../03-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../04-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Preparing to unpack .../05-libasound2_1.2.6.1-1ubuntu1.2_amd64.deb ...
Unpacking libasound2:amd64 (1.2.6.1-1ubuntu1.2) over (1.2.6.1-1ubuntu1.1) ...
Preparing to unpack .../06-libasound2-data_1.2.6.1-1ubuntu1.2_all.deb ...
Unpacking libasound2-data (1.2.6.1-1ubuntu1.2) over (1.2.6.1-1ubuntu1.1) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../07-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../08-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../09-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Preparing to unpack .../10-libcups2_2.4.1op1-1ubuntu4.21_amd64.deb ...
Unpacking libcups2:amd64 (2.4.1op1-1ubuntu4.21) over (2.4.1op1-1ubuntu4.16) ...
Preparing to unpack .../11-libegl-mesa0_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libegl-mesa0:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../12-libgbm1_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libgbm1:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../13-libgl1-mesa-dri_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libgl1-mesa-dri:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../14-libglx-mesa0_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libglx-mesa0:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../15-libglapi-mesa_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libglapi-mesa:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../16-libnss3_2%3a3.98-0ubuntu0.22.04.4_amd64.deb ...
Unpacking libnss3:amd64 (2:3.98-0ubuntu0.22.04.4) over (2:3.98-0ubuntu0.22.04.3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../17-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libgbm1:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libnss3:amd64 (2:3.98-0ubuntu0.22.04.4) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libasound2-data (1.2.6.1-1ubuntu1.2) ...
Setting up libglapi-mesa:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up libcups2:amd64 (2.4.1op1-1ubuntu4.21) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up libasound2:amd64 (1.2.6.1-1ubuntu1.2) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up libgl1-mesa-dri:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Setting up libegl-mesa0:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up libglx-mesa0:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.9) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Setting up at-spi2-core (2.44.0-3) ...

In [3]:
import plotly.io as pio

pio.get_chrome()

PosixPath('/usr/local/lib/python3.12/dist-packages/choreographer/cli/browser_exe/chrome-linux64/chrome')

# Login

In [1]:
from google.colab import userdata
WANDB_KEY = userdata.get('WANDB_TOKEN')

In [2]:
import wandb
print(wandb.__version__)
wandb.login(key=WANDB_KEY)

/usr/local/lib/python3.12/dist-packages/pydantic/_internal/_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'repr' attribute with value False was provided to the `Field()` function, which has no effect in the context it was used. 'repr' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/pydantic/_internal/_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'frozen' attribute with value True was provided to the `Field()` function, which has no effect in the context it was used. 'frozen' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(

0.22.0

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: rofifpriyo (rofifpriyo-) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

# Parameter

In [3]:
import wandb
from wandb.apis.public import Api
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.subplots as ps
import plotly.graph_objects as go

ENTITY = wandb.apis.PublicApi().default_entity
PROJECT = "calibration-on-quantized-multilingual"

# 3x Run

## Real 3x Run

In [4]:
pd.options.mode.chained_assignment = None

def visualize_deliver_bar(eval_languages, runs, base_models, quantization_technique, bits, eval_dataset, custom_title="", vertical_spacing=0.1, horizontal_spacing=0.05, display_mean=True, compile=False, random_guess_score=0.25, embed_sinq=True, generate_until=False, strict_answer=False, write_pdf=""):
  language_sort = {
      # Flores Plus
      "eng_Latn": 0, "fra_Latn": 1, "hin_Deva": 2, "npi_Deva": 3, "tam_Taml": 6, "tel_Telu": 7, "ind_Latn": 8, "zsm_Latn": 9, "swh_Latn": 10, "yor_Latn": 11, "cmn_Hans": 12, "jpn_Jpan": 13, "kor_Hang": 14, "arb_Arab" : 15,\
      # Wikipedia
      "en": 0, "fr": 1, "hi": 2, "ne": 3, "ta": 6, "te": 7, "id": 8, "ms": 9, "sw": 10, "yo": 11, "zh": 12, "ja": 13, "ko": 14, "ar": 15,\
      # INCLUDE
      "french": 1, "hindi": 2, "nepali": 3, "albanian": 4, "tamil": 6, "telugu": 7, "indonesian": 8, "malay": 9, "chinese": 12, "japanese": 13, "korean": 14, "arabic": 15,\
      "dutch": 0.2, "german": 0.4, "tagalog": 8.5, "malayalam": 7.5,\
      # Global MMLU Lite
      "en": 0, "fr": 1, "hi": 2, "bn": 5, "id": 8, "sw": 10, "yo": 11, "zh": 12, "ja": 13, "ko": 14, "ar": 15,
      # Multi Blimp
      "eng": 0, "tam": 6, "idn": 8, "swa": 10, "zhoblimp": 12,
      # Belebele
      "eng_Latn": 0, "nld_Latn": 0.2, "deu_Latn": 0.4, "mal_Mlym": 5.8, "tam_Taml": 6, "tel_Telu": 7, "ind_Latn": 8, "tgl_Latn": 8.5, "zsm_Latn": 9, "swh_Latn": 10, "yor_Latn": 11, "lug_Latn": 10.5, "bod_Tibt": 12.2, "mya_Mymr": 12.4, "zho_Hans": 12,
      # Massive
      'en-US': 0, 'id-ID': 8, 'ta-IN': 6, 'sw-KE': 10, 'zh-CN': 12,
      # MGSM
      "en": 0, "ta": 6, "sw": 10, "zh": 12,
  }
  # Add include evals, and count their respective language's family
  family_counter = []
  if eval_dataset.lower() == 'belebele':
    flores_plus_add = ["eng_Latn", "nld_Latn", "deu_Latn"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 0 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
    flores_plus_add = ["mal_Mlym", "tam_Taml", "tel_Telu"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 6 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
    flores_plus_add = ["ind_Latn", "tgl_Latn", "zsm_Latn"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 8 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
    flores_plus_add = ["swh_Latn", "yor_Latn", "lug_Latn"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 10 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
    flores_plus_add = ["bod_Tibt", "mya_Mymr", "zho_Hans"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 12 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
  eval_languages = list(sorted(eval_languages, key=lambda x: language_sort.get(x, 100)))

  columns = ["Base Model", "Quantization Technique", "Bit Width", "Calibration Language"]
  columns.extend(eval_languages)
  custom_sort = {'Unquantized': 0, 'English': 1, 'Tamil': 2, 'Indonesian': 3, 'Swahili': 4, 'Chinese': 5,\
                 'Unquantized': 0, 'gptq': 1, 'slimllm': 2, 'tacq': 3,\
                 "Qwen/Qwen3-8B": 0, "CohereLabs/aya-expanse-8b": 1, "meta-llama/Llama-3.1-8B-Instruct": 2, "Qwen/Qwen3-14B": 3,\
                 "32-bit": 0, "2-bit": 1, "3-bit": 2, "4-bit": 3}

  calib_label_list = ["EN", "TA", "ID", "SW", "ZH"]
  calib_label = {"English": "EN", "Tamil": "TA", "Indonesian": "ID", "Swahili": "SW", "Chinese": "ZH"}
  base_model_label = {"Qwen/Qwen3-8B": "Qwen3", "CohereLabs/aya-expanse-8b": "Aya", "meta-llama/Llama-3.1-8B-Instruct": "Llama", "Qwen/Qwen3-14B": "Qwen3 14B"}
  eval_label = {
      # Global PIQA
      "eng_latn": "EN", "tam_taml": "TA", "ind_latn": "ID", "swh_latn": "SW", "cmn_hans": "ZH",\
      # INCLUDE
      "french": "FR", "hindi": "HI", "nepali": "NE", "albanian": "SQ", "tamil": "TA", "telugu": "TE", "indonesian": "ID", "malay": "MS", "chinese": "ZH", "japanese": "JA", "korean": "KO", "arabic": "AR",\
      "dutch": "NL", "german": "DE", "tagalog": "TL", "malayalam": "ML",\
      "english": "EN",\
      # Global MMLU Lite
      "en": "EN", "fr": "FR", "hi": "HI", "bn": "BN", "id": "ID", "sw": "SW", "yo": "YO", "zh": "ZH", "ja": "JA", "ko": "KO", "ar": "AR",
      # Multi Blimp
      "eng": "EN", "tam": "TA", "idn": "ID", "swa": "SW", "zhoblimp": "ZH",
      # Belebele
      "eng_Latn": "EN", "nld_Latn": "NL", "deu_Latn": "DE", "mal_Mlym": "ML", "tam_Taml": "TA", "tel_Telu": "TE", "ind_Latn": "ID", "tgl_Latn": "TL", "zsm_Latn": "MS", "swh_Latn": "SW", "yor_Latn": "YO", "lug_Latn": "LG", "bod_Tibt": "BO", "mya_Mymr": "MY", "zho_Hans": "ZH",
      # Massive
      'en-US': "EN", 'id-ID': "ID", 'ta-IN': "TA", 'sw-KE': "SW", 'zh-CN': "ZH",
      # MGSM
      "en": "EN", "ta": "TA", "sw": "SW", "zh": "ZH",
  }
  eval_label_list = [eval_label.get(x, x) for x in eval_languages]

  data_gptq = []
  data_slimllm = []
  data_tacq = []
  data_sinq = []
  quantization_techniques = set()

  unquantized_data_acc = []

  # Iterate over the runs and print details
  for run in runs:
      config = run.config
      summary = run.summary

      run_data_acc = []
      run_data_acc.extend([run.config["base_model"], config["quantization_technique"], config["bit_width"], config.get("calibration_language", None).capitalize() if config.get("calibration_language", None) else None])
      for lang in eval_languages:
        if not generate_until:
          run_data_acc.append(run.summary.get(f"{eval_dataset.lower()}_acc_{lang}", None))
        else:
          strict = run.summary.get(f"{eval_dataset.lower()}_strict_{lang}", None)
          flexible = run.summary.get(f"{eval_dataset.lower()}_flexible_{lang}", None)
          run_data_acc.append(max(strict, flexible) if not strict_answer else strict)

      quantization_techniques.add(config["quantization_technique"])
      if config["quantization_technique"] == "Unquantized":
        unquantized_data_acc.append(run_data_acc)
      elif config["quantization_technique"] == "gptq":
        data_gptq.append(run_data_acc)
      elif config["quantization_technique"] == "slimllm":
        data_slimllm.append(run_data_acc)
      elif config["quantization_technique"] == "tacq":
        data_tacq.append(run_data_acc)
      elif config["quantization_technique"] == "sinq":
        data_sinq.append(run_data_acc)

  df_unquantized_acc_chief = pd.DataFrame(unquantized_data_acc, columns=columns)
  df_gptq_chief = pd.DataFrame(data_gptq, columns=columns).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language', "Bit Width"], key=lambda x: x.map(custom_sort))
  df_slimllm_chief = pd.DataFrame(data_slimllm, columns=columns).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language', "Bit Width"], key=lambda x: x.map(custom_sort))
  df_tacq_chief = pd.DataFrame(data_tacq, columns=columns).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language', "Bit Width"], key=lambda x: x.map(custom_sort))
  df_sinq_chief = pd.DataFrame(data_sinq, columns=columns).sort_values(by=['Base Model', "Bit Width"], key=lambda x: x.map(custom_sort))

  print("Pre-AGG")
  display(df_gptq_chief)
  display(df_slimllm_chief)
  display(df_tacq_chief)

  if eval_dataset.lower() == "include" and not compile and 'telugu' not in eval_languages:
    for df_acc in [df_gptq_chief, df_slimllm_chief, df_tacq_chief, df_sinq_chief, df_unquantized_acc_chief]:
      df_acc.insert(5, 'english', (df_acc['german'] + df_acc['dutch']) / (2))
      df_acc.drop(["german", "dutch"], axis=1, inplace=True)

    replace_index = min(eval_languages.index("german"), eval_languages.index("dutch"))
    eval_languages.insert(replace_index, "english")
    eval_languages.remove("german")
    eval_languages.remove("dutch")
    print(eval_label_list)
    eval_label_list.insert(replace_index, "EN")
    eval_label_list.remove("DE")
    eval_label_list.remove("NL")

  # AGG to produce mean and stderr
  df_unquantized_acc_chief_std = df_unquantized_acc_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std")

  df_gptq_chief_std = df_gptq_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std", ddof=0).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_gptq_chief = df_gptq_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("mean").sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))

  df_slimllm_chief_std = df_slimllm_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std", ddof=0).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_slimllm_chief = df_slimllm_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("mean").sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))

  df_tacq_chief_std = df_tacq_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std", ddof=0).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_tacq_chief = df_tacq_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("mean").sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))

  print("Contrasting Acc and Stderr")
  print("GPTQ")
  display(df_gptq_chief)
  display(df_gptq_chief_std[((df_gptq_chief_std["Bit Width"] == "2-bit") & (df_gptq_chief_std["Base Model"].isin(["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b"]))) | ((df_gptq_chief_std["Bit Width"] == "3-bit") & (df_gptq_chief_std["Base Model"] == "Qwen/Qwen3-8B"))])
  print("SLIM")
  display(df_slimllm_chief)
  display(df_slimllm_chief_std[((df_slimllm_chief_std["Bit Width"] == "2-bit") & (df_slimllm_chief_std["Base Model"].isin(["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b"]))) | ((df_slimllm_chief_std["Bit Width"] == "3-bit") & (df_slimllm_chief_std["Base Model"] == "Qwen/Qwen3-8B"))])
  print("TACQ")
  display(df_tacq_chief)
  display(df_tacq_chief_std[((df_gptq_chief_std["Bit Width"] == "2-bit") & (df_tacq_chief_std["Base Model"].isin(["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b"]))) | ((df_tacq_chief_std["Bit Width"] == "3-bit") & (df_tacq_chief_std["Base Model"] == "Qwen/Qwen3-8B"))])

  # Add figure placeholder before iterations
  from plotly.subplots import make_subplots
  big_fig = make_subplots(rows=len(base_models), cols=len(eval_languages), subplot_titles=tuple([eval_label[lang] for lang in eval_languages]),
                          vertical_spacing=vertical_spacing,
                          horizontal_spacing=horizontal_spacing)

  # Iterate for each model for decoupling
  df_chief = pd.DataFrame([])
  df_zscore_chief = pd.DataFrame([])
  index_border_chief = [0]
  for base_model in base_models:
    df_gptq = df_gptq_chief.loc[df_gptq_chief["Base Model"] == base_model]
    df_gptq_std = df_gptq_chief_std.loc[df_gptq_chief_std["Base Model"] == base_model]
    df_slimllm = df_slimllm_chief.loc[df_slimllm_chief["Base Model"] == base_model]
    df_slimllm_std = df_slimllm_chief_std.loc[df_slimllm_chief_std["Base Model"] == base_model]
    df_tacq = df_tacq_chief.loc[df_tacq_chief["Base Model"] == base_model]
    df_tacq_std = df_tacq_chief_std.loc[df_tacq_chief_std["Base Model"] == base_model]
    df_sinq = df_sinq_chief.loc[df_sinq_chief["Base Model"] == base_model]
    df_unquantized_acc = df_unquantized_acc_chief.loc[df_unquantized_acc_chief["Base Model"] == base_model]
    df_unquantized_acc_std = df_unquantized_acc_chief_std.loc[df_unquantized_acc_chief_std["Base Model"] == base_model]
    base_model = base_model_label[base_model]

    df_gptq.iloc[:, 4:] = df_gptq.iloc[:, 4:].rename(lambda x: eval_label.get(x, x), axis='columns')
    # df_gptq = df_gptq.rename(lambda x: eval_label.get(x, x), axis='columns')
    df_gptq.loc[:, "Calibration Language"] = df_gptq.loc[:, "Calibration Language"].apply(lambda x: calib_label.get(x, x))
    if display_mean:
      df_gptq = pd.concat([df_gptq.T, df_gptq.mean(axis=0).to_frame('Mean')], axis=1).T
    df_gptq[df_gptq.columns[4:]] = df_gptq[df_gptq.columns[4:]].astype(float)
    df_gptq_std.iloc[:, 4:] = df_gptq_std.iloc[:, 4:].rename(lambda x: eval_label.get(x, x), axis='columns')
    df_gptq_std.loc[:, "Calibration Language"] = df_gptq_std.loc[:, "Calibration Language"].apply(lambda x: calib_label.get(x, x))

    df_slimllm.iloc[:, 4:] = df_slimllm.iloc[:, 4:].rename(lambda x: eval_label.get(x, x), axis='columns')
    # df_slimllm = df_slimllm.rename(lambda x: eval_label.get(x, x), axis='columns')
    df_slimllm.loc[:, "Calibration Language"] = df_slimllm.loc[:, "Calibration Language"].apply(lambda x: calib_label.get(x, x))
    if display_mean:
      df_slimllm = pd.concat([df_slimllm.T, df_slimllm.mean(axis=0).to_frame('Mean')], axis=1).T
    df_slimllm[df_gptq.columns[4:]] = df_slimllm[df_slimllm.columns[4:]].astype(float)
    df_slimllm_std.iloc[:, 4:] = df_slimllm_std.iloc[:, 4:].rename(lambda x: eval_label.get(x, x), axis='columns')
    df_slimllm_std.loc[:, "Calibration Language"] = df_slimllm_std.loc[:, "Calibration Language"].apply(lambda x: calib_label.get(x, x))

    df_tacq.iloc[:, 4:] = df_tacq.iloc[:, 4:].rename(lambda x: eval_label.get(x, x), axis='columns')
    # df_tacq = df_tacq.rename(lambda x: eval_label.get(x, x), axis='columns')
    df_tacq.loc[:, "Calibration Language"] = df_tacq.loc[:, "Calibration Language"].apply(lambda x: calib_label.get(x, x))
    if display_mean:
      df_tacq = pd.concat([df_tacq.T, df_tacq.mean(axis=0).to_frame('Mean')], axis=1).T
    df_tacq[df_gptq.columns[4:]] = df_tacq[df_tacq.columns[4:]].astype(float)
    df_tacq_std.iloc[:, 4:] = df_tacq_std.iloc[:, 4:].rename(lambda x: eval_label.get(x, x), axis='columns')
    df_tacq_std.loc[:, "Calibration Language"] = df_tacq_std.loc[:, "Calibration Language"].apply(lambda x: calib_label.get(x, x))

    df_sinq.iloc[:, 4:] = df_sinq.iloc[:, 4:].rename(lambda x: eval_label.get(x, x), axis='columns')
    # df_sinq = df_sinq.rename(lambda x: eval_label.get(x, x), axis='columns')
    df_sinq.loc[:, "Calibration Language"] = df_sinq.loc[:, "Calibration Language"].apply(lambda x: calib_label.get(x, x))
    if display_mean:
      df_sinq = pd.concat([df_tacq.T, df_sinq.mean(axis=0).to_frame('Mean')], axis=1).T
    df_sinq[df_gptq.columns[4:]] = df_sinq[df_sinq.columns[4:]].astype(float)

    # df_unquantized_acc.iloc[:, 4:] = df_unquantized_acc.iloc[:, 4:]
    df_unquantized_acc = df_unquantized_acc.rename(lambda x: eval_label.get(x, x), axis='columns')
    if display_mean:
      df_unquantized_acc = pd.concat([df_unquantized_acc, df_unquantized_acc.mean(axis=0).to_frame('Mean')], axis=0)
    df = pd.concat([df_gptq, df_slimllm, df_tacq], axis=1)
    if display_mean:
      df_mean_quantized = df.mean(axis=1).to_frame('Mean of Quantized')
    df_unquantized_acc_std.iloc[:, 4:] = df_unquantized_acc_std.iloc[:, 4:].rename(lambda x: eval_label.get(x, x), axis='columns')

    # The df structure: Column the eval, index (5 first columns) is the settings
    # Calculate Z-Score
    from scipy.stats import zscore
    import numpy as np
    ## Placeholder for Z-score, Direct, Cross
    df_gptq["zscore"] = np.empty(len(df_gptq))
    df_slimllm["zscore"] = np.empty(len(df_slimllm))
    df_tacq["zscore"] = np.empty(len(df_tacq))

    df_gptq["direct_transposed"] = np.empty(len(df_gptq))
    df_slimllm["direct_transposed"] = np.empty(len(df_slimllm))
    df_tacq["direct_transposed"] = np.empty(len(df_tacq))
    df_gptq["cross_transposed"] = np.empty(len(df_gptq))
    df_slimllm["cross_transposed"] = np.empty(len(df_slimllm))
    df_tacq["cross_transposed"] = np.empty(len(df_tacq))

    df_gptq_std["direct_transposed"] = np.empty(len(df_gptq_std))
    df_slimllm_std["direct_transposed"] = np.empty(len(df_slimllm_std))
    df_tacq_std["direct_transposed"] = np.empty(len(df_tacq_std))
    df_gptq_std["cross_transposed"] = np.empty(len(df_gptq_std))
    df_slimllm_std["cross_transposed"] = np.empty(len(df_slimllm_std))
    df_tacq_std["cross_transposed"] = np.empty(len(df_tacq_std))
    ## Calculate Z-score as usual
    ## Calculate Direct as En -> EN, while Cross as mean of ~En -> EN
    for bit in bits:
      # Acc GPTQ
      df_filter = df_gptq[df_gptq["Bit Width"] == bit]
      if len(df_filter) > 0:
        df_gptq.loc[df_filter.index, "zscore"] = zscore(df_filter.iloc[:, 4:], axis=0)[np.arange(len(df_filter)), [x for x in df_filter["Calibration Language"].apply(lambda x: eval_label_list.index(calib_label.get(x, x))).values.tolist()]]
        mean_ppl = df_filter.iloc[:, 4:4+len(eval_languages)].sum(axis=0, min_count=0)                                    # Seek the column using iloc, because seeking using loc is harder
        df_gptq.loc[df_filter.index, "direct_transposed"] = [df_filter.iloc[i, 4 + eval_label_list.index(calib)] for i, calib in enumerate(df_filter["Calibration Language"].unique())]
        df_gptq.loc[df_filter.index, "cross_transposed"] = (mean_ppl.values - df_gptq.loc[df_filter.index, "direct_transposed"].values) / (len(df_filter) - 1)
        print(list([calib_label_list.index(calib), calib] for i, calib in enumerate(df_filter["Calibration Language"].unique())))

      # Std GPTQ
      df_filter = df_gptq_std[df_gptq_std["Bit Width"] == bit]
      if len(df_filter) > 0:
        df_gptq_std.loc[df_filter.index, "zscore"] = zscore(df_filter.iloc[:, 4:], axis=0)[np.arange(len(df_filter)), [x for x in df_filter["Calibration Language"].apply(lambda x: eval_label_list.index(calib_label.get(x, x))).values.tolist()]]
        mean_ppl = df_filter.iloc[:, 4:4+len(eval_languages)].map(lambda x: np.square(x)).sum(axis=0, min_count=0)                                    # Seek the column using iloc, because seeking using loc is harder
        df_gptq_std.loc[df_filter.index, "direct_transposed"] = [df_filter.iloc[i, 4 + eval_label_list.index(calib)] for i, calib in enumerate(df_filter["Calibration Language"].unique())]
        df_gptq_std.loc[df_filter.index, "cross_transposed"] = np.sqrt((mean_ppl.values - df_gptq_std.loc[df_filter.index, "direct_transposed"].map(lambda x: np.square(x)).values) / (len(df_filter) - 1))

      # Acc SliMLLM
      df_filter = df_slimllm[df_slimllm["Bit Width"] == bit]
      print("where TA located")
      print(df_filter["Calibration Language"].unique())
      if len(df_filter) > 0:
        df_slimllm.loc[df_filter.index, "zscore"] = zscore(df_filter.iloc[:, 4:], axis=0)[np.arange(len(df_filter)), [x for x in df_filter["Calibration Language"].apply(lambda x: eval_label_list.index(calib_label.get(x, x))).values.tolist()]]
        mean_ppl = df_filter.iloc[:, 4:4+len(eval_languages)].sum(axis=0, min_count=0)
        print("mean_ppl")
        display(mean_ppl)
        if base_model == "Aya" and "TA" in eval_label_list:   # Short hand by the renaming indexes before
          mean_ppl = mean_ppl.drop(eval_languages[eval_label_list.index("TA")], axis=0, errors='ignore')                        # Seek the column using iloc, because seeking using loc is harder
        df_slimllm.loc[df_filter.index, "direct_transposed"] = [df_filter.iloc[i, 4 + eval_label_list.index(calib)] for i, calib in enumerate(df_filter["Calibration Language"].unique())]
        df_slimllm.loc[df_filter.index, "cross_transposed"] = (mean_ppl.values - df_slimllm.loc[df_filter.index, "direct_transposed"].values) / (len(df_filter) - 1)

      # Std SliMLLM
      df_filter = df_slimllm_std[df_slimllm_std["Bit Width"] == bit]
      if len(df_filter) > 0:
        df_slimllm_std.loc[df_filter.index, "zscore"] = zscore(df_filter.iloc[:, 4:], axis=0)[np.arange(len(df_filter)), [x for x in df_filter["Calibration Language"].apply(lambda x: eval_label_list.index(calib_label.get(x, x))).values.tolist()]]
        mean_ppl = df_filter.iloc[:, 4:4+len(eval_languages)].map(lambda x: np.square(x)).sum(axis=0, min_count=0)
        if base_model == "Aya" and "TA" in eval_label_list:   # Short hand by the renaming indexes before
          mean_ppl = mean_ppl.drop(eval_languages[eval_label_list.index("TA")], axis=0, errors='ignore')                        # Seek the column using iloc, because seeking using loc is harder
        df_slimllm_std.loc[df_filter.index, "direct_transposed"] = [df_filter.iloc[i, 4 + eval_label_list.index(calib)] for i, calib in enumerate(df_filter["Calibration Language"].unique())]
        df_slimllm_std.loc[df_filter.index, "cross_transposed"] = np.sqrt((mean_ppl.values - df_slimllm_std.loc[df_filter.index, "direct_transposed"].map(lambda x: np.square(x)).values) / (len(df_filter) - 1))

      # Acc TaCQ
      df_filter = df_tacq[df_tacq["Bit Width"] == bit]
      if len(df_filter) > 0:
        df_tacq.loc[df_filter.index, "zscore"] = zscore(df_filter.iloc[:, 4:], axis=0)[np.arange(len(df_filter)), [x for x in df_filter["Calibration Language"].apply(lambda x: eval_label_list.index(calib_label.get(x, x))).values.tolist()]]
        mean_ppl = df_filter.iloc[:, 4:4+len(eval_languages)].sum(axis=0, min_count=0)                                   # Seek the column using iloc, because seeking using loc is harder
        df_tacq.loc[df_filter.index, "direct_transposed"] = [df_filter.iloc[i, 4 + eval_label_list.index(calib)] for i, calib in enumerate(df_filter["Calibration Language"].unique())]
        df_tacq.loc[df_filter.index, "cross_transposed"] = (mean_ppl.values - df_tacq.loc[df_filter.index, "direct_transposed"].values) / (len(df_filter) - 1)

      # Std TaCQ
      df_filter = df_tacq_std[df_tacq_std["Bit Width"] == bit]
      if len(df_filter) > 0:
        df_tacq_std.loc[df_filter.index, "zscore"] = zscore(df_filter.iloc[:, 4:], axis=0)[np.arange(len(df_filter)), [x for x in df_filter["Calibration Language"].apply(lambda x: eval_label_list.index(calib_label.get(x, x))).values.tolist()]]
        mean_ppl = df_filter.iloc[:, 4:4+len(eval_languages)].map(lambda x: np.square(x)).sum(axis=0, min_count=0)                                   # Seek the column using iloc, because seeking using loc is harder
        df_tacq_std.loc[df_filter.index, "direct_transposed"] = [df_filter.iloc[i, 4 + eval_label_list.index(calib)] for i, calib in enumerate(df_filter["Calibration Language"].unique())]
        df_tacq_std.loc[df_filter.index, "cross_transposed"] = np.sqrt((mean_ppl.values - df_tacq_std.loc[df_filter.index, "direct_transposed"].map(lambda x: np.square(x)).values) / (len(df_filter) - 1))

    # display(df_gptq)
    # display(df_slimllm)
    # display(df_tacq)
    # Append to the subplot for each model, languages
    for lang in eval_languages:
      # fig = go.Figure()
      trace = []
      # GPTQ
      for quant in ["sinq", "tacq", "slimllm", "gptq"]:
        if quant == 'sinq':
          df_filter = df_sinq
          marker_pattern_shape = '+'
          # line_dash = 'solid'
          # zorder=0
          shift = -0.2375 - 0.11875 if "slimllm" in quantization_techniques else -0.95/3
        elif quant == 'gptq':
          df_filter = df_gptq.loc[df_gptq["Calibration Language"] == eval_label[lang]]
          df_filter_std = df_gptq_std.loc[df_gptq_std["Calibration Language"] == eval_label[lang]]
          marker_pattern_shape = '/'
          # line_dash = 'solid'
          # zorder=0
          shift = -0.11875 if "slimllm" in quantization_techniques else 0
        elif quant == 'slimllm':
          df_filter = df_slimllm.loc[df_slimllm["Calibration Language"] == eval_label[lang]]
          df_filter_std = df_slimllm_std.loc[df_slimllm_std["Calibration Language"] == eval_label[lang]]
          marker_pattern_shape = '-'
          line_dash = 'dash'
          zorder=1
          shift = 0.11875 if "slimllm" in quantization_techniques else 0
        elif quant == 'tacq':
          df_filter = df_tacq.loc[df_tacq["Calibration Language"] == eval_label[lang]]
          df_filter_std = df_tacq_std.loc[df_tacq_std["Calibration Language"] == eval_label[lang]]
          marker_pattern_shape = '\\'
          line_dash = 'longdash'
          zorder=2
          shift = 0.2375 + 0.11875 if "slimllm" in quantization_techniques else 0.95/3

        # Categorical map for bit width to x-axis in integer
        categorical_map = {}
        for i, bit in enumerate(df_filter["Bit Width"]):
          categorical_map[bit] = i

        if quant != "sinq":
          # print(f"{base_model}, {quant}")
          # display(df_filter_std["cross_transposed"])
          # display(df_filter_std["cross_transposed"].map(lambda x: x != 0))
          df_error_bar = df_filter_std.copy().loc[:, ["Bit Width", "cross_transposed", "direct_transposed"]]
          zero_error = df_error_bar[df_error_bar['direct_transposed'] == 0]
          nonzero_error = df_error_bar[df_error_bar['direct_transposed'] != 0]
          # Without Error Bar
          trace = (go.Bar(x=list(map(lambda x: categorical_map[x] + shift, df_filter["Bit Width"].drop(nonzero_error.index))), y=df_filter["direct_transposed"].drop(nonzero_error.index),
                              # mode='lines+markers',
                              # marker_pattern_shape=marker_pattern_shape,
                              # marker_line_color=marker_line_color,
                              marker_color=px.colors.qualitative.Plotly[0],
                              # marker_line_width=2,
                              # marker_size=5,
                              # line_dash=line_dash,
                              width=([0.2375] if "slimllm" in quantization_techniques else [0.95 / 3]) * len(df_filter["Bit Width"]),
                              # opacity=0.8,
                              # zorder=zorder,
                              showlegend=False,
                              name=f'{quant}-Direct',
                              # text=df_filter["Quantization Technique"] + "-Direct"
                            ))
          big_fig.append_trace(
              trace,
              row=1 + [base_model_label[x] for x in base_models].index(base_model), col=1 + eval_languages.index(lang)
          )
          trace = (go.Bar(x=list(map(lambda x: categorical_map[x] + shift, df_filter["Bit Width"].drop(nonzero_error.index))), y=df_filter["cross_transposed"].drop(nonzero_error.index),
                              # mode='lines+markers',
                              # marker_pattern_shape=marker_pattern_shape,
                              # marker_line_color=marker_line_color,
                              marker_color=px.colors.qualitative.Plotly[4],
                              # marker_line_width=2,
                              # marker_size=5,
                              # line_dash=line_dash,
                              width=([0.11875] if "slimllm" in quantization_techniques else [0.95 / 6]) * len(df_filter["Bit Width"]),
                              # opacity=0.8,
                              # zorder=max(0, 1-zorder),
                              showlegend=False,
                              name=f'{quant}-Cross',
                              # text=df_filter["Quantization Technique"] + "-Cross"
                            ))
          big_fig.append_trace(
              trace,
              row=1 + [base_model_label[x] for x in base_models].index(base_model), col=1 + eval_languages.index(lang)
          )
          # With Error Bar
          trace = (go.Bar(x=list(map(lambda x: categorical_map[x] + shift, df_filter["Bit Width"].drop(zero_error.index))), y=df_filter["direct_transposed"].drop(zero_error.index),
                              error_y=dict(
                                  type='data',
                                  array=df_error_bar["direct_transposed"].drop(zero_error.index),             # Assigns standard deviation array
                                  visible=True,
                                  thickness=4,               # Line width of error bar
                                  width=6,                    # Width of the horizontal cap line
                                  color=px.colors.qualitative.Plotly[5],
                              ),
                              # mode='lines+markers',
                              # marker_pattern_shape=marker_pattern_shape,
                              # marker_line_color=marker_line_color,
                              marker_color=px.colors.qualitative.Plotly[0],
                              # marker_line_width=2,
                              # marker_size=5,
                              # line_dash=line_dash,
                              width=([0.2375] if "slimllm" in quantization_techniques else [0.95 / 3]) * len(df_filter["Bit Width"]),
                              # opacity=0.8,
                              # zorder=zorder,
                              showlegend=False,
                              name=f'{quant}-Direct',
                              # text=df_filter["Quantization Technique"] + "-Direct"
                            ))
          big_fig.append_trace(
              trace,
              row=1 + [base_model_label[x] for x in base_models].index(base_model), col=1 + eval_languages.index(lang)
          )
          trace = (go.Bar(x=list(map(lambda x: categorical_map[x] + shift, df_filter["Bit Width"].drop(zero_error.index))), y=df_filter["cross_transposed"].drop(zero_error.index),
                              error_y=dict(
                                  type='data',
                                  array=df_filter_std["cross_transposed"].drop(zero_error.index),             # Assigns standard deviation array
                                  visible=True,
                                  thickness=4,               # Line width of error bar
                                  width=6,                    # Width of the horizontal cap line
                                  color=px.colors.qualitative.Plotly[9],
                              ),
                              # mode='lines+markers',
                              # marker_pattern_shape=marker_pattern_shape,
                              # marker_line_color=marker_line_color,
                              marker_color=px.colors.qualitative.Plotly[4],
                              # marker_line_width=2,
                              # marker_size=5,
                              # line_dash=line_dash,
                              width=([0.11875] if "slimllm" in quantization_techniques else [0.95 / 6]) * len(df_filter["Bit Width"]),
                              # opacity=0.8,
                              # zorder=max(0, 1-zorder),
                              showlegend=False,
                              name=f'{quant}-Cross',
                              # text=df_filter["Quantization Technique"] + "-Cross"
                            ))
          big_fig.append_trace(
              trace,
              row=1 + [base_model_label[x] for x in base_models].index(base_model), col=1 + eval_languages.index(lang)
          )
        else: # sinq
            # print(f"SINQ: {df_filter[lang]}")
            trace = (go.Bar(x=list(map(lambda x: categorical_map[x] + shift, df_filter["Bit Width"])), y=df_filter[lang],
                              # mode='lines+markers',
                              # marker_pattern_shape=marker_pattern_shape,
                              # marker_line_color=marker_line_color,
                              marker_color=px.colors.qualitative.Plotly[2],
                              # marker_line_width=2,
                              # marker_size=5,
                              # line_dash=line_dash,
                              width=([0.2375] if "slimllm" in quantization_techniques else [0.95 / 3]) * len(df_filter["Bit Width"]),
                              # opacity=0.8,
                              # zorder=zorder,
                              showlegend=False,
                              name=f'{quant}',
                              # text=df_filter["Quantization Technique"] + "-Direct"
                            ))
            big_fig.append_trace(
                trace,
                row=1 + [base_model_label[x] for x in base_models].index(base_model), col=1 + eval_languages.index(lang)
            )

        # Add Quantization method label
        for x_coor in list(map(lambda x: categorical_map[x] + shift, df_filter["Bit Width"])):
          if quant != "sinq":
            big_fig.add_shape(
              type="rect",
              x0=x_coor,
              y0=0,
              x1=x_coor,
              y1=random_guess_score,
              xref=f"x{len(eval_languages) * [base_model_label[x] for x in base_models].index(base_model) + 1 + eval_languages.index(lang)}",
              yref=f"y{len(eval_languages) * [base_model_label[x] for x in base_models].index(base_model) + 1 + eval_languages.index(lang)}",
              line_width=0,
              layer="above",
              label=dict(text=quant[0].upper(), textposition="bottom center", font=dict(size=24)),
            )
        big_fig.update_xaxes(
            # yaxis={'title' : "ACC (Higher is better)"},
            # xaxis = dict(
            tickmode = 'array',
            tickvals = list(range(len(df_filter["Bit Width"]))),
            ticktext = df_filter["Bit Width"],
            # ),
            row=1 + [base_model_label[x] for x in base_models].index(base_model),
            col=1 + eval_languages.index(lang)
        )
      for quant in ["Unquantized"]:
        marker_pattern_shape = ''
        big_fig.add_hline(y=df_unquantized_acc[eval_label.get(lang, lang)].iloc[0], line_width=4, row=1 + [base_model_label[x] for x in base_models].index(base_model), col=1 + eval_languages.index(lang))
        big_fig.add_hline(y=random_guess_score, line_width=4, row=1 + [base_model_label[x] for x in base_models].index(base_model), col=1 + eval_languages.index(lang),
              line_dash="dot",
              # annotation_text="Random Guess Score",
              # annotation_position="bottom right",
        )
        # display(df_unquantized_acc)
        # print(list(filter(lambda x: x < (df_unquantized_acc[eval_label.get(lang, lang)].iloc[0] + 0.20), [0.0, 0.20, 0.40, 0.60, 0.80, 1.0])))
        big_fig.update_yaxes(tickvals=list(filter(lambda x: x < (df_unquantized_acc[eval_label.get(lang, lang)].iloc[0] + 0.20), [0.0, 0.20, 0.40, 0.60, 0.80, 1.0])), row=1 + [base_model_label[x] for x in base_models].index(base_model), col=1 + eval_languages.index(lang))

  # Figure Style
  big_fig.update_xaxes(title_standoff=15, automargin=True)
  big_fig.update_yaxes(title_standoff=5, automargin=True)
  big_fig.update_layout(
      margin=dict(t=100, b=20 if not write_pdf else 35, l=50, r=0)
  )
  # Early Config: t=100, b=15 if not write_pdf else 25, l=50, r=0
  # Early Config: big_fig.layout.height = 100 + 80 * 3 + (15 if not write_pdf else 25)
  # Early Config: big_fig.layout.width = 50 + 160 * len(eval_languages)
  # big_fig.update_xaxes(tickvals=list(filter(lambda x: x < (df_unquantized_acc[eval_label.get(lang, lang)].iloc[0] + 0.20), [0.0, 0.20, 0.40, 0.60, 0.80, 1.0])), row=1 + [base_model_label[x] for x in base_models].index(base_model), col=1 + eval_languages.index(lang))
  # big_fig.update_layout(xaxis=dict(range=[-0.5, len(bits) - 0.5]))
  big_fig.update_xaxes(range=[-0.5, len(bits) - 0.5])
  big_fig.layout.height = 100 + 160 * len(base_models) + (20 if not write_pdf else 35) # base_model
  big_fig.layout.width = 50 + 320 * len(eval_languages) # eval languages

  big_fig.update_xaxes(title_font=dict(size=20))
  big_fig.update_yaxes(title_font=dict(size=20))
  big_fig.update_xaxes(tickfont=dict(size=24))
  big_fig.update_yaxes(tickfont=dict(size=24))
  big_fig.update_layout(
      legend_font_size=20,       # Font size for legend items
      # legend_title_font_size=18  # Font size for legend title
  )

  # big_fig.update_layout(showlegend=False)

  big_fig.update_layout(barmode='overlay')
  big_fig.update_layout(legend=dict(
      orientation="h",
      yanchor="bottom",
      y=1.05,
      xanchor="center",
      x=0.5
  ))

  # just for display purpose, create traces so that legend contains colors.  does not connect with
  # bars
  # print(big_fig.data)
  legend_colors = [
      ("Direct", big_fig.data[1].x[0], big_fig.data[1].y[0], px.colors.qualitative.Plotly[0]),
      ("Cross", big_fig.data[1].x[0], big_fig.data[1].y[0], px.colors.qualitative.Plotly[4]),
      ("Calibration-Free", big_fig.data[1].x[0], big_fig.data[1].y[0], px.colors.qualitative.Plotly[2]),
  ]
  legend_dashes_score = [("Unquantized Score", "/", "solid"), ("Random Guess Score", "-", "dash")]
  legend_dashes = [("G=GPTQ", "/", "solid"), ("S=SliM-LLM", "-", "dash"), ("T=TaCQ", "\\", "longdash")]
  legend_zscores = [("1 Z-Score", "star", "purple"), ("0.5 Z-Score", "star", "green")]
  big_fig.update_traces(showlegend=False).add_traces(
      [
          go.Bar(name=name, x=[x], y=[y], marker_color=color, showlegend=True, zorder=-1, width=[0.2])
          for name, x, y, color in legend_colors
      ]
  )
  big_fig.add_traces(
      [
          go.Scatter(name=name, x=[big_fig.data[1].x[0]], y=[big_fig.data[1].y[0]-0.1], mode='lines', line_dash=dash, line_width=4, marker_color='black', showlegend=True, zorder=-1)
          for name, symbol, dash in legend_dashes_score
      ]
  )
  big_fig.add_traces(
      [
          go.Scatter(name=name, x=[big_fig.data[1].x[0]], y=[big_fig.data[1].y[0]-0.1], mode='none', marker_color='white', showlegend=True, zorder=-1)
          for name, symbol, dash in legend_dashes
      ]
  )
  # big_fig.add_traces(
  #     [
  #         go.Scatter(name=name, x=[big_fig.data[0].x[0]], y=[big_fig.data[0].y[0]], mode='markers', marker_symbol=symbol, marker_color=color, showlegend=True, zorder=-1)
  #         for name, symbol, color in legend_zscores
  #     ]
  # )

  for i, base_model in enumerate(base_models):
    big_fig.update_yaxes(title_text=base_model_label[base_model], row=i+1, col=1)
  big_fig.show()
  if write_pdf:
    big_fig.write_image(write_pdf)

### MultiBlimp Bar

In [ ]:
# eval_languages = ["eng_Latn", "tam_Taml", "ind_Latn", "swh_Latn", "zho_Hans"]
eval_languages = ["eng", "tam", "zhoblimp"]

# Initialize the W&B API
api = Api()

quantization_technique = "ALL"
# bit = 8
num_samples = 128
eval_dataset = "MultiBlimp"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.num_calibration_samples": num_samples},
                            {"$or": [
                                {"$and": [
                                  {"config.evaluation_dataset": f"{eval_dataset.lower()}"},
                                  {"created_at": {"$lt": "2026-07-01"}},
                                ]},
                                {"$and": [
                                  {"$or": [
                                    {"config.evaluation_dataset": f"{eval_dataset.lower()}-1000"},
                                    {"config.evaluation_dataset": f"{eval_dataset.lower()}-2000"},
                                  ]},
                                  {"created_at": {"$gt": "2026-07-01"}},
                                ]},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"$not": {"config.calibration_language": "WuuChinese"}},
                            {"$not": {"config.base_model": "Qwen/Qwen3-14B"}},
                            {"$not": {"$and": [{"created_at": {"$lt": "2026-03-01"}}, {"config.quantization_technique": "gptq"}]}},
                            {"$not": {"config.calibration_language": "Swahili"}},
                            {"$not": {"config.calibration_language": "Indonesian"}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.evaluation_dataset": eval_dataset.lower()},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"$not": {"config.base_model": "Qwen/Qwen3-14B"}},
                            {"config.output_type": "multiple_choice"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              {"config.evaluation_dataset": eval_dataset.lower()},
                              # {"config.base_model": base_model},
                            {"$not": {"config.base_model": "Qwen/Qwen3-14B"}},
                              {"config.enable_thinking": False},
                              {"created_at": {"$lt": "2026-07-01"}},
                          ]}
                      ]}
                  )

  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique=quantization_technique, bits=["2-bit", "3-bit", "4-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False, vertical_spacing=0.06, horizontal_spacing=0.04, random_guess_score=0.5, write_pdf="multiblimp_barplot_reduced_errorbar_final.pdf")

Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng,tam,zhoblimp
0,Qwen/Qwen3-8B,gptq,2-bit,English,0.681818,0.620419,0.562034
27,Qwen/Qwen3-8B,gptq,2-bit,English,0.637662,0.685864,0.561045
28,Qwen/Qwen3-8B,gptq,2-bit,English,0.715584,0.643979,0.557853
3,Qwen/Qwen3-8B,gptq,3-bit,English,0.977922,0.814136,0.804322
33,Qwen/Qwen3-8B,gptq,3-bit,English,0.972727,0.782723,0.805085
34,Qwen/Qwen3-8B,gptq,3-bit,English,0.966234,0.732984,0.815650
6,Qwen/Qwen3-8B,gptq,4-bit,English,0.997403,0.895288,1.000000
1,Qwen/Qwen3-8B,gptq,2-bit,Tamil,0.624675,0.706806,0.567147
29,Qwen/Qwen3-8B,gptq,2-bit,Tamil,0.616883,0.787958,0.583927
30,Qwen/Qwen3-8B,gptq,2-bit,Tamil,0.589610,0.793194,0.566723
4,Qwen/Qwen3-8B,gptq,3-bit,Tamil,0.972727,0.908377,0.821610
35,Qwen/Qwen3-8B,gptq,3-bit,Tamil,0.976623,0.931937,0.826525
36,Qwen/Qwen3-8B,gptq,3-bit,Tamil,0.970130,0.905759,0.826271
7,Qwen/Qwen3-8B,gptq,4-bit,Tamil,0.997403,0.921466,1.000000
2,Qwen/Qwen3-8B,gptq,2-bit,Chinese,0.627273,0.526178,0.595763
31,Qwen/Qwen3-8B,gptq,2-bit,Chinese,0.590909,0.638743,0.570819
32,Qwen/Qwen3-8B,gptq,2-bit,Chinese,0.635065,0.578534,0.597966
5,Qwen/Qwen3-8B,gptq,3-bit,Chinese,0.948052,0.814136,0.792260
37,Qwen/Qwen3-8B,gptq,3-bit,Chinese,0.955844,0.811518,0.786723
38,Qwen/Qwen3-8B,gptq,3-bit,Chinese,0.971429,0.814136,0.822345
8,Qwen/Qwen3-8B,gptq,4-bit,Chinese,0.996104,0.926702,1.000000
18,CohereLabs/aya-expanse-8b,gptq,2-bit,English,0.788312,0.630890,0.567429
45,CohereLabs/aya-expanse-8b,gptq,2-bit,English,0.822078,0.465969,0.567542
46,CohereLabs/aya-expanse-8b,gptq,2-bit,English,0.835065,0.547120,0.587655
21,CohereLabs/aya-expanse-8b,gptq,3-bit,English,0.967532,0.824607,0.760537
24,CohereLabs/aya-expanse-8b,gptq,4-bit,English,0.966234,0.913613,0.779661
19,CohereLabs/aya-expanse-8b,gptq,2-bit,Tamil,0.764935,0.795812,0.563785
47,CohereLabs/aya-expanse-8b,gptq,2-bit,Tamil,0.770130,0.837696,0.569548
48,CohereLabs/aya-expanse-8b,gptq,2-bit,Tamil,0.749351,0.780105,0.586356
22,CohereLabs/aya-expanse-8b,gptq,3-bit,Tamil,0.942857,0.897906,0.712203
25,CohereLabs/aya-expanse-8b,gptq,4-bit,Tamil,0.967532,0.918848,0.791384
20,CohereLabs/aya-expanse-8b,gptq,2-bit,Chinese,0.702597,0.604712,0.595141
49,CohereLabs/aya-expanse-8b,gptq,2-bit,Chinese,0.761039,0.651832,0.623588
50,CohereLabs/aya-expanse-8b,gptq,2-bit,Chinese,0.754545,0.473822,0.604492
23,CohereLabs/aya-expanse-8b,gptq,3-bit,Chinese,0.964935,0.840314,0.785904
26,CohereLabs/aya-expanse-8b,gptq,4-bit,Chinese,0.968831,0.931937,0.791017
9,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,English,0.777922,0.751309,0.546158
39,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,English,0.770130,0.780105,0.550734
40,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,English,0.729870,0.714660,0.555904
12,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,English,0.963636,0.816754,0.774689
15,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,English,0.972727,0.913613,0.793249
10,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Tamil,0.701299,0.691099,0.542401
41,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Tamil,0.712987,0.709424,0.567514
42,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Tamil,0.655844,0.664921,0.545989
13,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Tamil,0.957143,0.934555,0.748362
16,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Tamil,0.975325,0.918848,0.803220
11,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Chinese,0.715584,0.743455,0.587684
43,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Chinese,0.723377,0.714660,0.577514
44,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Chinese,0.694805,0.725131,0.571130
14,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Chinese,0.967532,0.814136,0.793362
17,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Chinese,0.975325,0.934555,0.795904

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng,tam,zhoblimp
0,Qwen/Qwen3-8B,slimllm,2-bit,English,0.937662,0.479058,0.572825
24,Qwen/Qwen3-8B,slimllm,2-bit,English,0.923377,0.672775,0.579040
25,Qwen/Qwen3-8B,slimllm,2-bit,English,0.928571,0.696335,0.588277
4,Qwen/Qwen3-8B,slimllm,3-bit,English,0.970130,0.801047,0.791017
30,Qwen/Qwen3-8B,slimllm,3-bit,English,0.967532,0.714660,0.786723
31,Qwen/Qwen3-8B,slimllm,3-bit,English,0.958442,0.869110,0.803701
16,Qwen/Qwen3-8B,slimllm,4-bit,English,0.967532,0.908377,0.814802
1,Qwen/Qwen3-8B,slimllm,2-bit,Tamil,0.723377,0.814136,0.629153
26,Qwen/Qwen3-8B,slimllm,2-bit,Tamil,0.688312,0.848168,0.577740
27,Qwen/Qwen3-8B,slimllm,2-bit,Tamil,0.705195,0.790576,0.596384
6,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,0.966234,0.887435,0.814124
32,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,0.971429,0.903141,0.843559
33,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,0.954545,0.903141,0.811073
17,Qwen/Qwen3-8B,slimllm,4-bit,Tamil,0.967532,0.897906,0.816412
2,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,0.818182,0.599476,0.780282
28,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,0.728571,0.560209,0.741073
29,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,0.706494,0.583770,0.766299
8,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,0.970130,0.827225,0.844237
34,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,0.972727,0.801047,0.837655
35,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,0.966234,0.861257,0.833503
18,Qwen/Qwen3-8B,slimllm,4-bit,Chinese,0.967532,0.890052,0.813333
12,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,0.936364,0.552356,0.558870
42,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,0.946753,0.628272,0.557090
43,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,0.933766,0.589005,0.558870
14,CohereLabs/aya-expanse-8b,slimllm,3-bit,English,0.946753,0.887435,0.756158
22,CohereLabs/aya-expanse-8b,slimllm,4-bit,English,0.961039,0.924084,0.786045
13,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,0.735065,0.743455,0.733757
44,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,0.780519,0.534031,0.751158
45,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,0.781818,0.531414,0.740791
15,CohereLabs/aya-expanse-8b,slimllm,3-bit,Chinese,0.940260,0.866492,0.773814
23,CohereLabs/aya-expanse-8b,slimllm,4-bit,Chinese,0.957143,0.924084,0.779124
3,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,English,0.824675,0.782723,0.523051
36,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,English,0.854545,0.780105,0.536751
37,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,English,0.809091,0.871728,0.513531
9,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,English,0.977922,0.455497,0.758588
19,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,English,0.983117,0.895288,0.793475
5,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Tamil,0.703896,0.387435,0.535452
38,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Tamil,0.735065,0.594241,0.562119
39,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Tamil,0.746753,0.397906,0.545847
10,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Tamil,0.754545,0.795812,0.546751
20,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Tamil,0.984416,0.905759,0.791695
7,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,0.770130,0.709424,0.538362
40,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,0.753247,0.787958,0.570904
41,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,0.724675,0.866492,0.548107
11,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Chinese,0.963636,0.842932,0.805847
21,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Chinese,0.974026,0.908377,0.793249

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng,tam,zhoblimp
4,Qwen/Qwen3-8B,tacq,2-bit,English,0.962338,0.675393,0.764576
27,Qwen/Qwen3-8B,tacq,2-bit,English,0.979221,0.489529,0.777542
28,Qwen/Qwen3-8B,tacq,2-bit,English,0.968831,0.552356,0.786554
0,Qwen/Qwen3-8B,tacq,3-bit,English,0.971429,0.816754,0.817599
33,Qwen/Qwen3-8B,tacq,3-bit,English,0.968831,0.835079,0.809266
34,Qwen/Qwen3-8B,tacq,3-bit,English,0.970130,0.808901,0.809322
18,Qwen/Qwen3-8B,tacq,4-bit,English,0.970130,0.934555,0.810791
6,Qwen/Qwen3-8B,tacq,2-bit,Tamil,0.958442,0.869110,0.792062
29,Qwen/Qwen3-8B,tacq,2-bit,Tamil,0.962338,0.871728,0.804633
30,Qwen/Qwen3-8B,tacq,2-bit,Tamil,0.953247,0.861257,0.807034
1,Qwen/Qwen3-8B,tacq,3-bit,Tamil,0.962338,0.910995,0.812429
35,Qwen/Qwen3-8B,tacq,3-bit,Tamil,0.967532,0.900524,0.807175
36,Qwen/Qwen3-8B,tacq,3-bit,Tamil,0.967532,0.895288,0.795339
19,Qwen/Qwen3-8B,tacq,4-bit,Tamil,0.970130,0.900524,0.805367
8,Qwen/Qwen3-8B,tacq,2-bit,Chinese,0.942857,0.714660,0.840960
31,Qwen/Qwen3-8B,tacq,2-bit,Chinese,0.938961,0.560209,0.857966
32,Qwen/Qwen3-8B,tacq,2-bit,Chinese,0.940260,0.638743,0.849463
3,Qwen/Qwen3-8B,tacq,3-bit,Chinese,0.968831,0.806283,0.840734
37,Qwen/Qwen3-8B,tacq,3-bit,Chinese,0.970130,0.835079,0.829633
38,Qwen/Qwen3-8B,tacq,3-bit,Chinese,0.966234,0.840314,0.842655
20,Qwen/Qwen3-8B,tacq,4-bit,Chinese,0.974026,0.887435,0.820000
12,CohereLabs/aya-expanse-8b,tacq,2-bit,English,0.971429,0.667539,0.701017
45,CohereLabs/aya-expanse-8b,tacq,2-bit,English,0.975325,0.602094,0.712740
46,CohereLabs/aya-expanse-8b,tacq,2-bit,English,0.971429,0.748691,0.717514
15,CohereLabs/aya-expanse-8b,tacq,3-bit,English,0.970130,0.897906,0.772203
24,CohereLabs/aya-expanse-8b,tacq,4-bit,English,0.959740,0.921466,0.786949
13,CohereLabs/aya-expanse-8b,tacq,2-bit,Tamil,0.931169,0.897906,0.745226
47,CohereLabs/aya-expanse-8b,tacq,2-bit,Tamil,0.946753,0.882199,0.766723
48,CohereLabs/aya-expanse-8b,tacq,2-bit,Tamil,0.948052,0.903141,0.745678
16,CohereLabs/aya-expanse-8b,tacq,3-bit,Tamil,0.944156,0.924084,0.768785
25,CohereLabs/aya-expanse-8b,tacq,4-bit,Tamil,0.958442,0.924084,0.785141
14,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,0.948052,0.748691,0.786384
49,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,0.935065,0.628272,0.797373
50,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,0.945455,0.829843,0.782062
17,CohereLabs/aya-expanse-8b,tacq,3-bit,Chinese,0.953247,0.913613,0.786412
26,CohereLabs/aya-expanse-8b,tacq,4-bit,Chinese,0.959740,0.921466,0.785424
2,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,English,0.971429,0.748691,0.593164
39,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,English,0.972727,0.861257,0.605706
40,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,English,0.971429,0.759162,0.594124
9,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,English,0.980519,0.819372,0.823164
21,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,English,0.984416,0.882199,0.782006
5,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Tamil,0.958442,0.903141,0.656158
41,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Tamil,0.957143,0.910995,0.669011
42,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Tamil,0.954545,0.916230,0.639350
10,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Tamil,0.972727,0.924084,0.801356
22,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Tamil,0.981818,0.934555,0.804237
7,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,0.946753,0.612565,0.767401
43,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,0.958442,0.714660,0.800311
44,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,0.953247,0.688482,0.770960
11,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Chinese,0.972727,0.892670,0.828814
23,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Chinese,0.983117,0.903141,0.794040

Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng,tam,zhoblimp
12,Qwen/Qwen3-8B,gptq,English,2-bit,0.678355,0.650087,0.560311
13,Qwen/Qwen3-8B,gptq,English,3-bit,0.972294,0.776614,0.808352
14,Qwen/Qwen3-8B,gptq,English,4-bit,0.997403,0.895288,1.000000
15,Qwen/Qwen3-8B,gptq,Tamil,2-bit,0.610390,0.762653,0.572599
16,Qwen/Qwen3-8B,gptq,Tamil,3-bit,0.973160,0.915358,0.824802
17,Qwen/Qwen3-8B,gptq,Tamil,4-bit,0.997403,0.921466,1.000000
9,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.617749,0.581152,0.588183
10,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.958442,0.813264,0.800443
11,Qwen/Qwen3-8B,gptq,Chinese,4-bit,0.996104,0.926702,1.000000
3,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.815152,0.547993,0.574209
4,CohereLabs/aya-expanse-8b,gptq,English,3-bit,0.967532,0.824607,0.760537
5,CohereLabs/aya-expanse-8b,gptq,English,4-bit,0.966234,0.913613,0.779661
6,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,0.761472,0.804538,0.573230
7,CohereLabs/aya-expanse-8b,gptq,Tamil,3-bit,0.942857,0.897906,0.712203
8,CohereLabs/aya-expanse-8b,gptq,Tamil,4-bit,0.967532,0.918848,0.791384
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.739394,0.576789,0.607740
1,CohereLabs/aya-expanse-8b,gptq,Chinese,3-bit,0.964935,0.840314,0.785904
2,CohereLabs/aya-expanse-8b,gptq,Chinese,4-bit,0.968831,0.931937,0.791017
21,meta-llama/Llama-3.1-8B-Instruct,gptq,English,2-bit,0.759307,0.748691,0.550932
22,meta-llama/Llama-3.1-8B-Instruct,gptq,English,3-bit,0.963636,0.816754,0.774689
23,meta-llama/Llama-3.1-8B-Instruct,gptq,English,4-bit,0.972727,0.913613,0.793249
24,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,2-bit,0.690043,0.688482,0.551968
25,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,3-bit,0.957143,0.934555,0.748362
26,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,4-bit,0.975325,0.918848,0.803220
18,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,2-bit,0.711255,0.727749,0.578776
19,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,3-bit,0.967532,0.814136,0.793362
20,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,4-bit,0.975325,0.934555,0.795904

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng,tam,zhoblimp
12,Qwen/Qwen3-8B,gptq,English,2-bit,0.031906,0.027065,0.001784
13,Qwen/Qwen3-8B,gptq,English,3-bit,0.004782,0.033410,0.005170
15,Qwen/Qwen3-8B,gptq,Tamil,2-bit,0.015034,0.039547,0.008012
16,Qwen/Qwen3-8B,gptq,Tamil,3-bit,0.002669,0.011772,0.002260
9,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.019243,0.045992,0.012311
10,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.009719,0.001234,0.015651
3,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.019705,0.067332,0.009508
6,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,0.008829,0.024308,0.009575
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.026154,0.075307,0.011838

SLIM

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng,tam,zhoblimp
9,Qwen/Qwen3-8B,slimllm,English,2-bit,0.929870,0.616056,0.580047
10,Qwen/Qwen3-8B,slimllm,English,3-bit,0.965368,0.794939,0.793814
11,Qwen/Qwen3-8B,slimllm,English,4-bit,0.967532,0.908377,0.814802
12,Qwen/Qwen3-8B,slimllm,Tamil,2-bit,0.705628,0.817627,0.601092
13,Qwen/Qwen3-8B,slimllm,Tamil,3-bit,0.964069,0.897906,0.822919
14,Qwen/Qwen3-8B,slimllm,Tamil,4-bit,0.967532,0.897906,0.816412
6,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.751082,0.581152,0.762552
7,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.969697,0.829843,0.838465
8,Qwen/Qwen3-8B,slimllm,Chinese,4-bit,0.967532,0.890052,0.813333
3,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.938961,0.589878,0.558277
4,CohereLabs/aya-expanse-8b,slimllm,English,3-bit,0.946753,0.887435,0.756158
5,CohereLabs/aya-expanse-8b,slimllm,English,4-bit,0.961039,0.924084,0.786045
0,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.765801,0.602967,0.741902
1,CohereLabs/aya-expanse-8b,slimllm,Chinese,3-bit,0.940260,0.866492,0.773814
2,CohereLabs/aya-expanse-8b,slimllm,Chinese,4-bit,0.957143,0.924084,0.779124
18,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,2-bit,0.829437,0.811518,0.524444
19,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,3-bit,0.977922,0.455497,0.758588
20,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,4-bit,0.983117,0.895288,0.793475
21,meta-llama/Llama-3.1-8B-Instruct,slimllm,Tamil,2-bit,0.728571,0.459860,0.547806
22,meta-llama/Llama-3.1-8B-Instruct,slimllm,Tamil,3-bit,0.754545,0.795812,0.546751
23,meta-llama/Llama-3.1-8B-Instruct,slimllm,Tamil,4-bit,0.984416,0.905759,0.791695
15,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,2-bit,0.749351,0.787958,0.552458
16,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,3-bit,0.963636,0.842932,0.805847
17,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,4-bit,0.974026,0.908377,0.793249

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng,tam,zhoblimp
9,Qwen/Qwen3-8B,slimllm,English,2-bit,0.005904,0.097349,0.006348
10,Qwen/Qwen3-8B,slimllm,English,3-bit,0.005011,0.063202,0.007208
12,Qwen/Qwen3-8B,slimllm,Tamil,2-bit,0.014318,0.023641,0.021251
13,Qwen/Qwen3-8B,slimllm,Tamil,3-bit,0.007060,0.007404,0.014648
6,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.048295,0.016137,0.016225
7,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.002669,0.024650,0.004420
3,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.005611,0.030999,0.000839
0,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.021740,0.099346,0.007147

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng,tam,zhoblimp
12,Qwen/Qwen3-8B,tacq,English,2-bit,0.970130,0.572426,0.776224
13,Qwen/Qwen3-8B,tacq,English,3-bit,0.970130,0.820244,0.812062
14,Qwen/Qwen3-8B,tacq,English,4-bit,0.970130,0.934555,0.810791
15,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.958009,0.867365,0.801243
16,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.965801,0.902269,0.804981
17,Qwen/Qwen3-8B,tacq,Tamil,4-bit,0.970130,0.900524,0.805367
9,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.940693,0.637871,0.849463
10,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.968398,0.827225,0.837674
11,Qwen/Qwen3-8B,tacq,Chinese,4-bit,0.974026,0.887435,0.820000
3,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.972727,0.672775,0.710424
4,CohereLabs/aya-expanse-8b,tacq,English,3-bit,0.970130,0.897906,0.772203
5,CohereLabs/aya-expanse-8b,tacq,English,4-bit,0.959740,0.921466,0.786949
6,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,0.941991,0.894415,0.752542
7,CohereLabs/aya-expanse-8b,tacq,Tamil,3-bit,0.944156,0.924084,0.768785
8,CohereLabs/aya-expanse-8b,tacq,Tamil,4-bit,0.958442,0.924084,0.785141
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.942857,0.735602,0.788606
1,CohereLabs/aya-expanse-8b,tacq,Chinese,3-bit,0.953247,0.913613,0.786412
2,CohereLabs/aya-expanse-8b,tacq,Chinese,4-bit,0.959740,0.921466,0.785424
21,meta-llama/Llama-3.1-8B-Instruct,tacq,English,2-bit,0.971861,0.789703,0.597665
22,meta-llama/Llama-3.1-8B-Instruct,tacq,English,3-bit,0.980519,0.819372,0.823164
23,meta-llama/Llama-3.1-8B-Instruct,tacq,English,4-bit,0.984416,0.882199,0.782006
24,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,2-bit,0.956710,0.910122,0.654840
25,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,3-bit,0.972727,0.924084,0.801356
26,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,4-bit,0.981818,0.934555,0.804237
18,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,2-bit,0.952814,0.671902,0.779557
19,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,3-bit,0.972727,0.892670,0.828814
20,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,4-bit,0.983117,0.903141,0.794040

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng,tam,zhoblimp
12,Qwen/Qwen3-8B,tacq,English,2-bit,0.006953,0.077194,0.009021
13,Qwen/Qwen3-8B,tacq,English,3-bit,0.001060,0.010968,0.003915
15,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.003724,0.004449,0.006565
16,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.002449,0.006530,0.007148
9,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.001620,0.063057,0.006943
10,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.001620,0.014962,0.005740
3,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.001837,0.059962,0.006931
6,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,0.007671,0.008899,0.010029
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.005611,0.082810,0.006445

[[0, 'EN'], [1, 'TA'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ZH']
mean_ppl

eng         2.386580
tam         2.014834
zhoblimp    1.943691
dtype: float64

[[0, 'EN'], [1, 'TA'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ZH']
mean_ppl

eng         2.899134
tam         2.522688
zhoblimp    2.455198
dtype: float64

[[0, 'EN'], [1, 'TA'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ZH']
mean_ppl

/tmp/ipykernel_2704/4051798515.py:259: RuntimeWarning:

Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.

/tmp/ipykernel_2704/4051798515.py:278: RuntimeWarning:

Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.

eng         2.902597
tam         2.696335
zhoblimp    2.444548
dtype: float64

[[0, 'EN'], [1, 'TA'], [4, 'ZH']]
where TA located
['EN' 'ZH']
mean_ppl

eng         1.704762
tam         1.192845
zhoblimp    1.300179
dtype: float64

[[0, 'EN'], [1, 'TA'], [4, 'ZH']]
where TA located
['EN' 'ZH']
mean_ppl

eng         1.887013
tam         1.753927
zhoblimp    1.529972
dtype: float64

[[0, 'EN'], [1, 'TA'], [4, 'ZH']]
where TA located
['EN' 'ZH']
mean_ppl

/tmp/ipykernel_2704/4051798515.py:278: RuntimeWarning:

Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.

eng         1.918182
tam         1.848168
zhoblimp    1.565169
dtype: float64

[[0, 'EN'], [1, 'TA'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ZH']
mean_ppl

eng         2.307359
tam         2.059337
zhoblimp    1.624708
dtype: float64

[[0, 'EN'], [1, 'TA'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ZH']
mean_ppl

eng         2.696104
tam         2.094241
zhoblimp    2.111186
dtype: float64

[[0, 'EN'], [1, 'TA'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ZH']
mean_ppl

eng         2.941558
tam         2.709424
zhoblimp    2.378418
dtype: float64

In [ ]:
eval_languages = ["eng", "tam", "idn", "swa", "zhoblimp"]
# eval_languages = ["eng", "tam", "idn"]

# Initialize the W&B API
api = Api()

quantization_technique = "ALL"
# bit = 8
num_samples = 128
eval_dataset = "MultiBlimp"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.num_calibration_samples": num_samples},
                            {"config.evaluation_dataset": f"{eval_dataset.lower()}"},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"$not": {"config.calibration_language": "WuuChinese"}},
                            {"$not": {"$and": [{"created_at": {"$lt": "2026-03-01"}}, {"config.quantization_technique": "gptq"}]}},
                            {"created_at": {"$gt": "2026-07-01"}},
                            # {"$not": {"config.calibration_language": "Swahili"}},
                            # {"$not": {"config.calibration_language": "Chinese"}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.evaluation_dataset": eval_dataset.lower()},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            {"config.output_type": "multiple_choice"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              {"config.evaluation_dataset": eval_dataset.lower()},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                              {"created_at": {"$gt": "2026-07-01"}},
                          ]}
                      ]}
                  )

  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-14B"], quantization_technique=quantization_technique, bits=["2-bit", "3-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False, vertical_spacing=0.038, horizontal_spacing=0.040, random_guess_score=0.5, write_pdf="multiblimp_14b_barplot_reduced_errorbar_final.pdf")

Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng,tam,idn,swa,zhoblimp
0,Qwen/Qwen3-14B,gptq,2-bit,English,0.789610,0.672775,0.528947,0.512125,0.571328
3,Qwen/Qwen3-14B,gptq,3-bit,English,0.972727,0.866492,0.628947,0.461125,0.811356
2,Qwen/Qwen3-14B,gptq,2-bit,Tamil,0.661039,0.856021,0.494737,0.492625,0.577147
5,Qwen/Qwen3-14B,gptq,3-bit,Tamil,0.959740,0.910995,0.626316,0.471250,0.755763
1,Qwen/Qwen3-14B,gptq,2-bit,Indonesian,0.689610,0.523560,0.518421,0.481250,0.586186
4,Qwen/Qwen3-14B,gptq,3-bit,Indonesian,0.970130,0.905759,0.607895,0.457500,0.759124
8,Qwen/Qwen3-14B,gptq,2-bit,Swahili,0.618182,0.612565,0.521053,0.473375,0.579435
6,Qwen/Qwen3-14B,gptq,3-bit,Swahili,0.967532,0.884817,0.610526,0.465750,0.769181
9,Qwen/Qwen3-14B,gptq,2-bit,Chinese,0.693506,0.651832,0.555263,0.498875,0.611469
7,Qwen/Qwen3-14B,gptq,3-bit,Chinese,0.966234,0.882199,0.600000,0.478750,0.802062

Empty DataFrame
Columns: [Base Model, Quantization Technique, Bit Width, Calibration Language, eng, tam, idn, swa, zhoblimp]
Index: []

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng,tam,idn,swa,zhoblimp
0,Qwen/Qwen3-14B,tacq,2-bit,English,0.980519,0.678010,0.505263,0.476500,0.793616
3,Qwen/Qwen3-14B,tacq,3-bit,English,0.963636,0.895288,0.607895,0.441875,0.768079
2,Qwen/Qwen3-14B,tacq,2-bit,Tamil,0.958442,0.910995,0.526316,0.456625,0.825734
5,Qwen/Qwen3-14B,tacq,3-bit,Tamil,0.972727,0.918848,0.623684,0.474125,0.781554
1,Qwen/Qwen3-14B,tacq,2-bit,Indonesian,0.961039,0.636126,0.621053,0.463250,0.834633
4,Qwen/Qwen3-14B,tacq,3-bit,Indonesian,0.955844,0.897906,0.607895,0.476375,0.769661
6,Qwen/Qwen3-14B,tacq,2-bit,Swahili,0.967532,0.738220,0.550000,0.443875,0.818192
8,Qwen/Qwen3-14B,tacq,3-bit,Swahili,0.964935,0.910995,0.626316,0.471625,0.784605
7,Qwen/Qwen3-14B,tacq,2-bit,Chinese,0.962338,0.544503,0.442105,0.477375,0.855395
9,Qwen/Qwen3-14B,tacq,3-bit,Chinese,0.968831,0.903141,0.615789,0.470375,0.790876

Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng,tam,idn,swa,zhoblimp
2,Qwen/Qwen3-14B,gptq,English,2-bit,0.789610,0.672775,0.528947,0.512125,0.571328
3,Qwen/Qwen3-14B,gptq,English,3-bit,0.972727,0.866492,0.628947,0.461125,0.811356
8,Qwen/Qwen3-14B,gptq,Tamil,2-bit,0.661039,0.856021,0.494737,0.492625,0.577147
9,Qwen/Qwen3-14B,gptq,Tamil,3-bit,0.959740,0.910995,0.626316,0.471250,0.755763
4,Qwen/Qwen3-14B,gptq,Indonesian,2-bit,0.689610,0.523560,0.518421,0.481250,0.586186
5,Qwen/Qwen3-14B,gptq,Indonesian,3-bit,0.970130,0.905759,0.607895,0.457500,0.759124
6,Qwen/Qwen3-14B,gptq,Swahili,2-bit,0.618182,0.612565,0.521053,0.473375,0.579435
7,Qwen/Qwen3-14B,gptq,Swahili,3-bit,0.967532,0.884817,0.610526,0.465750,0.769181
0,Qwen/Qwen3-14B,gptq,Chinese,2-bit,0.693506,0.651832,0.555263,0.498875,0.611469
1,Qwen/Qwen3-14B,gptq,Chinese,3-bit,0.966234,0.882199,0.600000,0.478750,0.802062

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng, tam, idn, swa, zhoblimp]
Index: []

SLIM

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng, tam, idn, swa, zhoblimp]
Index: []

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng, tam, idn, swa, zhoblimp]
Index: []

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng,tam,idn,swa,zhoblimp
2,Qwen/Qwen3-14B,tacq,English,2-bit,0.980519,0.678010,0.505263,0.476500,0.793616
3,Qwen/Qwen3-14B,tacq,English,3-bit,0.963636,0.895288,0.607895,0.441875,0.768079
8,Qwen/Qwen3-14B,tacq,Tamil,2-bit,0.958442,0.910995,0.526316,0.456625,0.825734
9,Qwen/Qwen3-14B,tacq,Tamil,3-bit,0.972727,0.918848,0.623684,0.474125,0.781554
4,Qwen/Qwen3-14B,tacq,Indonesian,2-bit,0.961039,0.636126,0.621053,0.463250,0.834633
5,Qwen/Qwen3-14B,tacq,Indonesian,3-bit,0.955844,0.897906,0.607895,0.476375,0.769661
6,Qwen/Qwen3-14B,tacq,Swahili,2-bit,0.967532,0.738220,0.550000,0.443875,0.818192
7,Qwen/Qwen3-14B,tacq,Swahili,3-bit,0.964935,0.910995,0.626316,0.471625,0.784605
0,Qwen/Qwen3-14B,tacq,Chinese,2-bit,0.962338,0.544503,0.442105,0.477375,0.855395
1,Qwen/Qwen3-14B,tacq,Chinese,3-bit,0.968831,0.903141,0.615789,0.470375,0.790876

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng, tam, idn, swa, zhoblimp]
Index: []

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
[]
[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
[]

### Belebele Bar

In [ ]:
# eval_languages = ["eng_Latn", "tam_Taml", "ind_Latn", "swh_Latn", "zho_Hans"]
eval_languages = ["eng_Latn", "tam_Taml", "ind_Latn", "swh_Latn", "zho_Hans"]

# Initialize the W&B API
api = Api()

quantization_technique = "ALL"
# bit = 8
num_samples = 128
eval_dataset = "Belebele"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.num_calibration_samples": num_samples},
                            {"$or": [
                                {"$and": [
                                  {"config.evaluation_dataset": f"{eval_dataset.lower()}"},
                                  {"created_at": {"$lt": "2026-07-01"}},
                                ]},
                                {"$and": [
                                  {"$or": [
                                    {"config.evaluation_dataset": f"{eval_dataset.lower()}-1000"},
                                    {"config.evaluation_dataset": f"{eval_dataset.lower()}-2000"},
                                  ]},
                                  {"created_at": {"$gt": "2026-07-01"}},
                                ]},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"$not": {"config.calibration_language": "WuuChinese"}},
                            {"$not": {"$and": [{"created_at": {"$lt": "2026-03-01"}}, {"config.quantization_technique": "gptq"}]}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.evaluation_dataset": eval_dataset.lower()},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              {"config.evaluation_dataset": eval_dataset.lower()},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"created_at": {"$lt": "2026-07-01"}},
                          ]}
                      ]}
                  )

  # visualize_delta_unquantized_globalmmlulite(eval_languages=eval_languages, runs=runs, base_model=base_model, quantization_technique=quantization_technique, bit_width=bit, eval_dataset=eval_dataset, custom_title="")
  # visualize_delta_unquantized_deliver_bar(eval_languages=eval_languages, runs=runs, base_model=base_model, quantization_technique=quantization_technique, bits=["2-bit", "3-bit", "4-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False)
  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique=quantization_technique, bits=["2-bit", "3-bit", "4-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False, vertical_spacing=0.05, horizontal_spacing=0.025, random_guess_score=0.25, write_pdf="belebele_barplot_errorbar_final.pdf")

Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,zho_Hans
0,Qwen/Qwen3-8B,gptq,2-bit,English,0.223333,0.245556,0.257778,0.240000,0.233333
45,Qwen/Qwen3-8B,gptq,2-bit,English,0.215556,0.244444,0.245556,0.245556,0.246667
46,Qwen/Qwen3-8B,gptq,2-bit,English,0.253333,0.235556,0.254444,0.252222,0.264444
5,Qwen/Qwen3-8B,gptq,3-bit,English,0.856667,0.448889,0.728889,0.336667,0.814444
55,Qwen/Qwen3-8B,gptq,3-bit,English,0.863333,0.465556,0.771111,0.365556,0.837778
...,...,...,...,...,...,...,...,...,...
19,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Chinese,0.240000,0.260000,0.244444,0.255556,0.266667
73,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Chinese,0.246667,0.260000,0.272222,0.237778,0.247778
74,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Chinese,0.241111,0.234444,0.222222,0.256667,0.232222
24,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Chinese,0.735556,0.225556,0.461111,0.284444,0.750000
29,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Chinese,0.873333,0.537778,0.738889,0.507778,0.811111

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,zho_Hans
15,Qwen/Qwen3-8B,slimllm,2-bit,English,0.230000,0.233333,0.228889,0.230000,0.228889
42,Qwen/Qwen3-8B,slimllm,2-bit,English,0.228889,0.228889,0.228889,0.226667,0.228889
43,Qwen/Qwen3-8B,slimllm,2-bit,English,0.226667,0.228889,0.230000,0.228889,0.227778
20,Qwen/Qwen3-8B,slimllm,3-bit,English,0.851111,0.410000,0.731111,0.335556,0.831111
52,Qwen/Qwen3-8B,slimllm,3-bit,English,0.870000,0.437778,0.754444,0.338889,0.836667
...,...,...,...,...,...,...,...,...,...
4,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,0.226667,0.250000,0.273333,0.241111,0.227778
70,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,0.221111,0.231111,0.224444,0.243333,0.225556
71,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,0.222222,0.263333,0.264444,0.230000,0.251111
9,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Chinese,0.681111,0.296667,0.491111,0.287778,0.671111
14,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Chinese,0.860000,0.472222,0.730000,0.485556,0.802222

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,zho_Hans
15,Qwen/Qwen3-8B,tacq,2-bit,English,0.587778,0.230000,0.347778,0.230000,0.540000
45,Qwen/Qwen3-8B,tacq,2-bit,English,0.577778,0.268889,0.352222,0.275556,0.503333
46,Qwen/Qwen3-8B,tacq,2-bit,English,0.626667,0.233333,0.351111,0.244444,0.530000
20,Qwen/Qwen3-8B,tacq,3-bit,English,0.904444,0.563333,0.831111,0.421111,0.867778
55,Qwen/Qwen3-8B,tacq,3-bit,English,0.911111,0.564444,0.807778,0.418889,0.862222
...,...,...,...,...,...,...,...,...,...
4,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,0.235556,0.228889,0.231111,0.228889,0.247778
73,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,0.302222,0.228889,0.227778,0.233333,0.342222
74,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,0.263333,0.223333,0.235556,0.257778,0.260000
9,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Chinese,0.804444,0.435556,0.675556,0.391111,0.766667
14,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Chinese,0.876667,0.540000,0.750000,0.542222,0.834444

Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,zho_Hans
18,Qwen/Qwen3-8B,gptq,English,2-bit,0.230741,0.241852,0.252593,0.245926,0.248148
19,Qwen/Qwen3-8B,gptq,English,3-bit,0.852593,0.451852,0.757407,0.350370,0.816667
20,Qwen/Qwen3-8B,gptq,English,4-bit,0.906667,0.685556,0.857778,0.523333,0.872222
27,Qwen/Qwen3-8B,gptq,Tamil,2-bit,0.255185,0.238519,0.250370,0.234815,0.245926
28,Qwen/Qwen3-8B,gptq,Tamil,3-bit,0.814074,0.607778,0.730370,0.347037,0.800741
29,Qwen/Qwen3-8B,gptq,Tamil,4-bit,0.904444,0.700000,0.851111,0.505556,0.868889
21,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,0.242222,0.242963,0.234444,0.247037,0.241852
22,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,0.839630,0.498148,0.777037,0.373333,0.799259
23,Qwen/Qwen3-8B,gptq,Indonesian,4-bit,0.914444,0.683333,0.861111,0.496667,0.857778
24,Qwen/Qwen3-8B,gptq,Swahili,2-bit,0.244815,0.233704,0.248148,0.235185,0.252963
25,Qwen/Qwen3-8B,gptq,Swahili,3-bit,0.842222,0.530741,0.775556,0.455926,0.813704
26,Qwen/Qwen3-8B,gptq,Swahili,4-bit,0.904444,0.683333,0.850000,0.527778,0.868889
15,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.234444,0.221111,0.247407,0.250370,0.244444
16,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.848148,0.479630,0.776296,0.346667,0.832593
17,Qwen/Qwen3-8B,gptq,Chinese,4-bit,0.905556,0.695556,0.856667,0.524444,0.865556
3,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.236667,0.253333,0.238889,0.265556,0.260000
4,CohereLabs/aya-expanse-8b,gptq,English,3-bit,0.694444,0.337778,0.608889,0.296667,0.658889
5,CohereLabs/aya-expanse-8b,gptq,English,4-bit,0.791111,0.436667,0.700000,0.336667,0.781111
12,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,0.246667,0.260000,0.247778,0.266667,0.258889
13,CohereLabs/aya-expanse-8b,gptq,Tamil,3-bit,0.660000,0.400000,0.486667,0.255556,0.542222
14,CohereLabs/aya-expanse-8b,gptq,Tamil,4-bit,0.776667,0.428889,0.710000,0.316667,0.775556
6,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,0.227778,0.254444,0.238889,0.241111,0.254444
7,CohereLabs/aya-expanse-8b,gptq,Indonesian,3-bit,0.721111,0.353333,0.634444,0.334444,0.690000
8,CohereLabs/aya-expanse-8b,gptq,Indonesian,4-bit,0.774444,0.448889,0.706667,0.337778,0.780000
9,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,0.228889,0.251111,0.252222,0.238889,0.237778
10,CohereLabs/aya-expanse-8b,gptq,Swahili,3-bit,0.658889,0.324444,0.555556,0.285556,0.642222
11,CohereLabs/aya-expanse-8b,gptq,Swahili,4-bit,0.776667,0.430000,0.702222,0.324444,0.776667
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.243333,0.222222,0.216667,0.242222,0.243333
1,CohereLabs/aya-expanse-8b,gptq,Chinese,3-bit,0.662222,0.351111,0.603333,0.288889,0.690000
2,CohereLabs/aya-expanse-8b,gptq,Chinese,4-bit,0.785556,0.434444,0.727778,0.335556,0.778889
33,meta-llama/Llama-3.1-8B-Instruct,gptq,English,2-bit,0.241852,0.253333,0.252222,0.240370,0.246296
34,meta-llama/Llama-3.1-8B-Instruct,gptq,English,3-bit,0.790000,0.233333,0.491111,0.283333,0.538889
35,meta-llama/Llama-3.1-8B-Instruct,gptq,English,4-bit,0.877778,0.528889,0.751111,0.498889,0.844444
42,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,2-bit,0.240370,0.222593,0.238889,0.258148,0.240370
43,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,3-bit,0.766667,0.436667,0.586667,0.326667,0.677778
44,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,4-bit,0.877778,0.585556,0.775556,0.511111,0.845556
36,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,2-bit,0.237407,0.240741,0.247778,0.255185,0.225556
37,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,3-bit,0.724444,0.241111,0.626667,0.358889,0.650000
38,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,4-bit,0.885556,0.554444,0.760000,0.530000,0.827778
39,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,2-bit,0.246296,0.252222,0.264444,0.257037,0.259259
40,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,3-bit,0.670000,0.254444,0.537778,0.388889,0.575556
41,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,4-bit,0.868889,0.550000,0.744444,0.540000,0.825556
30,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,2-bit,0.242593,0.251481,0.246296,0.250000,0.248889
31,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,3-bit,0.735556,0.225556,0.461111,0.284444,0.750000
32,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,4-bit,0.873333,0.537778,0.738889,0.507778,0.811111

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,zho_Hans
18,Qwen/Qwen3-8B,gptq,English,2-bit,0.016288,0.004475,0.005159,0.004997,0.012744
19,Qwen/Qwen3-8B,gptq,English,3-bit,0.010823,0.010197,0.020171,0.011840,0.016405
27,Qwen/Qwen3-8B,gptq,Tamil,2-bit,0.011665,0.009087,0.012081,0.002772,0.005159
28,Qwen/Qwen3-8B,gptq,Tamil,3-bit,0.012873,0.019647,0.024635,0.008381,0.014778
21,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,0.002400,0.015432,0.010696,0.017317,0.002619
22,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,0.029902,0.020293,0.023940,0.025548,0.027612
24,Qwen/Qwen3-8B,gptq,Swahili,2-bit,0.012250,0.010034,0.022777,0.010974,0.007716
25,Qwen/Qwen3-8B,gptq,Swahili,3-bit,0.011898,0.015458,0.005949,0.014411,0.016263
15,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.005051,0.012205,0.011559,0.004997,0.003271
16,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.012250,0.026439,0.014239,0.032241,0.021494
3,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
12,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
6,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
9,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000

SLIM

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,zho_Hans
15,Qwen/Qwen3-8B,slimllm,English,2-bit,0.228519,0.230370,0.229259,0.228519,0.228519
16,Qwen/Qwen3-8B,slimllm,English,3-bit,0.868889,0.424074,0.758519,0.347778,0.833333
17,Qwen/Qwen3-8B,slimllm,English,4-bit,0.911111,0.671111,0.852222,0.493333,0.875556
24,Qwen/Qwen3-8B,slimllm,Tamil,2-bit,0.226296,0.230000,0.233704,0.238519,0.236296
25,Qwen/Qwen3-8B,slimllm,Tamil,3-bit,0.841481,0.641852,0.768889,0.400000,0.822963
26,Qwen/Qwen3-8B,slimllm,Tamil,4-bit,0.910000,0.711111,0.852222,0.505556,0.867778
18,Qwen/Qwen3-8B,slimllm,Indonesian,2-bit,0.233333,0.233333,0.237407,0.231852,0.226296
19,Qwen/Qwen3-8B,slimllm,Indonesian,3-bit,0.862222,0.507037,0.794444,0.396667,0.832593
20,Qwen/Qwen3-8B,slimllm,Indonesian,4-bit,0.917778,0.686667,0.851111,0.513333,0.873333
21,Qwen/Qwen3-8B,slimllm,Swahili,2-bit,0.229259,0.231481,0.230741,0.228889,0.231481
22,Qwen/Qwen3-8B,slimllm,Swahili,3-bit,0.837407,0.530370,0.770741,0.470000,0.811111
23,Qwen/Qwen3-8B,slimllm,Swahili,4-bit,0.910000,0.678889,0.865556,0.548889,0.873333
12,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.229630,0.229630,0.231111,0.228889,0.229259
13,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.841111,0.477037,0.751852,0.359630,0.836296
14,Qwen/Qwen3-8B,slimllm,Chinese,4-bit,0.910000,0.680000,0.863333,0.502222,0.874444
3,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.263333,0.225926,0.234444,0.235556,0.235556
4,CohereLabs/aya-expanse-8b,slimllm,English,3-bit,0.656667,0.304444,0.580000,0.286667,0.662222
5,CohereLabs/aya-expanse-8b,slimllm,English,4-bit,0.787778,0.443333,0.740000,0.322222,0.782222
6,CohereLabs/aya-expanse-8b,slimllm,Indonesian,2-bit,0.271852,0.243333,0.267778,0.252222,0.253333
7,CohereLabs/aya-expanse-8b,slimllm,Indonesian,3-bit,0.696667,0.354444,0.654444,0.320000,0.705556
8,CohereLabs/aya-expanse-8b,slimllm,Indonesian,4-bit,0.782222,0.443333,0.707778,0.343333,0.783333
9,CohereLabs/aya-expanse-8b,slimllm,Swahili,2-bit,0.250370,0.240370,0.237037,0.229630,0.242593
10,CohereLabs/aya-expanse-8b,slimllm,Swahili,3-bit,0.632222,0.336667,0.562222,0.297778,0.628889
11,CohereLabs/aya-expanse-8b,slimllm,Swahili,4-bit,0.761111,0.436667,0.713333,0.334444,0.767778
0,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.260000,0.235926,0.251481,0.242222,0.266667
1,CohereLabs/aya-expanse-8b,slimllm,Chinese,3-bit,0.672222,0.326667,0.562222,0.262222,0.684444
2,CohereLabs/aya-expanse-8b,slimllm,Chinese,4-bit,0.783333,0.430000,0.735556,0.324444,0.787778
30,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,2-bit,0.237037,0.248889,0.240370,0.237407,0.247037
31,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,3-bit,0.598889,0.224444,0.272222,0.255556,0.375556
32,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,4-bit,0.854444,0.477778,0.716667,0.495556,0.801111
39,meta-llama/Llama-3.1-8B-Instruct,slimllm,Tamil,2-bit,0.230370,0.228519,0.234074,0.243333,0.244815
40,meta-llama/Llama-3.1-8B-Instruct,slimllm,Tamil,3-bit,0.231111,0.246667,0.268889,0.240000,0.228889
41,meta-llama/Llama-3.1-8B-Instruct,slimllm,Tamil,4-bit,0.847778,0.441111,0.641111,0.433333,0.773333
33,meta-llama/Llama-3.1-8B-Instruct,slimllm,Indonesian,2-bit,0.241111,0.270741,0.243704,0.250741,0.226667
34,meta-llama/Llama-3.1-8B-Instruct,slimllm,Indonesian,3-bit,0.674444,0.268889,0.477778,0.292222,0.551111
35,meta-llama/Llama-3.1-8B-Instruct,slimllm,Indonesian,4-bit,0.865556,0.472222,0.714444,0.480000,0.800000
36,meta-llama/Llama-3.1-8B-Instruct,slimllm,Swahili,2-bit,0.265556,0.255185,0.262963,0.264444,0.267778
37,meta-llama/Llama-3.1-8B-Instruct,slimllm,Swahili,3-bit,0.517778,0.232222,0.312222,0.275556,0.263333
38,meta-llama/Llama-3.1-8B-Instruct,slimllm,Swahili,4-bit,0.862222,0.497778,0.742222,0.527778,0.807778
27,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,2-bit,0.223333,0.248148,0.254074,0.238148,0.234815
28,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,3-bit,0.681111,0.296667,0.491111,0.287778,0.671111
29,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,4-bit,0.860000,0.472222,0.730000,0.485556,0.802222

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,zho_Hans
15,Qwen/Qwen3-8B,slimllm,English,2-bit,0.001386,0.002095,0.000524,0.001386,0.000524
16,Qwen/Qwen3-8B,slimllm,English,3-bit,0.014084,0.011343,0.024213,0.014990,0.002400
24,Qwen/Qwen3-8B,slimllm,Tamil,2-bit,0.004091,0.005051,0.009267,0.009443,0.013220
25,Qwen/Qwen3-8B,slimllm,Tamil,3-bit,0.001048,0.002772,0.002722,0.004801,0.009952
18,Qwen/Qwen3-8B,slimllm,Indonesian,2-bit,0.014990,0.003143,0.008232,0.008232,0.008131
19,Qwen/Qwen3-8B,slimllm,Indonesian,3-bit,0.006849,0.002283,0.005949,0.011583,0.005159
21,Qwen/Qwen3-8B,slimllm,Swahili,2-bit,0.002283,0.002916,0.004287,0.001571,0.001889
22,Qwen/Qwen3-8B,slimllm,Swahili,3-bit,0.011559,0.015930,0.009529,0.017847,0.010463
12,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.001386,0.001048,0.003629,0.001571,0.002619
13,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.029856,0.020635,0.011840,0.015982,0.013220
3,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.018212,0.003666,0.006542,0.006849,0.000000
6,CohereLabs/aya-expanse-8b,slimllm,Indonesian,2-bit,0.010747,0.010102,0.007086,0.006849,0.015896
9,CohereLabs/aya-expanse-8b,slimllm,Swahili,2-bit,0.007333,0.004475,0.012841,0.009701,0.004475
0,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.009979,0.004566,0.006175,0.020428,0.008749

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,zho_Hans
18,Qwen/Qwen3-8B,tacq,English,2-bit,0.597407,0.244074,0.350370,0.250000,0.524444
19,Qwen/Qwen3-8B,tacq,English,3-bit,0.903333,0.571852,0.817037,0.427037,0.862222
20,Qwen/Qwen3-8B,tacq,English,4-bit,0.921111,0.682222,0.858889,0.501111,0.877778
27,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.365926,0.341852,0.299259,0.250741,0.399259
28,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.887407,0.680741,0.808519,0.443704,0.845185
29,Qwen/Qwen3-8B,tacq,Tamil,4-bit,0.911111,0.697778,0.853333,0.517778,0.875556
21,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.555556,0.232963,0.533704,0.246667,0.479630
22,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.902593,0.609630,0.835926,0.468889,0.858148
23,Qwen/Qwen3-8B,tacq,Indonesian,4-bit,0.917778,0.701111,0.855556,0.528889,0.880000
24,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.417778,0.238519,0.337407,0.265926,0.380000
25,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.891111,0.612963,0.821481,0.517407,0.854074
26,Qwen/Qwen3-8B,tacq,Swahili,4-bit,0.924444,0.701111,0.860000,0.544444,0.882222
15,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.594815,0.238519,0.322222,0.240370,0.645556
16,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.898889,0.587778,0.823704,0.438148,0.865926
17,Qwen/Qwen3-8B,tacq,Chinese,4-bit,0.916667,0.704444,0.863333,0.505556,0.876667
3,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.418889,0.244815,0.325926,0.230000,0.374074
4,CohereLabs/aya-expanse-8b,tacq,English,3-bit,0.722222,0.354444,0.651111,0.316667,0.734444
5,CohereLabs/aya-expanse-8b,tacq,English,4-bit,0.771111,0.442222,0.697778,0.333333,0.770000
12,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,0.399259,0.287037,0.332593,0.262963,0.401852
13,CohereLabs/aya-expanse-8b,tacq,Tamil,3-bit,0.728889,0.438889,0.676667,0.326667,0.738889
14,CohereLabs/aya-expanse-8b,tacq,Tamil,4-bit,0.770000,0.433333,0.700000,0.353333,0.781111
6,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.409630,0.232222,0.369259,0.230000,0.377778
7,CohereLabs/aya-expanse-8b,tacq,Indonesian,3-bit,0.704444,0.403333,0.655556,0.334444,0.727778
8,CohereLabs/aya-expanse-8b,tacq,Indonesian,4-bit,0.781111,0.446667,0.720000,0.358889,0.782222
9,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,0.367037,0.243704,0.324074,0.256296,0.345556
10,CohereLabs/aya-expanse-8b,tacq,Swahili,3-bit,0.715556,0.415556,0.632222,0.343333,0.715556
11,CohereLabs/aya-expanse-8b,tacq,Swahili,4-bit,0.768889,0.432222,0.706667,0.341111,0.756667
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.346667,0.247037,0.276296,0.219259,0.341852
1,CohereLabs/aya-expanse-8b,tacq,Chinese,3-bit,0.710000,0.390000,0.678889,0.324444,0.718889
2,CohereLabs/aya-expanse-8b,tacq,Chinese,4-bit,0.802222,0.436667,0.741111,0.320000,0.786667
33,meta-llama/Llama-3.1-8B-Instruct,tacq,English,2-bit,0.280370,0.227778,0.236296,0.233333,0.230000
34,meta-llama/Llama-3.1-8B-Instruct,tacq,English,3-bit,0.816667,0.327778,0.612222,0.377778,0.760000
35,meta-llama/Llama-3.1-8B-Instruct,tacq,English,4-bit,0.863333,0.517778,0.758889,0.531111,0.812222
42,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,2-bit,0.244444,0.231481,0.230741,0.231111,0.230741
43,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,3-bit,0.776667,0.461111,0.635556,0.395556,0.734444
44,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,4-bit,0.880000,0.550000,0.750000,0.502222,0.817778
36,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,2-bit,0.247778,0.230370,0.242963,0.231852,0.231481
37,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,3-bit,0.825556,0.388889,0.704444,0.435556,0.767778
38,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,4-bit,0.882222,0.561111,0.752222,0.552222,0.831111
39,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,2-bit,0.244815,0.228889,0.233333,0.239630,0.229259
40,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,3-bit,0.786667,0.353333,0.636667,0.464444,0.730000
41,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,4-bit,0.881111,0.534444,0.751111,0.536667,0.824444
30,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,2-bit,0.267037,0.227037,0.231481,0.240000,0.283333
31,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,3-bit,0.804444,0.435556,0.675556,0.391111,0.766667
32,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,4-bit,0.876667,0.540000,0.750000,0.542222,0.834444

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,zho_Hans
18,Qwen/Qwen3-8B,tacq,English,2-bit,0.021088,0.017599,0.001889,0.019008,0.015476
19,Qwen/Qwen3-8B,tacq,English,3-bit,0.006849,0.011270,0.010116,0.009993,0.004536
27,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.053026,0.052095,0.016786,0.017149,0.063098
28,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.006175,0.012317,0.003666,0.008950,0.005903
21,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.007909,0.005238,0.023593,0.013608,0.044972
22,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.004997,0.014750,0.010476,0.024696,0.008232
24,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.094808,0.012841,0.065711,0.034058,0.090354
25,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.006849,0.012712,0.004475,0.007716,0.004655
15,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.050270,0.011978,0.024411,0.005316,0.025451
16,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.008654,0.010463,0.010974,0.006563,0.003186
3,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.027050,0.007554,0.015458,0.010696,0.035629
12,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,0.014971,0.001048,0.014064,0.013220,0.032475
6,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.016464,0.014258,0.006041,0.005949,0.023535
9,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,0.023559,0.009701,0.027716,0.004997,0.016802
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.037745,0.023029,0.026948,0.001386,0.041019

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'SW' 'ZH']
mean_ppl

eng_Latn    1.147037
tam_Taml    1.154815
ind_Latn    1.162222
swh_Latn    1.156667
zho_Hans    1.151852
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'SW' 'ZH']
mean_ppl

eng_Latn    4.251111
tam_Taml    2.580370
ind_Latn    3.844444
swh_Latn    1.974074
zho_Hans    4.136296
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'SW' 'ZH']
mean_ppl

eng_Latn    4.558889
tam_Taml    3.427778
ind_Latn    4.284444
swh_Latn    2.563333
zho_Hans    4.364444
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

eng_Latn    1.045556
tam_Taml    0.945556
ind_Latn    0.990741
swh_Latn    0.959630
zho_Hans    0.998148
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

eng_Latn    2.657778
tam_Taml    1.322222
ind_Latn    2.358889
swh_Latn    1.166667
zho_Hans    2.681111
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

eng_Latn    3.114444
tam_Taml    1.753333
ind_Latn    2.896667
swh_Latn    1.324444
zho_Hans    3.121111
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'SW' 'ZH']
mean_ppl

eng_Latn    1.197407
tam_Taml    1.251481
ind_Latn    1.235185
swh_Latn    1.234074
zho_Hans    1.221111
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'SW' 'ZH']
mean_ppl

eng_Latn    2.703333
tam_Taml    1.268889
ind_Latn    1.822222
swh_Latn    1.351111
zho_Hans    2.090000
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'SW' 'ZH']
mean_ppl

eng_Latn    4.290000
tam_Taml    2.361111
ind_Latn    3.544444
swh_Latn    2.422222
zho_Hans    3.984444
dtype: float64

In [ ]:
eval_languages = ["eng_Latn", "tam_Taml", "ind_Latn", "swh_Latn", "zho_Hans"]
# eval_languages = ["eng_Latn", "tam_Taml", "ind_Latn"]

# Initialize the W&B API
api = Api()

quantization_technique = "ALL"
# bit = 8
num_samples = 128
eval_dataset = "Belebele"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            # {"config.bit_width": f"{bit}-bit"},
                            { "$or": [
                              {"config.evaluation_dataset": eval_dataset.lower()},
                              {"config.evaluation_dataset": f"{eval_dataset.lower()}-1000"},
                              {"config.evaluation_dataset": f"{eval_dataset.lower()}-2000"},
                            ]},
                            # {"config.base_model": base_model},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.evaluation_dataset": eval_dataset.lower()},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            {"config.output_type": "multiple_choice"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              {"config.evaluation_dataset": eval_dataset.lower()},
                              # {"config.base_model": base_model},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                              {"config.enable_thinking": False},
                              {"created_at": {"$gt": "2026-07-01"}},
                          ]}
                      ]}
                  )
  # visualize_delta_unquantized_globalmmlulite(eval_languages=eval_languages, runs=runs, base_model=base_model, quantization_technique=quantization_technique, bit_width=bit, eval_dataset=eval_dataset, custom_title="")
  # visualize_delta_unquantized_deliver_bar(eval_languages=eval_languages, runs=runs, base_model=base_model, quantization_technique=quantization_technique, bits=["2-bit", "3-bit", "4-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False)
  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-14B"], quantization_technique=quantization_technique, bits=["2-bit", "3-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False, vertical_spacing=0.038, horizontal_spacing=0.04, random_guess_score=0.25, write_pdf="belebele_14b_barplot_errorbar_final.pdf")

Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,zho_Hans
7,Qwen/Qwen3-14B,gptq,2-bit,English,0.235556,0.240000,0.240000,0.230000,0.222222
2,Qwen/Qwen3-14B,gptq,3-bit,English,0.915556,0.608889,0.853333,0.471111,0.878889
1,Qwen/Qwen3-14B,gptq,2-bit,Tamil,0.242222,0.243333,0.248889,0.224444,0.245556
4,Qwen/Qwen3-14B,gptq,3-bit,Tamil,0.894444,0.735556,0.853333,0.490000,0.877778
0,Qwen/Qwen3-14B,gptq,2-bit,Indonesian,0.250000,0.242222,0.238889,0.230000,0.241111
3,Qwen/Qwen3-14B,gptq,3-bit,Indonesian,0.903333,0.657778,0.844444,0.461111,0.880000
9,Qwen/Qwen3-14B,gptq,2-bit,Swahili,0.223333,0.244444,0.232222,0.225556,0.243333
5,Qwen/Qwen3-14B,gptq,3-bit,Swahili,0.903333,0.643333,0.842222,0.548889,0.866667
8,Qwen/Qwen3-14B,gptq,2-bit,Chinese,0.225556,0.231111,0.227778,0.235556,0.241111
6,Qwen/Qwen3-14B,gptq,3-bit,Chinese,0.904444,0.652222,0.831111,0.447778,0.884444

Empty DataFrame
Columns: [Base Model, Quantization Technique, Bit Width, Calibration Language, eng_Latn, tam_Taml, ind_Latn, swh_Latn, zho_Hans]
Index: []

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,zho_Hans
0,Qwen/Qwen3-14B,tacq,2-bit,English,0.823333,0.244444,0.435556,0.264444,0.692222
3,Qwen/Qwen3-14B,tacq,3-bit,English,0.925556,0.674444,0.865556,0.513333,0.898889
2,Qwen/Qwen3-14B,tacq,2-bit,Tamil,0.765556,0.600000,0.608889,0.288889,0.712222
5,Qwen/Qwen3-14B,tacq,3-bit,Tamil,0.924444,0.750000,0.871111,0.535556,0.906667
1,Qwen/Qwen3-14B,tacq,2-bit,Indonesian,0.774444,0.295556,0.737778,0.304444,0.744444
4,Qwen/Qwen3-14B,tacq,3-bit,Indonesian,0.934444,0.703333,0.876667,0.571111,0.896667
6,Qwen/Qwen3-14B,tacq,2-bit,Swahili,0.668889,0.271111,0.550000,0.408889,0.613333
8,Qwen/Qwen3-14B,tacq,3-bit,Swahili,0.926667,0.720000,0.870000,0.630000,0.888889
7,Qwen/Qwen3-14B,tacq,2-bit,Chinese,0.810000,0.280000,0.477778,0.290000,0.775556
9,Qwen/Qwen3-14B,tacq,3-bit,Chinese,0.930000,0.681111,0.880000,0.497778,0.895556

Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,zho_Hans
2,Qwen/Qwen3-14B,gptq,English,2-bit,0.235556,0.240000,0.240000,0.230000,0.222222
3,Qwen/Qwen3-14B,gptq,English,3-bit,0.915556,0.608889,0.853333,0.471111,0.878889
8,Qwen/Qwen3-14B,gptq,Tamil,2-bit,0.242222,0.243333,0.248889,0.224444,0.245556
9,Qwen/Qwen3-14B,gptq,Tamil,3-bit,0.894444,0.735556,0.853333,0.490000,0.877778
4,Qwen/Qwen3-14B,gptq,Indonesian,2-bit,0.250000,0.242222,0.238889,0.230000,0.241111
5,Qwen/Qwen3-14B,gptq,Indonesian,3-bit,0.903333,0.657778,0.844444,0.461111,0.880000
6,Qwen/Qwen3-14B,gptq,Swahili,2-bit,0.223333,0.244444,0.232222,0.225556,0.243333
7,Qwen/Qwen3-14B,gptq,Swahili,3-bit,0.903333,0.643333,0.842222,0.548889,0.866667
0,Qwen/Qwen3-14B,gptq,Chinese,2-bit,0.225556,0.231111,0.227778,0.235556,0.241111
1,Qwen/Qwen3-14B,gptq,Chinese,3-bit,0.904444,0.652222,0.831111,0.447778,0.884444

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, zho_Hans]
Index: []

SLIM

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, zho_Hans]
Index: []

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, zho_Hans]
Index: []

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,zho_Hans
2,Qwen/Qwen3-14B,tacq,English,2-bit,0.823333,0.244444,0.435556,0.264444,0.692222
3,Qwen/Qwen3-14B,tacq,English,3-bit,0.925556,0.674444,0.865556,0.513333,0.898889
8,Qwen/Qwen3-14B,tacq,Tamil,2-bit,0.765556,0.600000,0.608889,0.288889,0.712222
9,Qwen/Qwen3-14B,tacq,Tamil,3-bit,0.924444,0.750000,0.871111,0.535556,0.906667
4,Qwen/Qwen3-14B,tacq,Indonesian,2-bit,0.774444,0.295556,0.737778,0.304444,0.744444
5,Qwen/Qwen3-14B,tacq,Indonesian,3-bit,0.934444,0.703333,0.876667,0.571111,0.896667
6,Qwen/Qwen3-14B,tacq,Swahili,2-bit,0.668889,0.271111,0.550000,0.408889,0.613333
7,Qwen/Qwen3-14B,tacq,Swahili,3-bit,0.926667,0.720000,0.870000,0.630000,0.888889
0,Qwen/Qwen3-14B,tacq,Chinese,2-bit,0.810000,0.280000,0.477778,0.290000,0.775556
1,Qwen/Qwen3-14B,tacq,Chinese,3-bit,0.930000,0.681111,0.880000,0.497778,0.895556

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, zho_Hans]
Index: []

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
[]
[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
[]

### Massive Scenario Bar

In [ ]:
eval_languages = ['en-US', 'id-ID', 'ta-IN', 'sw-KE', 'zh-CN']

# Initialize the W&B API
api = Api()

quantization_technique = "GPTQ"
# bit = 8
num_samples = 128
eval_dataset = "massive"
eval_dataset_variant = "-scenario"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit in [3]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.num_calibration_samples": num_samples},
                            # {"config.evaluation_dataset": eval_dataset.lower()},
                            # {"config.evaluation_dataset": f"{eval_dataset}{eval_dataset_variant}"},
                            {"$or": [
                                {"$and": [
                                  {"config.evaluation_dataset": f"{eval_dataset.lower()}{eval_dataset_variant}"},
                                  {"created_at": {"$lt": "2026-07-01"}},
                                ]},
                                {"$and": [
                                  {"$or": [
                                    {"config.evaluation_dataset": f"{eval_dataset.lower()}{eval_dataset_variant}-1000"},
                                    {"config.evaluation_dataset": f"{eval_dataset.lower()}{eval_dataset_variant}-2000"},
                                  ]},
                                  {"created_at": {"$gt": "2026-07-01"}},
                                ]},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"$not": {"config.calibration_language": "WuuChinese"}},
                            # {"$not": {"config.calibration_language": "Chinese"}},
                            # {"$not": {"config.calibration_language": "Swahili"}},
                            # {"$not": {"config.calibration_language": "Indonesian"}},
                            # {"created_at": {"$lt": "2026-07-01"}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.evaluation_dataset": f"{eval_dataset}{eval_dataset_variant}"},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": eval_dataset.lower()},
                            {"config.evaluation_dataset": f"{eval_dataset}{eval_dataset_variant}"},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                            {"created_at": {"$lt": "2026-07-01"}},
                          ]}
                      ]}
                  )

  # visualize_delta_unquantized_deliver_bar(eval_languages=eval_languages, runs=runs, base_model=base_model, quantization_technique=quantization_technique, bits=['2-bit', '3-bit'], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=True)
  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b"], quantization_technique=quantization_technique, bits=['2-bit', '3-bit', '4-bit'], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=True, vertical_spacing=0.08, horizontal_spacing=0.025, random_guess_score=1/18, write_pdf="massive_barplot_sinq_final.pdf")

Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,en-US,ta-IN,id-ID,sw-KE,zh-CN
5,Qwen/Qwen3-8B,gptq,2-bit,English,0.075319,0.063887,0.062206,0.065905,0.068931
30,Qwen/Qwen3-8B,gptq,2-bit,English,0.083389,0.061197,0.088097,0.069603,0.066241
31,Qwen/Qwen3-8B,gptq,2-bit,English,0.078682,0.065232,0.081708,0.065232,0.060188
0,Qwen/Qwen3-8B,gptq,3-bit,English,0.474445,0.364492,0.457969,0.259919,0.483524
40,Qwen/Qwen3-8B,gptq,3-bit,English,0.499328,0.408204,0.458305,0.300269,0.496301
41,Qwen/Qwen3-8B,gptq,3-bit,English,0.532616,0.422999,0.522192,0.319435,0.548420
20,Qwen/Qwen3-8B,gptq,4-bit,English,0.486550,0.438803,0.464694,0.363820,0.486886
7,Qwen/Qwen3-8B,gptq,2-bit,Tamil,0.062878,0.062878,0.080363,0.071957,0.068258
34,Qwen/Qwen3-8B,gptq,2-bit,Tamil,0.062206,0.065568,0.057498,0.063551,0.063551
35,Qwen/Qwen3-8B,gptq,2-bit,Tamil,0.057498,0.058507,0.060861,0.064223,0.061533
2,Qwen/Qwen3-8B,gptq,3-bit,Tamil,0.513786,0.457633,0.494956,0.316409,0.520511
44,Qwen/Qwen3-8B,gptq,3-bit,Tamil,0.486214,0.440148,0.475118,0.292535,0.514122
45,Qwen/Qwen3-8B,gptq,3-bit,Tamil,0.538668,0.482179,0.510424,0.369536,0.534297
22,Qwen/Qwen3-8B,gptq,4-bit,Tamil,0.476463,0.439812,0.452925,0.352051,0.491930
6,Qwen/Qwen3-8B,gptq,2-bit,Indonesian,0.082381,0.072293,0.073302,0.079354,0.074983
32,Qwen/Qwen3-8B,gptq,2-bit,Indonesian,0.082044,0.059852,0.080363,0.067586,0.069603
33,Qwen/Qwen3-8B,gptq,2-bit,Indonesian,0.070276,0.054136,0.081036,0.063215,0.063215
1,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,0.537323,0.438803,0.504035,0.319771,0.535306
42,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,0.540350,0.446200,0.511769,0.320108,0.541695
43,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,0.521184,0.405851,0.482179,0.338265,0.510760
21,Qwen/Qwen3-8B,gptq,4-bit,Indonesian,0.462340,0.408204,0.445192,0.354405,0.466711
8,Qwen/Qwen3-8B,gptq,2-bit,Swahili,0.067249,0.062878,0.067586,0.069603,0.059516
36,Qwen/Qwen3-8B,gptq,2-bit,Swahili,0.057835,0.060525,0.064896,0.056826,0.065568
37,Qwen/Qwen3-8B,gptq,2-bit,Swahili,0.066577,0.062878,0.066913,0.071957,0.061197
3,Qwen/Qwen3-8B,gptq,3-bit,Swahili,0.502017,0.408541,0.465703,0.359112,0.501681
46,Qwen/Qwen3-8B,gptq,3-bit,Swahili,0.438130,0.361466,0.437122,0.310020,0.462677
47,Qwen/Qwen3-8B,gptq,3-bit,Swahili,0.479489,0.385676,0.448218,0.338601,0.495965
23,Qwen/Qwen3-8B,gptq,4-bit,Swahili,0.465703,0.416611,0.440820,0.356086,0.470410
9,Qwen/Qwen3-8B,gptq,2-bit,Chinese,0.085407,0.072293,0.062542,0.070612,0.089442
38,Qwen/Qwen3-8B,gptq,2-bit,Chinese,0.096167,0.069939,0.079354,0.070948,0.088097
39,Qwen/Qwen3-8B,gptq,2-bit,Chinese,0.103228,0.080027,0.086752,0.073302,0.084398
4,Qwen/Qwen3-8B,gptq,3-bit,Chinese,0.497646,0.379960,0.466711,0.268998,0.520847
48,Qwen/Qwen3-8B,gptq,3-bit,Chinese,0.398790,0.325151,0.408204,0.252522,0.441829
49,Qwen/Qwen3-8B,gptq,3-bit,Chinese,0.489576,0.374580,0.458978,0.286147,0.500672
24,Qwen/Qwen3-8B,gptq,4-bit,Chinese,0.499664,0.448218,0.482515,0.370545,0.513450
15,CohereLabs/aya-expanse-8b,gptq,2-bit,English,0.108944,0.053800,0.083389,0.095494,0.096503
10,CohereLabs/aya-expanse-8b,gptq,3-bit,English,0.561870,0.380968,0.550437,0.278077,0.562206
25,CohereLabs/aya-expanse-8b,gptq,4-bit,English,0.588769,0.481170,0.570612,0.368863,0.578346
17,CohereLabs/aya-expanse-8b,gptq,2-bit,Tamil,0.064560,0.066577,0.064223,0.063215,0.073302
12,CohereLabs/aya-expanse-8b,gptq,3-bit,Tamil,0.554136,0.397108,0.514459,0.195360,0.515467
27,CohereLabs/aya-expanse-8b,gptq,4-bit,Tamil,0.608608,0.489240,0.594822,0.368863,0.607263
16,CohereLabs/aya-expanse-8b,gptq,2-bit,Indonesian,0.118023,0.058171,0.112979,0.081036,0.101547
11,CohereLabs/aya-expanse-8b,gptq,3-bit,Indonesian,0.557498,0.374580,0.546402,0.299597,0.559516
26,CohereLabs/aya-expanse-8b,gptq,4-bit,Indonesian,0.589778,0.489240,0.573974,0.369872,0.575992
18,CohereLabs/aya-expanse-8b,gptq,2-bit,Swahili,0.084398,0.080699,0.088769,0.091796,0.090114
13,CohereLabs/aya-expanse-8b,gptq,3-bit,Swahili,0.565232,0.366174,0.538332,0.330531,0.552455
28,CohereLabs/aya-expanse-8b,gptq,4-bit,Swahili,0.598857,0.460995,0.574983,0.364156,0.583053
19,CohereLabs/aya-expanse-8b,gptq,2-bit,Chinese,0.080027,0.049428,0.055145,0.056153,0.076664
14,CohereLabs/aya-expanse-8b,gptq,3-bit,Chinese,0.621722,0.400134,0.601210,0.292199,0.610289
29,CohereLabs/aya-expanse-8b,gptq,4-bit,Chinese,0.607935,0.491930,0.591123,0.361802,0.605582
50,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,English,0.079018,0.061870,0.074647,0.071957,0.061870
51,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,English,0.071621,0.084398,0.075656,0.076664,0.077001
52,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Indonesian,0.082381,0.061533,0.072966,0.081372,0.070948
53,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Indonesian,0.089106,0.070276,0.073638,0.076328,0.083053

,Base Model,Quantization Technique,Bit Width,Calibration Language,en-US,ta-IN,id-ID,sw-KE,zh-CN
7,Qwen/Qwen3-8B,slimllm,2-bit,English,0.111298,0.058843,0.083053,0.066913,0.097176
2,Qwen/Qwen3-8B,slimllm,3-bit,English,0.503026,0.383995,0.473100,0.300605,0.497310
27,Qwen/Qwen3-8B,slimllm,3-bit,English,0.483524,0.307666,0.440484,0.271015,0.485878
28,Qwen/Qwen3-8B,slimllm,3-bit,English,0.507061,0.355414,0.465030,0.300605,0.500000
0,Qwen/Qwen3-8B,slimllm,4-bit,English,0.503026,0.451580,0.497983,0.381641,0.525891
9,Qwen/Qwen3-8B,slimllm,2-bit,Tamil,0.105582,0.099866,0.099193,0.093141,0.091459
4,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,0.419637,0.415266,0.386012,0.273033,0.455952
31,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,0.434432,0.393746,0.398790,0.238399,0.438467
32,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,0.418292,0.436113,0.384331,0.259247,0.485878
20,Qwen/Qwen3-8B,slimllm,4-bit,Tamil,0.483524,0.456288,0.469738,0.363820,0.501009
8,Qwen/Qwen3-8B,slimllm,2-bit,Indonesian,0.091796,0.070948,0.086752,0.069939,0.080027
3,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,0.522192,0.371217,0.483188,0.309011,0.517485
29,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,0.463685,0.318426,0.420646,0.252858,0.459314
30,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,0.511096,0.382650,0.478816,0.341627,0.502017
1,Qwen/Qwen3-8B,slimllm,4-bit,Indonesian,0.496638,0.451580,0.472764,0.367855,0.515131
10,Qwen/Qwen3-8B,slimllm,2-bit,Swahili,0.106590,0.066241,0.083053,0.066577,0.102219
5,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,0.554808,0.396772,0.502017,0.387357,0.535306
33,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,0.458305,0.373907,0.432414,0.330195,0.452925
34,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,0.467720,0.399462,0.475454,0.360794,0.484869
21,Qwen/Qwen3-8B,slimllm,4-bit,Swahili,0.475790,0.442838,0.452589,0.374243,0.496638
11,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,0.163416,0.078009,0.089778,0.076664,0.167115
6,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,0.497310,0.370545,0.458978,0.298588,0.479153
35,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,0.524882,0.350706,0.468729,0.259583,0.538332
36,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,0.464358,0.331540,0.442838,0.266644,0.465703
22,Qwen/Qwen3-8B,slimllm,4-bit,Chinese,0.485205,0.444519,0.471755,0.366510,0.508742
16,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,0.323134,0.088097,0.131137,0.093141,0.175521
12,CohereLabs/aya-expanse-8b,slimllm,3-bit,English,0.602555,0.393746,0.578682,0.302286,0.592132
23,CohereLabs/aya-expanse-8b,slimllm,4-bit,English,0.604573,0.460323,0.597848,0.341964,0.607935
17,CohereLabs/aya-expanse-8b,slimllm,2-bit,Indonesian,0.110289,0.056490,0.151648,0.037323,0.085071
13,CohereLabs/aya-expanse-8b,slimllm,3-bit,Indonesian,0.584734,0.388702,0.575992,0.283793,0.594486
24,CohereLabs/aya-expanse-8b,slimllm,4-bit,Indonesian,0.614997,0.473436,0.604237,0.360121,0.613315
18,CohereLabs/aya-expanse-8b,slimllm,2-bit,Swahili,0.242434,0.084734,0.256221,0.113652,0.231338
14,CohereLabs/aya-expanse-8b,slimllm,3-bit,Swahili,0.588097,0.413921,0.563551,0.336584,0.585407
25,CohereLabs/aya-expanse-8b,slimllm,4-bit,Swahili,0.586079,0.456288,0.569603,0.360794,0.583389
19,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,0.165098,0.100202,0.128783,0.109280,0.237727
15,CohereLabs/aya-expanse-8b,slimllm,3-bit,Chinese,0.594822,0.386685,0.582381,0.284802,0.594149
26,CohereLabs/aya-expanse-8b,slimllm,4-bit,Chinese,0.603900,0.476463,0.592804,0.361802,0.607599

,Base Model,Quantization Technique,Bit Width,Calibration Language,en-US,ta-IN,id-ID,sw-KE,zh-CN
10,Qwen/Qwen3-8B,tacq,2-bit,English,0.421318,0.084734,0.261264,0.106254,0.371217
5,Qwen/Qwen3-8B,tacq,3-bit,English,0.493948,0.421991,0.481843,0.320444,0.507397
30,Qwen/Qwen3-8B,tacq,3-bit,English,0.485205,0.360121,0.442838,0.292199,0.489576
31,Qwen/Qwen3-8B,tacq,3-bit,English,0.481506,0.361130,0.438803,0.287492,0.493948
0,Qwen/Qwen3-8B,tacq,4-bit,English,0.518494,0.463013,0.501009,0.373235,0.515131
12,Qwen/Qwen3-8B,tacq,2-bit,Tamil,0.298252,0.185609,0.207801,0.099529,0.358104
7,Qwen/Qwen3-8B,tacq,3-bit,Tamil,0.497310,0.451244,0.476126,0.344990,0.517821
34,Qwen/Qwen3-8B,tacq,3-bit,Tamil,0.467048,0.458642,0.466039,0.330868,0.501681
35,Qwen/Qwen3-8B,tacq,3-bit,Tamil,0.502690,0.467720,0.490249,0.337592,0.504035
2,Qwen/Qwen3-8B,tacq,4-bit,Tamil,0.506389,0.447545,0.486550,0.371890,0.512105
11,Qwen/Qwen3-8B,tacq,2-bit,Indonesian,0.460323,0.122394,0.414929,0.132145,0.443510
6,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,0.442502,0.379623,0.413921,0.308675,0.441493
32,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,0.439812,0.395763,0.434768,0.308339,0.458642
33,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,0.435440,0.393410,0.428379,0.325824,0.443510
1,Qwen/Qwen3-8B,tacq,4-bit,Indonesian,0.517821,0.466039,0.495965,0.376261,0.521856
13,Qwen/Qwen3-8B,tacq,2-bit,Swahili,0.250504,0.115669,0.195696,0.157364,0.169469
8,Qwen/Qwen3-8B,tacq,3-bit,Swahili,0.442165,0.366846,0.412912,0.348016,0.438130
36,Qwen/Qwen3-8B,tacq,3-bit,Swahili,0.471755,0.377942,0.433423,0.328850,0.479489
37,Qwen/Qwen3-8B,tacq,3-bit,Swahili,0.457633,0.410222,0.437122,0.347007,0.469065
3,Qwen/Qwen3-8B,tacq,4-bit,Swahili,0.499328,0.434768,0.458978,0.372562,0.495293
14,Qwen/Qwen3-8B,tacq,2-bit,Chinese,0.395427,0.092804,0.257566,0.106590,0.440484
9,Qwen/Qwen3-8B,tacq,3-bit,Chinese,0.439812,0.378278,0.435440,0.303295,0.480834
4,Qwen/Qwen3-8B,tacq,4-bit,Chinese,0.496638,0.451580,0.467048,0.375588,0.510087
19,CohereLabs/aya-expanse-8b,tacq,2-bit,English,0.539005,0.118023,0.498991,0.138870,0.511432
15,CohereLabs/aya-expanse-8b,tacq,3-bit,English,0.609280,0.416947,0.591459,0.319435,0.589778
23,CohereLabs/aya-expanse-8b,tacq,4-bit,English,0.602892,0.479489,0.594822,0.359449,0.595158
29,CohereLabs/aya-expanse-8b,tacq,2-bit,Tamil,0.463685,0.334566,0.452253,0.168796,0.477135
28,CohereLabs/aya-expanse-8b,tacq,3-bit,Tamil,0.578346,0.456960,0.567922,0.343981,0.585743
25,CohereLabs/aya-expanse-8b,tacq,4-bit,Tamil,0.609953,0.491930,0.601883,0.389038,0.626765
20,CohereLabs/aya-expanse-8b,tacq,2-bit,Indonesian,0.549092,0.156355,0.525555,0.192670,0.541695
16,CohereLabs/aya-expanse-8b,tacq,3-bit,Indonesian,0.596839,0.409549,0.570276,0.331540,0.587761
24,CohereLabs/aya-expanse-8b,tacq,4-bit,Indonesian,0.610962,0.467720,0.588097,0.363820,0.598521
21,CohereLabs/aya-expanse-8b,tacq,2-bit,Swahili,0.494620,0.171822,0.483188,0.273369,0.485205
17,CohereLabs/aya-expanse-8b,tacq,3-bit,Swahili,0.596839,0.404842,0.580027,0.358776,0.598857
26,CohereLabs/aya-expanse-8b,tacq,4-bit,Swahili,0.610962,0.479489,0.603228,0.369872,0.614324
22,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,0.552455,0.173504,0.508742,0.176866,0.560188
18,CohereLabs/aya-expanse-8b,tacq,3-bit,Chinese,0.584062,0.421318,0.587761,0.295225,0.589442
27,CohereLabs/aya-expanse-8b,tacq,4-bit,Chinese,0.610625,0.474109,0.602219,0.361802,0.610625

Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en-US,ta-IN,id-ID,sw-KE,zh-CN
18,Qwen/Qwen3-8B,gptq,English,2-bit,0.079130,0.063439,0.077337,0.066913,0.065120
19,Qwen/Qwen3-8B,gptq,English,3-bit,0.502130,0.398565,0.479489,0.293208,0.509415
20,Qwen/Qwen3-8B,gptq,English,4-bit,0.486550,0.438803,0.464694,0.363820,0.486886
27,Qwen/Qwen3-8B,gptq,Tamil,2-bit,0.060861,0.062318,0.066241,0.066577,0.064447
28,Qwen/Qwen3-8B,gptq,Tamil,3-bit,0.512889,0.459987,0.493499,0.326160,0.522977
29,Qwen/Qwen3-8B,gptq,Tamil,4-bit,0.476463,0.439812,0.452925,0.352051,0.491930
21,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,0.078234,0.062094,0.078234,0.070052,0.069267
22,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,0.532952,0.430285,0.499328,0.326048,0.529254
23,Qwen/Qwen3-8B,gptq,Indonesian,4-bit,0.462340,0.408204,0.445192,0.354405,0.466711
24,Qwen/Qwen3-8B,gptq,Swahili,2-bit,0.063887,0.062094,0.066465,0.066129,0.062094
25,Qwen/Qwen3-8B,gptq,Swahili,3-bit,0.473212,0.385228,0.450347,0.335911,0.486774
26,Qwen/Qwen3-8B,gptq,Swahili,4-bit,0.465703,0.416611,0.440820,0.356086,0.470410
15,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.094934,0.074087,0.076216,0.071621,0.087312
16,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.462004,0.359897,0.444631,0.269222,0.487783
17,Qwen/Qwen3-8B,gptq,Chinese,4-bit,0.499664,0.448218,0.482515,0.370545,0.513450
3,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.108944,0.053800,0.083389,0.095494,0.096503
4,CohereLabs/aya-expanse-8b,gptq,English,3-bit,0.561870,0.380968,0.550437,0.278077,0.562206
5,CohereLabs/aya-expanse-8b,gptq,English,4-bit,0.588769,0.481170,0.570612,0.368863,0.578346
12,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,0.064560,0.066577,0.064223,0.063215,0.073302
13,CohereLabs/aya-expanse-8b,gptq,Tamil,3-bit,0.554136,0.397108,0.514459,0.195360,0.515467
14,CohereLabs/aya-expanse-8b,gptq,Tamil,4-bit,0.608608,0.489240,0.594822,0.368863,0.607263
6,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,0.118023,0.058171,0.112979,0.081036,0.101547
7,CohereLabs/aya-expanse-8b,gptq,Indonesian,3-bit,0.557498,0.374580,0.546402,0.299597,0.559516
8,CohereLabs/aya-expanse-8b,gptq,Indonesian,4-bit,0.589778,0.489240,0.573974,0.369872,0.575992
9,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,0.084398,0.080699,0.088769,0.091796,0.090114
10,CohereLabs/aya-expanse-8b,gptq,Swahili,3-bit,0.565232,0.366174,0.538332,0.330531,0.552455
11,CohereLabs/aya-expanse-8b,gptq,Swahili,4-bit,0.598857,0.460995,0.574983,0.364156,0.583053
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.080027,0.049428,0.055145,0.056153,0.076664
1,CohereLabs/aya-expanse-8b,gptq,Chinese,3-bit,0.621722,0.400134,0.601210,0.292199,0.610289
2,CohereLabs/aya-expanse-8b,gptq,Chinese,4-bit,0.607935,0.491930,0.591123,0.361802,0.605582
30,meta-llama/Llama-3.1-8B-Instruct,gptq,English,2-bit,0.075319,0.073134,0.075151,0.074311,0.069435
31,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,2-bit,0.085743,0.065905,0.073302,0.078850,0.077001

,Base Model,Quantization Technique,Calibration Language,Bit Width,en-US,ta-IN,id-ID,sw-KE,zh-CN
18,Qwen/Qwen3-8B,gptq,English,2-bit,0.003310,0.001677,0.011013,0.001922,0.003656
19,Qwen/Qwen3-8B,gptq,English,3-bit,0.023831,0.024839,0.030196,0.024805,0.028069
27,Qwen/Qwen3-8B,gptq,Tamil,2-bit,0.002393,0.002910,0.010080,0.003814,0.002818
28,Qwen/Qwen3-8B,gptq,Tamil,3-bit,0.021424,0.017240,0.014450,0.032183,0.008419
21,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,0.005629,0.007580,0.003498,0.006816,0.004810
22,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,0.008413,0.017539,0.012530,0.008640,0.013335
24,Qwen/Qwen3-8B,gptq,Swahili,2-bit,0.004289,0.001110,0.001143,0.006648,0.002551
25,Qwen/Qwen3-8B,gptq,Swahili,3-bit,0.026457,0.019221,0.011765,0.020132,0.017199
15,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.007327,0.004309,0.010130,0.001197,0.002133
16,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.044821,0.024667,0.025950,0.013728,0.033522
3,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
12,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
6,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
9,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000

SLIM

,Base Model,Quantization Technique,Calibration Language,Bit Width,en-US,ta-IN,id-ID,sw-KE,zh-CN
15,Qwen/Qwen3-8B,slimllm,English,2-bit,0.111298,0.058843,0.083053,0.066913,0.097176
16,Qwen/Qwen3-8B,slimllm,English,3-bit,0.497870,0.349025,0.459538,0.290742,0.494396
17,Qwen/Qwen3-8B,slimllm,English,4-bit,0.503026,0.451580,0.497983,0.381641,0.525891
24,Qwen/Qwen3-8B,slimllm,Tamil,2-bit,0.105582,0.099866,0.099193,0.093141,0.091459
25,Qwen/Qwen3-8B,slimllm,Tamil,3-bit,0.424120,0.415041,0.389711,0.256893,0.460099
26,Qwen/Qwen3-8B,slimllm,Tamil,4-bit,0.483524,0.456288,0.469738,0.363820,0.501009
18,Qwen/Qwen3-8B,slimllm,Indonesian,2-bit,0.091796,0.070948,0.086752,0.069939,0.080027
19,Qwen/Qwen3-8B,slimllm,Indonesian,3-bit,0.498991,0.357431,0.460883,0.301166,0.492939
20,Qwen/Qwen3-8B,slimllm,Indonesian,4-bit,0.496638,0.451580,0.472764,0.367855,0.515131
21,Qwen/Qwen3-8B,slimllm,Swahili,2-bit,0.106590,0.066241,0.083053,0.066577,0.102219
22,Qwen/Qwen3-8B,slimllm,Swahili,3-bit,0.493611,0.390047,0.469962,0.359449,0.491033
23,Qwen/Qwen3-8B,slimllm,Swahili,4-bit,0.475790,0.442838,0.452589,0.374243,0.496638
12,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.163416,0.078009,0.089778,0.076664,0.167115
13,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.495517,0.350930,0.456848,0.274938,0.494396
14,Qwen/Qwen3-8B,slimllm,Chinese,4-bit,0.485205,0.444519,0.471755,0.366510,0.508742
3,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.323134,0.088097,0.131137,0.093141,0.175521
4,CohereLabs/aya-expanse-8b,slimllm,English,3-bit,0.602555,0.393746,0.578682,0.302286,0.592132
5,CohereLabs/aya-expanse-8b,slimllm,English,4-bit,0.604573,0.460323,0.597848,0.341964,0.607935
6,CohereLabs/aya-expanse-8b,slimllm,Indonesian,2-bit,0.110289,0.056490,0.151648,0.037323,0.085071
7,CohereLabs/aya-expanse-8b,slimllm,Indonesian,3-bit,0.584734,0.388702,0.575992,0.283793,0.594486
8,CohereLabs/aya-expanse-8b,slimllm,Indonesian,4-bit,0.614997,0.473436,0.604237,0.360121,0.613315
9,CohereLabs/aya-expanse-8b,slimllm,Swahili,2-bit,0.242434,0.084734,0.256221,0.113652,0.231338
10,CohereLabs/aya-expanse-8b,slimllm,Swahili,3-bit,0.588097,0.413921,0.563551,0.336584,0.585407
11,CohereLabs/aya-expanse-8b,slimllm,Swahili,4-bit,0.586079,0.456288,0.569603,0.360794,0.583389
0,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.165098,0.100202,0.128783,0.109280,0.237727
1,CohereLabs/aya-expanse-8b,slimllm,Chinese,3-bit,0.594822,0.386685,0.582381,0.284802,0.594149
2,CohereLabs/aya-expanse-8b,slimllm,Chinese,4-bit,0.603900,0.476463,0.592804,0.361802,0.607599

,Base Model,Quantization Technique,Calibration Language,Bit Width,en-US,ta-IN,id-ID,sw-KE,zh-CN
15,Qwen/Qwen3-8B,slimllm,English,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
16,Qwen/Qwen3-8B,slimllm,English,3-bit,0.010277,0.031487,0.013870,0.013949,0.006123
24,Qwen/Qwen3-8B,slimllm,Tamil,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
25,Qwen/Qwen3-8B,slimllm,Tamil,3-bit,0.007312,0.017297,0.006456,0.014237,0.019576
18,Qwen/Qwen3-8B,slimllm,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
19,Qwen/Qwen3-8B,slimllm,Indonesian,3-bit,0.025373,0.027973,0.028508,0.036662,0.024601
21,Qwen/Qwen3-8B,slimllm,Swahili,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
22,Qwen/Qwen3-8B,slimllm,Swahili,3-bit,0.043443,0.011465,0.028680,0.023356,0.033913
12,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
13,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.024742,0.015924,0.010677,0.016969,0.031549
3,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
6,CohereLabs/aya-expanse-8b,slimllm,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
9,CohereLabs/aya-expanse-8b,slimllm,Swahili,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
0,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en-US,ta-IN,id-ID,sw-KE,zh-CN
18,Qwen/Qwen3-8B,tacq,English,2-bit,0.421318,0.084734,0.261264,0.106254,0.371217
19,Qwen/Qwen3-8B,tacq,English,3-bit,0.486886,0.381080,0.454495,0.300045,0.496974
20,Qwen/Qwen3-8B,tacq,English,4-bit,0.518494,0.463013,0.501009,0.373235,0.515131
27,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.298252,0.185609,0.207801,0.099529,0.358104
28,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.489016,0.459202,0.477471,0.337817,0.507846
29,Qwen/Qwen3-8B,tacq,Tamil,4-bit,0.506389,0.447545,0.486550,0.371890,0.512105
21,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.460323,0.122394,0.414929,0.132145,0.443510
22,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.439251,0.389599,0.425689,0.314279,0.447882
23,Qwen/Qwen3-8B,tacq,Indonesian,4-bit,0.517821,0.466039,0.495965,0.376261,0.521856
24,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.250504,0.115669,0.195696,0.157364,0.169469
25,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.457184,0.385003,0.427819,0.341291,0.462228
26,Qwen/Qwen3-8B,tacq,Swahili,4-bit,0.499328,0.434768,0.458978,0.372562,0.495293
15,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.395427,0.092804,0.257566,0.106590,0.440484
16,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.439812,0.378278,0.435440,0.303295,0.480834
17,Qwen/Qwen3-8B,tacq,Chinese,4-bit,0.496638,0.451580,0.467048,0.375588,0.510087
3,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.539005,0.118023,0.498991,0.138870,0.511432
4,CohereLabs/aya-expanse-8b,tacq,English,3-bit,0.609280,0.416947,0.591459,0.319435,0.589778
5,CohereLabs/aya-expanse-8b,tacq,English,4-bit,0.602892,0.479489,0.594822,0.359449,0.595158
12,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,0.463685,0.334566,0.452253,0.168796,0.477135
13,CohereLabs/aya-expanse-8b,tacq,Tamil,3-bit,0.578346,0.456960,0.567922,0.343981,0.585743
14,CohereLabs/aya-expanse-8b,tacq,Tamil,4-bit,0.609953,0.491930,0.601883,0.389038,0.626765
6,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.549092,0.156355,0.525555,0.192670,0.541695
7,CohereLabs/aya-expanse-8b,tacq,Indonesian,3-bit,0.596839,0.409549,0.570276,0.331540,0.587761
8,CohereLabs/aya-expanse-8b,tacq,Indonesian,4-bit,0.610962,0.467720,0.588097,0.363820,0.598521
9,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,0.494620,0.171822,0.483188,0.273369,0.485205
10,CohereLabs/aya-expanse-8b,tacq,Swahili,3-bit,0.596839,0.404842,0.580027,0.358776,0.598857
11,CohereLabs/aya-expanse-8b,tacq,Swahili,4-bit,0.610962,0.479489,0.603228,0.369872,0.614324
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.552455,0.173504,0.508742,0.176866,0.560188
1,CohereLabs/aya-expanse-8b,tacq,Chinese,3-bit,0.584062,0.421318,0.587761,0.295225,0.589442
2,CohereLabs/aya-expanse-8b,tacq,Chinese,4-bit,0.610625,0.474109,0.602219,0.361802,0.610625

/tmp/ipykernel_4192/3088488596.py:164: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

,Base Model,Quantization Technique,Calibration Language,Bit Width,en-US,ta-IN,id-ID,sw-KE,zh-CN
18,Qwen/Qwen3-8B,tacq,English,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
19,Qwen/Qwen3-8B,tacq,English,3-bit,0.005216,0.028931,0.019408,0.014552,0.007584
27,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
28,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.015688,0.006738,0.009929,0.005768,0.007119
21,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
22,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.002910,0.007119,0.008721,0.008164,0.007653
24,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
25,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.012084,0.018399,0.010648,0.008807,0.017563
15,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
16,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
3,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
12,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
6,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
9,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'SW' 'ZH']
mean_ppl

en-US    0.578682
ta-IN    0.373907
id-ID    0.441829
sw-KE    0.373235
zh-CN    0.537996
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'SW' 'ZH']
mean_ppl

en-US    2.410110
ta-IN    1.862475
id-ID    2.236942
sw-KE    1.483188
zh-CN    2.432863
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'SW' 'ZH']
mean_ppl

en-US    2.444183
ta-IN    2.246806
id-ID    2.364829
sw-KE    1.854069
zh-CN    2.547411
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en-US    0.840955
ta-IN    0.329523
id-ID    0.667787
sw-KE    0.353396
zh-CN    0.729657
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en-US    2.370208
ta-IN    1.583053
id-ID    2.300605
sw-KE    1.207465
zh-CN    2.366174
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en-US    2.409549
ta-IN    1.866510
id-ID    2.364492
sw-KE    1.424681
zh-CN    2.412239
dtype: float64

In [ ]:
eval_languages = ['en-US', 'id-ID', 'ta-IN', 'sw-KE', 'zh-CN']

# Initialize the W&B API
api = Api()

quantization_technique = "GPTQ"
# bit = 8
num_samples = 128
eval_dataset = "massive"
eval_dataset_variant = "-scenario"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.num_calibration_samples": num_samples},
                            {"config.evaluation_dataset": f"{eval_dataset.lower()}{eval_dataset_variant}"},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"$not": {"config.calibration_language": "WuuChinese"}},
                            {"$not": {"$and": [{"created_at": {"$lt": "2026-03-01"}}, {"config.quantization_technique": "gptq"}]}},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.evaluation_dataset": f"{eval_dataset.lower()}{eval_dataset_variant}"},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            {"config.output_type": "multiple_choice"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              {"config.evaluation_dataset": f"{eval_dataset.lower()}{eval_dataset_variant}"},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                              {"created_at": {"$gt": "2026-07-01"}},
                          ]}
                      ]}
                  )

  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-14B"], quantization_technique=quantization_technique, bits=["2-bit", "3-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False, vertical_spacing=0.038, horizontal_spacing=0.040, random_guess_score=1/18, write_pdf="massive_14b_barplot_reduced_errorbar_final.pdf")

Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,en-US,ta-IN,id-ID,sw-KE,zh-CN
2,Qwen/Qwen3-14B,gptq,2-bit,English,0.113315,0.082381,0.089778,0.083389,0.088097
4,Qwen/Qwen3-14B,gptq,3-bit,English,0.518494,0.428379,0.491258,0.349361,0.471083
3,Qwen/Qwen3-14B,gptq,2-bit,Tamil,0.087088,0.075992,0.080363,0.068594,0.087424
5,Qwen/Qwen3-14B,gptq,3-bit,Tamil,0.561533,0.537660,0.553800,0.411903,0.546066
6,Qwen/Qwen3-14B,gptq,2-bit,Indonesian,0.111298,0.072293,0.107599,0.066577,0.087761
7,Qwen/Qwen3-14B,gptq,3-bit,Indonesian,0.544048,0.464694,0.527236,0.386348,0.508406
8,Qwen/Qwen3-14B,gptq,2-bit,Swahili,0.091123,0.073638,0.093813,0.079691,0.074311
0,Qwen/Qwen3-14B,gptq,3-bit,Swahili,0.571957,0.519166,0.541358,0.459314,0.549428
9,Qwen/Qwen3-14B,gptq,2-bit,Chinese,0.112979,0.084398,0.093141,0.075656,0.112979
1,Qwen/Qwen3-14B,gptq,3-bit,Chinese,0.570948,0.515131,0.533289,0.390720,0.553127

Empty DataFrame
Columns: [Base Model, Quantization Technique, Bit Width, Calibration Language, en-US, ta-IN, id-ID, sw-KE, zh-CN]
Index: []

,Base Model,Quantization Technique,Bit Width,Calibration Language,en-US,ta-IN,id-ID,sw-KE,zh-CN
4,Qwen/Qwen3-14B,tacq,2-bit,English,0.488904,0.113652,0.303631,0.140888,0.442502
7,Qwen/Qwen3-14B,tacq,3-bit,English,0.582381,0.486214,0.552455,0.393073,0.561533
6,Qwen/Qwen3-14B,tacq,2-bit,Tamil,0.450235,0.417956,0.387021,0.208137,0.448890
9,Qwen/Qwen3-14B,tacq,3-bit,Tamil,0.594822,0.551110,0.545393,0.432414,0.561870
5,Qwen/Qwen3-14B,tacq,2-bit,Indonesian,0.466039,0.187962,0.463349,0.195360,0.442838
8,Qwen/Qwen3-14B,tacq,3-bit,Indonesian,0.588433,0.525891,0.568258,0.442165,0.565568
0,Qwen/Qwen3-14B,tacq,2-bit,Swahili,0.394418,0.147276,0.354069,0.289173,0.389711
2,Qwen/Qwen3-14B,tacq,3-bit,Swahili,0.579691,0.513786,0.537996,0.445528,0.575656
1,Qwen/Qwen3-14B,tacq,2-bit,Chinese,0.462004,0.120040,0.316073,0.159045,0.458978
3,Qwen/Qwen3-14B,tacq,3-bit,Chinese,0.562542,0.498655,0.531271,0.390383,0.546402

Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en-US,ta-IN,id-ID,sw-KE,zh-CN
2,Qwen/Qwen3-14B,gptq,English,2-bit,0.113315,0.082381,0.089778,0.083389,0.088097
3,Qwen/Qwen3-14B,gptq,English,3-bit,0.518494,0.428379,0.491258,0.349361,0.471083
8,Qwen/Qwen3-14B,gptq,Tamil,2-bit,0.087088,0.075992,0.080363,0.068594,0.087424
9,Qwen/Qwen3-14B,gptq,Tamil,3-bit,0.561533,0.537660,0.553800,0.411903,0.546066
4,Qwen/Qwen3-14B,gptq,Indonesian,2-bit,0.111298,0.072293,0.107599,0.066577,0.087761
5,Qwen/Qwen3-14B,gptq,Indonesian,3-bit,0.544048,0.464694,0.527236,0.386348,0.508406
6,Qwen/Qwen3-14B,gptq,Swahili,2-bit,0.091123,0.073638,0.093813,0.079691,0.074311
7,Qwen/Qwen3-14B,gptq,Swahili,3-bit,0.571957,0.519166,0.541358,0.459314,0.549428
0,Qwen/Qwen3-14B,gptq,Chinese,2-bit,0.112979,0.084398,0.093141,0.075656,0.112979
1,Qwen/Qwen3-14B,gptq,Chinese,3-bit,0.570948,0.515131,0.533289,0.390720,0.553127

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en-US, ta-IN, id-ID, sw-KE, zh-CN]
Index: []

SLIM

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en-US, ta-IN, id-ID, sw-KE, zh-CN]
Index: []

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en-US, ta-IN, id-ID, sw-KE, zh-CN]
Index: []

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en-US,ta-IN,id-ID,sw-KE,zh-CN
2,Qwen/Qwen3-14B,tacq,English,2-bit,0.488904,0.113652,0.303631,0.140888,0.442502
3,Qwen/Qwen3-14B,tacq,English,3-bit,0.582381,0.486214,0.552455,0.393073,0.561533
8,Qwen/Qwen3-14B,tacq,Tamil,2-bit,0.450235,0.417956,0.387021,0.208137,0.448890
9,Qwen/Qwen3-14B,tacq,Tamil,3-bit,0.594822,0.551110,0.545393,0.432414,0.561870
4,Qwen/Qwen3-14B,tacq,Indonesian,2-bit,0.466039,0.187962,0.463349,0.195360,0.442838
5,Qwen/Qwen3-14B,tacq,Indonesian,3-bit,0.588433,0.525891,0.568258,0.442165,0.565568
6,Qwen/Qwen3-14B,tacq,Swahili,2-bit,0.394418,0.147276,0.354069,0.289173,0.389711
7,Qwen/Qwen3-14B,tacq,Swahili,3-bit,0.579691,0.513786,0.537996,0.445528,0.575656
0,Qwen/Qwen3-14B,tacq,Chinese,2-bit,0.462004,0.120040,0.316073,0.159045,0.458978
1,Qwen/Qwen3-14B,tacq,Chinese,3-bit,0.562542,0.498655,0.531271,0.390383,0.546402

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en-US, ta-IN, id-ID, sw-KE, zh-CN]
Index: []

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
[]
[[0, 'EN'], [1, 'TA'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
[]

### XStoryCloze Bar

In [ ]:
eval_languages = ["en", "id", "sw", "zh"]

# Initialize the W&B API
api = Api()

quantization_technique = "GPTQ"
# bit = 8
num_samples = 128
eval_dataset = "xstorycloze"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit in [3]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.num_calibration_samples": num_samples},
                            {"$or": [
                                {"$and": [
                                  {"config.evaluation_dataset": f"{eval_dataset.lower()}"},
                                  {"created_at": {"$lt": "2026-07-01"}},
                                ]},
                                {"$and": [
                                  {"$or": [
                                    {"config.evaluation_dataset": f"{eval_dataset.lower()}-1000"},
                                    {"config.evaluation_dataset": f"{eval_dataset.lower()}-2000"},
                                  ]},
                                  {"created_at": {"$gt": "2026-07-01"}},
                                ]},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"$not": {"config.calibration_language": "WuuChinese"}},
                            {"$not": {"config.calibration_language": "Tamil"}},
                            {"$not": {"$and": [{"created_at": {"$lt": "2026-03-01"}}, {"config.quantization_technique": "gptq"}]}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.evaluation_dataset": eval_dataset.lower()},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              {"config.evaluation_dataset": eval_dataset.lower()},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"created_at": {"$lt": "2026-07-01"}},
                          ]}
                      ]}
                  )

  # visualize_delta_unquantized_deliver_bar(eval_languages=eval_languages, runs=runs, base_model=base_model, quantization_technique=quantization_technique, bits=['2-bit', '3-bit'], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=True)
  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b"], quantization_technique=quantization_technique, bits=['2-bit', '3-bit', '4-bit'], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=True, vertical_spacing=0.08, horizontal_spacing=0.025, random_guess_score=1/2, write_pdf="xstorycloze_barplot_sinq_final.pdf")

Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,id,sw,zh
8,Qwen/Qwen3-8B,gptq,2-bit,English,0.503640,0.453342,0.468564,0.472535
24,Qwen/Qwen3-8B,gptq,2-bit,English,0.497684,0.448048,0.463931,0.467240
25,Qwen/Qwen3-8B,gptq,2-bit,English,0.510258,0.462608,0.463931,0.479815
4,Qwen/Qwen3-8B,gptq,3-bit,English,0.666446,0.596956,0.511582,0.602912
32,Qwen/Qwen3-8B,gptq,3-bit,English,0.690933,0.602250,0.510920,0.608868
33,Qwen/Qwen3-8B,gptq,3-bit,English,0.697551,0.610854,0.508273,0.625414
0,Qwen/Qwen3-8B,gptq,4-bit,English,0.685639,0.617472,0.523494,0.618795
9,Qwen/Qwen3-8B,gptq,2-bit,Indonesian,0.455989,0.483786,0.464593,0.457975
26,Qwen/Qwen3-8B,gptq,2-bit,Indonesian,0.488418,0.473197,0.467240,0.469226
27,Qwen/Qwen3-8B,gptq,2-bit,Indonesian,0.490404,0.469887,0.473858,0.459298
5,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,0.666446,0.612839,0.503640,0.618134
34,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,0.684315,0.615486,0.514229,0.618134
35,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,0.683653,0.615486,0.510258,0.605559
1,Qwen/Qwen3-8B,gptq,4-bit,Indonesian,0.688286,0.622766,0.520185,0.626075
10,Qwen/Qwen3-8B,gptq,2-bit,Swahili,0.452019,0.447386,0.501655,0.471873
28,Qwen/Qwen3-8B,gptq,2-bit,Swahili,0.469887,0.452680,0.508273,0.469226
29,Qwen/Qwen3-8B,gptq,2-bit,Swahili,0.489742,0.455328,0.492389,0.461946
6,Qwen/Qwen3-8B,gptq,3-bit,Swahili,0.669755,0.598279,0.525480,0.597617
36,Qwen/Qwen3-8B,gptq,3-bit,Swahili,0.653210,0.585043,0.524156,0.589014
37,Qwen/Qwen3-8B,gptq,3-bit,Swahili,0.659828,0.600265,0.534083,0.602250
2,Qwen/Qwen3-8B,gptq,4-bit,Swahili,0.699537,0.625414,0.529451,0.621443
11,Qwen/Qwen3-8B,gptq,2-bit,Chinese,0.487095,0.440106,0.461946,0.471873
30,Qwen/Qwen3-8B,gptq,2-bit,Chinese,0.489080,0.453342,0.471211,0.489742
31,Qwen/Qwen3-8B,gptq,2-bit,Chinese,0.493713,0.451357,0.465255,0.506287
7,Qwen/Qwen3-8B,gptq,3-bit,Chinese,0.673064,0.585043,0.508934,0.623428
38,Qwen/Qwen3-8B,gptq,3-bit,Chinese,0.671741,0.592323,0.526803,0.624752
39,Qwen/Qwen3-8B,gptq,3-bit,Chinese,0.684977,0.600927,0.503640,0.626737
3,Qwen/Qwen3-8B,gptq,4-bit,Chinese,0.695566,0.632032,0.522833,0.634679
20,CohereLabs/aya-expanse-8b,gptq,2-bit,English,0.513567,0.442753,0.468564,0.465917
16,CohereLabs/aya-expanse-8b,gptq,3-bit,English,0.747849,0.639312,0.485771,0.623428
12,CohereLabs/aya-expanse-8b,gptq,4-bit,English,0.769027,0.681006,0.502978,0.657181
21,CohereLabs/aya-expanse-8b,gptq,2-bit,Indonesian,0.510920,0.492389,0.467240,0.470549
17,CohereLabs/aya-expanse-8b,gptq,3-bit,Indonesian,0.740569,0.655195,0.487095,0.636003
13,CohereLabs/aya-expanse-8b,gptq,4-bit,Indonesian,0.764394,0.680344,0.506287,0.658504
22,CohereLabs/aya-expanse-8b,gptq,2-bit,Swahili,0.476506,0.454666,0.485109,0.469226
18,CohereLabs/aya-expanse-8b,gptq,3-bit,Swahili,0.747187,0.649901,0.508273,0.636664
14,CohereLabs/aya-expanse-8b,gptq,4-bit,Swahili,0.747849,0.658504,0.502978,0.652548
23,CohereLabs/aya-expanse-8b,gptq,2-bit,Chinese,0.485771,0.449371,0.470549,0.524818
19,CohereLabs/aya-expanse-8b,gptq,3-bit,Chinese,0.745202,0.651886,0.487756,0.643283
15,CohereLabs/aya-expanse-8b,gptq,4-bit,Chinese,0.750496,0.671079,0.495698,0.654533
40,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,English,0.493713,0.428855,0.469226,0.473858
41,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,English,0.490404,0.442753,0.465917,0.469887
42,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Indonesian,0.474520,0.466578,0.471211,0.477829
43,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Indonesian,0.476506,0.445400,0.465917,0.479815

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,id,sw,zh
8,Qwen/Qwen3-8B,slimllm,2-bit,English,0.540702,0.463269,0.481800,0.477167
4,Qwen/Qwen3-8B,slimllm,3-bit,English,0.665784,0.591661,0.505625,0.600265
24,Qwen/Qwen3-8B,slimllm,3-bit,English,0.675711,0.592985,0.513567,0.596294
25,Qwen/Qwen3-8B,slimllm,3-bit,English,0.657842,0.565189,0.489742,0.587690
0,Qwen/Qwen3-8B,slimllm,4-bit,English,0.692257,0.624090,0.524156,0.623428
9,Qwen/Qwen3-8B,slimllm,2-bit,Indonesian,0.510258,0.501655,0.485109,0.491066
5,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,0.637988,0.591661,0.501655,0.596956
26,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,0.672402,0.613501,0.512244,0.595632
27,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,0.653872,0.605559,0.491066,0.595632
1,Qwen/Qwen3-8B,slimllm,4-bit,Indonesian,0.696228,0.635341,0.516214,0.621443
10,Qwen/Qwen3-8B,slimllm,2-bit,Swahili,0.483124,0.459960,0.495698,0.485771
6,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,0.670417,0.587028,0.518862,0.608206
28,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,0.672402,0.592323,0.525480,0.591661
29,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,0.660490,0.586367,0.518200,0.611516
2,Qwen/Qwen3-8B,slimllm,4-bit,Swahili,0.709464,0.630708,0.527465,0.624090
11,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,0.505625,0.474520,0.477829,0.516214
7,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,0.669755,0.581734,0.504964,0.615486
30,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,0.666446,0.584381,0.493051,0.590999
31,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,0.665784,0.569159,0.498345,0.616148
3,Qwen/Qwen3-8B,slimllm,4-bit,Chinese,0.681668,0.624752,0.512244,0.625414
20,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,0.640635,0.454004,0.469226,0.473197
16,CohereLabs/aya-expanse-8b,slimllm,3-bit,English,0.733289,0.633355,0.500993,0.619457
12,CohereLabs/aya-expanse-8b,slimllm,4-bit,English,0.762409,0.669093,0.504302,0.653210
21,CohereLabs/aya-expanse-8b,slimllm,2-bit,Indonesian,0.606883,0.578425,0.473197,0.469226
17,CohereLabs/aya-expanse-8b,slimllm,3-bit,Indonesian,0.751158,0.651886,0.513567,0.625414
13,CohereLabs/aya-expanse-8b,slimllm,4-bit,Indonesian,0.767042,0.695566,0.518200,0.655857
22,CohereLabs/aya-expanse-8b,slimllm,2-bit,Swahili,0.540040,0.504964,0.499669,0.477829
18,CohereLabs/aya-expanse-8b,slimllm,3-bit,Swahili,0.756453,0.677035,0.503640,0.652548
14,CohereLabs/aya-expanse-8b,slimllm,4-bit,Swahili,0.758438,0.674388,0.512905,0.655195
23,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,0.488418,0.463269,0.471211,0.568498
19,CohereLabs/aya-expanse-8b,slimllm,3-bit,Chinese,0.730642,0.624752,0.494375,0.631370
15,CohereLabs/aya-expanse-8b,slimllm,4-bit,Chinese,0.761085,0.664461,0.515553,0.650563

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,id,sw,zh
8,Qwen/Qwen3-8B,tacq,2-bit,English,0.636664,0.477167,0.490404,0.544672
4,Qwen/Qwen3-8B,tacq,3-bit,English,0.682991,0.590999,0.516214,0.610854
24,Qwen/Qwen3-8B,tacq,3-bit,English,0.696889,0.614825,0.524818,0.621443
25,Qwen/Qwen3-8B,tacq,3-bit,English,0.690933,0.595632,0.505625,0.612177
0,Qwen/Qwen3-8B,tacq,4-bit,English,0.682330,0.622105,0.521509,0.618795
9,Qwen/Qwen3-8B,tacq,2-bit,Indonesian,0.622105,0.558570,0.487756,0.551291
5,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,0.677035,0.626737,0.514229,0.620781
26,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,0.681006,0.616148,0.514891,0.616148
27,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,0.674388,0.609530,0.511582,0.613501
1,Qwen/Qwen3-8B,tacq,4-bit,Indonesian,0.707478,0.626075,0.519523,0.618134
10,Qwen/Qwen3-8B,tacq,2-bit,Swahili,0.579749,0.504964,0.505625,0.521509
6,Qwen/Qwen3-8B,tacq,3-bit,Swahili,0.671079,0.607545,0.520847,0.622766
28,Qwen/Qwen3-8B,tacq,3-bit,Swahili,0.675050,0.600927,0.531436,0.598941
29,Qwen/Qwen3-8B,tacq,3-bit,Swahili,0.669093,0.592985,0.528127,0.615486
2,Qwen/Qwen3-8B,tacq,4-bit,Swahili,0.701522,0.628061,0.539378,0.630046
11,Qwen/Qwen3-8B,tacq,2-bit,Chinese,0.601588,0.487756,0.487095,0.565850
7,Qwen/Qwen3-8B,tacq,3-bit,Chinese,0.677035,0.610854,0.502978,0.608206
3,Qwen/Qwen3-8B,tacq,4-bit,Chinese,0.690271,0.617472,0.518862,0.624090
20,CohereLabs/aya-expanse-8b,tacq,2-bit,English,0.739246,0.558570,0.495036,0.596294
16,CohereLabs/aya-expanse-8b,tacq,3-bit,English,0.748511,0.652548,0.497022,0.646592
12,CohereLabs/aya-expanse-8b,tacq,4-bit,English,0.771674,0.669093,0.506287,0.662475
21,CohereLabs/aya-expanse-8b,tacq,2-bit,Indonesian,0.728657,0.666446,0.487095,0.612177
17,CohereLabs/aya-expanse-8b,tacq,3-bit,Indonesian,0.765056,0.662475,0.490404,0.653872
13,CohereLabs/aya-expanse-8b,tacq,4-bit,Indonesian,0.781602,0.699537,0.501655,0.673064
22,CohereLabs/aya-expanse-8b,tacq,2-bit,Swahili,0.677035,0.614163,0.504302,0.567836
18,CohereLabs/aya-expanse-8b,tacq,3-bit,Swahili,0.761747,0.663799,0.510920,0.650563
14,CohereLabs/aya-expanse-8b,tacq,4-bit,Swahili,0.776969,0.666446,0.510258,0.655857
23,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,0.707478,0.611516,0.496360,0.623428
19,CohereLabs/aya-expanse-8b,tacq,3-bit,Chinese,0.771674,0.680344,0.488418,0.653872
15,CohereLabs/aya-expanse-8b,tacq,4-bit,Chinese,0.761085,0.675050,0.510258,0.649901

Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
15,Qwen/Qwen3-8B,gptq,English,2-bit,0.503861,0.454666,0.465475,0.473197
16,Qwen/Qwen3-8B,gptq,English,3-bit,0.684977,0.603353,0.510258,0.612398
17,Qwen/Qwen3-8B,gptq,English,4-bit,0.685639,0.617472,0.523494,0.618795
18,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,0.478270,0.475623,0.468564,0.462166
19,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,0.678138,0.614604,0.509376,0.613942
20,Qwen/Qwen3-8B,gptq,Indonesian,4-bit,0.688286,0.622766,0.520185,0.626075
21,Qwen/Qwen3-8B,gptq,Swahili,2-bit,0.470549,0.451798,0.500772,0.467681
22,Qwen/Qwen3-8B,gptq,Swahili,3-bit,0.660931,0.594529,0.527906,0.596294
23,Qwen/Qwen3-8B,gptq,Swahili,4-bit,0.699537,0.625414,0.529451,0.621443
12,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.489962,0.448268,0.466137,0.489301
13,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.676594,0.592764,0.513126,0.624972
14,Qwen/Qwen3-8B,gptq,Chinese,4-bit,0.695566,0.632032,0.522833,0.634679
3,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.513567,0.442753,0.468564,0.465917
4,CohereLabs/aya-expanse-8b,gptq,English,3-bit,0.747849,0.639312,0.485771,0.623428
5,CohereLabs/aya-expanse-8b,gptq,English,4-bit,0.769027,0.681006,0.502978,0.657181
6,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,0.510920,0.492389,0.467240,0.470549
7,CohereLabs/aya-expanse-8b,gptq,Indonesian,3-bit,0.740569,0.655195,0.487095,0.636003
8,CohereLabs/aya-expanse-8b,gptq,Indonesian,4-bit,0.764394,0.680344,0.506287,0.658504
9,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,0.476506,0.454666,0.485109,0.469226
10,CohereLabs/aya-expanse-8b,gptq,Swahili,3-bit,0.747187,0.649901,0.508273,0.636664
11,CohereLabs/aya-expanse-8b,gptq,Swahili,4-bit,0.747849,0.658504,0.502978,0.652548
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.485771,0.449371,0.470549,0.524818
1,CohereLabs/aya-expanse-8b,gptq,Chinese,3-bit,0.745202,0.651886,0.487756,0.643283
2,CohereLabs/aya-expanse-8b,gptq,Chinese,4-bit,0.750496,0.671079,0.495698,0.654533
24,meta-llama/Llama-3.1-8B-Instruct,gptq,English,2-bit,0.492058,0.435804,0.467571,0.471873
25,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,2-bit,0.475513,0.455989,0.468564,0.478822

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
15,Qwen/Qwen3-8B,gptq,English,2-bit,0.005136,0.006017,0.002184,0.005155
16,Qwen/Qwen3-8B,gptq,English,3-bit,0.013379,0.005727,0.001430,0.009519
18,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,0.015776,0.005928,0.003897,0.005021
19,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,0.008272,0.001248,0.004368,0.005928
21,Qwen/Qwen3-8B,gptq,Swahili,2-bit,0.015408,0.003302,0.006514,0.004197
22,Qwen/Qwen3-8B,gptq,Swahili,3-bit,0.006799,0.006756,0.004401,0.005484
12,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.002773,0.005828,0.003834,0.014053
13,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.005952,0.006492,0.009910,0.001360
3,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.000000,0.000000,0.000000,0.000000
6,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000
9,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,0.000000,0.000000,0.000000,0.000000
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.000000,0.000000,0.000000,0.000000

SLIM

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
15,Qwen/Qwen3-8B,slimllm,English,2-bit,0.540702,0.463269,0.481800,0.477167
16,Qwen/Qwen3-8B,slimllm,English,3-bit,0.666446,0.583278,0.502978,0.594750
17,Qwen/Qwen3-8B,slimllm,English,4-bit,0.692257,0.624090,0.524156,0.623428
18,Qwen/Qwen3-8B,slimllm,Indonesian,2-bit,0.510258,0.501655,0.485109,0.491066
19,Qwen/Qwen3-8B,slimllm,Indonesian,3-bit,0.654754,0.603574,0.501655,0.596073
20,Qwen/Qwen3-8B,slimllm,Indonesian,4-bit,0.696228,0.635341,0.516214,0.621443
21,Qwen/Qwen3-8B,slimllm,Swahili,2-bit,0.483124,0.459960,0.495698,0.485771
22,Qwen/Qwen3-8B,slimllm,Swahili,3-bit,0.667770,0.588573,0.520847,0.603794
23,Qwen/Qwen3-8B,slimllm,Swahili,4-bit,0.709464,0.630708,0.527465,0.624090
12,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.505625,0.474520,0.477829,0.516214
13,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.667328,0.578425,0.498787,0.607545
14,Qwen/Qwen3-8B,slimllm,Chinese,4-bit,0.681668,0.624752,0.512244,0.625414
3,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.640635,0.454004,0.469226,0.473197
4,CohereLabs/aya-expanse-8b,slimllm,English,3-bit,0.733289,0.633355,0.500993,0.619457
5,CohereLabs/aya-expanse-8b,slimllm,English,4-bit,0.762409,0.669093,0.504302,0.653210
6,CohereLabs/aya-expanse-8b,slimllm,Indonesian,2-bit,0.606883,0.578425,0.473197,0.469226
7,CohereLabs/aya-expanse-8b,slimllm,Indonesian,3-bit,0.751158,0.651886,0.513567,0.625414
8,CohereLabs/aya-expanse-8b,slimllm,Indonesian,4-bit,0.767042,0.695566,0.518200,0.655857
9,CohereLabs/aya-expanse-8b,slimllm,Swahili,2-bit,0.540040,0.504964,0.499669,0.477829
10,CohereLabs/aya-expanse-8b,slimllm,Swahili,3-bit,0.756453,0.677035,0.503640,0.652548
11,CohereLabs/aya-expanse-8b,slimllm,Swahili,4-bit,0.758438,0.674388,0.512905,0.655195
0,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.488418,0.463269,0.471211,0.568498
1,CohereLabs/aya-expanse-8b,slimllm,Chinese,3-bit,0.730642,0.624752,0.494375,0.631370
2,CohereLabs/aya-expanse-8b,slimllm,Chinese,4-bit,0.761085,0.664461,0.515553,0.650563

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
15,Qwen/Qwen3-8B,slimllm,English,2-bit,0.000000,0.000000,0.000000,0.000000
16,Qwen/Qwen3-8B,slimllm,English,3-bit,0.007310,0.012803,0.009905,0.005248
18,Qwen/Qwen3-8B,slimllm,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000
19,Qwen/Qwen3-8B,slimllm,Indonesian,3-bit,0.014063,0.009026,0.008646,0.000624
21,Qwen/Qwen3-8B,slimllm,Swahili,2-bit,0.000000,0.000000,0.000000,0.000000
22,Qwen/Qwen3-8B,slimllm,Swahili,3-bit,0.005211,0.002666,0.003287,0.008685
12,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.000000,0.000000,0.000000,0.000000
13,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.001737,0.006640,0.004873,0.011702
3,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.000000,0.000000,0.000000,0.000000
6,CohereLabs/aya-expanse-8b,slimllm,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000
9,CohereLabs/aya-expanse-8b,slimllm,Swahili,2-bit,0.000000,0.000000,0.000000,0.000000
0,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.000000,0.000000,0.000000,0.000000

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
15,Qwen/Qwen3-8B,tacq,English,2-bit,0.636664,0.477167,0.490404,0.544672
16,Qwen/Qwen3-8B,tacq,English,3-bit,0.690271,0.600485,0.515553,0.614825
17,Qwen/Qwen3-8B,tacq,English,4-bit,0.682330,0.622105,0.521509,0.618795
18,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.622105,0.558570,0.487756,0.551291
19,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.677476,0.617472,0.513567,0.616810
20,Qwen/Qwen3-8B,tacq,Indonesian,4-bit,0.707478,0.626075,0.519523,0.618134
21,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.579749,0.504964,0.505625,0.521509
22,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.671741,0.600485,0.526803,0.612398
23,Qwen/Qwen3-8B,tacq,Swahili,4-bit,0.701522,0.628061,0.539378,0.630046
12,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.601588,0.487756,0.487095,0.565850
13,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.677035,0.610854,0.502978,0.608206
14,Qwen/Qwen3-8B,tacq,Chinese,4-bit,0.690271,0.617472,0.518862,0.624090
3,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.739246,0.558570,0.495036,0.596294
4,CohereLabs/aya-expanse-8b,tacq,English,3-bit,0.748511,0.652548,0.497022,0.646592
5,CohereLabs/aya-expanse-8b,tacq,English,4-bit,0.771674,0.669093,0.506287,0.662475
6,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.728657,0.666446,0.487095,0.612177
7,CohereLabs/aya-expanse-8b,tacq,Indonesian,3-bit,0.765056,0.662475,0.490404,0.653872
8,CohereLabs/aya-expanse-8b,tacq,Indonesian,4-bit,0.781602,0.699537,0.501655,0.673064
9,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,0.677035,0.614163,0.504302,0.567836
10,CohereLabs/aya-expanse-8b,tacq,Swahili,3-bit,0.761747,0.663799,0.510920,0.650563
11,CohereLabs/aya-expanse-8b,tacq,Swahili,4-bit,0.776969,0.666446,0.510258,0.655857
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.707478,0.611516,0.496360,0.623428
1,CohereLabs/aya-expanse-8b,tacq,Chinese,3-bit,0.771674,0.680344,0.488418,0.653872
2,CohereLabs/aya-expanse-8b,tacq,Chinese,4-bit,0.761085,0.675050,0.510258,0.649901

/tmp/ipykernel_4192/3088488596.py:164: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
15,Qwen/Qwen3-8B,tacq,English,2-bit,0.000000,0.000000,0.000000,0.000000
16,Qwen/Qwen3-8B,tacq,English,3-bit,0.005693,0.010314,0.007849,0.004711
18,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000
19,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.002720,0.007087,0.001430,0.003009
21,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.000000,0.000000,0.000000,0.000000
22,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.002476,0.005952,0.004423,0.009969
12,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.000000,0.000000,0.000000,0.000000
13,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.000000,0.000000,0.000000,0.000000
3,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.000000,0.000000,0.000000,0.000000
6,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000
9,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,0.000000,0.000000,0.000000,0.000000
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.000000,0.000000,0.000000,0.000000

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    2.039709
id    1.899404
sw    1.940437
zh    1.970218
dtype: float64

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    2.656298
id    2.353850
sw    2.024266
zh    2.402162
dtype: float64

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    2.779616
id    2.514891
sw    2.080079
zh    2.494375
dtype: float64

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    2.275976
id    2.000662
sw    1.913302
zh    1.988749
dtype: float64

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    2.971542
id    2.587028
sw    2.012574
zh    2.528789
dtype: float64

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    3.048974
id    2.703508
sw    2.050960
zh    2.614825
dtype: float64

In [ ]:
eval_languages = ["en", "id", "sw", "zh"]

# Initialize the W&B API
api = Api()

quantization_technique = "GPTQ"
# bit = 8
num_samples = 128
eval_dataset = "xstorycloze"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.num_calibration_samples": num_samples},
                            {"config.evaluation_dataset": f"{eval_dataset.lower()}"},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"$not": {"config.calibration_language": "WuuChinese"}},
                            {"$not": {"$and": [{"created_at": {"$lt": "2026-03-01"}}, {"config.quantization_technique": "gptq"}]}},
                            {"created_at": {"$gt": "2026-07-01"}},
                            {"$not": {"config.calibration_language": "Tamil"}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.evaluation_dataset": eval_dataset.lower()},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            {"config.output_type": "multiple_choice"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              {"config.evaluation_dataset": eval_dataset.lower()},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                              {"created_at": {"$gt": "2026-07-01"}},
                          ]}
                      ]}
                  )

  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-14B"], quantization_technique=quantization_technique, bits=["2-bit", "3-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False, vertical_spacing=0.038, horizontal_spacing=0.040, random_guess_score=0.5, write_pdf="xstorycloze_14b_barplot_reduced_errorbar_final.pdf")

Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,id,sw,zh
2,Qwen/Qwen3-14B,gptq,2-bit,English,0.517538,0.450695,0.459298,0.489080
4,Qwen/Qwen3-14B,gptq,3-bit,English,0.697551,0.632694,0.486433,0.642621
3,Qwen/Qwen3-14B,gptq,2-bit,Indonesian,0.497022,0.493051,0.484447,0.467902
5,Qwen/Qwen3-14B,gptq,3-bit,Indonesian,0.707478,0.634017,0.521509,0.645930
7,Qwen/Qwen3-14B,gptq,2-bit,Swahili,0.482462,0.459960,0.504964,0.458637
0,Qwen/Qwen3-14B,gptq,3-bit,Swahili,0.673726,0.630046,0.537392,0.634679
6,Qwen/Qwen3-14B,gptq,2-bit,Chinese,0.499007,0.443415,0.479153,0.497022
1,Qwen/Qwen3-14B,gptq,3-bit,Chinese,0.696889,0.628723,0.491727,0.652548

Empty DataFrame
Columns: [Base Model, Quantization Technique, Bit Width, Calibration Language, en, id, sw, zh]
Index: []

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,id,sw,zh
4,Qwen/Qwen3-14B,tacq,2-bit,English,0.657842,0.478491,0.497684,0.573792
6,Qwen/Qwen3-14B,tacq,3-bit,English,0.699537,0.630708,0.518862,0.653872
5,Qwen/Qwen3-14B,tacq,2-bit,Indonesian,0.643944,0.585043,0.495698,0.587690
7,Qwen/Qwen3-14B,tacq,3-bit,Indonesian,0.702184,0.636664,0.514229,0.661152
0,Qwen/Qwen3-14B,tacq,2-bit,Swahili,0.624752,0.545996,0.516214,0.563203
2,Qwen/Qwen3-14B,tacq,3-bit,Swahili,0.697551,0.632032,0.533422,0.653210
1,Qwen/Qwen3-14B,tacq,2-bit,Chinese,0.638650,0.479153,0.491066,0.582396
3,Qwen/Qwen3-14B,tacq,3-bit,Chinese,0.690933,0.626737,0.519523,0.647915

Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
2,Qwen/Qwen3-14B,gptq,English,2-bit,0.517538,0.450695,0.459298,0.489080
3,Qwen/Qwen3-14B,gptq,English,3-bit,0.697551,0.632694,0.486433,0.642621
4,Qwen/Qwen3-14B,gptq,Indonesian,2-bit,0.497022,0.493051,0.484447,0.467902
5,Qwen/Qwen3-14B,gptq,Indonesian,3-bit,0.707478,0.634017,0.521509,0.645930
6,Qwen/Qwen3-14B,gptq,Swahili,2-bit,0.482462,0.459960,0.504964,0.458637
7,Qwen/Qwen3-14B,gptq,Swahili,3-bit,0.673726,0.630046,0.537392,0.634679
0,Qwen/Qwen3-14B,gptq,Chinese,2-bit,0.499007,0.443415,0.479153,0.497022
1,Qwen/Qwen3-14B,gptq,Chinese,3-bit,0.696889,0.628723,0.491727,0.652548

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en, id, sw, zh]
Index: []

SLIM

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en, id, sw, zh]
Index: []

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en, id, sw, zh]
Index: []

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
2,Qwen/Qwen3-14B,tacq,English,2-bit,0.657842,0.478491,0.497684,0.573792
3,Qwen/Qwen3-14B,tacq,English,3-bit,0.699537,0.630708,0.518862,0.653872
4,Qwen/Qwen3-14B,tacq,Indonesian,2-bit,0.643944,0.585043,0.495698,0.587690
5,Qwen/Qwen3-14B,tacq,Indonesian,3-bit,0.702184,0.636664,0.514229,0.661152
6,Qwen/Qwen3-14B,tacq,Swahili,2-bit,0.624752,0.545996,0.516214,0.563203
7,Qwen/Qwen3-14B,tacq,Swahili,3-bit,0.697551,0.632032,0.533422,0.653210
0,Qwen/Qwen3-14B,tacq,Chinese,2-bit,0.638650,0.479153,0.491066,0.582396
1,Qwen/Qwen3-14B,tacq,Chinese,3-bit,0.690933,0.626737,0.519523,0.647915

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en, id, sw, zh]
Index: []

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
[]
[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
[]

### INCLUDE BAR

In [ ]:
eval_languages = ["Dutch", "German", "Chinese", "Indonesian", "Tamil"]
# eval_languages = ["Dutch", "German", "Chinese", "Indonesian", "Malay", "Tagalog", "Tamil", "Telugu", "Malayalam"]
eval_languages = [lang.lower() for lang in eval_languages]

# Initialize the W&B API
api = Api()

quantization_technique = "ALL"
# bit = 8
num_samples = 128
eval_dataset = "include"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

for bit in [4]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.num_calibration_samples": num_samples},
                            {"$or": [
                                {"$and": [
                                  {"config.evaluation_dataset": f"{eval_dataset.lower()}"},
                                  {"created_at": {"$lt": "2026-07-01"}},
                                ]},
                                {"$and": [
                                  {"$or": [
                                    {"config.evaluation_dataset": f"{eval_dataset.lower()}-1000"},
                                    {"config.evaluation_dataset": f"{eval_dataset.lower()}-2000"},
                                  ]},
                                  {"created_at": {"$gt": "2026-07-01"}},
                                ]},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"$not": {"$and": [{"created_at": {"$lt": "2026-03-01"}}, {"config.quantization_technique": "gptq"}]}},
                            {"$not": {"config.calibration_language": "WuuChinese"}},
                            {"$not": {"config.calibration_language": "Swahili"}},
                            {"$not": {"config.bit_width": "8-bit"}},
                            {"$not": {"config.base_model": "Qwen/Qwen3-1.7B"}},
                            {"$not": {"config.base_model": "Qwen/Qwen3-4B"}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.evaluation_dataset": eval_dataset.lower()},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              {"config.evaluation_dataset": eval_dataset.lower()},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"$not": {"config.base_model": "Qwen/Qwen3-1.7B"}},
                              {"$not": {"config.base_model": "Qwen/Qwen3-4B"}},
                            {"created_at": {"$lt": "2026-07-01"}},
                          ]}
                      ]}
                  )

  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique=quantization_technique, bits=["2-bit", "3-bit", "4-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False, vertical_spacing=0.080, horizontal_spacing=0.030, write_pdf="include_barplot_sinq_final.pdf")

Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,dutch,german,tamil,indonesian,chinese
8,Qwen/Qwen3-8B,gptq,2-bit,English,0.192377,0.280576,0.234545,0.240000,0.255046
36,Qwen/Qwen3-8B,gptq,2-bit,English,0.255898,0.280576,0.249091,0.221818,0.244037
37,Qwen/Qwen3-8B,gptq,2-bit,English,0.206897,0.230216,0.252727,0.225455,0.244037
4,Qwen/Qwen3-8B,gptq,3-bit,English,0.401089,0.323741,0.245455,0.418182,0.526606
44,Qwen/Qwen3-8B,gptq,3-bit,English,0.450091,0.287770,0.261818,0.458182,0.544954
...,...,...,...,...,...,...,...,...,...
23,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Chinese,0.197822,0.309353,0.229091,0.232727,0.264220
58,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Chinese,0.257713,0.287770,0.258182,0.241818,0.262385
59,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Chinese,0.239564,0.280576,0.249091,0.247273,0.227523
19,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Chinese,0.319419,0.287770,0.243636,0.360000,0.357798
15,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Chinese,0.578947,0.517986,0.350909,0.601818,0.506422

,Base Model,Quantization Technique,Bit Width,Calibration Language,dutch,german,tamil,indonesian,chinese
4,Qwen/Qwen3-8B,slimllm,2-bit,English,0.165154,0.330935,0.256364,0.252727,0.245872
33,Qwen/Qwen3-8B,slimllm,2-bit,English,0.186933,0.251799,0.252727,0.263636,0.249541
34,Qwen/Qwen3-8B,slimllm,2-bit,English,0.132486,0.323741,0.245455,0.256364,0.244037
26,Qwen/Qwen3-8B,slimllm,3-bit,English,0.393829,0.388489,0.238182,0.460000,0.590826
41,Qwen/Qwen3-8B,slimllm,3-bit,English,0.528131,0.381295,0.270909,0.523636,0.622018
...,...,...,...,...,...,...,...,...,...
18,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,0.312160,0.323741,0.285455,0.223636,0.244037
55,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,0.221416,0.244604,0.236364,0.272727,0.249541
56,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,0.217786,0.208633,0.258182,0.250909,0.269725
22,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Chinese,0.352087,0.345324,0.267273,0.316364,0.348624
16,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Chinese,0.522686,0.366906,0.356364,0.510909,0.475229

,Base Model,Quantization Technique,Bit Width,Calibration Language,dutch,german,tamil,indonesian,chinese
3,Qwen/Qwen3-8B,tacq,2-bit,English,0.290381,0.316547,0.263636,0.236364,0.308257
36,Qwen/Qwen3-8B,tacq,2-bit,English,0.259528,0.230216,0.207273,0.278182,0.335780
37,Qwen/Qwen3-8B,tacq,2-bit,English,0.281307,0.215827,0.249091,0.274545,0.359633
25,Qwen/Qwen3-8B,tacq,3-bit,English,0.513612,0.467626,0.250909,0.467273,0.622018
44,Qwen/Qwen3-8B,tacq,3-bit,English,0.528131,0.402878,0.314545,0.532727,0.618349
...,...,...,...,...,...,...,...,...,...
13,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,0.134301,0.330935,0.245455,0.247273,0.260550
58,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,0.214156,0.287770,0.249091,0.261818,0.275229
59,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,0.323049,0.287770,0.296364,0.250909,0.249541
23,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Chinese,0.462795,0.417266,0.290909,0.483636,0.436697
34,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Chinese,0.573503,0.467626,0.350909,0.556364,0.513761

['NL', 'DE', 'TA', 'ID', 'ZH']
Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,english,tamil,indonesian,chinese
15,Qwen/Qwen3-8B,gptq,English,2-bit,0.241090,0.245455,0.229091,0.247706
16,Qwen/Qwen3-8B,gptq,English,3-bit,0.361216,0.247273,0.449091,0.519266
17,Qwen/Qwen3-8B,gptq,English,4-bit,0.576695,0.396364,0.649091,0.715596
21,Qwen/Qwen3-8B,gptq,Tamil,2-bit,0.228236,0.255152,0.253939,0.240979
22,Qwen/Qwen3-8B,gptq,Tamil,3-bit,0.478304,0.338788,0.531515,0.592049
23,Qwen/Qwen3-8B,gptq,Tamil,4-bit,0.593839,0.383636,0.652727,0.732110
18,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,0.286179,0.250303,0.229697,0.253211
19,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,0.468366,0.263636,0.546061,0.576147
20,Qwen/Qwen3-8B,gptq,Indonesian,4-bit,0.585672,0.403636,0.654545,0.732110
12,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.243131,0.235152,0.258182,0.240979
13,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.440333,0.290303,0.509697,0.613456
14,Qwen/Qwen3-8B,gptq,Chinese,4-bit,0.574071,0.416364,0.640000,0.721101
3,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.244308,0.255758,0.256970,0.247095
4,CohereLabs/aya-expanse-8b,gptq,English,3-bit,0.503388,0.300000,0.485455,0.484404
5,CohereLabs/aya-expanse-8b,gptq,English,4-bit,0.525232,0.280000,0.532727,0.515596
9,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,0.239913,0.241818,0.250303,0.235474
10,CohereLabs/aya-expanse-8b,gptq,Tamil,3-bit,0.393235,0.294545,0.412727,0.381651
11,CohereLabs/aya-expanse-8b,gptq,Tamil,4-bit,0.542278,0.287273,0.523636,0.522936
6,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,0.243477,0.244848,0.249697,0.234251
7,CohereLabs/aya-expanse-8b,gptq,Indonesian,3-bit,0.502546,0.283636,0.494545,0.478899
8,CohereLabs/aya-expanse-8b,gptq,Indonesian,4-bit,0.532328,0.280000,0.534545,0.495413
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.248186,0.241212,0.270303,0.271560
1,CohereLabs/aya-expanse-8b,gptq,Chinese,3-bit,0.505301,0.278182,0.516364,0.484404
2,CohereLabs/aya-expanse-8b,gptq,Chinese,4-bit,0.536964,0.278182,0.525455,0.486239
27,meta-llama/Llama-3.1-8B-Instruct,gptq,English,2-bit,0.239815,0.256364,0.243030,0.234251
28,meta-llama/Llama-3.1-8B-Instruct,gptq,English,3-bit,0.343359,0.254545,0.409091,0.293578
29,meta-llama/Llama-3.1-8B-Instruct,gptq,English,4-bit,0.516869,0.327273,0.581818,0.519266
33,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,2-bit,0.240409,0.260606,0.255758,0.250153
34,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,3-bit,0.399130,0.327273,0.396364,0.388991
35,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,4-bit,0.523319,0.363636,0.576364,0.530275
30,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,2-bit,0.253631,0.247273,0.254545,0.244648
31,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,3-bit,0.356096,0.254545,0.414545,0.383486
32,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,4-bit,0.539523,0.345455,0.574545,0.515596
24,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,2-bit,0.262133,0.245455,0.240606,0.251376
25,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,3-bit,0.303595,0.243636,0.360000,0.357798
26,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,4-bit,0.548466,0.350909,0.601818,0.506422

,Base Model,Quantization Technique,Calibration Language,Bit Width,english,tamil,indonesian,chinese
15,Qwen/Qwen3-8B,gptq,English,2-bit,0.020543,0.007855,0.007855,0.005190
16,Qwen/Qwen3-8B,gptq,English,3-bit,0.006841,0.011208,0.022465,0.024526
21,Qwen/Qwen3-8B,gptq,Tamil,2-bit,0.017172,0.015452,0.018798,0.002288
22,Qwen/Qwen3-8B,gptq,Tamil,3-bit,0.023573,0.017835,0.029179,0.021933
18,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,0.017567,0.005214,0.008176,0.014292
19,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,0.024772,0.021869,0.032400,0.027746
12,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.019244,0.005214,0.014162,0.011245
13,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.081236,0.030436,0.072732,0.028320
3,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.006899,0.007016,0.008441,0.014396
9,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,0.017658,0.017999,0.031293,0.004577
6,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,0.021606,0.020801,0.020156,0.008778
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.003471,0.024136,0.007016,0.018226

SLIM

,Base Model,Quantization Technique,Calibration Language,Bit Width,english,tamil,indonesian,chinese
12,Qwen/Qwen3-8B,slimllm,English,2-bit,0.231841,0.251515,0.257576,0.246483
13,Qwen/Qwen3-8B,slimllm,English,3-bit,0.430168,0.249697,0.495152,0.600000
14,Qwen/Qwen3-8B,slimllm,English,4-bit,0.481740,0.323636,0.558182,0.684404
18,Qwen/Qwen3-8B,slimllm,Tamil,2-bit,0.253922,0.249091,0.246061,0.266055
19,Qwen/Qwen3-8B,slimllm,Tamil,3-bit,0.474524,0.332121,0.528485,0.566361
20,Qwen/Qwen3-8B,slimllm,Tamil,4-bit,0.499889,0.354545,0.547273,0.662385
15,Qwen/Qwen3-8B,slimllm,Indonesian,2-bit,0.242515,0.252727,0.249697,0.251988
16,Qwen/Qwen3-8B,slimllm,Indonesian,3-bit,0.487790,0.261212,0.538788,0.600612
17,Qwen/Qwen3-8B,slimllm,Indonesian,4-bit,0.518038,0.332727,0.581818,0.677064
9,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.251492,0.256970,0.260606,0.256269
10,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.468723,0.304848,0.541818,0.624465
11,Qwen/Qwen3-8B,slimllm,Chinese,4-bit,0.522510,0.343636,0.556364,0.673394
3,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.259119,0.249697,0.248485,0.249541
4,CohereLabs/aya-expanse-8b,slimllm,English,3-bit,0.435591,0.267273,0.458182,0.381651
5,CohereLabs/aya-expanse-8b,slimllm,English,4-bit,0.507279,0.270909,0.541818,0.510092
6,CohereLabs/aya-expanse-8b,slimllm,Indonesian,2-bit,0.235010,0.263636,0.247273,0.259327
7,CohereLabs/aya-expanse-8b,slimllm,Indonesian,3-bit,0.474350,0.278182,0.490909,0.438532
8,CohereLabs/aya-expanse-8b,slimllm,Indonesian,4-bit,0.521570,0.289091,0.563636,0.511927
0,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.247777,0.268485,0.255152,0.237309
1,CohereLabs/aya-expanse-8b,slimllm,Chinese,3-bit,0.489000,0.290909,0.516364,0.460550
2,CohereLabs/aya-expanse-8b,slimllm,Chinese,4-bit,0.535181,0.285455,0.538182,0.510092
24,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,2-bit,0.238692,0.252121,0.267879,0.239755
25,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,3-bit,0.215997,0.252727,0.250909,0.273394
26,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,4-bit,0.428462,0.321818,0.414545,0.346789
30,meta-llama/Llama-3.1-8B-Instruct,slimllm,Tamil,2-bit,0.253922,0.254545,0.264848,0.246483
31,meta-llama/Llama-3.1-8B-Instruct,slimllm,Tamil,3-bit,0.287097,0.243636,0.243636,0.266055
32,meta-llama/Llama-3.1-8B-Instruct,slimllm,Tamil,4-bit,0.401370,0.350909,0.523636,0.469725
27,meta-llama/Llama-3.1-8B-Instruct,slimllm,Indonesian,2-bit,0.243682,0.258788,0.266061,0.237309
28,meta-llama/Llama-3.1-8B-Instruct,slimllm,Indonesian,3-bit,0.406586,0.252727,0.470909,0.403670
29,meta-llama/Llama-3.1-8B-Instruct,slimllm,Indonesian,4-bit,0.472796,0.325455,0.509091,0.480734
21,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,2-bit,0.254723,0.260000,0.249091,0.254434
22,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,3-bit,0.348705,0.267273,0.316364,0.348624
23,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,4-bit,0.444796,0.356364,0.510909,0.475229

,Base Model,Quantization Technique,Calibration Language,Bit Width,english,tamil,indonesian,chinese
12,Qwen/Qwen3-8B,slimllm,English,2-bit,0.012001,0.004535,0.004535,0.002288
13,Qwen/Qwen3-8B,slimllm,English,3-bit,0.027889,0.015018,0.026404,0.015641
18,Qwen/Qwen3-8B,slimllm,Tamil,2-bit,0.012821,0.015499,0.027467,0.012800
19,Qwen/Qwen3-8B,slimllm,Tamil,3-bit,0.026416,0.003090,0.004772,0.007080
15,Qwen/Qwen3-8B,slimllm,Indonesian,2-bit,0.003569,0.004454,0.021885,0.003770
16,Qwen/Qwen3-8B,slimllm,Indonesian,3-bit,0.014366,0.015594,0.062357,0.041957
9,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.011591,0.012091,0.010739,0.008251
10,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.019652,0.031293,0.003928,0.013428
3,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.039802,0.007323,0.008441,0.006530
6,CohereLabs/aya-expanse-8b,slimllm,Indonesian,2-bit,0.015381,0.011783,0.015066,0.007541
0,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.010121,0.031222,0.011142,0.009030

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,english,tamil,indonesian,chinese
15,Qwen/Qwen3-8B,tacq,English,2-bit,0.265634,0.240000,0.263030,0.334557
16,Qwen/Qwen3-8B,tacq,English,3-bit,0.473628,0.290909,0.527273,0.630581
17,Qwen/Qwen3-8B,tacq,English,4-bit,0.577570,0.396364,0.610909,0.704587
21,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.261313,0.286061,0.268485,0.270948
22,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.511901,0.349697,0.576970,0.647706
23,Qwen/Qwen3-8B,tacq,Tamil,4-bit,0.560426,0.365455,0.634545,0.697248
18,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.281328,0.237576,0.318788,0.322936
19,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.528753,0.304242,0.555152,0.612844
20,Qwen/Qwen3-8B,tacq,Indonesian,4-bit,0.572223,0.372727,0.620000,0.715596
12,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.248589,0.243636,0.281212,0.402446
13,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.511675,0.299394,0.585455,0.653823
14,Qwen/Qwen3-8B,tacq,Chinese,4-bit,0.587486,0.376364,0.609091,0.706422
3,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.346708,0.249091,0.312121,0.307645
4,CohereLabs/aya-expanse-8b,tacq,English,3-bit,0.490782,0.254545,0.512727,0.477064
5,CohereLabs/aya-expanse-8b,tacq,English,4-bit,0.526982,0.290909,0.549091,0.513761
9,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,0.336500,0.272121,0.308485,0.284404
10,CohereLabs/aya-expanse-8b,tacq,Tamil,3-bit,0.481805,0.263636,0.540000,0.499083
11,CohereLabs/aya-expanse-8b,tacq,Tamil,4-bit,0.525297,0.274545,0.556364,0.510092
6,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.327534,0.223030,0.347879,0.312538
7,CohereLabs/aya-expanse-8b,tacq,Indonesian,3-bit,0.501704,0.278182,0.541818,0.478899
8,CohereLabs/aya-expanse-8b,tacq,Indonesian,4-bit,0.504557,0.278182,0.552727,0.519266
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.319863,0.263636,0.342424,0.321713
1,CohereLabs/aya-expanse-8b,tacq,Chinese,3-bit,0.497101,0.290909,0.536364,0.493578
2,CohereLabs/aya-expanse-8b,tacq,Chinese,4-bit,0.543218,0.274545,0.558182,0.533945
27,meta-llama/Llama-3.1-8B-Instruct,tacq,English,2-bit,0.246241,0.247273,0.260000,0.245872
28,meta-llama/Llama-3.1-8B-Instruct,tacq,English,3-bit,0.403733,0.294545,0.396364,0.328440
29,meta-llama/Llama-3.1-8B-Instruct,tacq,English,4-bit,0.533171,0.347273,0.543636,0.456881
33,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,2-bit,0.252108,0.242424,0.248485,0.266055
34,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,3-bit,0.395050,0.320000,0.458182,0.414679
35,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,4-bit,0.507149,0.376364,0.545455,0.493578
30,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,2-bit,0.242472,0.243636,0.258788,0.255657
31,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,3-bit,0.445704,0.303636,0.496364,0.431193
32,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,4-bit,0.569272,0.374545,0.583636,0.526606
24,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,2-bit,0.262997,0.263636,0.253333,0.261774
25,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,3-bit,0.440031,0.290909,0.483636,0.436697
26,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,4-bit,0.520564,0.350909,0.556364,0.513761

,Base Model,Quantization Technique,Calibration Language,Bit Width,english,tamil,indonesian,chinese
15,Qwen/Qwen3-8B,tacq,English,2-bit,0.026792,0.023891,0.018915,0.020992
16,Qwen/Qwen3-8B,tacq,English,3-bit,0.012018,0.028440,0.046922,0.014780
21,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.015562,0.021530,0.021632,0.014396
22,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.014151,0.007472,0.021064,0.018410
18,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.013023,0.016420,0.038292,0.041626
19,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.014354,0.017397,0.016352,0.024754
12,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.023864,0.027813,0.019318,0.030605
13,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.016391,0.013388,0.015641,0.017748
3,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.021757,0.014162,0.025120,0.005261
9,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,0.016958,0.007618,0.028023,0.021762
6,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.032097,0.039622,0.011531,0.020340
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.006756,0.012151,0.021324,0.018970

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'ZH']
mean_ppl

english       0.979771
tamil         1.010303
indonesian    1.013939
chinese       1.020795
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'ZH']
mean_ppl

english       1.861205
tamil         1.147879
indonesian    2.104242
chinese       2.391437
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'ZH']
mean_ppl

english       2.022177
tamil         1.354545
indonesian    2.243636
chinese       2.697248
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [4, 'ZH']]
where TA located
['EN' 'ID' 'ZH']
mean_ppl

english       0.741906
tamil         0.781818
indonesian    0.750909
chinese       0.746177
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [4, 'ZH']]
where TA located
['EN' 'ID' 'ZH']
mean_ppl

english       1.398941
tamil         0.836364
indonesian    1.465455
chinese       1.280734
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [4, 'ZH']]
where TA located
['EN' 'ID' 'ZH']
mean_ppl

english       1.564030
tamil         0.845455
indonesian    1.643636
chinese       1.532110
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'ZH']
mean_ppl

english       0.991019
tamil         1.025455
indonesian    1.047879
chinese       0.977982
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'ZH']
mean_ppl

english       1.258386
tamil         1.016364
indonesian    1.281818
chinese       1.291743
dtype: float64

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [4, 'ZH']]
where TA located
['EN' 'TA' 'ID' 'ZH']
mean_ppl

english       1.747425
tamil         1.354545
indonesian    1.958182
chinese       1.772477
dtype: float64

In [ ]:
eval_languages = ["Dutch", "German", "Chinese", "Indonesian", "Tamil"]
# eval_languages = ["Dutch", "German", "Chinese", "Indonesian", "Malay", "Tagalog", "Tamil", "Telugu", "Malayalam"]
eval_languages = [lang.lower() for lang in eval_languages]

# Initialize the W&B API
api = Api()

quantization_technique = "ALL"
# bit = 8
num_samples = 128
eval_dataset = "include"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.num_calibration_samples": num_samples},
                            {"config.evaluation_dataset": f"{eval_dataset.lower()}"},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"$not": {"config.calibration_language": "WuuChinese"}},
                            {"$not": {"$and": [{"created_at": {"$lt": "2026-03-01"}}, {"config.quantization_technique": "gptq"}]}},
                            {"created_at": {"$gt": "2026-07-01"}},
                            {"$not": {"config.calibration_language": "Swahili"}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.evaluation_dataset": eval_dataset.lower()},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            {"config.output_type": "multiple_choice"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              {"config.evaluation_dataset": eval_dataset.lower()},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                              {"created_at": {"$gt": "2026-07-01"}},
                          ]}
                      ]}
                  )

  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-14B"], quantization_technique=quantization_technique, bits=["2-bit", "3-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False, vertical_spacing=0.038, horizontal_spacing=0.040, random_guess_score=0.25, write_pdf="include_14b_barplot_reduced_errorbar_final.pdf")

Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,dutch,german,tamil,indonesian,chinese
1,Qwen/Qwen3-14B,gptq,2-bit,English,0.192377,0.294964,0.229091,0.258182,0.253211
4,Qwen/Qwen3-14B,gptq,3-bit,English,0.678766,0.503597,0.356364,0.654545,0.722936
2,Qwen/Qwen3-14B,gptq,2-bit,Tamil,0.183303,0.287770,0.241818,0.207273,0.240367
5,Qwen/Qwen3-14B,gptq,3-bit,Tamil,0.666062,0.525180,0.407273,0.627273,0.735780
3,Qwen/Qwen3-14B,gptq,2-bit,Indonesian,0.239564,0.258993,0.232727,0.267273,0.264220
6,Qwen/Qwen3-14B,gptq,3-bit,Indonesian,0.678766,0.496403,0.398182,0.656364,0.721101
7,Qwen/Qwen3-14B,gptq,2-bit,Chinese,0.159710,0.258993,0.238182,0.252727,0.249541
0,Qwen/Qwen3-14B,gptq,3-bit,Chinese,0.660617,0.510791,0.358182,0.640000,0.717431

Empty DataFrame
Columns: [Base Model, Quantization Technique, Bit Width, Calibration Language, dutch, german, tamil, indonesian, chinese]
Index: []

,Base Model,Quantization Technique,Bit Width,Calibration Language,dutch,german,tamil,indonesian,chinese
2,Qwen/Qwen3-14B,tacq,2-bit,English,0.375681,0.323741,0.256364,0.285455,0.368807
5,Qwen/Qwen3-14B,tacq,3-bit,English,0.709619,0.546763,0.340000,0.672727,0.724771
4,Qwen/Qwen3-14B,tacq,2-bit,Tamil,0.346642,0.330935,0.321818,0.323636,0.381651
6,Qwen/Qwen3-14B,tacq,3-bit,Tamil,0.682396,0.517986,0.410909,0.674545,0.746789
3,Qwen/Qwen3-14B,tacq,2-bit,Indonesian,0.399274,0.395683,0.292727,0.490909,0.418349
7,Qwen/Qwen3-14B,tacq,3-bit,Indonesian,0.713249,0.539568,0.341818,0.690909,0.732110
0,Qwen/Qwen3-14B,tacq,2-bit,Chinese,0.328494,0.266187,0.245455,0.290909,0.467890
1,Qwen/Qwen3-14B,tacq,3-bit,Chinese,0.689655,0.539568,0.365455,0.656364,0.737615

['NL', 'DE', 'TA', 'ID', 'ZH']
Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,english,tamil,indonesian,chinese
2,Qwen/Qwen3-14B,gptq,English,2-bit,0.243671,0.229091,0.258182,0.253211
3,Qwen/Qwen3-14B,gptq,English,3-bit,0.591182,0.356364,0.654545,0.722936
6,Qwen/Qwen3-14B,gptq,Tamil,2-bit,0.235536,0.241818,0.207273,0.240367
7,Qwen/Qwen3-14B,gptq,Tamil,3-bit,0.595621,0.407273,0.627273,0.735780
4,Qwen/Qwen3-14B,gptq,Indonesian,2-bit,0.249279,0.232727,0.267273,0.264220
5,Qwen/Qwen3-14B,gptq,Indonesian,3-bit,0.587584,0.398182,0.656364,0.721101
0,Qwen/Qwen3-14B,gptq,Chinese,2-bit,0.209351,0.238182,0.252727,0.249541
1,Qwen/Qwen3-14B,gptq,Chinese,3-bit,0.585704,0.358182,0.640000,0.717431

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, english, tamil, indonesian, chinese]
Index: []

SLIM

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, english, tamil, indonesian, chinese]
Index: []

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, english, tamil, indonesian, chinese]
Index: []

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,english,tamil,indonesian,chinese
2,Qwen/Qwen3-14B,tacq,English,2-bit,0.349711,0.256364,0.285455,0.368807
3,Qwen/Qwen3-14B,tacq,English,3-bit,0.628191,0.340000,0.672727,0.724771
6,Qwen/Qwen3-14B,tacq,Tamil,2-bit,0.338789,0.321818,0.323636,0.381651
7,Qwen/Qwen3-14B,tacq,Tamil,3-bit,0.600191,0.410909,0.674545,0.746789
4,Qwen/Qwen3-14B,tacq,Indonesian,2-bit,0.397479,0.292727,0.490909,0.418349
5,Qwen/Qwen3-14B,tacq,Indonesian,3-bit,0.626408,0.341818,0.690909,0.732110
0,Qwen/Qwen3-14B,tacq,Chinese,2-bit,0.297340,0.245455,0.290909,0.467890
1,Qwen/Qwen3-14B,tacq,Chinese,3-bit,0.614612,0.365455,0.656364,0.737615

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, english, tamil, indonesian, chinese]
Index: []

[[0, 'EN'], [1, 'TA'], [2, 'ID'], [4, 'ZH']]
where TA located
[]
[[0, 'EN'], [1, 'TA'], [2, 'ID'], [4, 'ZH']]
where TA located
[]

### GlobalMMLULite Bar

In [ ]:
eval_languages = ["en", "zh", "id", "sw"]

# Initialize the W&B API
api = Api()

quantization_technique = "ALL"
# bit = 8
num_samples = 128
eval_dataset = "globalmmlulite"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

for bit in [4]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.num_calibration_samples": num_samples},
                            {"$or": [
                                {"$and": [
                                  {"config.evaluation_dataset": f"{eval_dataset.lower()}"},
                                  {"created_at": {"$lt": "2026-07-01"}},
                                ]},
                                {"$and": [
                                  {"$or": [
                                    {"config.evaluation_dataset": f"{eval_dataset.lower()}-1000"},
                                    {"config.evaluation_dataset": f"{eval_dataset.lower()}-2000"},
                                  ]},
                                  {"created_at": {"$gt": "2026-07-01"}},
                                ]},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"$not": {"$and": [{"created_at": {"$lt": "2026-03-01"}}, {"config.quantization_technique": "gptq"}]}},
                            {"$not": {"config.calibration_language": "WuuChinese"}},
                            {"$not": {"config.calibration_language": "Tamil"}},
                            {"$not": {"config.bit_width": "8-bit"}},
                            {"$not": {"config.base_model": "Qwen/Qwen3-1.7B"}},
                            {"$not": {"config.base_model": "Qwen/Qwen3-4B"}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.evaluation_dataset": eval_dataset.lower()},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              {"config.evaluation_dataset": eval_dataset.lower()},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"$not": {"config.base_model": "Qwen/Qwen3-1.7B"}},
                              {"$not": {"config.base_model": "Qwen/Qwen3-4B"}},
                            {"created_at": {"$lt": "2026-07-01"}},
                          ]}
                      ]}
                  )

  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique=quantization_technique, bits=["2-bit", "3-bit", "4-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False, vertical_spacing=0.08, horizontal_spacing=0.035, write_pdf="globalmmlulite_barplot_sinq_final.pdf")

Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,id,sw,zh
4,Qwen/Qwen3-8B,gptq,2-bit,English,0.2550,0.2425,0.2650,0.2450
36,Qwen/Qwen3-8B,gptq,2-bit,English,0.2675,0.2700,0.2325,0.2350
37,Qwen/Qwen3-8B,gptq,2-bit,English,0.2350,0.2725,0.2400,0.2350
11,Qwen/Qwen3-8B,gptq,3-bit,English,0.5050,0.3600,0.2725,0.4225
44,Qwen/Qwen3-8B,gptq,3-bit,English,0.5850,0.4875,0.2950,0.5225
...,...,...,...,...,...,...,...,...
20,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Chinese,0.2400,0.2325,0.2325,0.2800
58,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Chinese,0.2625,0.2400,0.2325,0.2175
59,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Chinese,0.2350,0.2275,0.2475,0.2400
16,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Chinese,0.5025,0.3175,0.2725,0.4250
28,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Chinese,0.6600,0.5700,0.4200,0.5775

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,id,sw,zh
4,Qwen/Qwen3-8B,slimllm,2-bit,English,0.2350,0.2400,0.2300,0.2400
36,Qwen/Qwen3-8B,slimllm,2-bit,English,0.2450,0.2775,0.2975,0.2450
37,Qwen/Qwen3-8B,slimllm,2-bit,English,0.2450,0.2650,0.2350,0.2300
30,Qwen/Qwen3-8B,slimllm,3-bit,English,0.5400,0.3425,0.2675,0.4950
44,Qwen/Qwen3-8B,slimllm,3-bit,English,0.6600,0.5525,0.3200,0.5525
...,...,...,...,...,...,...,...,...
13,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,0.2800,0.2600,0.2525,0.2575
58,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,0.2625,0.2325,0.2575,0.2775
59,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,0.2625,0.2525,0.2875,0.2725
17,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Chinese,0.3975,0.3550,0.2975,0.3775
11,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Chinese,0.6350,0.5175,0.3450,0.5050

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,id,sw,zh
3,Qwen/Qwen3-8B,tacq,2-bit,English,0.3350,0.2550,0.2575,0.3625
36,Qwen/Qwen3-8B,tacq,2-bit,English,0.3375,0.2600,0.2575,0.2975
37,Qwen/Qwen3-8B,tacq,2-bit,English,0.3275,0.2675,0.2775,0.3150
32,Qwen/Qwen3-8B,tacq,3-bit,English,0.6175,0.4975,0.2700,0.6075
44,Qwen/Qwen3-8B,tacq,3-bit,English,0.7000,0.5850,0.3600,0.6275
...,...,...,...,...,...,...,...,...
15,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,0.2425,0.2500,0.2275,0.2475
58,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,0.2875,0.2800,0.2850,0.3100
59,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,0.2575,0.3125,0.2800,0.2925
19,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Chinese,0.5450,0.4400,0.3200,0.4125
11,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Chinese,0.6650,0.5575,0.3650,0.5850

Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
15,Qwen/Qwen3-8B,gptq,English,2-bit,0.252500,0.261667,0.245833,0.238333
16,Qwen/Qwen3-8B,gptq,English,3-bit,0.578333,0.428333,0.278333,0.478333
17,Qwen/Qwen3-8B,gptq,English,4-bit,0.677500,0.632500,0.340000,0.640000
18,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,0.251667,0.250833,0.250833,0.241667
19,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,0.539167,0.489167,0.290833,0.493333
20,Qwen/Qwen3-8B,gptq,Indonesian,4-bit,0.700000,0.665000,0.370000,0.652500
21,Qwen/Qwen3-8B,gptq,Swahili,2-bit,0.246667,0.269167,0.250833,0.224167
22,Qwen/Qwen3-8B,gptq,Swahili,3-bit,0.560833,0.550833,0.315833,0.524167
23,Qwen/Qwen3-8B,gptq,Swahili,4-bit,0.670000,0.647500,0.350000,0.625000
12,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.258333,0.250833,0.235833,0.240000
13,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.580833,0.509167,0.270833,0.582500
14,Qwen/Qwen3-8B,gptq,Chinese,4-bit,0.710000,0.647500,0.342500,0.652500
3,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.242500,0.242500,0.247500,0.240000
4,CohereLabs/aya-expanse-8b,gptq,English,3-bit,0.620000,0.507500,0.277500,0.532500
5,CohereLabs/aya-expanse-8b,gptq,English,4-bit,0.627500,0.547500,0.307500,0.597500
6,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,0.235833,0.250833,0.262500,0.245000
7,CohereLabs/aya-expanse-8b,gptq,Indonesian,3-bit,0.617500,0.545000,0.300000,0.557500
8,CohereLabs/aya-expanse-8b,gptq,Indonesian,4-bit,0.635000,0.562500,0.315000,0.595000
9,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,0.243333,0.241667,0.260000,0.249167
10,CohereLabs/aya-expanse-8b,gptq,Swahili,3-bit,0.595000,0.517500,0.287500,0.500000
11,CohereLabs/aya-expanse-8b,gptq,Swahili,4-bit,0.615000,0.575000,0.295000,0.592500
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.250000,0.250833,0.220833,0.223333
1,CohereLabs/aya-expanse-8b,gptq,Chinese,3-bit,0.622500,0.530000,0.282500,0.565000
2,CohereLabs/aya-expanse-8b,gptq,Chinese,4-bit,0.625000,0.575000,0.317500,0.605000
27,meta-llama/Llama-3.1-8B-Instruct,gptq,English,2-bit,0.230833,0.249167,0.243333,0.254167
28,meta-llama/Llama-3.1-8B-Instruct,gptq,English,3-bit,0.467500,0.325000,0.270000,0.337500
29,meta-llama/Llama-3.1-8B-Instruct,gptq,English,4-bit,0.655000,0.560000,0.402500,0.555000
30,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,2-bit,0.234167,0.250000,0.252500,0.247500
31,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,3-bit,0.557500,0.427500,0.345000,0.400000
32,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,4-bit,0.650000,0.570000,0.395000,0.567500
33,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,2-bit,0.250833,0.242500,0.240833,0.245000
34,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,3-bit,0.442500,0.362500,0.327500,0.405000
35,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,4-bit,0.642500,0.560000,0.422500,0.585000
24,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,2-bit,0.245833,0.233333,0.237500,0.245833
25,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,3-bit,0.502500,0.317500,0.272500,0.425000
26,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,4-bit,0.660000,0.570000,0.420000,0.577500

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
15,Qwen/Qwen3-8B,gptq,English,2-bit,0.013385,0.013591,0.013894,0.004714
16,Qwen/Qwen3-8B,gptq,English,3-bit,0.057349,0.052454,0.011961,0.041650
18,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,0.018966,0.016997,0.015321,0.009204
19,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,0.051330,0.020548,0.006236,0.018522
21,Qwen/Qwen3-8B,gptq,Swahili,2-bit,0.008250,0.022943,0.017361,0.004249
22,Qwen/Qwen3-8B,gptq,Swahili,3-bit,0.060633,0.029744,0.008498,0.047185
12,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.006236,0.021826,0.006562,0.014720
13,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.047886,0.024608,0.021246,0.013385
3,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.022079,0.007360,0.007071,0.025577
6,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,0.011607,0.009428,0.002041,0.020104
9,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,0.013281,0.034781,0.008898,0.002357
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.015411,0.013281,0.015590,0.005137

SLIM

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
15,Qwen/Qwen3-8B,slimllm,English,2-bit,0.241667,0.260833,0.254167,0.238333
16,Qwen/Qwen3-8B,slimllm,English,3-bit,0.602500,0.458333,0.286667,0.520833
17,Qwen/Qwen3-8B,slimllm,English,4-bit,0.670000,0.587500,0.332500,0.637500
18,Qwen/Qwen3-8B,slimllm,Indonesian,2-bit,0.250000,0.255000,0.254167,0.255000
19,Qwen/Qwen3-8B,slimllm,Indonesian,3-bit,0.642500,0.542500,0.295833,0.552500
20,Qwen/Qwen3-8B,slimllm,Indonesian,4-bit,0.667500,0.577500,0.330000,0.597500
21,Qwen/Qwen3-8B,slimllm,Swahili,2-bit,0.236667,0.251667,0.238333,0.226667
22,Qwen/Qwen3-8B,slimllm,Swahili,3-bit,0.580000,0.475833,0.320000,0.546667
23,Qwen/Qwen3-8B,slimllm,Swahili,4-bit,0.667500,0.602500,0.310000,0.652500
12,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.242500,0.258333,0.250000,0.235000
13,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.635833,0.517500,0.290000,0.585000
14,Qwen/Qwen3-8B,slimllm,Chinese,4-bit,0.687500,0.535000,0.312500,0.630000
3,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.250833,0.271667,0.276667,0.225000
4,CohereLabs/aya-expanse-8b,slimllm,English,3-bit,0.535000,0.462500,0.282500,0.440000
5,CohereLabs/aya-expanse-8b,slimllm,English,4-bit,0.605000,0.540000,0.305000,0.605000
6,CohereLabs/aya-expanse-8b,slimllm,Indonesian,2-bit,0.244167,0.256667,0.248333,0.245833
7,CohereLabs/aya-expanse-8b,slimllm,Indonesian,3-bit,0.547500,0.480000,0.280000,0.545000
8,CohereLabs/aya-expanse-8b,slimllm,Indonesian,4-bit,0.615000,0.535000,0.275000,0.580000
9,CohereLabs/aya-expanse-8b,slimllm,Swahili,2-bit,0.260833,0.246667,0.260833,0.263333
10,CohereLabs/aya-expanse-8b,slimllm,Swahili,3-bit,0.570000,0.492500,0.302500,0.507500
11,CohereLabs/aya-expanse-8b,slimllm,Swahili,4-bit,0.620000,0.557500,0.327500,0.580000
0,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.260000,0.261667,0.265000,0.265000
1,CohereLabs/aya-expanse-8b,slimllm,Chinese,3-bit,0.577500,0.500000,0.340000,0.535000
2,CohereLabs/aya-expanse-8b,slimllm,Chinese,4-bit,0.630000,0.557500,0.325000,0.570000
27,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,2-bit,0.238333,0.262500,0.256667,0.229167
28,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,3-bit,0.290000,0.277500,0.245000,0.265000
29,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,4-bit,0.560000,0.470000,0.372500,0.445000
30,meta-llama/Llama-3.1-8B-Instruct,slimllm,Indonesian,2-bit,0.250000,0.245833,0.220000,0.233333
31,meta-llama/Llama-3.1-8B-Instruct,slimllm,Indonesian,3-bit,0.492500,0.427500,0.272500,0.405000
32,meta-llama/Llama-3.1-8B-Instruct,slimllm,Indonesian,4-bit,0.582500,0.515000,0.380000,0.502500
33,meta-llama/Llama-3.1-8B-Instruct,slimllm,Swahili,2-bit,0.257500,0.270000,0.262500,0.253333
34,meta-llama/Llama-3.1-8B-Instruct,slimllm,Swahili,3-bit,0.310000,0.242500,0.240000,0.262500
35,meta-llama/Llama-3.1-8B-Instruct,slimllm,Swahili,4-bit,0.660000,0.580000,0.422500,0.542500
24,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,2-bit,0.268333,0.248333,0.265833,0.269167
25,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,3-bit,0.397500,0.355000,0.297500,0.377500
26,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,4-bit,0.635000,0.517500,0.345000,0.505000

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
15,Qwen/Qwen3-8B,slimllm,English,2-bit,0.004714,0.015590,0.030709,0.006236
16,Qwen/Qwen3-8B,slimllm,English,3-bit,0.049117,0.087090,0.023658,0.023834
18,Qwen/Qwen3-8B,slimllm,Indonesian,2-bit,0.010801,0.006124,0.006562,0.037472
19,Qwen/Qwen3-8B,slimllm,Indonesian,3-bit,0.031425,0.027613,0.015456,0.032081
21,Qwen/Qwen3-8B,slimllm,Swahili,2-bit,0.006236,0.020138,0.003118,0.018409
22,Qwen/Qwen3-8B,slimllm,Swahili,3-bit,0.037249,0.040893,0.020104,0.014482
12,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.008165,0.017834,0.016708,0.007360
13,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.013591,0.003536,0.020716,0.025577
3,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.021826,0.017834,0.009204,0.014720
6,CohereLabs/aya-expanse-8b,slimllm,Indonesian,2-bit,0.019293,0.012472,0.012472,0.008250
9,CohereLabs/aya-expanse-8b,slimllm,Swahili,2-bit,0.008250,0.037878,0.017119,0.023482
0,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.022730,0.016997,0.010206,0.033727

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
15,Qwen/Qwen3-8B,tacq,English,2-bit,0.333333,0.260833,0.264167,0.325000
16,Qwen/Qwen3-8B,tacq,English,3-bit,0.670000,0.557500,0.318333,0.618333
17,Qwen/Qwen3-8B,tacq,English,4-bit,0.697500,0.652500,0.347500,0.675000
18,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.307500,0.315833,0.260833,0.309167
19,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.670833,0.597500,0.301667,0.615000
20,Qwen/Qwen3-8B,tacq,Indonesian,4-bit,0.707500,0.617500,0.317500,0.662500
21,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.284167,0.275000,0.268333,0.284167
22,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.673333,0.584167,0.320000,0.600833
23,Qwen/Qwen3-8B,tacq,Swahili,4-bit,0.715000,0.625000,0.315000,0.697500
12,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.372500,0.280000,0.275000,0.353333
13,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.673333,0.610833,0.302500,0.625833
14,Qwen/Qwen3-8B,tacq,Chinese,4-bit,0.702500,0.617500,0.347500,0.692500
3,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.450833,0.393333,0.285833,0.381667
4,CohereLabs/aya-expanse-8b,tacq,English,3-bit,0.620000,0.517500,0.312500,0.552500
5,CohereLabs/aya-expanse-8b,tacq,English,4-bit,0.610000,0.552500,0.335000,0.570000
6,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.428333,0.391667,0.267500,0.384167
7,CohereLabs/aya-expanse-8b,tacq,Indonesian,3-bit,0.585000,0.532500,0.317500,0.560000
8,CohereLabs/aya-expanse-8b,tacq,Indonesian,4-bit,0.607500,0.555000,0.322500,0.600000
9,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,0.413333,0.375833,0.293333,0.368333
10,CohereLabs/aya-expanse-8b,tacq,Swahili,3-bit,0.605000,0.507500,0.342500,0.547500
11,CohereLabs/aya-expanse-8b,tacq,Swahili,4-bit,0.622500,0.537500,0.330000,0.590000
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.420833,0.387500,0.280833,0.420000
1,CohereLabs/aya-expanse-8b,tacq,Chinese,3-bit,0.615000,0.512500,0.290000,0.550000
2,CohereLabs/aya-expanse-8b,tacq,Chinese,4-bit,0.640000,0.562500,0.330000,0.587500
27,meta-llama/Llama-3.1-8B-Instruct,tacq,English,2-bit,0.257500,0.240833,0.252500,0.244167
28,meta-llama/Llama-3.1-8B-Instruct,tacq,English,3-bit,0.627500,0.422500,0.330000,0.385000
29,meta-llama/Llama-3.1-8B-Instruct,tacq,English,4-bit,0.670000,0.565000,0.410000,0.560000
30,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,2-bit,0.250833,0.249167,0.254167,0.249167
31,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,3-bit,0.600000,0.505000,0.345000,0.500000
32,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,4-bit,0.680000,0.565000,0.405000,0.570000
33,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,2-bit,0.250000,0.251667,0.250833,0.251667
34,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,3-bit,0.580000,0.482500,0.372500,0.457500
35,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,4-bit,0.665000,0.570000,0.425000,0.555000
24,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,2-bit,0.262500,0.280833,0.264167,0.283333
25,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,3-bit,0.545000,0.440000,0.320000,0.412500
26,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,4-bit,0.665000,0.557500,0.365000,0.585000

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
15,Qwen/Qwen3-8B,tacq,English,2-bit,0.004249,0.005137,0.009428,0.027462
16,Qwen/Qwen3-8B,tacq,English,3-bit,0.037249,0.042475,0.037044,0.008250
18,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.030208,0.014337,0.015590,0.047886
19,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.013894,0.010801,0.007169,0.003536
21,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.027563,0.023004,0.018856,0.022577
22,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.006562,0.005137,0.022079,0.035139
12,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.028940,0.014289,0.015943,0.022392
13,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.030641,0.003118,0.029439,0.027411
3,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.018966,0.039493,0.018522,0.012304
6,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.018295,0.021826,0.019472,0.035198
9,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,0.028674,0.010475,0.018295,0.024353
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.044550,0.025083,0.019401,0.035765

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    0.970833
id    1.025833
sw    0.996667
zh    0.955000
dtype: float64

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    2.460833
id    1.994167
sw    1.192500
zh    2.205000
dtype: float64

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    2.6925
id    2.3025
sw    1.2850
zh    2.5175
dtype: float64

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    1.015833
id    1.036667
sw    1.050833
zh    0.999167
dtype: float64

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    2.2300
id    1.9350
sw    1.2050
zh    2.0275
dtype: float64

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    2.4700
id    2.1900
sw    1.2325
zh    2.3350
dtype: float64

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    1.014167
id    1.026667
sw    1.005000
zh    0.985000
dtype: float64

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    1.4900
id    1.3025
sw    1.0550
zh    1.3100
dtype: float64

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'ID' 'SW' 'ZH']
mean_ppl

en    2.4375
id    2.0825
sw    1.5200
zh    1.9950
dtype: float64

In [ ]:
eval_languages = ["en", "zh", "id", "sw"]

# Initialize the W&B API
api = Api()

quantization_technique = "ALL"
# bit = 8
num_samples = 128
eval_dataset = "globalmmlulite"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.num_calibration_samples": num_samples},
                            {"config.evaluation_dataset": f"{eval_dataset.lower()}"},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "multiple_choice"},
                            {"$not": {"config.calibration_language": "WuuChinese"}},
                            {"$not": {"$and": [{"created_at": {"$lt": "2026-03-01"}}, {"config.quantization_technique": "gptq"}]}},
                            {"created_at": {"$gt": "2026-07-01"}},
                            {"$not": {"config.calibration_language": "Tamil"}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.evaluation_dataset": eval_dataset.lower()},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            {"config.output_type": "multiple_choice"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              {"config.evaluation_dataset": eval_dataset.lower()},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                              {"created_at": {"$gt": "2026-07-01"}},
                          ]}
                      ]}
                  )

  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-14B"], quantization_technique=quantization_technique, bits=["2-bit", "3-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False, vertical_spacing=0.038, horizontal_spacing=0.040, random_guess_score=0.25, write_pdf="globalmmlulite_14b_barplot_reduced_errorbar_final.pdf")

Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,id,sw,zh
2,Qwen/Qwen3-14B,gptq,2-bit,English,0.2125,0.2525,0.2275,0.2500
4,Qwen/Qwen3-14B,gptq,3-bit,English,0.7200,0.6375,0.3925,0.6575
3,Qwen/Qwen3-14B,gptq,2-bit,Indonesian,0.2450,0.2300,0.2750,0.1725
5,Qwen/Qwen3-14B,gptq,3-bit,Indonesian,0.7250,0.5950,0.3875,0.6500
6,Qwen/Qwen3-14B,gptq,2-bit,Swahili,0.2400,0.2675,0.2550,0.2425
0,Qwen/Qwen3-14B,gptq,3-bit,Swahili,0.7325,0.6475,0.3975,0.6825
7,Qwen/Qwen3-14B,gptq,2-bit,Chinese,0.2275,0.2425,0.2750,0.2175
1,Qwen/Qwen3-14B,gptq,3-bit,Chinese,0.7200,0.6100,0.3425,0.5950

Empty DataFrame
Columns: [Base Model, Quantization Technique, Bit Width, Calibration Language, en, id, sw, zh]
Index: []

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,id,sw,zh
4,Qwen/Qwen3-14B,tacq,2-bit,English,0.4575,0.2750,0.2350,0.3225
6,Qwen/Qwen3-14B,tacq,3-bit,English,0.7225,0.6000,0.3300,0.6675
5,Qwen/Qwen3-14B,tacq,2-bit,Indonesian,0.4475,0.3875,0.2675,0.4300
7,Qwen/Qwen3-14B,tacq,3-bit,Indonesian,0.7375,0.6500,0.3950,0.6650
0,Qwen/Qwen3-14B,tacq,2-bit,Swahili,0.3850,0.2925,0.2650,0.3275
2,Qwen/Qwen3-14B,tacq,3-bit,Swahili,0.7350,0.6625,0.3925,0.6625
1,Qwen/Qwen3-14B,tacq,2-bit,Chinese,0.4200,0.2900,0.2500,0.3950
3,Qwen/Qwen3-14B,tacq,3-bit,Chinese,0.7125,0.6125,0.3625,0.6675

Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
2,Qwen/Qwen3-14B,gptq,English,2-bit,0.2125,0.2525,0.2275,0.2500
3,Qwen/Qwen3-14B,gptq,English,3-bit,0.7200,0.6375,0.3925,0.6575
4,Qwen/Qwen3-14B,gptq,Indonesian,2-bit,0.2450,0.2300,0.2750,0.1725
5,Qwen/Qwen3-14B,gptq,Indonesian,3-bit,0.7250,0.5950,0.3875,0.6500
6,Qwen/Qwen3-14B,gptq,Swahili,2-bit,0.2400,0.2675,0.2550,0.2425
7,Qwen/Qwen3-14B,gptq,Swahili,3-bit,0.7325,0.6475,0.3975,0.6825
0,Qwen/Qwen3-14B,gptq,Chinese,2-bit,0.2275,0.2425,0.2750,0.2175
1,Qwen/Qwen3-14B,gptq,Chinese,3-bit,0.7200,0.6100,0.3425,0.5950

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en, id, sw, zh]
Index: []

SLIM

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en, id, sw, zh]
Index: []

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en, id, sw, zh]
Index: []

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,id,sw,zh
2,Qwen/Qwen3-14B,tacq,English,2-bit,0.4575,0.2750,0.2350,0.3225
3,Qwen/Qwen3-14B,tacq,English,3-bit,0.7225,0.6000,0.3300,0.6675
4,Qwen/Qwen3-14B,tacq,Indonesian,2-bit,0.4475,0.3875,0.2675,0.4300
5,Qwen/Qwen3-14B,tacq,Indonesian,3-bit,0.7375,0.6500,0.3950,0.6650
6,Qwen/Qwen3-14B,tacq,Swahili,2-bit,0.3850,0.2925,0.2650,0.3275
7,Qwen/Qwen3-14B,tacq,Swahili,3-bit,0.7350,0.6625,0.3925,0.6625
0,Qwen/Qwen3-14B,tacq,Chinese,2-bit,0.4200,0.2900,0.2500,0.3950
1,Qwen/Qwen3-14B,tacq,Chinese,3-bit,0.7125,0.6125,0.3625,0.6675

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en, id, sw, zh]
Index: []

[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
[]
[[0, 'EN'], [2, 'ID'], [3, 'SW'], [4, 'ZH']]
where TA located
[]

### MGSM Bar

In [ ]:
# eval_languages = ["eng_Latn", "tam_Taml", "ind_Latn", "swh_Latn", "zho_Hans"]
eval_languages = ["en", "ta", "sw", "zh"]

# Initialize the W&B API
api = Api()

quantization_technique = "ALL"
# bit = 8
num_samples = 128
eval_dataset = "mgsm"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"
strict_answer = True

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"$not": {"config.bit_width": f"2-bit"}},
                            {"config.num_calibration_samples": num_samples},
                            {"config.evaluation_dataset": f"{eval_dataset.lower()}"},
                            {"$not": {"config.base_model": "Qwen/Qwen3-14B"}},
                            {"config.enable_thinking": True},
                            # {"config.output_type": "generate_until"},
                            {"$not": {"config.calibration_language": "WuuChinese"}},
                            # {"$not": {"$and": [{"created_at": {"$lt": "2026-03-01"}}, {"config.quantization_technique": "gptq"}]}},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            {"$not": {"config.bit_width": f"2-bit"}},
                            {"config.evaluation_dataset": eval_dataset.lower()},
                            {"$not": {"config.base_model": "Qwen/Qwen3-14B"}},
                            {"config.enable_thinking": True},
                            # {"config.output_type": "generate_until"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              {"config.evaluation_dataset": eval_dataset.lower()},
                            {"$not": {"config.base_model": "Qwen/Qwen3-14B"}},
                              {"config.enable_thinking": True},
                              {"created_at": {"$gt": "2026-07-01"}},
                          ]}
                      ]}
                  )
  print(len(runs))

  # visualize_delta_unquantized_globalmmlulite(eval_languages=eval_languages, runs=runs, base_model=base_model, quantization_technique=quantization_technique, bit_width=bit, eval_dataset=eval_dataset, custom_title="")
  # visualize_delta_unquantized_deliver_bar(eval_languages=eval_languages, runs=runs, base_model=base_model, quantization_technique=quantization_technique, bits=["2-bit", "3-bit", "4-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False)
  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique=quantization_technique, bits=["3-bit", "4-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, generate_until=True, compile=False, vertical_spacing=0.07, horizontal_spacing=0.030, random_guess_score=0.0, strict_answer=strict_answer, write_pdf=f"mgsm_barplot_errorbar_{'strict' if strict_answer else 'flexible'}_final.pdf")

79
Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,ta,sw,zh
4,Qwen/Qwen3-8B,gptq,3-bit,English,0.444,0.124,0.004,0.408
0,Qwen/Qwen3-8B,gptq,4-bit,English,0.824,0.496,0.232,0.840
5,Qwen/Qwen3-8B,gptq,3-bit,Tamil,0.456,0.288,0.004,0.260
1,Qwen/Qwen3-8B,gptq,4-bit,Tamil,0.744,0.628,0.028,0.820
6,Qwen/Qwen3-8B,gptq,3-bit,Swahili,0.252,0.060,0.000,0.468
2,Qwen/Qwen3-8B,gptq,4-bit,Swahili,0.788,0.520,0.080,0.784
7,Qwen/Qwen3-8B,gptq,3-bit,Chinese,0.256,0.048,0.008,0.472
3,Qwen/Qwen3-8B,gptq,4-bit,Chinese,0.748,0.544,0.040,0.864
8,CohereLabs/aya-expanse-8b,gptq,3-bit,English,0.140,0.000,0.004,0.008
10,CohereLabs/aya-expanse-8b,gptq,4-bit,English,0.528,0.000,0.004,0.252
9,CohereLabs/aya-expanse-8b,gptq,3-bit,Tamil,0.348,0.008,0.000,0.016
11,CohereLabs/aya-expanse-8b,gptq,4-bit,Tamil,0.524,0.000,0.004,0.200
12,CohereLabs/aya-expanse-8b,gptq,3-bit,Swahili,0.248,0.012,0.012,0.004
14,CohereLabs/aya-expanse-8b,gptq,4-bit,Swahili,0.604,0.000,0.008,0.140
13,CohereLabs/aya-expanse-8b,gptq,3-bit,Chinese,0.528,0.000,0.004,0.160
15,CohereLabs/aya-expanse-8b,gptq,4-bit,Chinese,0.448,0.004,0.008,0.256
16,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,English,0.232,0.000,0.000,0.048
20,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,English,0.704,0.084,0.104,0.356
18,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Tamil,0.240,0.044,0.000,0.080
22,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Tamil,0.768,0.060,0.240,0.608
17,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Swahili,0.192,0.000,0.000,0.048
21,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Swahili,0.752,0.076,0.200,0.488
19,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Chinese,0.244,0.000,0.000,0.012
23,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Chinese,0.756,0.116,0.104,0.468

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,ta,sw,zh
4,Qwen/Qwen3-8B,slimllm,3-bit,English,0.376,0.012,0.008,0.496
0,Qwen/Qwen3-8B,slimllm,4-bit,English,0.760,0.648,0.012,0.808
5,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,0.344,0.360,0.020,0.540
1,Qwen/Qwen3-8B,slimllm,4-bit,Tamil,0.776,0.564,0.092,0.816
6,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,0.704,0.064,0.028,0.512
2,Qwen/Qwen3-8B,slimllm,4-bit,Swahili,0.800,0.652,0.056,0.796
7,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,0.712,0.036,0.004,0.700
3,Qwen/Qwen3-8B,slimllm,4-bit,Chinese,0.816,0.532,0.012,0.788
16,CohereLabs/aya-expanse-8b,slimllm,3-bit,English,0.124,0.000,0.000,0.008
19,CohereLabs/aya-expanse-8b,slimllm,4-bit,English,0.568,0.004,0.004,0.076
17,CohereLabs/aya-expanse-8b,slimllm,3-bit,Swahili,0.120,0.004,0.004,0.084
20,CohereLabs/aya-expanse-8b,slimllm,4-bit,Swahili,0.188,0.000,0.004,0.080
18,CohereLabs/aya-expanse-8b,slimllm,3-bit,Chinese,0.152,0.020,0.000,0.052
21,CohereLabs/aya-expanse-8b,slimllm,4-bit,Chinese,0.196,0.008,0.004,0.136
8,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,English,0.016,0.000,0.000,0.012
12,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,English,0.440,0.060,0.004,0.132
9,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Tamil,0.000,0.000,0.000,0.000
13,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Tamil,0.296,0.032,0.000,0.008
10,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Swahili,0.040,0.000,0.000,0.012
14,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Swahili,0.676,0.092,0.048,0.276
11,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Chinese,0.032,0.016,0.004,0.008
15,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Chinese,0.712,0.056,0.252,0.288

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,ta,sw,zh
4,Qwen/Qwen3-8B,tacq,3-bit,English,0.760,0.184,0.004,0.812
0,Qwen/Qwen3-8B,tacq,4-bit,English,0.816,0.652,0.080,0.828
5,Qwen/Qwen3-8B,tacq,3-bit,Tamil,0.724,0.484,0.000,0.776
1,Qwen/Qwen3-8B,tacq,4-bit,Tamil,0.780,0.664,0.064,0.844
6,Qwen/Qwen3-8B,tacq,3-bit,Swahili,0.680,0.420,0.008,0.724
2,Qwen/Qwen3-8B,tacq,4-bit,Swahili,0.776,0.620,0.140,0.792
7,Qwen/Qwen3-8B,tacq,3-bit,Chinese,0.788,0.176,0.000,0.772
3,Qwen/Qwen3-8B,tacq,4-bit,Chinese,0.784,0.600,0.020,0.840
16,CohereLabs/aya-expanse-8b,tacq,3-bit,English,0.328,0.008,0.008,0.032
20,CohereLabs/aya-expanse-8b,tacq,4-bit,English,0.408,0.004,0.000,0.268
17,CohereLabs/aya-expanse-8b,tacq,3-bit,Tamil,0.172,0.016,0.012,0.088
21,CohereLabs/aya-expanse-8b,tacq,4-bit,Tamil,0.520,0.000,0.004,0.232
18,CohereLabs/aya-expanse-8b,tacq,3-bit,Swahili,0.124,0.008,0.000,0.080
22,CohereLabs/aya-expanse-8b,tacq,4-bit,Swahili,0.588,0.000,0.008,0.208
19,CohereLabs/aya-expanse-8b,tacq,3-bit,Chinese,0.428,0.004,0.004,0.072
23,CohereLabs/aya-expanse-8b,tacq,4-bit,Chinese,0.408,0.004,0.012,0.056
8,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,English,0.456,0.004,0.004,0.028
12,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,English,0.700,0.088,0.268,0.432
9,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Tamil,0.528,0.092,0.000,0.200
13,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Tamil,0.648,0.092,0.376,0.440
10,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Swahili,0.152,0.004,0.032,0.040
14,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Swahili,0.776,0.140,0.256,0.452
11,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Chinese,0.388,0.056,0.000,0.300
15,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Chinese,0.724,0.104,0.168,0.432

Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,ta,sw,zh
10,Qwen/Qwen3-8B,gptq,English,3-bit,0.444,0.124,0.004,0.408
11,Qwen/Qwen3-8B,gptq,English,4-bit,0.824,0.496,0.232,0.840
14,Qwen/Qwen3-8B,gptq,Tamil,3-bit,0.456,0.288,0.004,0.260
15,Qwen/Qwen3-8B,gptq,Tamil,4-bit,0.744,0.628,0.028,0.820
12,Qwen/Qwen3-8B,gptq,Swahili,3-bit,0.252,0.060,0.000,0.468
13,Qwen/Qwen3-8B,gptq,Swahili,4-bit,0.788,0.520,0.080,0.784
8,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.256,0.048,0.008,0.472
9,Qwen/Qwen3-8B,gptq,Chinese,4-bit,0.748,0.544,0.040,0.864
2,CohereLabs/aya-expanse-8b,gptq,English,3-bit,0.140,0.000,0.004,0.008
3,CohereLabs/aya-expanse-8b,gptq,English,4-bit,0.528,0.000,0.004,0.252
6,CohereLabs/aya-expanse-8b,gptq,Tamil,3-bit,0.348,0.008,0.000,0.016
7,CohereLabs/aya-expanse-8b,gptq,Tamil,4-bit,0.524,0.000,0.004,0.200
4,CohereLabs/aya-expanse-8b,gptq,Swahili,3-bit,0.248,0.012,0.012,0.004
5,CohereLabs/aya-expanse-8b,gptq,Swahili,4-bit,0.604,0.000,0.008,0.140
0,CohereLabs/aya-expanse-8b,gptq,Chinese,3-bit,0.528,0.000,0.004,0.160
1,CohereLabs/aya-expanse-8b,gptq,Chinese,4-bit,0.448,0.004,0.008,0.256
18,meta-llama/Llama-3.1-8B-Instruct,gptq,English,3-bit,0.232,0.000,0.000,0.048
19,meta-llama/Llama-3.1-8B-Instruct,gptq,English,4-bit,0.704,0.084,0.104,0.356
22,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,3-bit,0.240,0.044,0.000,0.080
23,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,4-bit,0.768,0.060,0.240,0.608
20,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,3-bit,0.192,0.000,0.000,0.048
21,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,4-bit,0.752,0.076,0.200,0.488
16,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,3-bit,0.244,0.000,0.000,0.012
17,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,4-bit,0.756,0.116,0.104,0.468

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,ta,sw,zh
10,Qwen/Qwen3-8B,gptq,English,3-bit,0.0,0.0,0.0,0.0
14,Qwen/Qwen3-8B,gptq,Tamil,3-bit,0.0,0.0,0.0,0.0
12,Qwen/Qwen3-8B,gptq,Swahili,3-bit,0.0,0.0,0.0,0.0
8,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.0,0.0,0.0,0.0

SLIM

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,ta,sw,zh
8,Qwen/Qwen3-8B,slimllm,English,3-bit,0.376,0.012,0.008,0.496
9,Qwen/Qwen3-8B,slimllm,English,4-bit,0.760,0.648,0.012,0.808
12,Qwen/Qwen3-8B,slimllm,Tamil,3-bit,0.344,0.360,0.020,0.540
13,Qwen/Qwen3-8B,slimllm,Tamil,4-bit,0.776,0.564,0.092,0.816
10,Qwen/Qwen3-8B,slimllm,Swahili,3-bit,0.704,0.064,0.028,0.512
11,Qwen/Qwen3-8B,slimllm,Swahili,4-bit,0.800,0.652,0.056,0.796
6,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.712,0.036,0.004,0.700
7,Qwen/Qwen3-8B,slimllm,Chinese,4-bit,0.816,0.532,0.012,0.788
2,CohereLabs/aya-expanse-8b,slimllm,English,3-bit,0.124,0.000,0.000,0.008
3,CohereLabs/aya-expanse-8b,slimllm,English,4-bit,0.568,0.004,0.004,0.076
4,CohereLabs/aya-expanse-8b,slimllm,Swahili,3-bit,0.120,0.004,0.004,0.084
5,CohereLabs/aya-expanse-8b,slimllm,Swahili,4-bit,0.188,0.000,0.004,0.080
0,CohereLabs/aya-expanse-8b,slimllm,Chinese,3-bit,0.152,0.020,0.000,0.052
1,CohereLabs/aya-expanse-8b,slimllm,Chinese,4-bit,0.196,0.008,0.004,0.136
16,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,3-bit,0.016,0.000,0.000,0.012
17,meta-llama/Llama-3.1-8B-Instruct,slimllm,English,4-bit,0.440,0.060,0.004,0.132
20,meta-llama/Llama-3.1-8B-Instruct,slimllm,Tamil,3-bit,0.000,0.000,0.000,0.000
21,meta-llama/Llama-3.1-8B-Instruct,slimllm,Tamil,4-bit,0.296,0.032,0.000,0.008
18,meta-llama/Llama-3.1-8B-Instruct,slimllm,Swahili,3-bit,0.040,0.000,0.000,0.012
19,meta-llama/Llama-3.1-8B-Instruct,slimllm,Swahili,4-bit,0.676,0.092,0.048,0.276
14,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,3-bit,0.032,0.016,0.004,0.008
15,meta-llama/Llama-3.1-8B-Instruct,slimllm,Chinese,4-bit,0.712,0.056,0.252,0.288

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,ta,sw,zh
8,Qwen/Qwen3-8B,slimllm,English,3-bit,0.0,0.0,0.0,0.0
12,Qwen/Qwen3-8B,slimllm,Tamil,3-bit,0.0,0.0,0.0,0.0
10,Qwen/Qwen3-8B,slimllm,Swahili,3-bit,0.0,0.0,0.0,0.0
6,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.0,0.0,0.0,0.0

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,ta,sw,zh
10,Qwen/Qwen3-8B,tacq,English,3-bit,0.760,0.184,0.004,0.812
11,Qwen/Qwen3-8B,tacq,English,4-bit,0.816,0.652,0.080,0.828
14,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.724,0.484,0.000,0.776
15,Qwen/Qwen3-8B,tacq,Tamil,4-bit,0.780,0.664,0.064,0.844
12,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.680,0.420,0.008,0.724
13,Qwen/Qwen3-8B,tacq,Swahili,4-bit,0.776,0.620,0.140,0.792
8,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.788,0.176,0.000,0.772
9,Qwen/Qwen3-8B,tacq,Chinese,4-bit,0.784,0.600,0.020,0.840
2,CohereLabs/aya-expanse-8b,tacq,English,3-bit,0.328,0.008,0.008,0.032
3,CohereLabs/aya-expanse-8b,tacq,English,4-bit,0.408,0.004,0.000,0.268
6,CohereLabs/aya-expanse-8b,tacq,Tamil,3-bit,0.172,0.016,0.012,0.088
7,CohereLabs/aya-expanse-8b,tacq,Tamil,4-bit,0.520,0.000,0.004,0.232
4,CohereLabs/aya-expanse-8b,tacq,Swahili,3-bit,0.124,0.008,0.000,0.080
5,CohereLabs/aya-expanse-8b,tacq,Swahili,4-bit,0.588,0.000,0.008,0.208
0,CohereLabs/aya-expanse-8b,tacq,Chinese,3-bit,0.428,0.004,0.004,0.072
1,CohereLabs/aya-expanse-8b,tacq,Chinese,4-bit,0.408,0.004,0.012,0.056
18,meta-llama/Llama-3.1-8B-Instruct,tacq,English,3-bit,0.456,0.004,0.004,0.028
19,meta-llama/Llama-3.1-8B-Instruct,tacq,English,4-bit,0.700,0.088,0.268,0.432
22,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,3-bit,0.528,0.092,0.000,0.200
23,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,4-bit,0.648,0.092,0.376,0.440
20,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,3-bit,0.152,0.004,0.032,0.040
21,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,4-bit,0.776,0.140,0.256,0.452
16,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,3-bit,0.388,0.056,0.000,0.300
17,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,4-bit,0.724,0.104,0.168,0.432

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,ta,sw,zh
10,Qwen/Qwen3-8B,tacq,English,3-bit,0.0,0.0,0.0,0.0
14,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.0,0.0,0.0,0.0
12,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.0,0.0,0.0,0.0
8,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.0,0.0,0.0,0.0

[[0, 'EN'], [1, 'TA'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'TA' 'SW' 'ZH']
mean_ppl

en    2.136
ta    0.472
sw    0.060
zh    2.248
dtype: float64

[[0, 'EN'], [1, 'TA'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'TA' 'SW' 'ZH']
mean_ppl

en    3.152
ta    2.396
sw    0.172
zh    3.208
dtype: float64

[[0, 'EN'], [1, 'TA'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'SW' 'ZH']
mean_ppl

en    0.396
ta    0.024
sw    0.004
zh    0.144
dtype: float64

[[0, 'EN'], [1, 'TA'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'SW' 'ZH']
mean_ppl

/tmp/ipykernel_2704/4051798515.py:278: RuntimeWarning:

Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.

en    0.952
ta    0.012
sw    0.012
zh    0.292
dtype: float64

[[0, 'EN'], [1, 'TA'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'TA' 'SW' 'ZH']
mean_ppl

en    0.088
ta    0.016
sw    0.004
zh    0.032
dtype: float64

[[0, 'EN'], [1, 'TA'], [3, 'SW'], [4, 'ZH']]
where TA located
['EN' 'TA' 'SW' 'ZH']
mean_ppl

en    2.124
ta    0.240
sw    0.304
zh    0.704
dtype: float64

In [7]:
# eval_languages = ["eng_Latn", "tam_Taml", "ind_Latn", "swh_Latn", "zho_Hans"]
eval_languages = ["en", "ta", "sw", "zh"]

# Initialize the W&B API
api = Api()

quantization_technique = "ALL"
# bit = 8
num_samples = 128
eval_dataset = "mgsm"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"
strict_answer = True

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.num_calibration_samples": num_samples},
                            {"config.evaluation_dataset": f"{eval_dataset.lower()}"},
                            {"config.base_model": "Qwen/Qwen3-14B"},
                            {"config.enable_thinking": True},
                            # {"config.output_type": "generate_until"},
                            {"$not": {"config.calibration_language": "Indonesian"}},
                            {"$not": {"config.calibration_language": "WuuChinese"}},
                            # {"$not": {"$and": [{"created_at": {"$lt": "2026-03-01"}}, {"config.quantization_technique": "gptq"}]}},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            # {"config.bit_width": f"{bit}-bit"},
                            {"config.evaluation_dataset": eval_dataset.lower()},
                            {"config.base_model": "Qwen/Qwen3-14B"},
                            {"config.enable_thinking": True},
                            # {"config.output_type": "generate_until"},
                            {"created_at": {"$gt": "2026-07-01"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              {"config.evaluation_dataset": eval_dataset.lower()},
                            {"config.base_model": "Qwen/Qwen3-14B"},
                              {"config.enable_thinking": True},
                              {"created_at": {"$gt": "2026-07-01"}},
                          ]}
                      ]}
                  )
  print(len(runs))

  # visualize_delta_unquantized_globalmmlulite(eval_languages=eval_languages, runs=runs, base_model=base_model, quantization_technique=quantization_technique, bit_width=bit, eval_dataset=eval_dataset, custom_title="")
  # visualize_delta_unquantized_deliver_bar(eval_languages=eval_languages, runs=runs, base_model=base_model, quantization_technique=quantization_technique, bits=["2-bit", "3-bit", "4-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, compile=False)
  visualize_deliver_bar(eval_languages=eval_languages, runs=runs, base_models=["Qwen/Qwen3-14B"], quantization_technique=quantization_technique, bits=["2-bit", "3-bit"], eval_dataset=eval_dataset, custom_title="", display_mean=False, generate_until=True, compile=False, vertical_spacing=0.040, horizontal_spacing=0.04, random_guess_score=0.0, strict_answer=strict_answer, write_pdf=f"mgsm_14b_barplot_errorbar_{'strict' if strict_answer else 'flexible'}_final.pdf")

19
Pre-AGG

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,ta,sw,zh
5,Qwen/Qwen3-14B,gptq,2-bit,English,0.000,0.000,0.000,0.000
3,Qwen/Qwen3-14B,gptq,3-bit,English,0.876,0.240,0.100,0.808
4,Qwen/Qwen3-14B,gptq,2-bit,Tamil,0.000,0.000,0.000,0.000
2,Qwen/Qwen3-14B,gptq,3-bit,Tamil,0.908,0.488,0.240,0.856
7,Qwen/Qwen3-14B,gptq,2-bit,Swahili,0.000,0.000,0.000,0.000
1,Qwen/Qwen3-14B,gptq,3-bit,Swahili,0.740,0.552,0.216,0.872
0,Qwen/Qwen3-14B,gptq,2-bit,Chinese,0.000,0.000,0.000,0.000
6,Qwen/Qwen3-14B,gptq,3-bit,Chinese,0.916,0.468,0.272,0.832

Empty DataFrame
Columns: [Base Model, Quantization Technique, Bit Width, Calibration Language, en, ta, sw, zh]
Index: []

,Base Model,Quantization Technique,Bit Width,Calibration Language,en,ta,sw,zh
4,Qwen/Qwen3-14B,tacq,2-bit,English,0.248,0.000,0.000,0.112
6,Qwen/Qwen3-14B,tacq,3-bit,English,0.872,0.448,0.384,0.860
5,Qwen/Qwen3-14B,tacq,2-bit,Tamil,0.024,0.016,0.000,0.008
7,Qwen/Qwen3-14B,tacq,3-bit,Tamil,0.948,0.784,0.416,0.804
0,Qwen/Qwen3-14B,tacq,2-bit,Swahili,0.020,0.000,0.000,0.040
2,Qwen/Qwen3-14B,tacq,3-bit,Swahili,0.876,0.588,0.512,0.820
1,Qwen/Qwen3-14B,tacq,2-bit,Chinese,0.028,0.000,0.000,0.148
3,Qwen/Qwen3-14B,tacq,3-bit,Chinese,0.848,0.632,0.428,0.868

Contrasting Acc and Stderr
GPTQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,ta,sw,zh
2,Qwen/Qwen3-14B,gptq,English,2-bit,0.000,0.000,0.000,0.000
3,Qwen/Qwen3-14B,gptq,English,3-bit,0.876,0.240,0.100,0.808
6,Qwen/Qwen3-14B,gptq,Tamil,2-bit,0.000,0.000,0.000,0.000
7,Qwen/Qwen3-14B,gptq,Tamil,3-bit,0.908,0.488,0.240,0.856
4,Qwen/Qwen3-14B,gptq,Swahili,2-bit,0.000,0.000,0.000,0.000
5,Qwen/Qwen3-14B,gptq,Swahili,3-bit,0.740,0.552,0.216,0.872
0,Qwen/Qwen3-14B,gptq,Chinese,2-bit,0.000,0.000,0.000,0.000
1,Qwen/Qwen3-14B,gptq,Chinese,3-bit,0.916,0.468,0.272,0.832

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en, ta, sw, zh]
Index: []

SLIM

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en, ta, sw, zh]
Index: []

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en, ta, sw, zh]
Index: []

TACQ

,Base Model,Quantization Technique,Calibration Language,Bit Width,en,ta,sw,zh
2,Qwen/Qwen3-14B,tacq,English,2-bit,0.248,0.000,0.000,0.112
3,Qwen/Qwen3-14B,tacq,English,3-bit,0.872,0.448,0.384,0.860
6,Qwen/Qwen3-14B,tacq,Tamil,2-bit,0.024,0.016,0.000,0.008
7,Qwen/Qwen3-14B,tacq,Tamil,3-bit,0.948,0.784,0.416,0.804
4,Qwen/Qwen3-14B,tacq,Swahili,2-bit,0.020,0.000,0.000,0.040
5,Qwen/Qwen3-14B,tacq,Swahili,3-bit,0.876,0.588,0.512,0.820
0,Qwen/Qwen3-14B,tacq,Chinese,2-bit,0.028,0.000,0.000,0.148
1,Qwen/Qwen3-14B,tacq,Chinese,3-bit,0.848,0.632,0.428,0.868

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, en, ta, sw, zh]
Index: []

[[0, 'EN'], [1, 'TA'], [3, 'SW'], [4, 'ZH']]
where TA located
[]
[[0, 'EN'], [1, 'TA'], [3, 'SW'], [4, 'ZH']]
where TA located
[]