Resource
-

In [1]:
!pip install wandb==0.22.0

Collecting wandb==0.22.0
  Downloading wandb-0.22.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: click>=8.0.1 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (8.3.1)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (3.1.46)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (26.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (4.9.4)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (5.29.6)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (2.12.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (6.0.3)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (2.32.4)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (2.57.0)
Requirement already satisfied: typing-extensions<5,>=4.8 in /usr/local/lib/python3.12/dist-packages (from wandb==0.22.0) (4.15.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb==0.22.0) (4.0.12)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb==0.22.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb==0.22.0) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb==0.22.0) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb==0.22.0) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb==0.22.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb==0.22.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb==0.22.0) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb==0.22.0) (5.0.3)
Downloading wandb-0.22.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.6/19.6 MB 46.4 MB/s eta 0:00:00
Installing collected packages: wandb
  Attempting uninstall: wandb
    Found existing installation: wandb 0.25.1
    Uninstalling wandb-0.25.1:
      Successfully uninstalled wandb-0.25.1
Successfully installed wandb-0.22.0

### Install kaleido for export pdf

In [2]:
!pip install plotly==6.4.0
!pip install kaleido==1.2.0
!pip install choreographer==1.2.1
!pip install pypdf
!apt update
!apt-get install libnss3 libatk-bridge2.0-0 libcups2 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libpango-1.0-0 libcairo2 libasound2

Collecting plotly==6.4.0
  Downloading plotly-6.4.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: narwhals>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from plotly==6.4.0) (2.18.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly==6.4.0) (26.0)
Downloading plotly-6.4.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 25.0 MB/s eta 0:00:00
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1
Successfully installed plotly-6.4.0
Collecting kaleido==1.2.0
  Downloading kaleido-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Collecting choreographer>=1.1.1 (from kaleido==1.2.0)
  Downloading choreographer-1.4.0-py3-none-any.whl.metadata (5.5 kB)
Collecting logistro>=1.0.8 (from kaleido==1.2.0)
  Downloading logistro-2.0.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: orjson>=3.10.15 in /usr/local/lib/python3.12/dist-packages (from kaleido==1.2.0) (3.11.8)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaleido==1.2.0) (26.0)
Collecting pytest-timeout>=2.4.0 (from kaleido==1.2.0)
  Downloading pytest_timeout-2.4.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: platformdirs>=4.3.6 in /usr/local/lib/python3.12/dist-packages (from choreographer>=1.1.1->kaleido==1.2.0) (4.9.4)
Requirement already satisfied: simplejson>=3.19.3 in /usr/local/lib/python3.12/dist-packages (from choreographer>=1.1.1->kaleido==1.2.0) (3.20.2)
Requirement already satisfied: pytest>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from pytest-timeout>=2.4.0->kaleido==1.2.0) (8.4.2)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido==1.2.0) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido==1.2.0) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido==1.2.0) (2.20.0)
Downloading kaleido-1.2.0-py3-none-any.whl (68 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 3.0 MB/s eta 0:00:00
Downloading choreographer-1.4.0-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.0/58.0 kB 6.2 MB/s eta 0:00:00
Downloading logistro-2.0.1-py3-none-any.whl (8.6 kB)
Downloading pytest_timeout-2.4.0-py3-none-any.whl (14 kB)
Installing collected packages: logistro, pytest-timeout, choreographer, kaleido
Successfully installed choreographer-1.4.0 kaleido-1.2.0 logistro-2.0.1 pytest-timeout-2.4.0
Collecting choreographer==1.2.1
  Downloading choreographer-1.2.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: logistro>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from choreographer==1.2.1) (2.0.1)
Requirement already satisfied: simplejson>=3.19.3 in /usr/local/lib/python3.12/dist-packages (from choreographer==1.2.1) (3.20.2)
Downloading choreographer-1.2.1-py3-none-any.whl (49 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 3.0 MB/s eta 0:00:00
Installing collected packages: choreographer
  Attempting uninstall: choreographer
    Found existing installation: choreographer 1.4.0
    Uninstalling choreographer-1.4.0:
      Successfully uninstalled choreographer-1.4.0
Successfully installed choreographer-1.2.1
Collecting pypdf
  Downloading pypdf-6.19.0-py3-none-any.whl.metadata (7.5 kB)
Downloading pypdf-6.19.0-py3-none-any.whl (395 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.5/395.5 kB 8.7 MB/s eta 0:00:00
Installing collected packages: pypdf
Successfully installed pypdf-6.19.0
Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Get:3 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Err:2 https://cli.github.com/packages stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5612B36462313325
Get:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Hit:8 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:10 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [114 kB]
Get:11 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,242 kB]
Get:12 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [11.0 MB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [4,355 kB]
Get:14 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [49.0 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [8,124 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [84.6 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,819 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,321 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,623 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [93.2 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,698 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.6 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [82.9 kB]
Fetched 43.0 MB in 7s (5,848 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
245 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://cli.github.com/packages stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5612B36462313325
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
W: Failed to fetch https://cli.github.com/packages/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5612B36462313325
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxdamage1 set to manually installed.
libxfixes3 is already the newest version (1:6.0.0-1).
libxfixes3 set to manually installed.
libxkbcommon0 is already the newest version (1.4.0-1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libcairo2 is already the newest version (1.16.0-5ubuntu2.1).
libcairo2 set to manually installed.
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpango-1.0-0 set to manually installed.
The following additional packages will be installed:
  at-spi2-core gsettings-desktop-schemas libasound2-data libatk1.0-0
  libatk1.0-data libatspi2.0-0 libegl-mesa0 libgl1-mesa-dri libglapi-mesa
  libglx-mesa0 libxtst6 session-migration
Suggested packages:
  libasound2-plugins alsa-utils cups-common
Recommended packages:
  alsa-ucm-conf alsa-topology-conf libgl1-amber-dri
The following NEW packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0 libatk1.0-0
  libatk1.0-data libatspi2.0-0 libxcomposite1 libxtst6 session-migration
The following packages will be upgraded:
  libasound2 libasound2-data libcups2 libegl-mesa0 libgbm1 libgl1-mesa-dri
  libglapi-mesa libglx-mesa0 libnss3
9 upgraded, 9 newly installed, 0 to remove and 236 not upgraded.
Need to get 11.5 MB of archives.
After this operation, 1,502 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libasound2 amd64 1.2.6.1-1ubuntu1.2 [391 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libasound2-data all 1.2.6.1-1ubuntu1.2 [19.3 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcups2 amd64 2.4.1op1-1ubuntu4.21 [266 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libegl-mesa0 amd64 23.2.1-1ubuntu3.1~22.04.4 [118 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgbm1 amd64 23.2.1-1ubuntu3.1~22.04.4 [33.7 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgl1-mesa-dri amd64 23.2.1-1ubuntu3.1~22.04.4 [8,860 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglx-mesa0 amd64 23.2.1-1ubuntu3.1~22.04.4 [158 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglapi-mesa amd64 23.2.1-1ubuntu3.1~22.04.4 [35.6 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libnss3 amd64 2:3.98-0ubuntu0.22.04.4 [1,347 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Fetched 11.5 MB in 1s (7,731 kB/s)
Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 118194 files and directories currently installed.)
Preparing to unpack .../00-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../01-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../02-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../03-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../04-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Preparing to unpack .../05-libasound2_1.2.6.1-1ubuntu1.2_amd64.deb ...
Unpacking libasound2:amd64 (1.2.6.1-1ubuntu1.2) over (1.2.6.1-1ubuntu1.1) ...
Preparing to unpack .../06-libasound2-data_1.2.6.1-1ubuntu1.2_all.deb ...
Unpacking libasound2-data (1.2.6.1-1ubuntu1.2) over (1.2.6.1-1ubuntu1.1) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../07-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../08-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../09-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Preparing to unpack .../10-libcups2_2.4.1op1-1ubuntu4.21_amd64.deb ...
Unpacking libcups2:amd64 (2.4.1op1-1ubuntu4.21) over (2.4.1op1-1ubuntu4.16) ...
Preparing to unpack .../11-libegl-mesa0_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libegl-mesa0:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../12-libgbm1_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libgbm1:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../13-libgl1-mesa-dri_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libgl1-mesa-dri:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../14-libglx-mesa0_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libglx-mesa0:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../15-libglapi-mesa_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libglapi-mesa:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../16-libnss3_2%3a3.98-0ubuntu0.22.04.4_amd64.deb ...
Unpacking libnss3:amd64 (2:3.98-0ubuntu0.22.04.4) over (2:3.98-0ubuntu0.22.04.3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../17-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libgbm1:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libnss3:amd64 (2:3.98-0ubuntu0.22.04.4) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libasound2-data (1.2.6.1-1ubuntu1.2) ...
Setting up libglapi-mesa:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up libcups2:amd64 (2.4.1op1-1ubuntu4.21) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up libasound2:amd64 (1.2.6.1-1ubuntu1.2) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up libgl1-mesa-dri:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Setting up libegl-mesa0:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up libglx-mesa0:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.9) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Setting up at-spi2-core (2.44.0-3) ...

In [3]:
import plotly.io as pio

pio.get_chrome()

PosixPath('/usr/local/lib/python3.12/dist-packages/choreographer/cli/browser_exe/chrome-linux64/chrome')

# Login

In [1]:
from google.colab import userdata
WANDB_KEY = userdata.get('WANDB_TOKEN')

In [2]:
import wandb
print(wandb.__version__)
wandb.login(key=WANDB_KEY)

/usr/local/lib/python3.12/dist-packages/pydantic/_internal/_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'repr' attribute with value False was provided to the `Field()` function, which has no effect in the context it was used. 'repr' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/pydantic/_internal/_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'frozen' attribute with value True was provided to the `Field()` function, which has no effect in the context it was used. 'frozen' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(

0.22.0

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: rofifpriyo (rofifpriyo-) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

# Parameter

In [3]:
import wandb
from wandb.apis.public import Api
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.subplots as ps
import plotly.graph_objects as go

ENTITY = wandb.apis.PublicApi().default_entity
PROJECT = "calibration-on-quantized-multilingual"

# Plot from WandB

> Docs: https://docs.wandb.ai/ref/python/public-api/api/#method-apiruns

## Perplexity

### Deliverables + Functions

#### 3x Run Stabilizer

In [4]:
import numpy as np
import re
def perplexity_heatmap_deliver_vertical(eval_languages, runs, base_models, quantization_technique, bit_width, eval_dataset, custom_title="", display_mean=True, compile=False, show_subline=True, hf_evaluate=False, zscore_threshold=1, gmean_aggregate=False, two_color=True, display_colorbar=True, write_pdf=""):
  language_sort = {
      # # Flores Plus
      # "eng_Latn": 0, "fra_Latn": 1, "hin_Deva": 2, "npi_Deva": 3, "tam_Taml": 6, "tel_Telu": 7, "ind_Latn": 8, "zsm_Latn": 9, "swh_Latn": 10, "yor_Latn": 11, "cmn_Hans": 12, "jpn_Jpan": 13, "kor_Hang": 14, "arb_Arab" : 15,\
      # Wikipedia
      "en": 0, "fr": 1, "hi": 2, "ne": 3, "ta": 6, "te": 7, "id": 8, "ms": 9, "sw": 10, "yo": 11, "zh": 12, "ja": 13, "ko": 14, "ar": 15,\
      # INCLUDE
      "french": 1, "hindi": 2, "nepali": 3, "albanian": 4, "tamil": 6, "telugu": 7, "indonesian": 8, "malay": 9, "chinese": 12, "japanese": 13, "korean": 14, "arabic": 15,\
      # Global MMLU Lite
      "en": 0, "fr": 1, "hi": 2, "bn": 5, "id": 8, "sw": 10, "yo": 11, "zh": 12, "ja": 13, "ko": 14, "ar": 15,
  } # Add floresplus evals, and count their respective language's family
  family_counter = []
  if eval_dataset == 'floresplus':
    # flores_plus_add = ["afr_Latn", "dan_Latn", "deu_Latn", "eng_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"]
    flores_plus_add = ["eng_Latn", "tpi_Latn", "afr_Latn", "deu_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "ydd_Hebr", "dan_Latn", "fao_Latn", "isl_Latn", "nno_Latn", "nob_Latn", "swe_Latn"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 0 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
    flores_plus_add = ["kan_Knda", "mal_Mlym", "tam_Taml", "tel_Telu"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 6 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
    # flores_plus_add = ["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "ind_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"]
    flores_plus_add = ["ind_Latn", "zsm_Latn", "bjn_Latn", "min_Latn", "ace_Latn", "ban_Latn", "bug_Latn", "jav_Latn", "sun_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "fil_Latn", "war_Latn"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 8 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
    flores_plus_add = ["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "swh_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 10 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
    flores_plus_add = ["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant", "cmn_Hans"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 12 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
  elif eval_dataset == 'wikipedia':
    wikipedia_add = ["en", "de", "nl"]
    for index, lang in enumerate(wikipedia_add):
      language_sort[lang] = 0 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in wikipedia_add]))
    wikipedia_add = ["ml", "ta", "te"]
    for index, lang in enumerate(wikipedia_add):
      language_sort[lang] = 6 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in wikipedia_add]))
    wikipedia_add = ["id", "tl", "ms"]
    for index, lang in enumerate(wikipedia_add):
      language_sort[lang] = 8 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in wikipedia_add]))
    wikipedia_add = ["sw", "lg", "yo"]
    for index, lang in enumerate(wikipedia_add):
      language_sort[lang] = 10 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in wikipedia_add]))
    wikipedia_add = ["bo", "my", "zh"]
    for index, lang in enumerate(wikipedia_add):
      language_sort[lang] = 12 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in wikipedia_add]))
  eval_languages = list(sorted(eval_languages, key=lambda x: language_sort.get(x, 100)))
  # print(eval_languages)

  columns = ["Base Model", "Quantization Technique", "Bit Width", "Calibration Language"]
  columns.extend(eval_languages)
  custom_sort = {'Unquantized': 0, 'English': 1, 'Tamil': 2, 'Indonesian': 3, 'Swahili': 4, 'Chinese': 5,\
                 'Unquantized': 0, 'gptq': 1, 'slimllm': 2, 'tacq': 3,\
                 "Qwen/Qwen3-8B": 0, "CohereLabs/aya-expanse-8b": 1, "meta-llama/Llama-3.1-8B-Instruct": 2}

  calib_label = {"English": "EN", "Tamil": "TA", "Indonesian": "ID", "Swahili": "SW", "Chinese": "ZH"}
  base_model_label = {"Qwen/Qwen3-8B": "Qwen3", "CohereLabs/aya-expanse-8b": "Aya", "meta-llama/Llama-3.1-8B-Instruct": "Llama"}
  quantization_technique_label = {"UQ": "Unquantized", "gptq": "GPTQ", "slimllm": "SliM-LLM", "tacq": "TaCQ"}
  eval_label = {
      # # Flores Plus
      "eng_Latn": "EN", "fra_Latn": "FR", "hin_Deva": "HI", "npi_Deva": "NE", "tam_Taml": "TA", "tel_Telu": "TE", "ind_Latn": "ID", "zsm_Latn": "ZSM", "swh_Latn": "SW", "yor_Latn": "YO", "cmn_Hans": "ZH", "jpn_Jpan": "JA", "kor_Hang": "KO", "arb_Arab" : "AR",\
      "ace_Latn": "ACE", "ban_Latn": "BAN", "bjn_Latn": "BJN", "bug_Latn": "BUG", "ceb_Latn": "CEB", "fij_Latn": "FIJ", "ilo_Latn": "ILO", "jav_Latn": "JAV", "min_Latn": "MIN", "plt_Latn": "PLT", "mri_Latn": "MRI", "pag_Latn": "PAG", "smo_Latn": "SMO", "sun_Latn": "SUN", "fil_Latn": "FIL", "war_Latn": "WAR",\
      # Wikipedia
      "en": "EN", "fr": "FR", "hi": "HI", "ne": "NE", "ta": "TA", "te": "TE", "id": "ID", "ms": "MS", "sw": "SW", "yo": "YO", "zh": "ZH", "ja": "JA", "ko": "KO", "ar": "AR",\
      # INCLUDE
      "french": "FR", "hindi": "HI", "nepali": "NE", "albanian": "SQ", "tamil": "TA", "telugu": "TE", "indonesian": "ID", "malay": "MS", "chinese": "ZH", "japanese": "JA", "korean": "KO", "arabic": "AR",\
      # Global MMLU Lite
      "en": "EN", "fr": "FR", "hi": "HI", "bn": "BN", "id": "ID", "sw": "SW", "yo": "YO", "zh": "ZH", "ja": "JA", "ko": "KO", "ar": "AR",
      # Multi Blimp
      "eng": "EN", "tam": "TA", "idn": "ID", "swa": "SW", "zhoblimp": "ZH",
      # # Belebele
      # "eng_Latn": "EN", "nld_Latn": "NL", "deu_Latn": "DE", "mal_Mlym": "ML", "tam_Taml": "TA", "tel_Telu": "TE", "ind_Latn": "ID", "tgl_Latn": "TE", "zsm_Latn": "MS", "swh_Latn": "SW", "yor_Latn": "YO", "lug_Latn": "LG", "bod_Tibt": "BO", "mya_Mymr": "MY", "zho_Hans": "ZH",
  }

  data_acc = []
  data_nancount = []

  data_gptq = []
  data_slimllm = []
  data_tacq = []

  # import numpy as np
  # data_slimllm.append(["-", "CohereLabs/aya-expanse-8b", "slimllm", "4-bit", "Tamil"] + [np.nan for _ in eval_languages])

  unquantized_data_acc = []

  # Iterate over the runs and print details
  for run in runs:
      config = run.config
      summary = run.summary

      if config["calibration_language"] == "WuuChinese":
        continue

      run_data_acc = []
      run_data_nancount = []
      run_data_acc.extend([run.config["base_model"], config["quantization_technique"], config["bit_width"], config["calibration_language"]])
      run_data_nancount.extend([run.config["base_model"], config["quantization_technique"], config["bit_width"], config["calibration_language"]])
      if not hf_evaluate:
        for lang in eval_languages:
          if lang in ["zh", "Chinese", "cmn_Hans", "ja", "Japanese", "jpn_Jpan", "bo", "Tibetan", "bod_Tibt", "dz", "Dzongkha", "dzo_Tibt", "Yue Chinese", "yue_Hant"]:
            acc = run.summary.get(f"{eval_dataset.lower()}_byte_acc_{lang}", None)
            nancount = run.summary.get(f"{eval_dataset.lower()}_nan_count_{lang}", 0)
            if acc:
              # acc = math.pow(acc, 1/3)
              pass
            run_data_acc.append(acc)
            run_data_nancount.append(nancount)
          else:
            run_data_acc.append(run.summary.get(f"{eval_dataset.lower()}_token_perplexity_{lang}",
                                                run.summary.get(f"{eval_dataset.lower()}_word_acc_{lang}", None)
                                                ))
            run_data_nancount.append(run.summary.get(f"{eval_dataset.lower()}_nan_count_{lang}", 0))
      elif hf_evaluate:
        for lang in eval_languages:
          if gmean_aggregate:
            run_data_acc.append(run.summary.get(f"{eval_dataset.lower()}_gmean_perplexity_{lang}",
                                                run.summary.get(f"{eval_dataset.lower()}_word_acc_{lang}", None)
                                                ))
          else:
            run_data_acc.append(run.summary.get(f"{eval_dataset.lower()}_token_perplexity_{lang}",
                                                run.summary.get(f"{eval_dataset.lower()}_word_acc_{lang}", None)
                                                ))
          run_data_nancount.append(run.summary.get(f"{eval_dataset.lower()}_nancount_{lang}", 0))
      if config["quantization_technique"] == "Unquantized":
        unquantized_data_acc.append(run_data_acc)
        # data_nancount.append(run_data_nancount)
      elif config["quantization_technique"] == "gptq":
        data_gptq.append(run_data_acc)
        # data_nancount.append(run_data_nancount)
      elif config["quantization_technique"] == "slimllm":
        data_slimllm.append(run_data_acc)
        # data_nancount.append(run_data_nancount)
      elif config["quantization_technique"] == "tacq":
        data_tacq.append(run_data_acc)
        # data_nancount.append(run_data_nancount)

  df_unquantized_acc_chief = pd.DataFrame(unquantized_data_acc, columns=columns)
  df_gptq_chief = pd.DataFrame(data_gptq, columns=columns).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_slimllm_chief = pd.DataFrame(data_slimllm, columns=columns).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_tacq_chief = pd.DataFrame(data_tacq, columns=columns).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))

  display(pd.concat([df_unquantized_acc_chief, df_gptq_chief, df_slimllm_chief, df_tacq_chief], axis=0))

  # with pd.option_context('display.max_rows', None):

  # Unquantized
  df_unquantized_acc_chief_std = df_unquantized_acc_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std")

  # GPTQ agg
  df_gptq_chief_std = df_gptq_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std", ddof=0).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_gptq_chief = df_gptq_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("mean").sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))

  # Slim agg
  df_slimllm_chief_std = df_slimllm_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std", ddof=0).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_slimllm_chief = df_slimllm_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("mean").sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))

  # Tacq agg
  df_tacq_chief_std = df_tacq_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std", ddof=0).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_tacq_chief = df_tacq_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("mean").sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  with pd.option_context('display.max_rows', None):
    display(df_tacq_chief_std)
  display(df_gptq_chief.columns)

  # display(df_gptq_chief_acc)
  # display(df_gptq_chief_std)

  df_gptq_chief[df_gptq_chief.columns[4:]] = df_gptq_chief[df_gptq_chief.columns[4:]].astype(float)
  df_slimllm_chief[df_slimllm_chief.columns[4:]] = df_slimllm_chief[df_slimllm_chief.columns[4:]].astype(float)
  df_tacq_chief[df_tacq_chief.columns[4:]] = df_tacq_chief[df_tacq_chief.columns[4:]].astype(float)
  df_unquantized_acc_chief[df_unquantized_acc_chief.columns[4:]] = df_unquantized_acc_chief[df_unquantized_acc_chief.columns[4:]].astype(float)

  # Easying aggregate calculation
  # Perplexity related, change order of PPL
  df_gptq_chief.iloc[:, 4:] = df_gptq_chief.iloc[:, 4:].apply(np.log10)
  df_slimllm_chief.iloc[:, 4:] = df_slimllm_chief.iloc[:, 4:].apply(np.log10)
  df_tacq_chief.iloc[:, 4:] = df_tacq_chief.iloc[:, 4:].apply(np.log10)
  df_unquantized_acc_chief.iloc[:, 4:] = df_unquantized_acc_chief.iloc[:, 4:].apply(np.log10)


  fig = go.Figure()

  df_chief = pd.DataFrame([])
  df_chief_std = pd.DataFrame([])
  df_zscore_chief = pd.DataFrame([])
  index_border_chief = [(0, 0)]
  # for base_model in ["CohereLabs/aya-expanse-8b"]:
  for base_model in base_models:
    print(f"start model: {base_model}")
    df_gptq = df_gptq_chief.loc[df_gptq_chief["Base Model"] == base_model]
    df_slimllm = df_slimllm_chief.loc[df_slimllm_chief["Base Model"] == base_model]
    df_tacq = df_tacq_chief.loc[df_tacq_chief["Base Model"] == base_model]
    df_unquantized_acc = df_unquantized_acc_chief.loc[df_unquantized_acc_chief["Base Model"] == base_model]
    df_gptq_std = df_gptq_chief_std.loc[df_gptq_chief_std["Base Model"] == base_model]
    df_slimllm_std = df_slimllm_chief_std.loc[df_slimllm_chief_std["Base Model"] == base_model]
    df_tacq_std = df_tacq_chief_std.loc[df_tacq_chief_std["Base Model"] == base_model]
    df_unquantized_acc_std = df_unquantized_acc_chief_std.loc[df_unquantized_acc_chief_std["Base Model"] == base_model]
    display(df_gptq)

    # display(df_unquantized_acc)
    base_model = base_model_label[base_model]

    df_gptq_std = df_gptq_std.iloc[:, 4:].T.rename(df_gptq_std['Quantization Technique'].apply(lambda x: quantization_technique_label.get(x, x)) + '-' + df_gptq_std['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    df_slimllm_std = df_slimllm_std.iloc[:, 4:].T.rename(df_slimllm_std['Quantization Technique'].apply(lambda x: quantization_technique_label.get(x, x)) + '-' + df_slimllm_std['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    df_tacq_std = df_tacq_std.iloc[:, 4:].T.rename(df_tacq_std['Quantization Technique'].apply(lambda x: quantization_technique_label.get(x, x)) + '-' + df_tacq_std['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    df_unquantized_acc_std = df_unquantized_acc_std.iloc[:, 4:].T.rename(lambda x: "UQ", axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')

    # Take only the result and reformat the indices
    # df_gptq = df_gptq.iloc[:, 5:].sub(df_unquantized_acc.iloc[:, 5:].values).T.rename(df_gptq['Quantization Technique'].apply(lambda x: x[0].upper()) + '-' + df_gptq['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    df_gptq = df_gptq.iloc[:, 4:].T.rename(df_gptq['Quantization Technique'].apply(lambda x: quantization_technique_label.get(x, x)) + '-' + df_gptq['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    if display_mean:
      df_gptq = pd.concat([df_gptq.T, df_gptq.mean(axis=0).to_frame('Mean')], axis=1).T
    df_gptq = df_gptq.astype(float)
    display(df_gptq)

    # df_slimllm = df_slimllm.iloc[:, 5:].sub(df_unquantized_acc.iloc[:, 5:].values).T.rename(df_slimllm['Quantization Technique'].apply(lambda x: x[0].upper()) + '-' + df_slimllm['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    df_slimllm = df_slimllm.iloc[:, 4:].T.rename(df_slimllm['Quantization Technique'].apply(lambda x: quantization_technique_label.get(x, x)) + '-' + df_slimllm['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    if display_mean:
      df_slimllm = pd.concat([df_slimllm.T, df_slimllm.mean(axis=0).to_frame('Mean')], axis=1).T
    df_slimllm = df_slimllm.astype(float)

    # df_tacq = df_tacq.iloc[:, 5:].sub(df_unquantized_acc.iloc[:, 5:].values).T.rename(df_tacq['Quantization Technique'].apply(lambda x: x[0].upper()) + '-' + df_tacq['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    df_tacq = df_tacq.iloc[:, 4:].T.rename(df_tacq['Quantization Technique'].apply(lambda x: quantization_technique_label.get(x, x)) + '-' + df_tacq['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    if display_mean:
      df_tacq = pd.concat([df_tacq.T, df_tacq.mean(axis=0).to_frame('Mean')], axis=1).T
    df_tacq = df_tacq.astype(float)

    df_unquantized_acc = df_unquantized_acc.iloc[:, 4:].T.rename(lambda x: "UQ", axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    if display_mean:
      df_unquantized_acc = pd.concat([df_unquantized_acc, df_unquantized_acc.mean(axis=0).to_frame(f'Mean_{base_model}').T], axis=0)
    df = pd.concat([df_gptq, df_slimllm, df_tacq], axis=1)
    df_std = pd.concat([df_gptq_std, df_slimllm_std, df_tacq_std], axis=1)
    df_mean_quantized = df.mean(axis=1).to_frame('Mean of Quantized')
    # display(df_unquantized_acc)

    for iter, (index_row, index_col) in enumerate([df_unquantized_acc.shape, df_gptq.shape, df_slimllm.shape, df_tacq.shape]):
      if iter != 0:
        index_row = 0
      index_border_chief.append((index_border_chief[-1][0] + index_row, index_border_chief[-1][1] + index_col))

    from scipy.stats import zscore
    df_zscore_gptq = pd.DataFrame(zscore(df_gptq, axis=1, nan_policy='omit'), columns=df_gptq.columns, index=df_gptq.index)
    df_zscore_slimllm = pd.DataFrame(zscore(df_slimllm, axis=1, nan_policy='omit'), columns=df_slimllm.columns, index=df_slimllm.index)
    df_zscore_tacq = pd.DataFrame(zscore(df_tacq, axis=1, nan_policy='omit'), columns=df_tacq.columns, index=df_tacq.index)

    # Skip mean of quantized
    df_zscore = pd.concat([pd.Series(np.zeros_like(df_zscore_tacq.index), index=df_zscore_tacq.index, name="UQ"), df_zscore_gptq, df_zscore_slimllm, df_zscore_tacq], axis=1)

    df = pd.concat([df_unquantized_acc, df], axis=1)
    df_chief = pd.concat([df_chief, df], axis=0)
    df_zscore_chief = pd.concat([df_zscore_chief, df_zscore], axis=0)

    df_std = pd.concat([df_unquantized_acc_std, df_std], axis=1)
    df_chief_std = pd.concat([df_chief_std, df_std], axis=0)

  # Revariable for onness usage of df, we was using chief for the sake of differentiating between chief and iter df
  df = df_chief
  df_std = df_chief_std
  df_zscore = df_zscore_chief
  df = df.rename(lambda x: eval_label.get(x, x), axis=0)
  df_std = df_std.rename(lambda x: eval_label.get(x, x), axis=0)
  df_zscore = df_zscore.rename(lambda x: eval_label.get(x, x), axis=0)
  # display(df)
  # display(df_zscore)

  # Rebase the number
  df = df.apply(lambda x: 10 ** x)

  # display(df)
  # display(df_zscore)
  if not display_mean:
    df = df.reindex(index=df.index[::-1])
    df_std = df_std.reindex(index=df_std.index[::-1])
    df_zscore = df_zscore.reindex(index=df_zscore.index[::-1])
  display(df)
  display(df_std)

  # df_text = df.copy().map(lambda x: f"x10^{x:.1f}" if not np.isnan(x) else "-")
  # df_text = df.copy().map(lambda x: f"{(10**x):.2f}" if x < 3 else f"{(10**x):.1e}" if not np.isnan(x) else "-")
  df_std = df_std.map(lambda x: f"{x:.2f}" if 0 < x < 100 else f"{x:.1f}" if 0 < x < 1000 else re.sub(r'([eE][+-])0+(?=\d)', r'\1', f"{x:.1e}") if (not np.isnan(x) and not x == 0) else "")
  df_text = df.copy().map(lambda x: f"{x:.2f}" if x < 100 else f"{x:.1f}" if x < 1000 else re.sub(r'([eE][+-])0+(?=\d)', r'\1', f"{x:.1e}") if not np.isnan(x) else "-")
  # df_text = list(zip(df_text.values, df_std.values))
  print("## Shape")
  print(f"df text: {df_text.shape}")
  print(f"df std: {df_std.shape}")
  df_text = [list(zip(x, y)) for x, y in list(zip(df_text.values.tolist(), df_std.values.tolist()))]
  # df_text.iloc[:, 0] = df_text.iloc[:, 0].apply(lambda x: x[1:])

  # Color palette use this: Green: https://colordesigner.io/gradient-generator from 255, 255, 255 to 6, 54, 21, Red: https://colordesigner.io/gradient-generator from 255, 255, 255 to 214, 39, 40
  def exact_zscore_scale(z, df_zscore):
    return (z - df_zscore.min(axis=None)) / (df_zscore.max(axis=None) - df_zscore.min(axis=None))
  # Add 0, then iteratively add green and red until it touch min 0 or max 1
  colorscale = []
  # If light = good, dark = bad
  if not two_color:
    colorscale = [[0, 'rgba(255, 255, 255, 0.85)'], [1, 'rgba(214, 39, 40, 0.85)']]
  # For two color signaling, e.g. red = bad, green = good
  else:
    colorscale = [[exact_zscore_scale(0, df_zscore), 'rgba(255, 255, 255, 0.85)']]
    # Green for negativee z   1. Three scale different color, 2. Normal, 3. Thresholded z-score
    if zscore_threshold >= 1:
      color_zip = zip([-1+10**-5, -1, -2, -3], ['rgba(255, 255, 255, 0.85)', 'rgba(144, 166, 151, 0.85)', 'rgba(61, 99, 73, 0.85)', 'rgba(6,54,21, 0.85)'])
    elif zscore_threshold >= 1/2:
      color_zip = zip([-1/2+10**-5, -1/2, -2, -3], ['rgba(255, 255, 255, 0.85)', 'rgba(144, 166, 151, 0.85)', 'rgba(61, 99, 73, 0.85)', 'rgba(6,54,21, 0.85)'])
    else:
      # color_zip = zip([-1, -2, -3], ['rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)'])
      color_zip = zip([-3], ['rgba(6,54,21, 0.85)'])
    # for z, color in zip([1, 2, 3], ['rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)']):
    # for z, color in zip([1, 2, 3], ['rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)']):
    for z, color in color_zip:
    # for z, color in zip([-10**-5, -1, -1-10**-5, -2, -3], ['rgba(0,255,255, 0.85)', 'rgba(0,255,255, 0.85)', 'rgba(6,54,21, 0.85)', 'rgba(6,54,21, 0.85)', 'rgba(191,139,255, 0.85)']):
    # for z, color in zip([-1, -1-10**(-5), -2], ['rgba(144, 166, 151, 0.85)', 'rgba(89, 121, 99, 0.85)', 'rgba(6,54,21, 0.85)']):
    # for z, color in zip([-1+10**-5, -1, -2, -3], ['rgba(255, 255, 255, 0.85)', 'rgba(144, 166, 151, 0.85)', 'rgba(61, 99, 73, 0.85)', 'rgba(6,54,21, 0.85)']):
      z_scale = exact_zscore_scale(z, df_zscore)
      colorscale.insert(0, [max(0, z_scale), color])
      if z_scale < 0:
        break
    # Red for positive z
    if zscore_threshold >= 1:
      color_zip = zip([1-10**-5, 1, 2, 3], ['rgba(255, 255, 255, 0.85)', 'rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)'])
    elif zscore_threshold >= 1/2:
      color_zip = zip([1/2-10**-5, 1/2, 2, 3], ['rgba(255, 255, 255, 0.85)', 'rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)'])
    else:
      # color_zip = zip([1, 2, 3], ['rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)'])
      color_zip = zip([3], ['rgba(214, 39, 40, 0.85)'])
    # for z, color in zip([1, 2, 3], ['rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)']):
    # for z, color in zip([1, 2, 3], ['rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)']):
    for z, color in color_zip:
      z_scale = exact_zscore_scale(z, df_zscore)
      colorscale.append([min(1, z_scale), color])
      if z_scale > 1:
        break
  print("Display df")
  display(df)
  print("Display df std")
  display(df_std)
  fig = go.Figure(data=go.Heatmap(
                      z=df_zscore,
                      x=[[col_name.split("-")[0] if col_name != "UQ" else "16-bit" for col_name in df_zscore.columns], [col_name.split("-")[-1] if col_name != "UQ" else "-" for col_name in df_zscore.columns]],
                      y=[[f"""<span style='rotate: 0.5turn; display: inline-block;'> {idx_name.split("_")[-1]} </span>""" for idx_name in df_zscore.index],
                       [f"""<span style='rotate: -90deg;'> {idx_name.split("_")[-0]} </span>""" for idx_name in df_zscore.index]],
                      # text=[list(zip(x, y)) for x, y in list(zip(pd.concat([df_unquantized_acc, df, df_mean_quantized], axis=0).T.values.tolist(), df_nancount_all.T.values.tolist()))],
                      text=df_text,
                      # texttemplate="×10^%{text:.1f}",
                      texttemplate="%{text[0]}<sub>%{text[1]}</sub>",
                      # colorscale='Viridis',
                      # colorscale= [[0, 'rgba(6,54,21, 0.85)'],
                      #               [(0 - df_zscore.min(axis=None)) / (df_zscore.max(axis=None) - df_zscore.min(axis=None)), 'rgba(255, 255, 255, 0.85)'],
                      #               [1, 'rgba(214, 39, 40, 0.85)']],
                      colorscale=colorscale,
                      # colorbar=dict(title='Z-score'),
                      textfont={"size":16, "family": "Arial Black"},
                  ))
  # print(colorscale)

  # Horizontal each Eval Languages
  row_gptq, col_gptq = df_gptq.shape
  row_slimllm, col_slimllm = df_slimllm.shape
  row_tacq, col_tacq = df_tacq.shape
  row, col = df_zscore.shape
  offset_mean = 0 if display_mean else 1
  # Horizontal Line
  fig.add_shape(type="line",
                x0=-0.5, y0=row+offset_mean-1.5, x1=col-0.5, y1=row+offset_mean-1.5,
                line=dict(color="black", width = 1),
                )
  # # Vertical Line
  # fig.add_shape(type="line",
  #               x0=col-1.5, y0=-0.5, x1=col-1.5, y1=row-1.5,
  #               line=dict(color="black", width = 5),
  #               )
  # Vertical Each Quant Tech
  # print(index_border_chief)
  for (row_each, col_each) in index_border_chief[:5]:
    fig.add_shape(type="line",
                  x0=col_each-0.5, y0=-0.5, x1=col_each-0.5, y1=row+offset_mean-1.5,
                  line=dict(color="black", width = 5),
                  )
  # Horizontal Each Quant Tech
  for (row_each, col_each) in index_border_chief:
    fig.add_shape(type="line",
                  x0=-0.5, y0=row_each-0.5, x1=col-0.5, y1=row_each-0.5,
                  line=dict(color="black", width = 1),
                  )
  if show_subline:
    if not display_mean:
      family_counter = list(reversed(family_counter))
    # Horizontal Each Family Language Evaluation
    row_cum = 0
    # for row_each in family_counter:
    for row_each in family_counter * len(base_models):
      row_cum += row_each
      fig.add_shape(type="line",
                    x0=-0.5, y0=row_cum-0.5, x1=col-0.5, y1=row_cum-0.5,
                    line=dict(color="black", width = 1),
                    )

  fig.update_xaxes(automargin=False)
  fig.update_yaxes(automargin=False)
  fig.update_layout(
      # title_text=f"{base_model} {custom_title} {eval_dataset} (Max 1.0, +other language improve): Delta acc with Unquantized of <b>{quantization_technique} {bit_width}-bit</b> model",
      xaxis_title_text='Quantization Technique - Calibration Language',
      yaxis_title_text='Base Model - Eval Language',
      margin=dict(t=70, b=10 if write_pdf else 0, l=120, r=110 if display_colorbar else 0)
  )
  fig.update_layout(coloraxis_colorbar_title_side="right")
  if not display_mean:
    fig.update_xaxes(side="top")

  fig.layout.height = 70 + 35 * row + (10 if write_pdf else 0)
  fig.layout.width = 120 + 89 * col + (110 if display_colorbar else 0)

  # Color bar annotation
  if not display_colorbar:
    fig.update_traces(showscale=False)
  if display_colorbar:
    fig.update_layout(
        # margin=dict(r=150),
        # ^^ making a bit of space for the annotation
        annotations=[
            dict(
                text="Z-score",
                font_size=20,
                font_family='Arial',
                # font_color='red',
                textangle=90,
                showarrow=False,
                # ^^ appearance
                xref="paper",
                yref="paper",
                x=1 + (5 + 10 * col)/(fig.layout.margin.l + fig.layout.width + fig.layout.margin.r),
                y=0.5,
                # ^^ position
            ),
        ]
    )

  # fig.update_traces(showscale=False)
  # fig.update_layout(yaxis_visible=False, yaxis_showticklabels=False)

  fig.show()
  # print(fig)

  if write_pdf:
    print(f"Writing to pdf ...")
    fig.write_image(write_pdf)

#### The data

##### Only the random_seed

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [3]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"config.bit_width": f"{bit_width}-bit"},
                            {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                            {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            # {"$not": {"$and": [{"config.quantization_technique": "gptq"}, {"config.calibration_language": "Swahili"}]}}
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                              # {"config.base_model": base_model},
                            {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                          ]}
                      ]}
                  )

  eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
  # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
  # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
  # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
  # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
  # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

  # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
  perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, write_pdf="ablation_floresplus_3bit_vert.pdf")

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
0,Qwen/Qwen3-8B,gptq,3-bit,English,40.188512,4.329966,24.304464,160.417519,62.901249
5,Qwen/Qwen3-8B,gptq,3-bit,English,40.949766,4.233635,25.688953,160.373092,64.743586
6,Qwen/Qwen3-8B,gptq,3-bit,English,40.436502,4.268332,24.618706,166.343463,63.556982
2,Qwen/Qwen3-8B,gptq,3-bit,Tamil,42.012760,2.919523,22.620578,144.263196,62.475377
9,Qwen/Qwen3-8B,gptq,3-bit,Tamil,42.729569,2.937405,23.351523,141.058965,65.202294
10,Qwen/Qwen3-8B,gptq,3-bit,Tamil,43.151184,2.916437,23.161336,140.340460,64.788691
1,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,42.385494,3.915570,19.171946,143.357820,62.972576
7,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,43.250695,3.672597,18.982422,133.669715,62.093137
8,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,43.147129,3.778896,19.069444,132.905051,63.068583
3,Qwen/Qwen3-8B,gptq,3-bit,Swahili,44.786866,3.771811,22.734896,79.985090,66.249266
11,Qwen/Qwen3-8B,gptq,3-bit,Swahili,42.717366,3.676404,21.716492,77.506947,64.011188
12,Qwen/Qwen3-8B,gptq,3-bit,Swahili,44.940711,3.725982,22.273758,79.844660,65.004796
4,Qwen/Qwen3-8B,gptq,3-bit,Chinese,40.865351,4.132577,24.873793,151.040822,56.098754
13,Qwen/Qwen3-8B,gptq,3-bit,Chinese,41.267661,4.332161,24.900326,178.141356,56.762463
14,Qwen/Qwen3-8B,gptq,3-bit,Chinese,40.662271,4.109008,24.741668,156.282612,55.063003
0,Qwen/Qwen3-8B,slimllm,3-bit,English,37.996881,5.016177,26.602903,168.990251,62.766314
5,Qwen/Qwen3-8B,slimllm,3-bit,English,37.998784,5.006315,26.158109,167.302009,64.763401
6,Qwen/Qwen3-8B,slimllm,3-bit,English,38.569713,4.824668,26.094763,156.663898,66.608623
2,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,44.634059,2.900774,23.035248,135.082451,62.115039
9,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,47.864063,2.908678,24.164053,148.063340,64.064579
10,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,45.744729,2.912922,24.153516,153.229178,64.256978
1,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,40.979761,3.987145,18.939585,135.638807,63.992288
7,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,42.648606,3.982393,18.998192,135.061858,65.711417
8,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,41.908018,4.059630,19.014005,142.466939,64.754799
3,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,45.255367,4.003747,22.944876,74.916424,68.855317
11,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,43.240062,3.958805,22.119773,74.219013,69.179620
12,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,44.855199,3.953273,22.687072,73.187326,67.086059
4,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,44.252408,4.236144,26.923226,168.427617,54.448928
13,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,45.122009,4.719561,29.264508,188.082925,56.398916
14,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,42.562075,4.407932,27.065704,182.361335,55.811099
0,Qwen/Qwen3-8B,tacq,3-bit,English,34.710002,3.851373,21.065718,117.199228,53.504737
5,Qwen/Qwen3-8B,tacq,3-bit,English,35.069878,3.771026,21.311044,115.479045,53.388031
6,Qwen/Qwen3-8B,tacq,3-bit,English,34.810374,3.764617,21.243588,121.969836,52.769961
2,Qwen/Qwen3-8B,tacq,3-bit,Tamil,38.876412,2.786321,19.325887,106.376712,54.060936
9,Qwen/Qwen3-8B,tacq,3-bit,Tamil,36.997150,2.796624,19.635890,104.581084,53.732649
10,Qwen/Qwen3-8B,tacq,3-bit,Tamil,37.563208,2.791408,19.625883,103.342648,54.562860
1,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,36.946025,3.450643,17.499579,102.484387,54.492987
7,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,36.064564,3.455403,17.407666,110.818460,52.491162
8,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,37.156511,3.426878,17.452419,98.432025,53.919998
3,Qwen/Qwen3-8B,tacq,3-bit,Swahili,37.239785,3.283538,19.188073,66.064982,53.378040
11,Qwen/Qwen3-8B,tacq,3-bit,Swahili,37.234178,3.334953,19.223837,65.375300,54.450253
12,Qwen/Qwen3-8B,tacq,3-bit,Swahili,37.239153,3.337267,19.129131,66.556862,53.816706
4,Qwen/Qwen3-8B,tacq,3-bit,Chinese,36.939861,3.656487,21.255791,117.447664,48.256635
13,Qwen/Qwen3-8B,tacq,3-bit,Chinese,36.811469,3.561307,21.206081,112.252142,47.935979
14,Qwen/Qwen3-8B,tacq,3-bit,Chinese,36.083784,3.604412,20.891435,116.602262,47.850495

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
1,Qwen/Qwen3-8B,tacq,English,3-bit,0.151631,0.039473,0.103480,2.745665,0.322409
4,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.787157,0.004207,0.143836,1.245594,0.341394
2,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.473008,0.012477,0.037528,5.156465,0.841770
3,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.002507,0.024800,0.039048,0.484618,0.440133
0,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.376958,0.038915,0.161324,2.276247,0.174826

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
1,Qwen/Qwen3-8B,gptq,English,3-bit,1.607722,0.631171,1.395688,2.210527,1.804371
4,Qwen/Qwen3-8B,gptq,Tamil,3-bit,1.629727,0.466045,1.362567,2.151944,1.807234
2,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,1.632738,0.578527,1.280456,2.135591,1.797347
3,Qwen/Qwen3-8B,gptq,Swahili,3-bit,1.644914,0.571095,1.347168,1.898244,1.813504
0,Qwen/Qwen3-8B,gptq,Chinese,3-bit,1.612060,0.622343,1.395127,2.209036,1.747992

           GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3  1.607722  1.629727  1.632738  1.644914  1.612060
TA_Qwen3  0.631171  0.466045  0.578527  0.571095  0.622343
ID_Qwen3  1.395688  1.362567  1.280456  1.347168  1.395127
SW_Qwen3  2.210527  2.151944  2.135591  1.898244  2.209036
ZH_Qwen3  1.804371  1.807234  1.797347  1.813504  1.747992

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Qwen3,46.980806,63.733939,64.155454,62.711432,65.088417,55.974740,64.712779,63.478865,64.819501,68.373666,55.552981,53.220909,54.118815,53.634716,53.881667,48.014369
SW_Qwen3,64.534645,162.378025,141.887540,136.644195,79.112232,161.821596,164.318719,145.458323,137.722535,74.107588,179.623959,118.216036,104.766815,103.911624,65.999048,115.434023
ID_Qwen3,16.699008,24.870707,23.044479,19.074604,22.241715,24.838596,26.285258,23.784272,18.983927,22.583907,27.751146,21.206783,19.529220,17.453221,19.180347,21.117769
TA_Qwen3,2.741605,4.277311,2.924455,3.789021,3.724733,4.191249,4.949053,2.907458,4.009722,3.971942,4.454546,3.795672,2.791451,3.444308,3.318586,3.607402
EN_Qwen3,33.428698,40.524927,42.631171,42.927773,44.148314,40.931761,38.188459,46.080950,41.845462,44.450209,43.978831,34.863418,37.812257,36.722366,37.237706,36.611705

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Qwen3,NaN,0.762469,1.199933,0.438954,0.915603,0.699321,1.569024,0.967564,0.703321,0.920051,0.816734,0.322409,0.341394,0.841770,0.440133,0.174826
SW_Qwen3,NaN,2.804047,1.705260,4.757503,1.136555,11.736552,5.456480,7.633938,3.363059,0.710285,8.254401,2.745665,1.245594,5.156465,0.484618,2.276247
ID_Qwen3,NaN,0.592639,0.309636,0.077459,0.416378,0.069389,0.226093,0.529658,0.032012,0.344655,1.071688,0.103480,0.143836,0.037528,0.039048,0.161324
TA_Qwen3,NaN,0.039836,0.009243,0.099452,0.038960,0.100104,0.088046,0.005034,0.035343,0.022603,0.200087,0.039473,0.004207,0.012477,0.024800,0.038915
EN_Qwen3,NaN,0.317008,0.469939,0.385773,1.013781,0.251571,0.269588,1.339904,0.682738,0.871159,1.062842,0.151631,0.787157,0.473008,0.002507,0.376958

## Shape
df text: (5, 16)
df std: (5, 16)
Display df

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Qwen3,46.980806,63.733939,64.155454,62.711432,65.088417,55.974740,64.712779,63.478865,64.819501,68.373666,55.552981,53.220909,54.118815,53.634716,53.881667,48.014369
SW_Qwen3,64.534645,162.378025,141.887540,136.644195,79.112232,161.821596,164.318719,145.458323,137.722535,74.107588,179.623959,118.216036,104.766815,103.911624,65.999048,115.434023
ID_Qwen3,16.699008,24.870707,23.044479,19.074604,22.241715,24.838596,26.285258,23.784272,18.983927,22.583907,27.751146,21.206783,19.529220,17.453221,19.180347,21.117769
TA_Qwen3,2.741605,4.277311,2.924455,3.789021,3.724733,4.191249,4.949053,2.907458,4.009722,3.971942,4.454546,3.795672,2.791451,3.444308,3.318586,3.607402
EN_Qwen3,33.428698,40.524927,42.631171,42.927773,44.148314,40.931761,38.188459,46.080950,41.845462,44.450209,43.978831,34.863418,37.812257,36.722366,37.237706,36.611705

Display df std

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Qwen3,,0.76,1.20,0.44,0.92,0.70,1.57,0.97,0.70,0.92,0.82,0.32,0.34,0.84,0.44,0.17
SW_Qwen3,,2.80,1.71,4.76,1.14,11.74,5.46,7.63,3.36,0.71,8.25,2.75,1.25,5.16,0.48,2.28
ID_Qwen3,,0.59,0.31,0.08,0.42,0.07,0.23,0.53,0.03,0.34,1.07,0.10,0.14,0.04,0.04,0.16
TA_Qwen3,,0.04,0.01,0.10,0.04,0.10,0.09,0.01,0.04,0.02,0.20,0.04,0.00,0.01,0.02,0.04
EN_Qwen3,,0.32,0.47,0.39,1.01,0.25,0.27,1.34,0.68,0.87,1.06,0.15,0.79,0.47,0.00,0.38

Writing to pdf ...

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"config.bit_width": f"{bit_width}-bit"},
                            {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                            {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            {"$not": {"$and": [{"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}, {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}]}},
                            # {"$not": {"$and": [{"config.quantization_technique": "gptq"}, {"config.calibration_language": "Swahili"}]}}
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                              # {"config.base_model": base_model},
                            {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                          ]}
                      ]}
                  )

  eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
  # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
  # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
  # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
  # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
  # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

  # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
  perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, write_pdf="ablation_floresplus_2bit_vert.pdf")

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
0,Qwen/Qwen3-8B,gptq,2-bit,English,13062.876244,48256.105485,39854.463930,38231.523295,34286.236528
10,Qwen/Qwen3-8B,gptq,2-bit,English,12451.018302,40756.553633,38410.667460,41726.485947,39319.365601
11,Qwen/Qwen3-8B,gptq,2-bit,English,12969.810741,48809.762083,39445.203775,41236.898022,44868.795841
...,...,...,...,...,...,...,...,...,...
26,CohereLabs/aya-expanse-8b,tacq,2-bit,Swahili,98.850604,10.082932,203.732166,333.068629,407.265983
27,CohereLabs/aya-expanse-8b,tacq,2-bit,Swahili,95.199483,10.107628,198.644097,320.552778,400.672744
9,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,87.566569,11.085941,287.207312,2165.595526,136.307643
28,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,86.254922,12.776039,322.690826,2640.984867,135.847607
29,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,83.905569,13.401760,283.077977,1899.481784,135.358869

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
6,Qwen/Qwen3-8B,tacq,English,2-bit,0.323566,0.665306,3.515737,10.556345,3.317178
9,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.461728,0.010456,14.028029,144.154089,2.312004
7,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.534628,0.818386,0.167729,23.810479,4.750264
8,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.458314,0.499177,0.602931,1.532377,10.103402
5,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.907797,1.544423,5.781454,15.010444,0.752618
1,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.218186,1.433973,4.411970,233.931693,12.841869
4,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,1.176844,0.012800,9.131215,52.022620,5.145499
2,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.472105,0.360203,2.482059,161.906780,15.790946
3,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,1.532074,0.192958,2.532162,8.991836,4.074086
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,1.514478,0.978149,17.780479,306.709847,0.387395

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
6,Qwen/Qwen3-8B,gptq,English,2-bit,4.108156,4.662199,4.593693,4.606363,4.596503
9,Qwen/Qwen3-8B,gptq,Tamil,2-bit,4.642051,0.873260,4.664672,4.670482,4.531575
7,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,4.544935,4.508749,3.226292,4.541529,4.624799
8,Qwen/Qwen3-8B,gptq,Swahili,2-bit,4.643958,4.572244,4.622783,3.166420,4.405375
5,Qwen/Qwen3-8B,gptq,Chinese,2-bit,4.489204,4.365599,4.580982,4.616916,4.249957

           GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3  4.108156  4.642051  4.544935  4.643958  4.489204
TA_Qwen3  4.662199  0.873260  4.508749  4.572244  4.365599
ID_Qwen3  4.593693  4.664672  3.226292  4.622783  4.580982
SW_Qwen3  4.606363  4.670482  4.541529  3.166420  4.616916
ZH_Qwen3  4.596503  4.531575  4.624799  4.405375  4.249957

start model: CohereLabs/aya-expanse-8b

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
1,CohereLabs/aya-expanse-8b,gptq,English,2-bit,2.383521,4.348801,3.784685,4.346861,4.282580
4,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,2.872552,0.808635,3.811151,4.341208,3.967499
2,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,2.718155,3.623270,2.737043,4.152934,3.997845
3,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,2.916441,3.176520,3.635588,3.201836,4.169309
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,3.002846,3.626023,3.789999,4.319220,3.012777

         GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Aya  2.383521  2.872552  2.718155  2.916441  3.002846
TA_Aya  4.348801  0.808635  3.623270  3.176520  3.626023
ID_Aya  3.784685  3.811151  2.737043  3.635588  3.789999
SW_Aya  4.346861  4.341208  4.152934  3.201836  4.319220
ZH_Aya  4.282580  3.967499  3.997845  4.169309  3.012777

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Aya,112.084228,19168.145370,9278.960985,9950.510277,14767.553330,1029.857317,7.409755e+06,NaN,1.631137e+06,1.004871e+06,274.084188,360.637008,275.617452,292.760948,406.131890,135.838040
SW_Aya,347.245294,22225.967596,21938.558958,14221.136656,1591.607966,20855.464249,9.978332e+03,NaN,5.561333e+03,4.189173e+02,50822.574116,1588.158444,1544.971890,1344.702942,332.042594,2235.354059
ID_Aya,92.363250,6090.955316,6473.671674,545.811702,4321.037729,6165.939366,4.766603e+04,NaN,2.328256e+02,1.044489e+03,484718.872812,306.205275,225.322198,117.137641,202.212119,297.658705
TA_Aya,3.798334,22325.499442,6.436282,4200.197925,1501.481445,4226.914393,4.110211e+05,NaN,4.490107e+05,6.071352e+05,290134.141033,14.739504,4.049754,12.200776,10.231536,12.421246
EN_Aya,53.754913,241.836277,745.679240,522.582423,824.976137,1006.574886,1.366964e+02,NaN,2.688014e+02,3.345557e+02,4622.001841,69.141747,93.205527,80.995250,97.275513,85.909020
ZH_Qwen3,46.980806,39491.465990,34007.536689,42150.094142,25431.655621,17781.024879,6.674189e+05,60166.327417,4.113642e+05,6.278313e+05,360.020385,146.704354,119.462250,122.105214,176.318815,63.072371
SW_Qwen3,64.534645,40398.302421,46825.504463,34796.007236,1466.964319,41391.915611,6.726278e+03,6525.812005,2.713585e+03,5.398065e+02,19233.229068,380.075948,433.095598,258.430765,69.236501,372.747064
ID_Qwen3,16.699008,39236.778388,46203.199536,1683.806307,41954.948059,38104.965297,2.493904e+03,11464.605865,1.232482e+02,7.012918e+02,18727.617100,116.218561,72.677371,21.817674,43.733264,127.139610
TA_Qwen3,2.741605,45940.807067,7.468949,32266.297200,37346.013068,23205.924496,1.476803e+04,4.442923,1.200714e+04,6.139446e+03,25621.911270,15.513642,3.063271,9.956398,9.944748,13.166703
EN_Qwen3,33.428698,12827.901762,43858.254034,35069.944932,44051.236215,30846.394995,1.515746e+02,6890.433754,1.077302e+03,2.003619e+03,5742.270277,43.983318,64.369847,52.554869,65.558487,59.187938

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Aya,NaN,1543.522189,1302.353438,866.080047,1180.853398,18.945158,1.202363e+06,NaN,416931.507561,648186.966924,13.882118,12.841869,5.145499,15.790946,4.074086,0.387395
SW_Aya,NaN,1277.195624,2050.239999,1152.198626,33.017260,2340.085532,2.119860e+03,NaN,1141.379148,37.523671,26373.980905,233.931693,52.022620,161.906780,8.991836,306.709847
ID_Aya,NaN,785.551907,453.403569,36.465574,597.968991,748.488685,1.619160e+04,NaN,10.858010,407.497337,46527.414954,4.411970,9.131215,2.482059,2.532162,17.780479
TA_Aya,NaN,6727.004278,0.242481,1013.398744,576.594778,1135.284190,2.832218e+05,NaN,322783.452104,828733.377281,268700.417046,1.433973,0.012800,0.360203,0.192958,0.978149
EN_Aya,NaN,6.347335,60.775949,25.456456,80.773855,75.660850,8.647104e+00,NaN,22.655564,117.247604,3534.650256,0.218186,1.176844,0.472105,1.532074,1.514478
ZH_Qwen3,NaN,4322.025321,12652.174248,1814.625584,214.562658,1521.218809,2.613922e+05,23070.095350,136201.928434,562039.370899,44.890879,3.317178,2.312004,4.750264,10.103402,0.752618
SW_Qwen3,NaN,1545.126299,41.811051,3225.378802,119.318857,6205.821677,9.155808e+02,1344.498076,1229.939922,152.852881,6050.793892,10.556345,144.154089,23.810479,1.532377,15.010444
ID_Qwen3,NaN,607.573270,5893.246746,463.524607,2132.436617,4590.185765,4.345302e+02,2181.571725,64.114112,63.687162,5190.682069,3.515737,14.028029,0.167729,0.602931,5.781454
TA_Qwen3,NaN,3672.782474,0.417630,3505.411760,1535.747660,1813.483650,9.351708e+03,0.104889,11122.033868,4051.681957,16018.499530,0.665306,0.010456,0.818386,0.499177,1.544423
EN_Qwen3,NaN,269.191572,3137.501577,1463.765358,1602.262531,492.546412,1.519971e+01,2585.158544,570.476116,812.771505,2266.421583,0.323566,0.461728,0.534628,0.458314,0.907797

## Shape
df text: (10, 16)
df std: (10, 16)
Display df

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Aya,112.084228,19168.145370,9278.960985,9950.510277,14767.553330,1029.857317,7.409755e+06,NaN,1.631137e+06,1.004871e+06,274.084188,360.637008,275.617452,292.760948,406.131890,135.838040
SW_Aya,347.245294,22225.967596,21938.558958,14221.136656,1591.607966,20855.464249,9.978332e+03,NaN,5.561333e+03,4.189173e+02,50822.574116,1588.158444,1544.971890,1344.702942,332.042594,2235.354059
ID_Aya,92.363250,6090.955316,6473.671674,545.811702,4321.037729,6165.939366,4.766603e+04,NaN,2.328256e+02,1.044489e+03,484718.872812,306.205275,225.322198,117.137641,202.212119,297.658705
TA_Aya,3.798334,22325.499442,6.436282,4200.197925,1501.481445,4226.914393,4.110211e+05,NaN,4.490107e+05,6.071352e+05,290134.141033,14.739504,4.049754,12.200776,10.231536,12.421246
EN_Aya,53.754913,241.836277,745.679240,522.582423,824.976137,1006.574886,1.366964e+02,NaN,2.688014e+02,3.345557e+02,4622.001841,69.141747,93.205527,80.995250,97.275513,85.909020
ZH_Qwen3,46.980806,39491.465990,34007.536689,42150.094142,25431.655621,17781.024879,6.674189e+05,60166.327417,4.113642e+05,6.278313e+05,360.020385,146.704354,119.462250,122.105214,176.318815,63.072371
SW_Qwen3,64.534645,40398.302421,46825.504463,34796.007236,1466.964319,41391.915611,6.726278e+03,6525.812005,2.713585e+03,5.398065e+02,19233.229068,380.075948,433.095598,258.430765,69.236501,372.747064
ID_Qwen3,16.699008,39236.778388,46203.199536,1683.806307,41954.948059,38104.965297,2.493904e+03,11464.605865,1.232482e+02,7.012918e+02,18727.617100,116.218561,72.677371,21.817674,43.733264,127.139610
TA_Qwen3,2.741605,45940.807067,7.468949,32266.297200,37346.013068,23205.924496,1.476803e+04,4.442923,1.200714e+04,6.139446e+03,25621.911270,15.513642,3.063271,9.956398,9.944748,13.166703
EN_Qwen3,33.428698,12827.901762,43858.254034,35069.944932,44051.236215,30846.394995,1.515746e+02,6890.433754,1.077302e+03,2.003619e+03,5742.270277,43.983318,64.369847,52.554869,65.558487,59.187938

Display df std

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Aya,,1.5e+3,1.3e+3,866.1,1.2e+3,18.95,1.2e+6,,4.2e+5,6.5e+5,13.88,12.84,5.15,15.79,4.07,0.39
SW_Aya,,1.3e+3,2.1e+3,1.2e+3,33.02,2.3e+3,2.1e+3,,1.1e+3,37.52,2.6e+4,233.9,52.02,161.9,8.99,306.7
ID_Aya,,785.6,453.4,36.47,598.0,748.5,1.6e+4,,10.86,407.5,4.7e+4,4.41,9.13,2.48,2.53,17.78
TA_Aya,,6.7e+3,0.24,1.0e+3,576.6,1.1e+3,2.8e+5,,3.2e+5,8.3e+5,2.7e+5,1.43,0.01,0.36,0.19,0.98
EN_Aya,,6.35,60.78,25.46,80.77,75.66,8.65,,22.66,117.2,3.5e+3,0.22,1.18,0.47,1.53,1.51
ZH_Qwen3,,4.3e+3,1.3e+4,1.8e+3,214.6,1.5e+3,2.6e+5,2.3e+4,1.4e+5,5.6e+5,44.89,3.32,2.31,4.75,10.10,0.75
SW_Qwen3,,1.5e+3,41.81,3.2e+3,119.3,6.2e+3,915.6,1.3e+3,1.2e+3,152.9,6.1e+3,10.56,144.2,23.81,1.53,15.01
ID_Qwen3,,607.6,5.9e+3,463.5,2.1e+3,4.6e+3,434.5,2.2e+3,64.11,63.69,5.2e+3,3.52,14.03,0.17,0.60,5.78
TA_Qwen3,,3.7e+3,0.42,3.5e+3,1.5e+3,1.8e+3,9.4e+3,0.10,1.1e+4,4.1e+3,1.6e+4,0.67,0.01,0.82,0.50,1.54
EN_Qwen3,,269.2,3.1e+3,1.5e+3,1.6e+3,492.5,15.20,2.6e+3,570.5,812.8,2.3e+3,0.32,0.46,0.53,0.46,0.91

Writing to pdf ...

##### All data

In [5]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [4]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"config.bit_width": f"{bit_width}-bit"},
                            {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            {"$not": {"$and": [{"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}, {"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}]}}
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                              # {"config.base_model": base_model},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                          ]}
                      ]}
                  )

  eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
  # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
  # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
  # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
  # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
  # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

  # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
  perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, write_pdf="ablation_floresplus_4bit_all_vert_final.pdf")

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
0,Qwen/Qwen3-8B,gptq,4-bit,English,38.633773,2.903144,18.795383,81.519027,54.471988
2,Qwen/Qwen3-8B,gptq,4-bit,Tamil,36.874922,2.789352,18.045387,80.639509,52.047636
1,Qwen/Qwen3-8B,gptq,4-bit,Indonesian,36.307482,2.869462,17.537566,75.503067,52.100443
3,Qwen/Qwen3-8B,gptq,4-bit,Swahili,36.782606,2.862192,18.727565,71.522493,52.984904
4,Qwen/Qwen3-8B,gptq,4-bit,Chinese,36.791005,2.921814,17.943838,78.501095,52.133661
5,CohereLabs/aya-expanse-8b,gptq,4-bit,English,50.815876,3.947913,89.978133,401.770728,113.312037
7,CohereLabs/aya-expanse-8b,gptq,4-bit,Tamil,51.355844,3.796851,90.784244,373.873691,112.280232
6,CohereLabs/aya-expanse-8b,gptq,4-bit,Indonesian,52.137953,3.977342,90.535852,365.351107,113.168497
8,CohereLabs/aya-expanse-8b,gptq,4-bit,Swahili,50.556806,3.900542,89.279740,352.421007,112.105412
9,CohereLabs/aya-expanse-8b,gptq,4-bit,Chinese,52.413353,3.929984,92.005672,381.202734,113.046247
10,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,English,47.372066,2.503244,27.111507,35.268858,40.062125
12,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Tamil,46.727688,2.341632,27.035368,34.343137,39.947466
11,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Indonesian,46.340421,2.454821,25.609484,33.018261,40.115798
13,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Swahili,46.679481,2.453562,26.443130,31.212913,40.419192
14,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Chinese,46.697379,2.436780,27.025912,34.342650,38.331823
0,Qwen/Qwen3-8B,slimllm,4-bit,English,34.260498,2.958074,17.888351,79.743173,49.544540
2,Qwen/Qwen3-8B,slimllm,4-bit,Tamil,36.234922,2.776822,18.097900,78.928706,50.708137
1,Qwen/Qwen3-8B,slimllm,4-bit,Indonesian,34.633644,2.891498,17.211146,77.379406,49.841062
3,Qwen/Qwen3-8B,slimllm,4-bit,Swahili,34.731503,2.901018,17.629107,63.984313,49.638112
4,Qwen/Qwen3-8B,slimllm,4-bit,Chinese,35.165068,2.918109,18.043827,78.800577,47.496192
5,CohereLabs/aya-expanse-8b,slimllm,4-bit,English,54.706773,4.021575,98.354503,397.648200,124.485867
6,CohereLabs/aya-expanse-8b,slimllm,4-bit,Indonesian,55.686326,3.975950,93.870980,372.462067,122.105721
7,CohereLabs/aya-expanse-8b,slimllm,4-bit,Swahili,55.946115,3.920454,97.055222,337.157383,123.359929
8,CohereLabs/aya-expanse-8b,slimllm,4-bit,Chinese,55.432520,3.954161,98.401795,412.249550,117.615823
9,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,English,43.532462,2.695015,28.568594,36.902012,41.523714
10,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Indonesian,44.632579,2.735899,26.986952,37.360703,44.224801
11,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Swahili,45.423450,2.699435,28.200670,32.886215,46.296442
12,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Chinese,44.928034,2.555277,27.777874,35.678429,38.107827
0,Qwen/Qwen3-8B,tacq,4-bit,English,34.147866,2.870331,17.424552,74.335601,48.763523
2,Qwen/Qwen3-8B,tacq,4-bit,Tamil,34.711885,2.758863,17.336806,73.351131,48.556783
1,Qwen/Qwen3-8B,tacq,4-bit,Indonesian,35.199599,2.878214,16.914091,73.971753,48.985351
3,Qwen/Qwen3-8B,tacq,4-bit,Swahili,34.439505,2.856956,17.086451,64.984794,48.547595
4,Qwen/Qwen3-8B,tacq,4-bit,Chinese,34.218867,2.906739,17.528538,73.939017,47.282614
5,CohereLabs/aya-expanse-8b,tacq,4-bit,English,55.022220,3.980362,96.781066,388.558360,120.301677
7,CohereLabs/aya-expanse-8b,tacq,4-bit,Tamil,55.689060,3.848132,97.586160,389.291678,120.618816
6,CohereLabs/aya-expanse-8b,tacq,4-bit,Indonesian,55.559975,3.942369,95.089391,381.536862,119.716704
8,CohereLabs/aya-expanse-8b,tacq,4-bit,Swahili,55.820594,3.988709,97.101196,364.872794,121.515856
9,CohereLabs/aya-expanse-8b,tacq,4-bit,Chinese,55.483941,3.928528,96.739712,411.201310,116.573491
10,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,English,45.535295,2.503889,27.187312,34.456392,40.119780
12,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Tamil,46.511978,2.345541,27.168395,33.305476,39.193255
11,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Indonesian,46.849139,2.457776,25.944766,32.882074,40.222063
13,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Swahili,46.166003,2.460396,26.501118,30.807823,39.940935
14,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Chinese,45.672605,2.424910,27.072293,33.288619,37.424322

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
6,Qwen/Qwen3-8B,tacq,English,4-bit,0.0,0.0,0.0,0.0,0.0
9,Qwen/Qwen3-8B,tacq,Tamil,4-bit,0.0,0.0,0.0,0.0,0.0
7,Qwen/Qwen3-8B,tacq,Indonesian,4-bit,0.0,0.0,0.0,0.0,0.0
8,Qwen/Qwen3-8B,tacq,Swahili,4-bit,0.0,0.0,0.0,0.0,0.0
5,Qwen/Qwen3-8B,tacq,Chinese,4-bit,0.0,0.0,0.0,0.0,0.0
1,CohereLabs/aya-expanse-8b,tacq,English,4-bit,0.0,0.0,0.0,0.0,0.0
4,CohereLabs/aya-expanse-8b,tacq,Tamil,4-bit,0.0,0.0,0.0,0.0,0.0
2,CohereLabs/aya-expanse-8b,tacq,Indonesian,4-bit,0.0,0.0,0.0,0.0,0.0
3,CohereLabs/aya-expanse-8b,tacq,Swahili,4-bit,0.0,0.0,0.0,0.0,0.0
0,CohereLabs/aya-expanse-8b,tacq,Chinese,4-bit,0.0,0.0,0.0,0.0,0.0
11,meta-llama/Llama-3.1-8B-Instruct,tacq,English,4-bit,0.0,0.0,0.0,0.0,0.0
14,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,4-bit,0.0,0.0,0.0,0.0,0.0
12,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,4-bit,0.0,0.0,0.0,0.0,0.0
13,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,4-bit,0.0,0.0,0.0,0.0,0.0
10,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,4-bit,0.0,0.0,0.0,0.0,0.0

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
6,Qwen/Qwen3-8B,gptq,English,4-bit,1.586967,0.462869,1.274051,1.911259,1.736173
9,Qwen/Qwen3-8B,gptq,Tamil,4-bit,1.566731,0.445503,1.256366,1.906548,1.716401
7,Qwen/Qwen3-8B,gptq,Indonesian,4-bit,1.559996,0.457800,1.243969,1.877965,1.716841
8,Qwen/Qwen3-8B,gptq,Swahili,4-bit,1.565642,0.456699,1.272481,1.854443,1.724152
5,Qwen/Qwen3-8B,gptq,Chinese,4-bit,1.565742,0.465653,1.253915,1.894876,1.717118

           GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3  1.586967  1.566731  1.559996  1.565642  1.565742
TA_Qwen3  0.462869  0.445503  0.457800  0.456699  0.465653
ID_Qwen3  1.274051  1.256366  1.243969  1.272481  1.253915
SW_Qwen3  1.911259  1.906548  1.877965  1.854443  1.894876
ZH_Qwen3  1.736173  1.716401  1.716841  1.724152  1.717118

start model: CohereLabs/aya-expanse-8b

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
1,CohereLabs/aya-expanse-8b,gptq,English,4-bit,1.705999,0.596368,1.954137,2.603978,2.054276
4,CohereLabs/aya-expanse-8b,gptq,Tamil,4-bit,1.710590,0.579424,1.958010,2.572725,2.050303
2,CohereLabs/aya-expanse-8b,gptq,Indonesian,4-bit,1.717154,0.599593,1.956821,2.562710,2.053726
3,CohereLabs/aya-expanse-8b,gptq,Swahili,4-bit,1.703780,0.591125,1.950753,2.547062,2.049627
0,CohereLabs/aya-expanse-8b,gptq,Chinese,4-bit,1.719442,0.594391,1.963815,2.581156,2.053256

         GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Aya  1.705999  1.710590  1.717154  1.703780  1.719442
TA_Aya  0.596368  0.579424  0.599593  0.591125  0.594391
ID_Aya  1.954137  1.958010  1.956821  1.950753  1.963815
SW_Aya  2.603978  2.572725  2.562710  2.547062  2.581156
ZH_Aya  2.054276  2.050303  2.053726  2.049627  2.053256

start model: meta-llama/Llama-3.1-8B-Instruct

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
11,meta-llama/Llama-3.1-8B-Instruct,gptq,English,4-bit,1.675522,0.398503,1.433154,1.547391,1.602734
14,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,4-bit,1.669574,0.369519,1.431932,1.535840,1.601489
12,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,4-bit,1.665960,0.390020,1.408401,1.518754,1.603315
13,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,4-bit,1.669126,0.389797,1.422313,1.494334,1.606588
10,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,4-bit,1.669293,0.386816,1.431780,1.535834,1.583559

           GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Llama  1.675522  1.669574  1.665960  1.669126  1.669293
TA_Llama  0.398503  0.369519  0.390020  0.389797  0.386816
ID_Llama  1.433154  1.431932  1.408401  1.422313  1.431780
SW_Llama  1.547391  1.535840  1.518754  1.494334  1.535834
ZH_Llama  1.602734  1.601489  1.603315  1.606588  1.583559

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,40.062125,39.947466,40.115798,40.419192,38.331823,41.523714,NaN,44.224801,46.296442,38.107827,40.119780,39.193255,40.222063,39.940935,37.424322
SW_Llama,30.056285,35.268858,34.343137,33.018261,31.212913,34.342650,36.902012,NaN,37.360703,32.886215,35.678429,34.456392,33.305476,32.882074,30.807823,33.288619
ID_Llama,24.823783,27.111507,27.035368,25.609484,26.443130,27.025912,28.568594,NaN,26.986952,28.200670,27.777874,27.187312,27.168395,25.944766,26.501118,27.072293
TA_Llama,2.311781,2.503244,2.341632,2.454821,2.453562,2.436780,2.695015,NaN,2.735899,2.699435,2.555277,2.503889,2.345541,2.457776,2.460396,2.424910
EN_Llama,45.105214,47.372066,46.727688,46.340421,46.679481,46.697379,43.532462,NaN,44.632579,45.423450,44.928034,45.535295,46.511978,46.849139,46.166003,45.672605
ZH_Aya,112.084228,113.312037,112.280232,113.168497,112.105412,113.046247,124.485867,NaN,122.105721,123.359929,117.615823,120.301677,120.618816,119.716704,121.515856,116.573491
SW_Aya,347.245294,401.770728,373.873691,365.351107,352.421007,381.202734,397.648200,NaN,372.462067,337.157383,412.249550,388.558360,389.291678,381.536862,364.872794,411.201310
ID_Aya,92.363250,89.978133,90.784244,90.535852,89.279740,92.005672,98.354503,NaN,93.870980,97.055222,98.401795,96.781066,97.586160,95.089391,97.101196,96.739712
TA_Aya,3.798334,3.947913,3.796851,3.977342,3.900542,3.929984,4.021575,NaN,3.975950,3.920454,3.954161,3.980362,3.848132,3.942369,3.988709,3.928528
EN_Aya,53.754913,50.815876,51.355844,52.137953,50.556806,52.413353,54.706773,NaN,55.686326,55.946115,55.432520,55.022220,55.689060,55.559975,55.820594,55.483941
ZH_Qwen3,46.980806,54.471988,52.047636,52.100443,52.984904,52.133661,49.544540,50.708137,49.841062,49.638112,47.496192,48.763523,48.556783,48.985351,48.547595,47.282614
SW_Qwen3,64.534645,81.519027,80.639509,75.503067,71.522493,78.501095,79.743173,78.928706,77.379406,63.984313,78.800577,74.335601,73.351131,73.971753,64.984794,73.939017
ID_Qwen3,16.699008,18.795383,18.045387,17.537566,18.727565,17.943838,17.888351,18.097900,17.211146,17.629107,18.043827,17.424552,17.336806,16.914091,17.086451,17.528538
TA_Qwen3,2.741605,2.903144,2.789352,2.869462,2.862192,2.921814,2.958074,2.776822,2.891498,2.901018,2.918109,2.870331,2.758863,2.878214,2.856956,2.906739
EN_Qwen3,33.428698,38.633773,36.874922,36.307482,36.782606,36.791005,34.260498,36.234922,34.633644,34.731503,35.165068,34.147866,34.711885,35.199599,34.439505,34.218867

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SW_Llama,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ID_Llama,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TA_Llama,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EN_Llama,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZH_Aya,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SW_Aya,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ID_Aya,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TA_Aya,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EN_Aya,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZH_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SW_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ID_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TA_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EN_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Shape
df text: (15, 16)
df std: (15, 16)
Display df

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,40.062125,39.947466,40.115798,40.419192,38.331823,41.523714,NaN,44.224801,46.296442,38.107827,40.119780,39.193255,40.222063,39.940935,37.424322
SW_Llama,30.056285,35.268858,34.343137,33.018261,31.212913,34.342650,36.902012,NaN,37.360703,32.886215,35.678429,34.456392,33.305476,32.882074,30.807823,33.288619
ID_Llama,24.823783,27.111507,27.035368,25.609484,26.443130,27.025912,28.568594,NaN,26.986952,28.200670,27.777874,27.187312,27.168395,25.944766,26.501118,27.072293
TA_Llama,2.311781,2.503244,2.341632,2.454821,2.453562,2.436780,2.695015,NaN,2.735899,2.699435,2.555277,2.503889,2.345541,2.457776,2.460396,2.424910
EN_Llama,45.105214,47.372066,46.727688,46.340421,46.679481,46.697379,43.532462,NaN,44.632579,45.423450,44.928034,45.535295,46.511978,46.849139,46.166003,45.672605
ZH_Aya,112.084228,113.312037,112.280232,113.168497,112.105412,113.046247,124.485867,NaN,122.105721,123.359929,117.615823,120.301677,120.618816,119.716704,121.515856,116.573491
SW_Aya,347.245294,401.770728,373.873691,365.351107,352.421007,381.202734,397.648200,NaN,372.462067,337.157383,412.249550,388.558360,389.291678,381.536862,364.872794,411.201310
ID_Aya,92.363250,89.978133,90.784244,90.535852,89.279740,92.005672,98.354503,NaN,93.870980,97.055222,98.401795,96.781066,97.586160,95.089391,97.101196,96.739712
TA_Aya,3.798334,3.947913,3.796851,3.977342,3.900542,3.929984,4.021575,NaN,3.975950,3.920454,3.954161,3.980362,3.848132,3.942369,3.988709,3.928528
EN_Aya,53.754913,50.815876,51.355844,52.137953,50.556806,52.413353,54.706773,NaN,55.686326,55.946115,55.432520,55.022220,55.689060,55.559975,55.820594,55.483941
ZH_Qwen3,46.980806,54.471988,52.047636,52.100443,52.984904,52.133661,49.544540,50.708137,49.841062,49.638112,47.496192,48.763523,48.556783,48.985351,48.547595,47.282614
SW_Qwen3,64.534645,81.519027,80.639509,75.503067,71.522493,78.501095,79.743173,78.928706,77.379406,63.984313,78.800577,74.335601,73.351131,73.971753,64.984794,73.939017
ID_Qwen3,16.699008,18.795383,18.045387,17.537566,18.727565,17.943838,17.888351,18.097900,17.211146,17.629107,18.043827,17.424552,17.336806,16.914091,17.086451,17.528538
TA_Qwen3,2.741605,2.903144,2.789352,2.869462,2.862192,2.921814,2.958074,2.776822,2.891498,2.901018,2.918109,2.870331,2.758863,2.878214,2.856956,2.906739
EN_Qwen3,33.428698,38.633773,36.874922,36.307482,36.782606,36.791005,34.260498,36.234922,34.633644,34.731503,35.165068,34.147866,34.711885,35.199599,34.439505,34.218867

Display df std

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,,,,,,,,,,,,,,,,
SW_Llama,,,,,,,,,,,,,,,,
ID_Llama,,,,,,,,,,,,,,,,
TA_Llama,,,,,,,,,,,,,,,,
EN_Llama,,,,,,,,,,,,,,,,
ZH_Aya,,,,,,,,,,,,,,,,
SW_Aya,,,,,,,,,,,,,,,,
ID_Aya,,,,,,,,,,,,,,,,
TA_Aya,,,,,,,,,,,,,,,,
EN_Aya,,,,,,,,,,,,,,,,
ZH_Qwen3,,,,,,,,,,,,,,,,
SW_Qwen3,,,,,,,,,,,,,,,,
ID_Qwen3,,,,,,,,,,,,,,,,
TA_Qwen3,,,,,,,,,,,,,,,,
EN_Qwen3,,,,,,,,,,,,,,,,

Writing to pdf ...

In [6]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [3]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"config.bit_width": f"{bit_width}-bit"},
                            {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            # {"$not": {"$and": [{"config.quantization_technique": "gptq"}, {"config.calibration_language": "Swahili"}]}}
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                              # {"config.base_model": base_model},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                          ]}
                      ]}
                  )

  eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
  # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
  # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
  # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
  # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
  # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

  # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
  perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, write_pdf="ablation_floresplus_3bit_all_vert_final.pdf")

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
0,Qwen/Qwen3-8B,gptq,3-bit,English,40.188512,4.329966,24.304464,160.417519,62.901249
15,Qwen/Qwen3-8B,gptq,3-bit,English,40.949766,4.233635,25.688953,160.373092,64.743586
...,...,...,...,...,...,...,...,...,...
10,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,English,48.270659,4.269030,39.772587,56.283017,57.113641
12,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Tamil,50.732388,2.430107,35.062178,46.878139,48.481814
11,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Indonesian,50.051469,3.463090,28.618159,43.463953,52.050964
13,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Swahili,51.241933,3.554056,34.721147,34.765476,56.756861
14,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Chinese,50.027819,3.123373,35.462255,50.868524,41.277322

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
6,Qwen/Qwen3-8B,tacq,English,3-bit,0.151631,0.039473,0.103480,2.745665,0.322409
9,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.787157,0.004207,0.143836,1.245594,0.341394
7,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.473008,0.012477,0.037528,5.156465,0.841770
8,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.002507,0.024800,0.039048,0.484618,0.440133
5,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.376958,0.038915,0.161324,2.276247,0.174826
1,CohereLabs/aya-expanse-8b,tacq,English,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
4,CohereLabs/aya-expanse-8b,tacq,Tamil,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
2,CohereLabs/aya-expanse-8b,tacq,Indonesian,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
3,CohereLabs/aya-expanse-8b,tacq,Swahili,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
0,CohereLabs/aya-expanse-8b,tacq,Chinese,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
11,meta-llama/Llama-3.1-8B-Instruct,tacq,English,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
14,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
12,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
13,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
10,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
6,Qwen/Qwen3-8B,gptq,English,3-bit,1.607722,0.631171,1.395688,2.210527,1.804371
9,Qwen/Qwen3-8B,gptq,Tamil,3-bit,1.629727,0.466045,1.362567,2.151944,1.807234
7,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,1.632738,0.578527,1.280456,2.135591,1.797347
8,Qwen/Qwen3-8B,gptq,Swahili,3-bit,1.644914,0.571095,1.347168,1.898244,1.813504
5,Qwen/Qwen3-8B,gptq,Chinese,3-bit,1.612060,0.622343,1.395127,2.209036,1.747992

           GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3  1.607722  1.629727  1.632738  1.644914  1.612060
TA_Qwen3  0.631171  0.466045  0.578527  0.571095  0.622343
ID_Qwen3  1.395688  1.362567  1.280456  1.347168  1.395127
SW_Qwen3  2.210527  2.151944  2.135591  1.898244  2.209036
ZH_Qwen3  1.804371  1.807234  1.797347  1.813504  1.747992

start model: CohereLabs/aya-expanse-8b

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
1,CohereLabs/aya-expanse-8b,gptq,English,3-bit,1.745987,0.739545,2.089555,2.846302,2.230725
4,CohereLabs/aya-expanse-8b,gptq,Tamil,3-bit,1.778123,0.595794,2.231180,2.937859,2.419087
2,CohereLabs/aya-expanse-8b,gptq,Indonesian,3-bit,1.765901,0.693843,2.004118,2.779111,2.180825
3,CohereLabs/aya-expanse-8b,gptq,Swahili,3-bit,1.754975,0.690446,2.039433,2.587162,2.186465
0,CohereLabs/aya-expanse-8b,gptq,Chinese,3-bit,1.751977,0.703135,2.034968,2.798352,2.093529

         GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Aya  1.745987  1.778123  1.765901  1.754975  1.751977
TA_Aya  0.739545  0.595794  0.693843  0.690446  0.703135
ID_Aya  2.089555  2.231180  2.004118  2.039433  2.034968
SW_Aya  2.846302  2.937859  2.779111  2.587162  2.798352
ZH_Aya  2.230725  2.419087  2.180825  2.186465  2.093529

start model: meta-llama/Llama-3.1-8B-Instruct

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
11,meta-llama/Llama-3.1-8B-Instruct,gptq,English,3-bit,1.732418,0.664582,1.690503,1.882521,1.818931
14,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,3-bit,1.755687,0.394067,1.631653,1.802044,1.760409
12,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,3-bit,1.753148,0.581291,1.506698,1.736565,1.793859
13,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,3-bit,1.740410,0.584530,1.584676,1.567509,1.796857
10,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,3-bit,1.749177,0.564655,1.657761,1.846888,1.656961

           GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Llama  1.732418  1.755687  1.753148  1.740410  1.749177
TA_Llama  0.664582  0.394067  0.581291  0.584530  0.564655
ID_Llama  1.690503  1.631653  1.506698  1.584676  1.657761
SW_Llama  1.882521  1.802044  1.736565  1.567509  1.846888
ZH_Llama  1.818931  1.760409  1.793859  1.796857  1.656961

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,65.906926,57.598253,62.209873,62.640825,45.390110,107.699684,896093.535485,68.901162,493.790219,44.496971,57.113641,48.481814,52.050964,56.756861,41.277322
SW_Llama,30.056285,76.299433,63.393429,54.521151,36.941053,70.289028,140.046129,82843.632618,64.677236,127.097711,79.511096,56.283017,46.878139,43.463953,34.765476,50.868524
ID_Llama,24.823783,49.034587,42.820579,32.114254,38.430521,45.473741,80.624982,147212.490658,33.437626,237.449086,52.094113,39.772587,35.062178,28.618159,34.721147,35.462255
TA_Llama,2.311781,4.619366,2.477804,3.813212,3.841755,3.669907,6.090120,349753.537060,4.954544,8.438959,3.885786,4.269030,2.430107,3.463090,3.554056,3.123373
EN_Llama,45.105214,54.002999,56.975352,56.643278,55.005956,56.127699,51.661761,20302.152824,52.608449,82.705680,55.081591,48.270659,50.732388,50.051469,51.241933,50.027819
ZH_Aya,112.084228,170.108220,262.474523,151.644070,153.626228,124.030659,153.807992,NaN,148.348093,152.570887,127.689433,132.582898,135.092829,132.251605,139.732992,119.321911
SW_Aya,347.245294,701.944022,866.680681,601.327532,386.510893,628.567549,694.409390,NaN,581.597703,372.344141,698.011042,488.415269,494.785107,505.833186,351.026762,561.057641
ID_Aya,92.363250,122.900772,170.286285,100.952621,109.504752,108.384593,128.241772,NaN,106.431040,117.153934,123.701714,104.218850,107.600928,96.903556,105.485363,106.001720
TA_Aya,3.798334,5.489648,3.942703,4.941318,4.902821,5.048185,5.190608,NaN,4.846758,4.707457,4.957356,4.598233,3.914037,4.432267,4.394636,4.441016
EN_Aya,53.754913,55.716955,59.996131,58.331153,56.882036,56.490654,70.334848,NaN,70.159288,71.447728,71.276244,56.603639,59.778306,57.988980,59.710328,58.374838
ZH_Qwen3,46.980806,63.733939,64.155454,62.711432,65.088417,55.974740,64.712779,63.478865,64.819501,68.373666,55.552981,53.220909,54.118815,53.634716,53.881667,48.014369
SW_Qwen3,64.534645,162.378025,141.887540,136.644195,79.112232,161.821596,164.318719,145.458323,137.722535,74.107588,179.623959,118.216036,104.766815,103.911624,65.999048,115.434023
ID_Qwen3,16.699008,24.870707,23.044479,19.074604,22.241715,24.838596,26.285258,23.784272,18.983927,22.583907,27.751146,21.206783,19.529220,17.453221,19.180347,21.117769
TA_Qwen3,2.741605,4.277311,2.924455,3.789021,3.724733,4.191249,4.949053,2.907458,4.009722,3.971942,4.454546,3.795672,2.791451,3.444308,3.318586,3.607402
EN_Qwen3,33.428698,40.524927,42.631171,42.927773,44.148314,40.931761,38.188459,46.080950,41.845462,44.450209,43.978831,34.863418,37.812257,36.722366,37.237706,36.611705

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
SW_Llama,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ID_Llama,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
TA_Llama,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
EN_Llama,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZH_Aya,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
SW_Aya,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ID_Aya,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
TA_Aya,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
EN_Aya,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZH_Qwen3,NaN,0.762469,1.199933,0.438954,0.915603,0.699321,1.569024,0.967564,0.703321,0.920051,0.816734,0.322409,0.341394,0.841770,0.440133,0.174826
SW_Qwen3,NaN,2.804047,1.705260,4.757503,1.136555,11.736552,5.456480,7.633938,3.363059,0.710285,8.254401,2.745665,1.245594,5.156465,0.484618,2.276247
ID_Qwen3,NaN,0.592639,0.309636,0.077459,0.416378,0.069389,0.226093,0.529658,0.032012,0.344655,1.071688,0.103480,0.143836,0.037528,0.039048,0.161324
TA_Qwen3,NaN,0.039836,0.009243,0.099452,0.038960,0.100104,0.088046,0.005034,0.035343,0.022603,0.200087,0.039473,0.004207,0.012477,0.024800,0.038915
EN_Qwen3,NaN,0.317008,0.469939,0.385773,1.013781,0.251571,0.269588,1.339904,0.682738,0.871159,1.062842,0.151631,0.787157,0.473008,0.002507,0.376958

## Shape
df text: (15, 16)
df std: (15, 16)
Display df

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,65.906926,57.598253,62.209873,62.640825,45.390110,107.699684,896093.535485,68.901162,493.790219,44.496971,57.113641,48.481814,52.050964,56.756861,41.277322
SW_Llama,30.056285,76.299433,63.393429,54.521151,36.941053,70.289028,140.046129,82843.632618,64.677236,127.097711,79.511096,56.283017,46.878139,43.463953,34.765476,50.868524
ID_Llama,24.823783,49.034587,42.820579,32.114254,38.430521,45.473741,80.624982,147212.490658,33.437626,237.449086,52.094113,39.772587,35.062178,28.618159,34.721147,35.462255
TA_Llama,2.311781,4.619366,2.477804,3.813212,3.841755,3.669907,6.090120,349753.537060,4.954544,8.438959,3.885786,4.269030,2.430107,3.463090,3.554056,3.123373
EN_Llama,45.105214,54.002999,56.975352,56.643278,55.005956,56.127699,51.661761,20302.152824,52.608449,82.705680,55.081591,48.270659,50.732388,50.051469,51.241933,50.027819
ZH_Aya,112.084228,170.108220,262.474523,151.644070,153.626228,124.030659,153.807992,NaN,148.348093,152.570887,127.689433,132.582898,135.092829,132.251605,139.732992,119.321911
SW_Aya,347.245294,701.944022,866.680681,601.327532,386.510893,628.567549,694.409390,NaN,581.597703,372.344141,698.011042,488.415269,494.785107,505.833186,351.026762,561.057641
ID_Aya,92.363250,122.900772,170.286285,100.952621,109.504752,108.384593,128.241772,NaN,106.431040,117.153934,123.701714,104.218850,107.600928,96.903556,105.485363,106.001720
TA_Aya,3.798334,5.489648,3.942703,4.941318,4.902821,5.048185,5.190608,NaN,4.846758,4.707457,4.957356,4.598233,3.914037,4.432267,4.394636,4.441016
EN_Aya,53.754913,55.716955,59.996131,58.331153,56.882036,56.490654,70.334848,NaN,70.159288,71.447728,71.276244,56.603639,59.778306,57.988980,59.710328,58.374838
ZH_Qwen3,46.980806,63.733939,64.155454,62.711432,65.088417,55.974740,64.712779,63.478865,64.819501,68.373666,55.552981,53.220909,54.118815,53.634716,53.881667,48.014369
SW_Qwen3,64.534645,162.378025,141.887540,136.644195,79.112232,161.821596,164.318719,145.458323,137.722535,74.107588,179.623959,118.216036,104.766815,103.911624,65.999048,115.434023
ID_Qwen3,16.699008,24.870707,23.044479,19.074604,22.241715,24.838596,26.285258,23.784272,18.983927,22.583907,27.751146,21.206783,19.529220,17.453221,19.180347,21.117769
TA_Qwen3,2.741605,4.277311,2.924455,3.789021,3.724733,4.191249,4.949053,2.907458,4.009722,3.971942,4.454546,3.795672,2.791451,3.444308,3.318586,3.607402
EN_Qwen3,33.428698,40.524927,42.631171,42.927773,44.148314,40.931761,38.188459,46.080950,41.845462,44.450209,43.978831,34.863418,37.812257,36.722366,37.237706,36.611705

Display df std

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,,,,,,,,,,,,,,,,
SW_Llama,,,,,,,,,,,,,,,,
ID_Llama,,,,,,,,,,,,,,,,
TA_Llama,,,,,,,,,,,,,,,,
EN_Llama,,,,,,,,,,,,,,,,
ZH_Aya,,,,,,,,,,,,,,,,
SW_Aya,,,,,,,,,,,,,,,,
ID_Aya,,,,,,,,,,,,,,,,
TA_Aya,,,,,,,,,,,,,,,,
EN_Aya,,,,,,,,,,,,,,,,
ZH_Qwen3,,0.76,1.20,0.44,0.92,0.70,1.57,0.97,0.70,0.92,0.82,0.32,0.34,0.84,0.44,0.17
SW_Qwen3,,2.80,1.71,4.76,1.14,11.74,5.46,7.63,3.36,0.71,8.25,2.75,1.25,5.16,0.48,2.28
ID_Qwen3,,0.59,0.31,0.08,0.42,0.07,0.23,0.53,0.03,0.34,1.07,0.10,0.14,0.04,0.04,0.16
TA_Qwen3,,0.04,0.01,0.10,0.04,0.10,0.09,0.01,0.04,0.02,0.20,0.04,0.00,0.01,0.02,0.04
EN_Qwen3,,0.32,0.47,0.39,1.01,0.25,0.27,1.34,0.68,0.87,1.06,0.15,0.79,0.47,0.00,0.38

Writing to pdf ...

In [7]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"config.bit_width": f"{bit_width}-bit"},
                            {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            {"$not": {"$and": [{"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}, {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}]}},
                            # {"$not": {"$and": [{"config.quantization_technique": "gptq"}, {"config.calibration_language": "Swahili"}]}}
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                              # {"config.base_model": base_model},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                          ]}
                      ]}
                  )

  eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
  # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
  # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
  # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
  # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
  # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

  # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
  perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, write_pdf="ablation_floresplus_2bit_all_vert_final.pdf")

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
0,Qwen/Qwen3-8B,gptq,2-bit,English,13062.876244,48256.105485,39854.463930,38231.523295,34286.236528
15,Qwen/Qwen3-8B,gptq,2-bit,English,12451.018302,40756.553633,38410.667460,41726.485947,39319.365601
...,...,...,...,...,...,...,...,...,...
10,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,English,71.305146,98.906951,409.737624,422.779281,698.255733
12,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Tamil,123.015885,2.790848,254.872068,329.592691,276.418416
11,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Indonesian,94.744345,11.290383,48.682029,208.366909,381.739075
13,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Swahili,108.396437,15.895496,135.912888,43.170179,1156.817653
14,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,110.839197,8.777216,481.666138,469.148661,68.792080

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
6,Qwen/Qwen3-8B,tacq,English,2-bit,0.323566,0.665306,3.515737,10.556345,3.317178
9,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.461728,0.010456,14.028029,144.154089,2.312004
7,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.534628,0.818386,0.167729,23.810479,4.750264
8,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.458314,0.499177,0.602931,1.532377,10.103402
5,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.907797,1.544423,5.781454,15.010444,0.752618
1,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.218186,1.433973,4.411970,233.931693,12.841869
4,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,1.176844,0.012800,9.131215,52.022620,5.145499
2,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.472105,0.360203,2.482059,161.906780,15.790946
3,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,1.532074,0.192958,2.532162,8.991836,4.074086
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,1.514478,0.978149,17.780479,306.709847,0.387395
11,meta-llama/Llama-3.1-8B-Instruct,tacq,English,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
14,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
12,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
13,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
10,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
6,Qwen/Qwen3-8B,gptq,English,2-bit,4.108156,4.662199,4.593693,4.606363,4.596503
9,Qwen/Qwen3-8B,gptq,Tamil,2-bit,4.642051,0.873260,4.664672,4.670482,4.531575
7,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,4.544935,4.508749,3.226292,4.541529,4.624799
8,Qwen/Qwen3-8B,gptq,Swahili,2-bit,4.643958,4.572244,4.622783,3.166420,4.405375
5,Qwen/Qwen3-8B,gptq,Chinese,2-bit,4.489204,4.365599,4.580982,4.616916,4.249957

           GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3  4.108156  4.642051  4.544935  4.643958  4.489204
TA_Qwen3  4.662199  0.873260  4.508749  4.572244  4.365599
ID_Qwen3  4.593693  4.664672  3.226292  4.622783  4.580982
SW_Qwen3  4.606363  4.670482  4.541529  3.166420  4.616916
ZH_Qwen3  4.596503  4.531575  4.624799  4.405375  4.249957

start model: CohereLabs/aya-expanse-8b

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
1,CohereLabs/aya-expanse-8b,gptq,English,2-bit,2.383521,4.348801,3.784685,4.346861,4.282580
4,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,2.872552,0.808635,3.811151,4.341208,3.967499
2,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,2.718155,3.623270,2.737043,4.152934,3.997845
3,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,2.916441,3.176520,3.635588,3.201836,4.169309
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,3.002846,3.626023,3.789999,4.319220,3.012777

         GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Aya  2.383521  2.872552  2.718155  2.916441  3.002846
TA_Aya  4.348801  0.808635  3.623270  3.176520  3.626023
ID_Aya  3.784685  3.811151  2.737043  3.635588  3.789999
SW_Aya  4.346861  4.341208  4.152934  3.201836  4.319220
ZH_Aya  4.282580  3.967499  3.997845  4.169309  3.012777

start model: meta-llama/Llama-3.1-8B-Instruct

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
11,meta-llama/Llama-3.1-8B-Instruct,gptq,English,2-bit,3.114075,NaN,4.504326,4.534616,4.591451
14,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,2-bit,3.928250,0.978895,4.589347,4.665602,4.501359
12,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,2-bit,3.786975,NaN,3.442164,4.289284,4.562845
13,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,2-bit,4.020273,NaN,4.433452,3.609202,4.668178
10,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,2-bit,3.885365,4.758571,4.551475,4.632221,3.496240

           GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Llama  3.114075  3.928250  3.786975  4.020273  3.885365
TA_Llama       NaN  0.978895       NaN       NaN  4.758571
ID_Llama  4.504326  4.589347  3.442164  4.433452  4.551475
SW_Llama  4.534616  4.665602  4.289284  3.609202  4.632221
ZH_Llama  4.591451  4.501359  4.562845  4.668178  3.496240

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,39034.718763,31721.858572,36546.410226,46577.700046,3135.019061,1.182826e+07,NaN,1.889792e+06,3.922542e+06,2407.566671,698.255733,276.418416,381.739075,1156.817653,68.792080
SW_Llama,30.056285,34246.515720,46302.289195,19466.319055,4066.321032,42876.669741,4.843673e+04,NaN,3.387789e+04,6.797139e+04,20333.921389,422.779281,329.592691,208.366909,43.170179,469.148661
ID_Llama,24.823783,31939.373115,38846.104053,2767.984113,27130.168106,35602.009931,9.034067e+04,NaN,8.363805e+04,1.253635e+05,54669.471081,409.737624,254.872068,48.682029,135.912888,481.666138
TA_Llama,2.311781,NaN,9.525656,NaN,NaN,57354.934756,1.325875e+07,NaN,2.981072e+06,5.918960e+05,212825.012183,98.906951,2.790848,11.290383,15.895496,8.777216
EN_Llama,45.105214,1300.394068,8477.161407,6123.151827,10477.869747,7680.062329,1.310330e+03,NaN,2.464687e+04,4.703085e+04,6997.865099,71.305146,123.015885,94.744345,108.396437,110.839197
ZH_Aya,112.084228,19168.145370,9278.960985,9950.510277,14767.553330,1029.857317,7.409755e+06,NaN,1.631137e+06,1.004871e+06,274.084188,360.637008,275.617452,292.760948,406.131890,135.838040
SW_Aya,347.245294,22225.967596,21938.558958,14221.136656,1591.607966,20855.464249,9.978332e+03,NaN,5.561333e+03,4.189173e+02,50822.574116,1588.158444,1544.971890,1344.702942,332.042594,2235.354059
ID_Aya,92.363250,6090.955316,6473.671674,545.811702,4321.037729,6165.939366,4.766603e+04,NaN,2.328256e+02,1.044489e+03,484718.872812,306.205275,225.322198,117.137641,202.212119,297.658705
TA_Aya,3.798334,22325.499442,6.436282,4200.197925,1501.481445,4226.914393,4.110211e+05,NaN,4.490107e+05,6.071352e+05,290134.141033,14.739504,4.049754,12.200776,10.231536,12.421246
EN_Aya,53.754913,241.836277,745.679240,522.582423,824.976137,1006.574886,1.366964e+02,NaN,2.688014e+02,3.345557e+02,4622.001841,69.141747,93.205527,80.995250,97.275513,85.909020
ZH_Qwen3,46.980806,39491.465990,34007.536689,42150.094142,25431.655621,17781.024879,6.674189e+05,60166.327417,4.113642e+05,6.278313e+05,360.020385,146.704354,119.462250,122.105214,176.318815,63.072371
SW_Qwen3,64.534645,40398.302421,46825.504463,34796.007236,1466.964319,41391.915611,6.726278e+03,6525.812005,2.713585e+03,5.398065e+02,19233.229068,380.075948,433.095598,258.430765,69.236501,372.747064
ID_Qwen3,16.699008,39236.778388,46203.199536,1683.806307,41954.948059,38104.965297,2.493904e+03,11464.605865,1.232482e+02,7.012918e+02,18727.617100,116.218561,72.677371,21.817674,43.733264,127.139610
TA_Qwen3,2.741605,45940.807067,7.468949,32266.297200,37346.013068,23205.924496,1.476803e+04,4.442923,1.200714e+04,6.139446e+03,25621.911270,15.513642,3.063271,9.956398,9.944748,13.166703
EN_Qwen3,33.428698,12827.901762,43858.254034,35069.944932,44051.236215,30846.394995,1.515746e+02,6890.433754,1.077302e+03,2.003619e+03,5742.270277,43.983318,64.369847,52.554869,65.558487,59.187938

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
SW_Llama,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ID_Llama,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
TA_Llama,NaN,NaN,0.000000,NaN,NaN,0.000000,0.000000e+00,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
EN_Llama,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZH_Aya,NaN,1543.522189,1302.353438,866.080047,1180.853398,18.945158,1.202363e+06,NaN,416931.507561,648186.966924,13.882118,12.841869,5.145499,15.790946,4.074086,0.387395
SW_Aya,NaN,1277.195624,2050.239999,1152.198626,33.017260,2340.085532,2.119860e+03,NaN,1141.379148,37.523671,26373.980905,233.931693,52.022620,161.906780,8.991836,306.709847
ID_Aya,NaN,785.551907,453.403569,36.465574,597.968991,748.488685,1.619160e+04,NaN,10.858010,407.497337,46527.414954,4.411970,9.131215,2.482059,2.532162,17.780479
TA_Aya,NaN,6727.004278,0.242481,1013.398744,576.594778,1135.284190,2.832218e+05,NaN,322783.452104,828733.377281,268700.417046,1.433973,0.012800,0.360203,0.192958,0.978149
EN_Aya,NaN,6.347335,60.775949,25.456456,80.773855,75.660850,8.647104e+00,NaN,22.655564,117.247604,3534.650256,0.218186,1.176844,0.472105,1.532074,1.514478
ZH_Qwen3,NaN,4322.025321,12652.174248,1814.625584,214.562658,1521.218809,2.613922e+05,23070.095350,136201.928434,562039.370899,44.890879,3.317178,2.312004,4.750264,10.103402,0.752618
SW_Qwen3,NaN,1545.126299,41.811051,3225.378802,119.318857,6205.821677,9.155808e+02,1344.498076,1229.939922,152.852881,6050.793892,10.556345,144.154089,23.810479,1.532377,15.010444
ID_Qwen3,NaN,607.573270,5893.246746,463.524607,2132.436617,4590.185765,4.345302e+02,2181.571725,64.114112,63.687162,5190.682069,3.515737,14.028029,0.167729,0.602931,5.781454
TA_Qwen3,NaN,3672.782474,0.417630,3505.411760,1535.747660,1813.483650,9.351708e+03,0.104889,11122.033868,4051.681957,16018.499530,0.665306,0.010456,0.818386,0.499177,1.544423
EN_Qwen3,NaN,269.191572,3137.501577,1463.765358,1602.262531,492.546412,1.519971e+01,2585.158544,570.476116,812.771505,2266.421583,0.323566,0.461728,0.534628,0.458314,0.907797

## Shape
df text: (15, 16)
df std: (15, 16)
Display df

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,39034.718763,31721.858572,36546.410226,46577.700046,3135.019061,1.182826e+07,NaN,1.889792e+06,3.922542e+06,2407.566671,698.255733,276.418416,381.739075,1156.817653,68.792080
SW_Llama,30.056285,34246.515720,46302.289195,19466.319055,4066.321032,42876.669741,4.843673e+04,NaN,3.387789e+04,6.797139e+04,20333.921389,422.779281,329.592691,208.366909,43.170179,469.148661
ID_Llama,24.823783,31939.373115,38846.104053,2767.984113,27130.168106,35602.009931,9.034067e+04,NaN,8.363805e+04,1.253635e+05,54669.471081,409.737624,254.872068,48.682029,135.912888,481.666138
TA_Llama,2.311781,NaN,9.525656,NaN,NaN,57354.934756,1.325875e+07,NaN,2.981072e+06,5.918960e+05,212825.012183,98.906951,2.790848,11.290383,15.895496,8.777216
EN_Llama,45.105214,1300.394068,8477.161407,6123.151827,10477.869747,7680.062329,1.310330e+03,NaN,2.464687e+04,4.703085e+04,6997.865099,71.305146,123.015885,94.744345,108.396437,110.839197
ZH_Aya,112.084228,19168.145370,9278.960985,9950.510277,14767.553330,1029.857317,7.409755e+06,NaN,1.631137e+06,1.004871e+06,274.084188,360.637008,275.617452,292.760948,406.131890,135.838040
SW_Aya,347.245294,22225.967596,21938.558958,14221.136656,1591.607966,20855.464249,9.978332e+03,NaN,5.561333e+03,4.189173e+02,50822.574116,1588.158444,1544.971890,1344.702942,332.042594,2235.354059
ID_Aya,92.363250,6090.955316,6473.671674,545.811702,4321.037729,6165.939366,4.766603e+04,NaN,2.328256e+02,1.044489e+03,484718.872812,306.205275,225.322198,117.137641,202.212119,297.658705
TA_Aya,3.798334,22325.499442,6.436282,4200.197925,1501.481445,4226.914393,4.110211e+05,NaN,4.490107e+05,6.071352e+05,290134.141033,14.739504,4.049754,12.200776,10.231536,12.421246
EN_Aya,53.754913,241.836277,745.679240,522.582423,824.976137,1006.574886,1.366964e+02,NaN,2.688014e+02,3.345557e+02,4622.001841,69.141747,93.205527,80.995250,97.275513,85.909020
ZH_Qwen3,46.980806,39491.465990,34007.536689,42150.094142,25431.655621,17781.024879,6.674189e+05,60166.327417,4.113642e+05,6.278313e+05,360.020385,146.704354,119.462250,122.105214,176.318815,63.072371
SW_Qwen3,64.534645,40398.302421,46825.504463,34796.007236,1466.964319,41391.915611,6.726278e+03,6525.812005,2.713585e+03,5.398065e+02,19233.229068,380.075948,433.095598,258.430765,69.236501,372.747064
ID_Qwen3,16.699008,39236.778388,46203.199536,1683.806307,41954.948059,38104.965297,2.493904e+03,11464.605865,1.232482e+02,7.012918e+02,18727.617100,116.218561,72.677371,21.817674,43.733264,127.139610
TA_Qwen3,2.741605,45940.807067,7.468949,32266.297200,37346.013068,23205.924496,1.476803e+04,4.442923,1.200714e+04,6.139446e+03,25621.911270,15.513642,3.063271,9.956398,9.944748,13.166703
EN_Qwen3,33.428698,12827.901762,43858.254034,35069.944932,44051.236215,30846.394995,1.515746e+02,6890.433754,1.077302e+03,2.003619e+03,5742.270277,43.983318,64.369847,52.554869,65.558487,59.187938

Display df std

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,,,,,,,,,,,,,,,,
SW_Llama,,,,,,,,,,,,,,,,
ID_Llama,,,,,,,,,,,,,,,,
TA_Llama,,,,,,,,,,,,,,,,
EN_Llama,,,,,,,,,,,,,,,,
ZH_Aya,,1.5e+3,1.3e+3,866.1,1.2e+3,18.95,1.2e+6,,4.2e+5,6.5e+5,13.88,12.84,5.15,15.79,4.07,0.39
SW_Aya,,1.3e+3,2.1e+3,1.2e+3,33.02,2.3e+3,2.1e+3,,1.1e+3,37.52,2.6e+4,233.9,52.02,161.9,8.99,306.7
ID_Aya,,785.6,453.4,36.47,598.0,748.5,1.6e+4,,10.86,407.5,4.7e+4,4.41,9.13,2.48,2.53,17.78
TA_Aya,,6.7e+3,0.24,1.0e+3,576.6,1.1e+3,2.8e+5,,3.2e+5,8.3e+5,2.7e+5,1.43,0.01,0.36,0.19,0.98
EN_Aya,,6.35,60.78,25.46,80.77,75.66,8.65,,22.66,117.2,3.5e+3,0.22,1.18,0.47,1.53,1.51
ZH_Qwen3,,4.3e+3,1.3e+4,1.8e+3,214.6,1.5e+3,2.6e+5,2.3e+4,1.4e+5,5.6e+5,44.89,3.32,2.31,4.75,10.10,0.75
SW_Qwen3,,1.5e+3,41.81,3.2e+3,119.3,6.2e+3,915.6,1.3e+3,1.2e+3,152.9,6.1e+3,10.56,144.2,23.81,1.53,15.01
ID_Qwen3,,607.6,5.9e+3,463.5,2.1e+3,4.6e+3,434.5,2.2e+3,64.11,63.69,5.2e+3,3.52,14.03,0.17,0.60,5.78
TA_Qwen3,,3.7e+3,0.42,3.5e+3,1.5e+3,1.8e+3,9.4e+3,0.10,1.1e+4,4.1e+3,1.6e+4,0.67,0.01,0.82,0.50,1.54
EN_Qwen3,,269.2,3.1e+3,1.5e+3,1.6e+3,492.5,15.20,2.6e+3,570.5,812.8,2.3e+3,0.32,0.46,0.53,0.46,0.91

Writing to pdf ...

##### All data - Each Quant

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [3]:
  for quantization_technique in ["gptq", "slimllm", "tacq"]:
    runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                    filters={"$or": [
                            { "$and": [
                              {"config.quantization_technique": quantization_technique.lower()},
                              {"config.bit_width": f"{bit_width}-bit"},
                              {"config.num_calibration_samples": 128},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"$or": [
                                {"config.evaluation_dataset": f"floresplus-evaluate"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                              ]},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                              {"created_at": {"$gt": '2026-01-15'}},
                              {"created_at": {"$lt": '2026-07-01'}},
                              # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                              # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              # {"$not": {"$and": [{"config.quantization_technique": "gptq"}, {"config.calibration_language": "Swahili"}]}}
                            ]
                            },
                            { "$and" : [
                                {"config.quantization_technique": "Unquantized"},
                                # {"config.evaluation_dataset": evaluation_dataset},
                                {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                                # {"config.base_model": base_model},
                              # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                              # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                                {"config.enable_thinking": False},
                                {"config.output_type": "perplexity"},
                              {"created_at": {"$gt": '2026-01-15'}},
                              {"created_at": {"$lt": '2026-07-01'}},
                            ]}
                        ]}
                    )

    eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
    # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
    # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
    # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
    # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
    # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

    # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
    perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, write_pdf=f"ablation_floresplus_{bit_width}bit_{quantization_technique}_all_vert.pdf")

/tmp/ipykernel_9034/1384151445.py:165: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
0,Qwen/Qwen3-8B,gptq,3-bit,English,40.188512,4.329966,24.304464,160.417519,62.901249
15,Qwen/Qwen3-8B,gptq,3-bit,English,40.949766,4.233635,25.688953,160.373092,64.743586
16,Qwen/Qwen3-8B,gptq,3-bit,English,40.436502,4.268332,24.618706,166.343463,63.556982
2,Qwen/Qwen3-8B,gptq,3-bit,Tamil,42.012760,2.919523,22.620578,144.263196,62.475377
19,Qwen/Qwen3-8B,gptq,3-bit,Tamil,42.729569,2.937405,23.351523,141.058965,65.202294
20,Qwen/Qwen3-8B,gptq,3-bit,Tamil,43.151184,2.916437,23.161336,140.340460,64.788691
1,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,42.385494,3.915570,19.171946,143.357820,62.972576
17,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,43.250695,3.672597,18.982422,133.669715,62.093137
18,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,43.147129,3.778896,19.069444,132.905051,63.068583
3,Qwen/Qwen3-8B,gptq,3-bit,Swahili,44.786866,3.771811,22.734896,79.985090,66.249266
21,Qwen/Qwen3-8B,gptq,3-bit,Swahili,42.717366,3.676404,21.716492,77.506947,64.011188
22,Qwen/Qwen3-8B,gptq,3-bit,Swahili,44.940711,3.725982,22.273758,79.844660,65.004796
4,Qwen/Qwen3-8B,gptq,3-bit,Chinese,40.865351,4.132577,24.873793,151.040822,56.098754
23,Qwen/Qwen3-8B,gptq,3-bit,Chinese,41.267661,4.332161,24.900326,178.141356,56.762463
24,Qwen/Qwen3-8B,gptq,3-bit,Chinese,40.662271,4.109008,24.741668,156.282612,55.063003
5,CohereLabs/aya-expanse-8b,gptq,3-bit,English,55.716955,5.489648,122.900772,701.944022,170.108220
7,CohereLabs/aya-expanse-8b,gptq,3-bit,Tamil,59.996131,3.942703,170.286285,866.680681,262.474523
6,CohereLabs/aya-expanse-8b,gptq,3-bit,Indonesian,58.331153,4.941318,100.952621,601.327532,151.644070
8,CohereLabs/aya-expanse-8b,gptq,3-bit,Swahili,56.882036,4.902821,109.504752,386.510893,153.626228
9,CohereLabs/aya-expanse-8b,gptq,3-bit,Chinese,56.490654,5.048185,108.384593,628.567549,124.030659
10,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,English,54.002999,4.619366,49.034587,76.299433,65.906926
12,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Tamil,56.975352,2.477804,42.820579,63.393429,57.598253
11,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Indonesian,56.643278,3.813212,32.114254,54.521151,62.209873
13,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Swahili,55.005956,3.841755,38.430521,36.941053,62.640825
14,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Chinese,56.127699,3.669907,45.473741,70.289028,45.390110

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
6,Qwen/Qwen3-8B,gptq,English,3-bit,1.607722,0.631171,1.395688,2.210527,1.804371
9,Qwen/Qwen3-8B,gptq,Tamil,3-bit,1.629727,0.466045,1.362567,2.151944,1.807234
7,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,1.632738,0.578527,1.280456,2.135591,1.797347
8,Qwen/Qwen3-8B,gptq,Swahili,3-bit,1.644914,0.571095,1.347168,1.898244,1.813504
5,Qwen/Qwen3-8B,gptq,Chinese,3-bit,1.612060,0.622343,1.395127,2.209036,1.747992

           GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3  1.607722  1.629727  1.632738  1.644914  1.612060
TA_Qwen3  0.631171  0.466045  0.578527  0.571095  0.622343
ID_Qwen3  1.395688  1.362567  1.280456  1.347168  1.395127
SW_Qwen3  2.210527  2.151944  2.135591  1.898244  2.209036
ZH_Qwen3  1.804371  1.807234  1.797347  1.813504  1.747992

start model: CohereLabs/aya-expanse-8b

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
1,CohereLabs/aya-expanse-8b,gptq,English,3-bit,1.745987,0.739545,2.089555,2.846302,2.230725
4,CohereLabs/aya-expanse-8b,gptq,Tamil,3-bit,1.778123,0.595794,2.231180,2.937859,2.419087
2,CohereLabs/aya-expanse-8b,gptq,Indonesian,3-bit,1.765901,0.693843,2.004118,2.779111,2.180825
3,CohereLabs/aya-expanse-8b,gptq,Swahili,3-bit,1.754975,0.690446,2.039433,2.587162,2.186465
0,CohereLabs/aya-expanse-8b,gptq,Chinese,3-bit,1.751977,0.703135,2.034968,2.798352,2.093529

         GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Aya  1.745987  1.778123  1.765901  1.754975  1.751977
TA_Aya  0.739545  0.595794  0.693843  0.690446  0.703135
ID_Aya  2.089555  2.231180  2.004118  2.039433  2.034968
SW_Aya  2.846302  2.937859  2.779111  2.587162  2.798352
ZH_Aya  2.230725  2.419087  2.180825  2.186465  2.093529

start model: meta-llama/Llama-3.1-8B-Instruct

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
11,meta-llama/Llama-3.1-8B-Instruct,gptq,English,3-bit,1.732418,0.664582,1.690503,1.882521,1.818931
14,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,3-bit,1.755687,0.394067,1.631653,1.802044,1.760409
12,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,3-bit,1.753148,0.581291,1.506698,1.736565,1.793859
13,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,3-bit,1.740410,0.584530,1.584676,1.567509,1.796857
10,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,3-bit,1.749177,0.564655,1.657761,1.846888,1.656961

           GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Llama  1.732418  1.755687  1.753148  1.740410  1.749177
TA_Llama  0.664582  0.394067  0.581291  0.584530  0.564655
ID_Llama  1.690503  1.631653  1.506698  1.584676  1.657761
SW_Llama  1.882521  1.802044  1.736565  1.567509  1.846888
ZH_Llama  1.818931  1.760409  1.793859  1.796857  1.656961

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH
ZH_Llama,36.821779,65.906926,57.598253,62.209873,62.640825,45.390110
SW_Llama,30.056285,76.299433,63.393429,54.521151,36.941053,70.289028
ID_Llama,24.823783,49.034587,42.820579,32.114254,38.430521,45.473741
TA_Llama,2.311781,4.619366,2.477804,3.813212,3.841755,3.669907
EN_Llama,45.105214,54.002999,56.975352,56.643278,55.005956,56.127699
ZH_Aya,112.084228,170.108220,262.474523,151.644070,153.626228,124.030659
SW_Aya,347.245294,701.944022,866.680681,601.327532,386.510893,628.567549
ID_Aya,92.363250,122.900772,170.286285,100.952621,109.504752,108.384593
TA_Aya,3.798334,5.489648,3.942703,4.941318,4.902821,5.048185
EN_Aya,53.754913,55.716955,59.996131,58.331153,56.882036,56.490654
ZH_Qwen3,46.980806,63.733939,64.155454,62.711432,65.088417,55.974740
SW_Qwen3,64.534645,162.378025,141.887540,136.644195,79.112232,161.821596
ID_Qwen3,16.699008,24.870707,23.044479,19.074604,22.241715,24.838596
TA_Qwen3,2.741605,4.277311,2.924455,3.789021,3.724733,4.191249
EN_Qwen3,33.428698,40.524927,42.631171,42.927773,44.148314,40.931761

          UQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW    GPTQ-ZH
ZH_Llama NaN  0.000000  0.000000  0.000000  0.000000   0.000000
SW_Llama NaN  0.000000  0.000000  0.000000  0.000000   0.000000
ID_Llama NaN  0.000000  0.000000  0.000000  0.000000   0.000000
TA_Llama NaN  0.000000  0.000000  0.000000  0.000000   0.000000
EN_Llama NaN  0.000000  0.000000  0.000000  0.000000   0.000000
ZH_Aya   NaN  0.000000  0.000000  0.000000  0.000000   0.000000
SW_Aya   NaN  0.000000  0.000000  0.000000  0.000000   0.000000
ID_Aya   NaN  0.000000  0.000000  0.000000  0.000000   0.000000
TA_Aya   NaN  0.000000  0.000000  0.000000  0.000000   0.000000
EN_Aya   NaN  0.000000  0.000000  0.000000  0.000000   0.000000
ZH_Qwen3 NaN  0.762469  1.199933  0.438954  0.915603   0.699321
SW_Qwen3 NaN  2.804047  1.705260  4.757503  1.136555  11.736552
ID_Qwen3 NaN  0.592639  0.309636  0.077459  0.416378   0.069389
TA_Qwen3 NaN  0.039836  0.009243  0.099452  0.038960   0.100104
EN_Qwen3 NaN  0.317008  0.469939  0.385773  1.013781   0.251571

## Shape
df text: (15, 6)
df std: (15, 6)
Display df

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH
ZH_Llama,36.821779,65.906926,57.598253,62.209873,62.640825,45.390110
SW_Llama,30.056285,76.299433,63.393429,54.521151,36.941053,70.289028
ID_Llama,24.823783,49.034587,42.820579,32.114254,38.430521,45.473741
TA_Llama,2.311781,4.619366,2.477804,3.813212,3.841755,3.669907
EN_Llama,45.105214,54.002999,56.975352,56.643278,55.005956,56.127699
ZH_Aya,112.084228,170.108220,262.474523,151.644070,153.626228,124.030659
SW_Aya,347.245294,701.944022,866.680681,601.327532,386.510893,628.567549
ID_Aya,92.363250,122.900772,170.286285,100.952621,109.504752,108.384593
TA_Aya,3.798334,5.489648,3.942703,4.941318,4.902821,5.048185
EN_Aya,53.754913,55.716955,59.996131,58.331153,56.882036,56.490654
ZH_Qwen3,46.980806,63.733939,64.155454,62.711432,65.088417,55.974740
SW_Qwen3,64.534645,162.378025,141.887540,136.644195,79.112232,161.821596
ID_Qwen3,16.699008,24.870707,23.044479,19.074604,22.241715,24.838596
TA_Qwen3,2.741605,4.277311,2.924455,3.789021,3.724733,4.191249
EN_Qwen3,33.428698,40.524927,42.631171,42.927773,44.148314,40.931761

Display df std

         UQ GPTQ-EN GPTQ-TA GPTQ-ID GPTQ-SW GPTQ-ZH
ZH_Llama
SW_Llama
ID_Llama
TA_Llama
EN_Llama
ZH_Aya
SW_Aya
ID_Aya
TA_Aya
EN_Aya
ZH_Qwen3       0.76    1.20    0.44    0.92    0.70
SW_Qwen3       2.80    1.71    4.76    1.14   11.74
ID_Qwen3       0.59    0.31    0.08    0.42    0.07
TA_Qwen3       0.04    0.01    0.10    0.04    0.10
EN_Qwen3       0.32    0.47    0.39    1.01    0.25

Writing to pdf ...

/tmp/ipykernel_9034/1384151445.py:165: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
0,Qwen/Qwen3-8B,slimllm,3-bit,English,37.996881,5.016177,26.602903,168.990251,62.766314
14,Qwen/Qwen3-8B,slimllm,3-bit,English,37.998784,5.006315,26.158109,167.302009,64.763401
15,Qwen/Qwen3-8B,slimllm,3-bit,English,38.569713,4.824668,26.094763,156.663898,66.608623
2,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,44.634059,2.900774,23.035248,135.082451,62.115039
18,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,47.864063,2.908678,24.164053,148.063340,64.064579
19,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,45.744729,2.912922,24.153516,153.229178,64.256978
1,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,40.979761,3.987145,18.939585,135.638807,63.992288
16,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,42.648606,3.982393,18.998192,135.061858,65.711417
17,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,41.908018,4.059630,19.014005,142.466939,64.754799
3,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,45.255367,4.003747,22.944876,74.916424,68.855317
20,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,43.240062,3.958805,22.119773,74.219013,69.179620
21,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,44.855199,3.953273,22.687072,73.187326,67.086059
4,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,44.252408,4.236144,26.923226,168.427617,54.448928
22,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,45.122009,4.719561,29.264508,188.082925,56.398916
23,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,42.562075,4.407932,27.065704,182.361335,55.811099
5,CohereLabs/aya-expanse-8b,slimllm,3-bit,English,70.334848,5.190608,128.241772,694.409390,153.807992
6,CohereLabs/aya-expanse-8b,slimllm,3-bit,Indonesian,70.159288,4.846758,106.431040,581.597703,148.348093
7,CohereLabs/aya-expanse-8b,slimllm,3-bit,Swahili,71.447728,4.707457,117.153934,372.344141,152.570887
8,CohereLabs/aya-expanse-8b,slimllm,3-bit,Chinese,71.276244,4.957356,123.701714,698.011042,127.689433
9,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,English,51.661761,6.090120,80.624982,140.046129,107.699684
11,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Tamil,20302.152824,349753.537060,147212.490658,82843.632618,896093.535485
10,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Indonesian,52.608449,4.954544,33.437626,64.677236,68.901162
12,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Swahili,82.705680,8.438959,237.449086,127.097711,493.790219
13,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Chinese,55.081591,3.885786,52.094113,79.511096,44.496971

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Qwen3, TA_Qwen3, ID_Qwen3, SW_Qwen3, ZH_Qwen3]

start model: CohereLabs/aya-expanse-8b

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Aya, TA_Aya, ID_Aya, SW_Aya, ZH_Aya]

start model: meta-llama/Llama-3.1-8B-Instruct

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Llama, TA_Llama, ID_Llama, SW_Llama, ZH_Llama]

,UQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,36.821779,107.699684,896093.535485,68.901162,493.790219,44.496971
SW_Llama,30.056285,140.046129,82843.632618,64.677236,127.097711,79.511096
ID_Llama,24.823783,80.624982,147212.490658,33.437626,237.449086,52.094113
TA_Llama,2.311781,6.090120,349753.537060,4.954544,8.438959,3.885786
EN_Llama,45.105214,51.661761,20302.152824,52.608449,82.705680,55.081591
ZH_Aya,112.084228,153.807992,NaN,148.348093,152.570887,127.689433
SW_Aya,347.245294,694.409390,NaN,581.597703,372.344141,698.011042
ID_Aya,92.363250,128.241772,NaN,106.431040,117.153934,123.701714
TA_Aya,3.798334,5.190608,NaN,4.846758,4.707457,4.957356
EN_Aya,53.754913,70.334848,NaN,70.159288,71.447728,71.276244
ZH_Qwen3,46.980806,64.712779,63.478865,64.819501,68.373666,55.552981
SW_Qwen3,64.534645,164.318719,145.458323,137.722535,74.107588,179.623959
ID_Qwen3,16.699008,26.285258,23.784272,18.983927,22.583907,27.751146
TA_Qwen3,2.741605,4.949053,2.907458,4.009722,3.971942,4.454546
EN_Qwen3,33.428698,38.188459,46.080950,41.845462,44.450209,43.978831

          UQ  SliM-LLM-EN  SliM-LLM-TA  SliM-LLM-ID  SliM-LLM-SW  SliM-LLM-ZH
ZH_Llama NaN     0.000000     0.000000     0.000000     0.000000     0.000000
SW_Llama NaN     0.000000     0.000000     0.000000     0.000000     0.000000
ID_Llama NaN     0.000000     0.000000     0.000000     0.000000     0.000000
TA_Llama NaN     0.000000     0.000000     0.000000     0.000000     0.000000
EN_Llama NaN     0.000000     0.000000     0.000000     0.000000     0.000000
ZH_Aya   NaN     0.000000          NaN     0.000000     0.000000     0.000000
SW_Aya   NaN     0.000000          NaN     0.000000     0.000000     0.000000
ID_Aya   NaN     0.000000          NaN     0.000000     0.000000     0.000000
TA_Aya   NaN     0.000000          NaN     0.000000     0.000000     0.000000
EN_Aya   NaN     0.000000          NaN     0.000000     0.000000     0.000000
ZH_Qwen3 NaN     1.569024     0.967564     0.703321     0.920051     0.816734
SW_Qwen3 NaN     5.456480     7.633938     3.363059     0.710285     8.254401
ID_Qwen3 NaN     0.226093     0.529658     0.032012     0.344655     1.071688
TA_Qwen3 NaN     0.088046     0.005034     0.035343     0.022603     0.200087
EN_Qwen3 NaN     0.269588     1.339904     0.682738     0.871159     1.062842

## Shape
df text: (15, 6)
df std: (15, 6)
Display df

,UQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,36.821779,107.699684,896093.535485,68.901162,493.790219,44.496971
SW_Llama,30.056285,140.046129,82843.632618,64.677236,127.097711,79.511096
ID_Llama,24.823783,80.624982,147212.490658,33.437626,237.449086,52.094113
TA_Llama,2.311781,6.090120,349753.537060,4.954544,8.438959,3.885786
EN_Llama,45.105214,51.661761,20302.152824,52.608449,82.705680,55.081591
ZH_Aya,112.084228,153.807992,NaN,148.348093,152.570887,127.689433
SW_Aya,347.245294,694.409390,NaN,581.597703,372.344141,698.011042
ID_Aya,92.363250,128.241772,NaN,106.431040,117.153934,123.701714
TA_Aya,3.798334,5.190608,NaN,4.846758,4.707457,4.957356
EN_Aya,53.754913,70.334848,NaN,70.159288,71.447728,71.276244
ZH_Qwen3,46.980806,64.712779,63.478865,64.819501,68.373666,55.552981
SW_Qwen3,64.534645,164.318719,145.458323,137.722535,74.107588,179.623959
ID_Qwen3,16.699008,26.285258,23.784272,18.983927,22.583907,27.751146
TA_Qwen3,2.741605,4.949053,2.907458,4.009722,3.971942,4.454546
EN_Qwen3,33.428698,38.188459,46.080950,41.845462,44.450209,43.978831

Display df std

         UQ SliM-LLM-EN SliM-LLM-TA SliM-LLM-ID SliM-LLM-SW SliM-LLM-ZH
ZH_Llama
SW_Llama
ID_Llama
TA_Llama
EN_Llama
ZH_Aya
SW_Aya
ID_Aya
TA_Aya
EN_Aya
ZH_Qwen3           1.57        0.97        0.70        0.92        0.82
SW_Qwen3           5.46        7.63        3.36        0.71        8.25
ID_Qwen3           0.23        0.53        0.03        0.34        1.07
TA_Qwen3           0.09        0.01        0.04        0.02        0.20
EN_Qwen3           0.27        1.34        0.68        0.87        1.06

Writing to pdf ...

/tmp/ipykernel_9034/1384151445.py:165: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
0,Qwen/Qwen3-8B,tacq,3-bit,English,34.710002,3.851373,21.065718,117.199228,53.504737
15,Qwen/Qwen3-8B,tacq,3-bit,English,35.069878,3.771026,21.311044,115.479045,53.388031
16,Qwen/Qwen3-8B,tacq,3-bit,English,34.810374,3.764617,21.243588,121.969836,52.769961
2,Qwen/Qwen3-8B,tacq,3-bit,Tamil,38.876412,2.786321,19.325887,106.376712,54.060936
19,Qwen/Qwen3-8B,tacq,3-bit,Tamil,36.997150,2.796624,19.635890,104.581084,53.732649
20,Qwen/Qwen3-8B,tacq,3-bit,Tamil,37.563208,2.791408,19.625883,103.342648,54.562860
1,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,36.946025,3.450643,17.499579,102.484387,54.492987
17,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,36.064564,3.455403,17.407666,110.818460,52.491162
18,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,37.156511,3.426878,17.452419,98.432025,53.919998
3,Qwen/Qwen3-8B,tacq,3-bit,Swahili,37.239785,3.283538,19.188073,66.064982,53.378040
21,Qwen/Qwen3-8B,tacq,3-bit,Swahili,37.234178,3.334953,19.223837,65.375300,54.450253
22,Qwen/Qwen3-8B,tacq,3-bit,Swahili,37.239153,3.337267,19.129131,66.556862,53.816706
4,Qwen/Qwen3-8B,tacq,3-bit,Chinese,36.939861,3.656487,21.255791,117.447664,48.256635
23,Qwen/Qwen3-8B,tacq,3-bit,Chinese,36.811469,3.561307,21.206081,112.252142,47.935979
24,Qwen/Qwen3-8B,tacq,3-bit,Chinese,36.083784,3.604412,20.891435,116.602262,47.850495
5,CohereLabs/aya-expanse-8b,tacq,3-bit,English,56.603639,4.598233,104.218850,488.415269,132.582898
7,CohereLabs/aya-expanse-8b,tacq,3-bit,Tamil,59.778306,3.914037,107.600928,494.785107,135.092829
6,CohereLabs/aya-expanse-8b,tacq,3-bit,Indonesian,57.988980,4.432267,96.903556,505.833186,132.251605
8,CohereLabs/aya-expanse-8b,tacq,3-bit,Swahili,59.710328,4.394636,105.485363,351.026762,139.732992
9,CohereLabs/aya-expanse-8b,tacq,3-bit,Chinese,58.374838,4.441016,106.001720,561.057641,119.321911
10,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,English,48.270659,4.269030,39.772587,56.283017,57.113641
12,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Tamil,50.732388,2.430107,35.062178,46.878139,48.481814
11,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Indonesian,50.051469,3.463090,28.618159,43.463953,52.050964
13,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Swahili,51.241933,3.554056,34.721147,34.765476,56.756861
14,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Chinese,50.027819,3.123373,35.462255,50.868524,41.277322

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
6,Qwen/Qwen3-8B,tacq,English,3-bit,0.151631,0.039473,0.103480,2.745665,0.322409
9,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.787157,0.004207,0.143836,1.245594,0.341394
7,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.473008,0.012477,0.037528,5.156465,0.841770
8,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.002507,0.024800,0.039048,0.484618,0.440133
5,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.376958,0.038915,0.161324,2.276247,0.174826
1,CohereLabs/aya-expanse-8b,tacq,English,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
4,CohereLabs/aya-expanse-8b,tacq,Tamil,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
2,CohereLabs/aya-expanse-8b,tacq,Indonesian,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
3,CohereLabs/aya-expanse-8b,tacq,Swahili,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
0,CohereLabs/aya-expanse-8b,tacq,Chinese,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
11,meta-llama/Llama-3.1-8B-Instruct,tacq,English,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
14,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
12,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
13,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
10,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Qwen3, TA_Qwen3, ID_Qwen3, SW_Qwen3, ZH_Qwen3]

start model: CohereLabs/aya-expanse-8b

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Aya, TA_Aya, ID_Aya, SW_Aya, ZH_Aya]

start model: meta-llama/Llama-3.1-8B-Instruct

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Llama, TA_Llama, ID_Llama, SW_Llama, ZH_Llama]

,UQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,57.113641,48.481814,52.050964,56.756861,41.277322
SW_Llama,30.056285,56.283017,46.878139,43.463953,34.765476,50.868524
ID_Llama,24.823783,39.772587,35.062178,28.618159,34.721147,35.462255
TA_Llama,2.311781,4.269030,2.430107,3.463090,3.554056,3.123373
EN_Llama,45.105214,48.270659,50.732388,50.051469,51.241933,50.027819
ZH_Aya,112.084228,132.582898,135.092829,132.251605,139.732992,119.321911
SW_Aya,347.245294,488.415269,494.785107,505.833186,351.026762,561.057641
ID_Aya,92.363250,104.218850,107.600928,96.903556,105.485363,106.001720
TA_Aya,3.798334,4.598233,3.914037,4.432267,4.394636,4.441016
EN_Aya,53.754913,56.603639,59.778306,57.988980,59.710328,58.374838
ZH_Qwen3,46.980806,53.220909,54.118815,53.634716,53.881667,48.014369
SW_Qwen3,64.534645,118.216036,104.766815,103.911624,65.999048,115.434023
ID_Qwen3,16.699008,21.206783,19.529220,17.453221,19.180347,21.117769
TA_Qwen3,2.741605,3.795672,2.791451,3.444308,3.318586,3.607402
EN_Qwen3,33.428698,34.863418,37.812257,36.722366,37.237706,36.611705

          UQ   TaCQ-EN   TaCQ-TA   TaCQ-ID   TaCQ-SW   TaCQ-ZH
ZH_Llama NaN  0.000000  0.000000  0.000000  0.000000  0.000000
SW_Llama NaN  0.000000  0.000000  0.000000  0.000000  0.000000
ID_Llama NaN  0.000000  0.000000  0.000000  0.000000  0.000000
TA_Llama NaN  0.000000  0.000000  0.000000  0.000000  0.000000
EN_Llama NaN  0.000000  0.000000  0.000000  0.000000  0.000000
ZH_Aya   NaN  0.000000  0.000000  0.000000  0.000000  0.000000
SW_Aya   NaN  0.000000  0.000000  0.000000  0.000000  0.000000
ID_Aya   NaN  0.000000  0.000000  0.000000  0.000000  0.000000
TA_Aya   NaN  0.000000  0.000000  0.000000  0.000000  0.000000
EN_Aya   NaN  0.000000  0.000000  0.000000  0.000000  0.000000
ZH_Qwen3 NaN  0.322409  0.341394  0.841770  0.440133  0.174826
SW_Qwen3 NaN  2.745665  1.245594  5.156465  0.484618  2.276247
ID_Qwen3 NaN  0.103480  0.143836  0.037528  0.039048  0.161324
TA_Qwen3 NaN  0.039473  0.004207  0.012477  0.024800  0.038915
EN_Qwen3 NaN  0.151631  0.787157  0.473008  0.002507  0.376958

## Shape
df text: (15, 6)
df std: (15, 6)
Display df

,UQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,57.113641,48.481814,52.050964,56.756861,41.277322
SW_Llama,30.056285,56.283017,46.878139,43.463953,34.765476,50.868524
ID_Llama,24.823783,39.772587,35.062178,28.618159,34.721147,35.462255
TA_Llama,2.311781,4.269030,2.430107,3.463090,3.554056,3.123373
EN_Llama,45.105214,48.270659,50.732388,50.051469,51.241933,50.027819
ZH_Aya,112.084228,132.582898,135.092829,132.251605,139.732992,119.321911
SW_Aya,347.245294,488.415269,494.785107,505.833186,351.026762,561.057641
ID_Aya,92.363250,104.218850,107.600928,96.903556,105.485363,106.001720
TA_Aya,3.798334,4.598233,3.914037,4.432267,4.394636,4.441016
EN_Aya,53.754913,56.603639,59.778306,57.988980,59.710328,58.374838
ZH_Qwen3,46.980806,53.220909,54.118815,53.634716,53.881667,48.014369
SW_Qwen3,64.534645,118.216036,104.766815,103.911624,65.999048,115.434023
ID_Qwen3,16.699008,21.206783,19.529220,17.453221,19.180347,21.117769
TA_Qwen3,2.741605,3.795672,2.791451,3.444308,3.318586,3.607402
EN_Qwen3,33.428698,34.863418,37.812257,36.722366,37.237706,36.611705

Display df std

         UQ TaCQ-EN TaCQ-TA TaCQ-ID TaCQ-SW TaCQ-ZH
ZH_Llama
SW_Llama
ID_Llama
TA_Llama
EN_Llama
ZH_Aya
SW_Aya
ID_Aya
TA_Aya
EN_Aya
ZH_Qwen3       0.32    0.34    0.84    0.44    0.17
SW_Qwen3       2.75    1.25    5.16    0.48    2.28
ID_Qwen3       0.10    0.14    0.04    0.04    0.16
TA_Qwen3       0.04    0.00    0.01    0.02    0.04
EN_Qwen3       0.15    0.79    0.47    0.00    0.38

Writing to pdf ...

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [2]:
  for quantization_technique in ["gptq", "slimllm", "tacq"]:
    runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                    filters={"$or": [
                            { "$and": [
                              {"config.quantization_technique": quantization_technique.lower()},
                              {"config.bit_width": f"{bit_width}-bit"},
                              {"config.num_calibration_samples": 128},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"$or": [
                                {"config.evaluation_dataset": f"floresplus-evaluate"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                              ]},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                              {"created_at": {"$gt": '2026-01-15'}},
                              {"created_at": {"$lt": '2026-07-01'}},
                              # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                              # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"$not": {"$and": [{"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}, {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}]}},
                              # {"$not": {"$and": [{"config.quantization_technique": "gptq"}, {"config.calibration_language": "Swahili"}]}}
                            ]
                            },
                            { "$and" : [
                                {"config.quantization_technique": "Unquantized"},
                                # {"config.evaluation_dataset": evaluation_dataset},
                                {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                                # {"config.base_model": base_model},
                              # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                              # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                                {"config.enable_thinking": False},
                                {"config.output_type": "perplexity"},
                              {"created_at": {"$gt": '2026-01-15'}},
                              {"created_at": {"$lt": '2026-07-01'}},
                            ]}
                        ]}
                    )

    eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
    # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
    # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
    # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
    # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
    # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

    # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
    perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, write_pdf=f"ablation_floresplus_{bit_width}bit_{quantization_technique}_all_vert.pdf")

/tmp/ipykernel_9034/1384151445.py:165: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
0,Qwen/Qwen3-8B,gptq,2-bit,English,13062.876244,48256.105485,39854.463930,38231.523295,34286.236528
15,Qwen/Qwen3-8B,gptq,2-bit,English,12451.018302,40756.553633,38410.667460,41726.485947,39319.365601
16,Qwen/Qwen3-8B,gptq,2-bit,English,12969.810741,48809.762083,39445.203775,41236.898022,44868.795841
2,Qwen/Qwen3-8B,gptq,2-bit,Tamil,45011.900151,8.059500,48568.139986,NaN,51742.189476
19,Qwen/Qwen3-8B,gptq,2-bit,Tamil,46991.916079,7.181371,51941.771740,46783.693412,23084.039656
20,Qwen/Qwen3-8B,gptq,2-bit,Tamil,39570.945873,7.165976,38099.686881,46867.315514,27196.380936
1,Qwen/Qwen3-8B,gptq,2-bit,Indonesian,33757.634711,27336.007204,1292.570740,31265.346026,44669.351995
17,Qwen/Qwen3-8B,gptq,2-bit,Indonesian,34339.631525,35179.825770,1423.920369,34060.252839,41313.908151
18,Qwen/Qwen3-8B,gptq,2-bit,Indonesian,37112.568558,34283.058625,2334.927811,39062.422844,40467.022281
3,Qwen/Qwen3-8B,gptq,2-bit,Swahili,43340.996447,37753.455878,39555.250129,1309.652535,NaN
21,Qwen/Qwen3-8B,gptq,2-bit,Swahili,46269.830658,35294.786837,44736.573327,1598.490207,25646.218279
22,Qwen/Qwen3-8B,gptq,2-bit,Swahili,42542.881541,38989.796488,41573.020723,1492.750216,25217.092964
4,Qwen/Qwen3-8B,gptq,2-bit,Chinese,31539.289356,20653.920899,33869.505357,36808.237214,19548.105776
23,Qwen/Qwen3-8B,gptq,2-bit,Chinese,30438.093103,24261.602330,44483.020061,50165.325089,17960.136218
24,Qwen/Qwen3-8B,gptq,2-bit,Chinese,30561.802526,24702.250261,35962.370472,37202.184530,15834.832642
5,CohereLabs/aya-expanse-8b,gptq,2-bit,English,235.528100,29179.092457,7146.061891,21486.634405,21098.267209
25,CohereLabs/aya-expanse-8b,gptq,2-bit,English,250.521023,24612.727518,5864.566907,24022.828229,19086.069948
26,CohereLabs/aya-expanse-8b,gptq,2-bit,English,239.459709,13184.678353,5262.237149,21168.440156,17320.098954
7,CohereLabs/aya-expanse-8b,gptq,2-bit,Tamil,831.145209,6.779198,6538.645808,21859.037272,11035.168409
29,CohereLabs/aya-expanse-8b,gptq,2-bit,Tamil,710.836129,6.266145,6993.630049,24488.396157,8881.469726
30,CohereLabs/aya-expanse-8b,gptq,2-bit,Tamil,695.056381,6.263502,5888.739165,19468.243446,7920.244820
6,CohereLabs/aya-expanse-8b,gptq,2-bit,Indonesian,525.795981,5129.666588,563.137217,15819.122889,10036.438793
27,CohereLabs/aya-expanse-8b,gptq,2-bit,Indonesian,552.028848,4680.202460,579.214097,13146.149859,10965.659524
28,CohereLabs/aya-expanse-8b,gptq,2-bit,Indonesian,489.922440,2790.724728,495.083793,13698.137220,8849.432514
8,CohereLabs/aya-expanse-8b,gptq,2-bit,Swahili,724.296003,1890.988821,4170.777295,1546.397329,13156.622437
31,CohereLabs/aya-expanse-8b,gptq,2-bit,Swahili,828.580174,686.320382,3675.462235,1604.103491,15191.838548
32,CohereLabs/aya-expanse-8b,gptq,2-bit,Swahili,922.052235,1927.135131,5116.873657,1624.323077,15954.199005
9,CohereLabs/aya-expanse-8b,gptq,2-bit,Chinese,908.806486,3844.228301,5362.628130,17568.374956,1019.285708
33,CohereLabs/aya-expanse-8b,gptq,2-bit,Chinese,1093.113453,5768.616208,7164.563377,22831.098388,1056.463519
34,CohereLabs/aya-expanse-8b,gptq,2-bit,Chinese,1017.804718,3067.898671,5970.626592,22166.919403,1013.822725
10,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,English,1300.394068,NaN,31939.373115,34246.515720,39034.718763
12,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Tamil,8477.161407,9.525656,38846.104053,46302.289195,31721.858572
11,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Indonesian,6123.151827,NaN,2767.984113,19466.319055,36546.410226
13,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Swahili,10477.869747,NaN,27130.168106,4066.321032,46577.700046
14,meta-llama/Llama-3.1-8B-Instruct,gptq,2-bit,Chinese,7680.062329,57354.934756,35602.009931,42876.669741,3135.019061

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
6,Qwen/Qwen3-8B,gptq,English,2-bit,4.108156,4.662199,4.593693,4.606363,4.596503
9,Qwen/Qwen3-8B,gptq,Tamil,2-bit,4.642051,0.873260,4.664672,4.670482,4.531575
7,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,4.544935,4.508749,3.226292,4.541529,4.624799
8,Qwen/Qwen3-8B,gptq,Swahili,2-bit,4.643958,4.572244,4.622783,3.166420,4.405375
5,Qwen/Qwen3-8B,gptq,Chinese,2-bit,4.489204,4.365599,4.580982,4.616916,4.249957

           GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3  4.108156  4.642051  4.544935  4.643958  4.489204
TA_Qwen3  4.662199  0.873260  4.508749  4.572244  4.365599
ID_Qwen3  4.593693  4.664672  3.226292  4.622783  4.580982
SW_Qwen3  4.606363  4.670482  4.541529  3.166420  4.616916
ZH_Qwen3  4.596503  4.531575  4.624799  4.405375  4.249957

start model: CohereLabs/aya-expanse-8b

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
1,CohereLabs/aya-expanse-8b,gptq,English,2-bit,2.383521,4.348801,3.784685,4.346861,4.282580
4,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,2.872552,0.808635,3.811151,4.341208,3.967499
2,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,2.718155,3.623270,2.737043,4.152934,3.997845
3,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,2.916441,3.176520,3.635588,3.201836,4.169309
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,3.002846,3.626023,3.789999,4.319220,3.012777

         GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Aya  2.383521  2.872552  2.718155  2.916441  3.002846
TA_Aya  4.348801  0.808635  3.623270  3.176520  3.626023
ID_Aya  3.784685  3.811151  2.737043  3.635588  3.789999
SW_Aya  4.346861  4.341208  4.152934  3.201836  4.319220
ZH_Aya  4.282580  3.967499  3.997845  4.169309  3.012777

start model: meta-llama/Llama-3.1-8B-Instruct

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
11,meta-llama/Llama-3.1-8B-Instruct,gptq,English,2-bit,3.114075,NaN,4.504326,4.534616,4.591451
14,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,2-bit,3.928250,0.978895,4.589347,4.665602,4.501359
12,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,2-bit,3.786975,NaN,3.442164,4.289284,4.562845
13,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,2-bit,4.020273,NaN,4.433452,3.609202,4.668178
10,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,2-bit,3.885365,4.758571,4.551475,4.632221,3.496240

           GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Llama  3.114075  3.928250  3.786975  4.020273  3.885365
TA_Llama       NaN  0.978895       NaN       NaN  4.758571
ID_Llama  4.504326  4.589347  3.442164  4.433452  4.551475
SW_Llama  4.534616  4.665602  4.289284  3.609202  4.632221
ZH_Llama  4.591451  4.501359  4.562845  4.668178  3.496240

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH
ZH_Llama,36.821779,39034.718763,31721.858572,36546.410226,46577.700046,3135.019061
SW_Llama,30.056285,34246.515720,46302.289195,19466.319055,4066.321032,42876.669741
ID_Llama,24.823783,31939.373115,38846.104053,2767.984113,27130.168106,35602.009931
TA_Llama,2.311781,NaN,9.525656,NaN,NaN,57354.934756
EN_Llama,45.105214,1300.394068,8477.161407,6123.151827,10477.869747,7680.062329
ZH_Aya,112.084228,19168.145370,9278.960985,9950.510277,14767.553330,1029.857317
SW_Aya,347.245294,22225.967596,21938.558958,14221.136656,1591.607966,20855.464249
ID_Aya,92.363250,6090.955316,6473.671674,545.811702,4321.037729,6165.939366
TA_Aya,3.798334,22325.499442,6.436282,4200.197925,1501.481445,4226.914393
EN_Aya,53.754913,241.836277,745.679240,522.582423,824.976137,1006.574886
ZH_Qwen3,46.980806,39491.465990,34007.536689,42150.094142,25431.655621,17781.024879
SW_Qwen3,64.534645,40398.302421,46825.504463,34796.007236,1466.964319,41391.915611
ID_Qwen3,16.699008,39236.778388,46203.199536,1683.806307,41954.948059,38104.965297
TA_Qwen3,2.741605,45940.807067,7.468949,32266.297200,37346.013068,23205.924496
EN_Qwen3,33.428698,12827.901762,43858.254034,35069.944932,44051.236215,30846.394995

          UQ      GPTQ-EN       GPTQ-TA      GPTQ-ID      GPTQ-SW      GPTQ-ZH
ZH_Llama NaN     0.000000      0.000000     0.000000     0.000000     0.000000
SW_Llama NaN     0.000000      0.000000     0.000000     0.000000     0.000000
ID_Llama NaN     0.000000      0.000000     0.000000     0.000000     0.000000
TA_Llama NaN          NaN      0.000000          NaN          NaN     0.000000
EN_Llama NaN     0.000000      0.000000     0.000000     0.000000     0.000000
ZH_Aya   NaN  1543.522189   1302.353438   866.080047  1180.853398    18.945158
SW_Aya   NaN  1277.195624   2050.239999  1152.198626    33.017260  2340.085532
ID_Aya   NaN   785.551907    453.403569    36.465574   597.968991   748.488685
TA_Aya   NaN  6727.004278      0.242481  1013.398744   576.594778  1135.284190
EN_Aya   NaN     6.347335     60.775949    25.456456    80.773855    75.660850
ZH_Qwen3 NaN  4322.025321  12652.174248  1814.625584   214.562658  1521.218809
SW_Qwen3 NaN  1545.126299     41.811051  3225.378802   119.318857  6205.821677
ID_Qwen3 NaN   607.573270   5893.246746   463.524607  2132.436617  4590.185765
TA_Qwen3 NaN  3672.782474      0.417630  3505.411760  1535.747660  1813.483650
EN_Qwen3 NaN   269.191572   3137.501577  1463.765358  1602.262531   492.546412

## Shape
df text: (15, 6)
df std: (15, 6)
Display df

,UQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH
ZH_Llama,36.821779,39034.718763,31721.858572,36546.410226,46577.700046,3135.019061
SW_Llama,30.056285,34246.515720,46302.289195,19466.319055,4066.321032,42876.669741
ID_Llama,24.823783,31939.373115,38846.104053,2767.984113,27130.168106,35602.009931
TA_Llama,2.311781,NaN,9.525656,NaN,NaN,57354.934756
EN_Llama,45.105214,1300.394068,8477.161407,6123.151827,10477.869747,7680.062329
ZH_Aya,112.084228,19168.145370,9278.960985,9950.510277,14767.553330,1029.857317
SW_Aya,347.245294,22225.967596,21938.558958,14221.136656,1591.607966,20855.464249
ID_Aya,92.363250,6090.955316,6473.671674,545.811702,4321.037729,6165.939366
TA_Aya,3.798334,22325.499442,6.436282,4200.197925,1501.481445,4226.914393
EN_Aya,53.754913,241.836277,745.679240,522.582423,824.976137,1006.574886
ZH_Qwen3,46.980806,39491.465990,34007.536689,42150.094142,25431.655621,17781.024879
SW_Qwen3,64.534645,40398.302421,46825.504463,34796.007236,1466.964319,41391.915611
ID_Qwen3,16.699008,39236.778388,46203.199536,1683.806307,41954.948059,38104.965297
TA_Qwen3,2.741605,45940.807067,7.468949,32266.297200,37346.013068,23205.924496
EN_Qwen3,33.428698,12827.901762,43858.254034,35069.944932,44051.236215,30846.394995

Display df std

         UQ GPTQ-EN GPTQ-TA GPTQ-ID GPTQ-SW GPTQ-ZH
ZH_Llama
SW_Llama
ID_Llama
TA_Llama
EN_Llama
ZH_Aya       1.5e+3  1.3e+3   866.1  1.2e+3   18.95
SW_Aya       1.3e+3  2.1e+3  1.2e+3   33.02  2.3e+3
ID_Aya        785.6   453.4   36.47   598.0   748.5
TA_Aya       6.7e+3    0.24  1.0e+3   576.6  1.1e+3
EN_Aya         6.35   60.78   25.46   80.77   75.66
ZH_Qwen3     4.3e+3  1.3e+4  1.8e+3   214.6  1.5e+3
SW_Qwen3     1.5e+3   41.81  3.2e+3   119.3  6.2e+3
ID_Qwen3      607.6  5.9e+3   463.5  2.1e+3  4.6e+3
TA_Qwen3     3.7e+3    0.42  3.5e+3  1.5e+3  1.8e+3
EN_Qwen3      269.2  3.1e+3  1.5e+3  1.6e+3   492.5

Writing to pdf ...

/tmp/ipykernel_9034/1384151445.py:165: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605e+00,16.699008,64.534645,4.698081e+01
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334e+00,92.363250,347.245294,1.120842e+02
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781e+00,24.823783,30.056285,3.682178e+01
0,Qwen/Qwen3-8B,slimllm,2-bit,English,136.421333,7.868718e+03,2487.644477,7155.155728,1.018849e+06
13,Qwen/Qwen3-8B,slimllm,2-bit,English,145.947709,8.446240e+03,1964.873514,5453.784432,3.923998e+05
14,Qwen/Qwen3-8B,slimllm,2-bit,English,172.354644,2.798914e+04,3029.195500,7569.894285,5.910075e+05
2,Qwen/Qwen3-8B,slimllm,2-bit,Tamil,9540.976268,4.296940e+00,8528.090849,6611.650597,9.224233e+04
17,Qwen/Qwen3-8B,slimllm,2-bit,Tamil,7745.881492,4.538700e+00,12113.386430,4837.904436,4.929471e+04
18,Qwen/Qwen3-8B,slimllm,2-bit,Tamil,3384.443502,4.493130e+00,13752.340316,8127.880981,3.896194e+04
1,Qwen/Qwen3-8B,slimllm,2-bit,Indonesian,1875.621188,2.773605e+04,213.786506,4277.163314,6.036315e+05
15,Qwen/Qwen3-8B,slimllm,2-bit,Indonesian,577.247574,4.120298e+03,73.732069,1271.837143,3.051602e+05
16,Qwen/Qwen3-8B,slimllm,2-bit,Indonesian,779.038622,4.165074e+03,82.225937,2591.754752,3.253010e+05
3,Qwen/Qwen3-8B,slimllm,2-bit,Swahili,1295.647887,1.297831e+03,734.790496,755.834788,2.030617e+05
19,Qwen/Qwen3-8B,slimllm,2-bit,Swahili,1573.397731,1.121417e+04,756.947240,438.488703,2.583997e+05
20,Qwen/Qwen3-8B,slimllm,2-bit,Swahili,3141.810162,5.906339e+03,612.137590,425.096027,1.422033e+06
4,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,4070.391396,6.230998e+03,17901.847298,14441.185178,2.967870e+02
21,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,4209.958053,2.517425e+04,12823.592259,27768.908708,3.965303e+02
22,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,8946.461382,4.546049e+04,25457.411743,15489.593320,3.867438e+02
5,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,126.665861,7.374725e+05,65378.469956,8350.373145,6.745728e+06
23,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,135.653633,4.487779e+05,26241.840456,8612.168775,6.386107e+06
24,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,147.769707,4.681287e+04,51377.790088,12972.453747,9.097430e+06
6,CohereLabs/aya-expanse-8b,slimllm,2-bit,Indonesian,242.230468,5.656487e+05,222.244075,5041.660038,2.213893e+06
25,CohereLabs/aya-expanse-8b,slimllm,2-bit,Indonesian,266.582063,7.728964e+05,247.753199,7144.640169,1.417499e+06
26,CohereLabs/aya-expanse-8b,slimllm,2-bit,Indonesian,297.591744,8.487007e+03,228.479655,4497.698899,1.262017e+06
7,CohereLabs/aya-expanse-8b,slimllm,2-bit,Swahili,405.966345,1.778943e+06,1264.551947,440.483106,1.380743e+06
27,CohereLabs/aya-expanse-8b,slimllm,2-bit,Swahili,428.449300,3.989524e+04,1395.717011,450.125152,1.540993e+06
28,CohereLabs/aya-expanse-8b,slimllm,2-bit,Swahili,169.251393,2.567245e+03,473.197985,366.143598,9.287707e+04
8,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,9591.055847,6.648169e+05,547790.766444,88041.956030,2.636727e+02
29,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,2608.649296,4.793396e+04,436945.540469,34314.908527,2.648757e+02
30,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,1666.300382,1.576516e+05,469420.311523,30110.857793,2.937042e+02
9,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,English,1310.330378,1.325875e+07,90340.666504,48436.726164,1.182826e+07
10,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Indonesian,24646.872946,2.981072e+06,83638.050378,33877.892535,1.889792e+06
11,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Swahili,47030.845866,5.918960e+05,125363.488876,67971.386394,3.922542e+06
12,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,6997.865099,2.128250e+05,54669.471081,20333.921389,2.407567e+03

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Qwen3, TA_Qwen3, ID_Qwen3, SW_Qwen3, ZH_Qwen3]

start model: CohereLabs/aya-expanse-8b

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Aya, TA_Aya, ID_Aya, SW_Aya, ZH_Aya]

start model: meta-llama/Llama-3.1-8B-Instruct

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Llama, TA_Llama, ID_Llama, SW_Llama, ZH_Llama]

,UQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,36.821779,1.182826e+07,NaN,1.889792e+06,3.922542e+06,2407.566671
SW_Llama,30.056285,4.843673e+04,NaN,3.387789e+04,6.797139e+04,20333.921389
ID_Llama,24.823783,9.034067e+04,NaN,8.363805e+04,1.253635e+05,54669.471081
TA_Llama,2.311781,1.325875e+07,NaN,2.981072e+06,5.918960e+05,212825.012183
EN_Llama,45.105214,1.310330e+03,NaN,2.464687e+04,4.703085e+04,6997.865099
ZH_Aya,112.084228,7.409755e+06,NaN,1.631137e+06,1.004871e+06,274.084188
SW_Aya,347.245294,9.978332e+03,NaN,5.561333e+03,4.189173e+02,50822.574116
ID_Aya,92.363250,4.766603e+04,NaN,2.328256e+02,1.044489e+03,484718.872812
TA_Aya,3.798334,4.110211e+05,NaN,4.490107e+05,6.071352e+05,290134.141033
EN_Aya,53.754913,1.366964e+02,NaN,2.688014e+02,3.345557e+02,4622.001841
ZH_Qwen3,46.980806,6.674189e+05,60166.327417,4.113642e+05,6.278313e+05,360.020385
SW_Qwen3,64.534645,6.726278e+03,6525.812005,2.713585e+03,5.398065e+02,19233.229068
ID_Qwen3,16.699008,2.493904e+03,11464.605865,1.232482e+02,7.012918e+02,18727.617100
TA_Qwen3,2.741605,1.476803e+04,4.442923,1.200714e+04,6.139446e+03,25621.911270
EN_Qwen3,33.428698,1.515746e+02,6890.433754,1.077302e+03,2.003619e+03,5742.270277

,UQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,NaN,0.000000e+00,NaN,0.000000,0.000000,0.000000
SW_Llama,NaN,0.000000e+00,NaN,0.000000,0.000000,0.000000
ID_Llama,NaN,0.000000e+00,NaN,0.000000,0.000000,0.000000
TA_Llama,NaN,0.000000e+00,NaN,0.000000,0.000000,0.000000
EN_Llama,NaN,0.000000e+00,NaN,0.000000,0.000000,0.000000
ZH_Aya,NaN,1.202363e+06,NaN,416931.507561,648186.966924,13.882118
SW_Aya,NaN,2.119860e+03,NaN,1141.379148,37.523671,26373.980905
ID_Aya,NaN,1.619160e+04,NaN,10.858010,407.497337,46527.414954
TA_Aya,NaN,2.832218e+05,NaN,322783.452104,828733.377281,268700.417046
EN_Aya,NaN,8.647104e+00,NaN,22.655564,117.247604,3534.650256
ZH_Qwen3,NaN,2.613922e+05,23070.095350,136201.928434,562039.370899,44.890879
SW_Qwen3,NaN,9.155808e+02,1344.498076,1229.939922,152.852881,6050.793892
ID_Qwen3,NaN,4.345302e+02,2181.571725,64.114112,63.687162,5190.682069
TA_Qwen3,NaN,9.351708e+03,0.104889,11122.033868,4051.681957,16018.499530
EN_Qwen3,NaN,1.519971e+01,2585.158544,570.476116,812.771505,2266.421583

## Shape
df text: (15, 6)
df std: (15, 6)
Display df

,UQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,36.821779,1.182826e+07,NaN,1.889792e+06,3.922542e+06,2407.566671
SW_Llama,30.056285,4.843673e+04,NaN,3.387789e+04,6.797139e+04,20333.921389
ID_Llama,24.823783,9.034067e+04,NaN,8.363805e+04,1.253635e+05,54669.471081
TA_Llama,2.311781,1.325875e+07,NaN,2.981072e+06,5.918960e+05,212825.012183
EN_Llama,45.105214,1.310330e+03,NaN,2.464687e+04,4.703085e+04,6997.865099
ZH_Aya,112.084228,7.409755e+06,NaN,1.631137e+06,1.004871e+06,274.084188
SW_Aya,347.245294,9.978332e+03,NaN,5.561333e+03,4.189173e+02,50822.574116
ID_Aya,92.363250,4.766603e+04,NaN,2.328256e+02,1.044489e+03,484718.872812
TA_Aya,3.798334,4.110211e+05,NaN,4.490107e+05,6.071352e+05,290134.141033
EN_Aya,53.754913,1.366964e+02,NaN,2.688014e+02,3.345557e+02,4622.001841
ZH_Qwen3,46.980806,6.674189e+05,60166.327417,4.113642e+05,6.278313e+05,360.020385
SW_Qwen3,64.534645,6.726278e+03,6525.812005,2.713585e+03,5.398065e+02,19233.229068
ID_Qwen3,16.699008,2.493904e+03,11464.605865,1.232482e+02,7.012918e+02,18727.617100
TA_Qwen3,2.741605,1.476803e+04,4.442923,1.200714e+04,6.139446e+03,25621.911270
EN_Qwen3,33.428698,1.515746e+02,6890.433754,1.077302e+03,2.003619e+03,5742.270277

Display df std

         UQ SliM-LLM-EN SliM-LLM-TA SliM-LLM-ID SliM-LLM-SW SliM-LLM-ZH
ZH_Llama
SW_Llama
ID_Llama
TA_Llama
EN_Llama
ZH_Aya           1.2e+6                  4.2e+5      6.5e+5       13.88
SW_Aya           2.1e+3                  1.1e+3       37.52      2.6e+4
ID_Aya           1.6e+4                   10.86       407.5      4.7e+4
TA_Aya           2.8e+5                  3.2e+5      8.3e+5      2.7e+5
EN_Aya             8.65                   22.66       117.2      3.5e+3
ZH_Qwen3         2.6e+5      2.3e+4      1.4e+5      5.6e+5       44.89
SW_Qwen3          915.6      1.3e+3      1.2e+3       152.9      6.1e+3
ID_Qwen3          434.5      2.2e+3       64.11       63.69      5.2e+3
TA_Qwen3         9.4e+3        0.10      1.1e+4      4.1e+3      1.6e+4
EN_Qwen3          15.20      2.6e+3       570.5       812.8      2.3e+3

Writing to pdf ...

/tmp/ipykernel_9034/1384151445.py:165: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
0,Qwen/Qwen3-8B,tacq,2-bit,English,44.433395,14.577590,118.646514,391.554554,143.963070
15,Qwen/Qwen3-8B,tacq,2-bit,English,43.686757,15.899181,111.247007,366.070096,144.778099
16,Qwen/Qwen3-8B,tacq,2-bit,English,43.829801,16.064154,118.762163,382.603195,151.371892
2,Qwen/Qwen3-8B,tacq,2-bit,Tamil,63.757700,3.077032,92.515647,636.812635,118.763591
19,Qwen/Qwen3-8B,tacq,2-bit,Tamil,64.479079,3.051704,62.860820,337.954866,122.577796
20,Qwen/Qwen3-8B,tacq,2-bit,Tamil,64.872761,3.061076,62.655647,324.519293,117.045363
1,Qwen/Qwen3-8B,tacq,2-bit,Indonesian,51.815953,11.100248,21.584579,233.382701,120.666159
17,Qwen/Qwen3-8B,tacq,2-bit,Indonesian,53.063046,9.231703,21.896152,290.444647,117.141929
18,Qwen/Qwen3-8B,tacq,2-bit,Indonesian,52.785607,9.537242,21.972291,251.464948,128.507554
3,Qwen/Qwen3-8B,tacq,2-bit,Swahili,65.675437,9.829573,44.399969,68.737696,189.921930
21,Qwen/Qwen3-8B,tacq,2-bit,Swahili,64.947907,9.399164,43.860256,67.659524,165.731162
22,Qwen/Qwen3-8B,tacq,2-bit,Swahili,66.052117,10.605509,42.939566,71.312283,173.303352
4,Qwen/Qwen3-8B,tacq,2-bit,Chinese,60.223406,11.664861,135.163071,351.530185,62.536472
23,Qwen/Qwen3-8B,tacq,2-bit,Chinese,58.012939,12.544227,124.490184,382.761221,62.543916
24,Qwen/Qwen3-8B,tacq,2-bit,Chinese,59.327470,15.291020,121.765576,383.949787,64.136725
5,CohereLabs/aya-expanse-8b,tacq,2-bit,English,69.124340,15.326975,305.453742,1488.831546,352.034252
25,CohereLabs/aya-expanse-8b,tacq,2-bit,English,69.417247,16.126714,311.945240,1911.110534,378.789915
26,CohereLabs/aya-expanse-8b,tacq,2-bit,English,68.883655,12.764824,301.216844,1364.533252,351.086857
7,CohereLabs/aya-expanse-8b,tacq,2-bit,Tamil,91.792128,4.032991,213.560697,1533.151085,268.351270
29,CohereLabs/aya-expanse-8b,tacq,2-bit,Tamil,94.673259,4.052219,226.585703,1613.768943,278.909667
30,CohereLabs/aya-expanse-8b,tacq,2-bit,Tamil,93.151194,4.064053,235.820194,1487.995641,279.591417
6,CohereLabs/aya-expanse-8b,tacq,2-bit,Indonesian,81.004478,11.747359,113.634638,1343.616888,299.083253
27,CohereLabs/aya-expanse-8b,tacq,2-bit,Indonesian,80.412482,12.628553,119.083204,1543.538237,271.051149
28,CohereLabs/aya-expanse-8b,tacq,2-bit,Indonesian,81.568789,12.226416,118.695079,1146.953701,308.148443
8,CohereLabs/aya-expanse-8b,tacq,2-bit,Swahili,97.776450,10.504047,204.260095,342.506376,410.456943
31,CohereLabs/aya-expanse-8b,tacq,2-bit,Swahili,98.850604,10.082932,203.732166,333.068629,407.265983
32,CohereLabs/aya-expanse-8b,tacq,2-bit,Swahili,95.199483,10.107628,198.644097,320.552778,400.672744
9,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,87.566569,11.085941,287.207312,2165.595526,136.307643
33,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,86.254922,12.776039,322.690826,2640.984867,135.847607
34,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,83.905569,13.401760,283.077977,1899.481784,135.358869
10,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,English,71.305146,98.906951,409.737624,422.779281,698.255733
12,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Tamil,123.015885,2.790848,254.872068,329.592691,276.418416
11,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Indonesian,94.744345,11.290383,48.682029,208.366909,381.739075
13,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Swahili,108.396437,15.895496,135.912888,43.170179,1156.817653
14,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,110.839197,8.777216,481.666138,469.148661,68.792080

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
6,Qwen/Qwen3-8B,tacq,English,2-bit,0.323566,0.665306,3.515737,10.556345,3.317178
9,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.461728,0.010456,14.028029,144.154089,2.312004
7,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.534628,0.818386,0.167729,23.810479,4.750264
8,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.458314,0.499177,0.602931,1.532377,10.103402
5,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.907797,1.544423,5.781454,15.010444,0.752618
1,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.218186,1.433973,4.411970,233.931693,12.841869
4,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,1.176844,0.012800,9.131215,52.022620,5.145499
2,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.472105,0.360203,2.482059,161.906780,15.790946
3,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,1.532074,0.192958,2.532162,8.991836,4.074086
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,1.514478,0.978149,17.780479,306.709847,0.387395
11,meta-llama/Llama-3.1-8B-Instruct,tacq,English,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
14,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
12,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
13,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
10,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Qwen3, TA_Qwen3, ID_Qwen3, SW_Qwen3, ZH_Qwen3]

start model: CohereLabs/aya-expanse-8b

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Aya, TA_Aya, ID_Aya, SW_Aya, ZH_Aya]

start model: meta-llama/Llama-3.1-8B-Instruct

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Llama, TA_Llama, ID_Llama, SW_Llama, ZH_Llama]

,UQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,698.255733,276.418416,381.739075,1156.817653,68.792080
SW_Llama,30.056285,422.779281,329.592691,208.366909,43.170179,469.148661
ID_Llama,24.823783,409.737624,254.872068,48.682029,135.912888,481.666138
TA_Llama,2.311781,98.906951,2.790848,11.290383,15.895496,8.777216
EN_Llama,45.105214,71.305146,123.015885,94.744345,108.396437,110.839197
ZH_Aya,112.084228,360.637008,275.617452,292.760948,406.131890,135.838040
SW_Aya,347.245294,1588.158444,1544.971890,1344.702942,332.042594,2235.354059
ID_Aya,92.363250,306.205275,225.322198,117.137641,202.212119,297.658705
TA_Aya,3.798334,14.739504,4.049754,12.200776,10.231536,12.421246
EN_Aya,53.754913,69.141747,93.205527,80.995250,97.275513,85.909020
ZH_Qwen3,46.980806,146.704354,119.462250,122.105214,176.318815,63.072371
SW_Qwen3,64.534645,380.075948,433.095598,258.430765,69.236501,372.747064
ID_Qwen3,16.699008,116.218561,72.677371,21.817674,43.733264,127.139610
TA_Qwen3,2.741605,15.513642,3.063271,9.956398,9.944748,13.166703
EN_Qwen3,33.428698,43.983318,64.369847,52.554869,65.558487,59.187938

          UQ     TaCQ-EN     TaCQ-TA     TaCQ-ID    TaCQ-SW     TaCQ-ZH
ZH_Llama NaN    0.000000    0.000000    0.000000   0.000000    0.000000
SW_Llama NaN    0.000000    0.000000    0.000000   0.000000    0.000000
ID_Llama NaN    0.000000    0.000000    0.000000   0.000000    0.000000
TA_Llama NaN    0.000000    0.000000    0.000000   0.000000    0.000000
EN_Llama NaN    0.000000    0.000000    0.000000   0.000000    0.000000
ZH_Aya   NaN   12.841869    5.145499   15.790946   4.074086    0.387395
SW_Aya   NaN  233.931693   52.022620  161.906780   8.991836  306.709847
ID_Aya   NaN    4.411970    9.131215    2.482059   2.532162   17.780479
TA_Aya   NaN    1.433973    0.012800    0.360203   0.192958    0.978149
EN_Aya   NaN    0.218186    1.176844    0.472105   1.532074    1.514478
ZH_Qwen3 NaN    3.317178    2.312004    4.750264  10.103402    0.752618
SW_Qwen3 NaN   10.556345  144.154089   23.810479   1.532377   15.010444
ID_Qwen3 NaN    3.515737   14.028029    0.167729   0.602931    5.781454
TA_Qwen3 NaN    0.665306    0.010456    0.818386   0.499177    1.544423
EN_Qwen3 NaN    0.323566    0.461728    0.534628   0.458314    0.907797

## Shape
df text: (15, 6)
df std: (15, 6)
Display df

,UQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,698.255733,276.418416,381.739075,1156.817653,68.792080
SW_Llama,30.056285,422.779281,329.592691,208.366909,43.170179,469.148661
ID_Llama,24.823783,409.737624,254.872068,48.682029,135.912888,481.666138
TA_Llama,2.311781,98.906951,2.790848,11.290383,15.895496,8.777216
EN_Llama,45.105214,71.305146,123.015885,94.744345,108.396437,110.839197
ZH_Aya,112.084228,360.637008,275.617452,292.760948,406.131890,135.838040
SW_Aya,347.245294,1588.158444,1544.971890,1344.702942,332.042594,2235.354059
ID_Aya,92.363250,306.205275,225.322198,117.137641,202.212119,297.658705
TA_Aya,3.798334,14.739504,4.049754,12.200776,10.231536,12.421246
EN_Aya,53.754913,69.141747,93.205527,80.995250,97.275513,85.909020
ZH_Qwen3,46.980806,146.704354,119.462250,122.105214,176.318815,63.072371
SW_Qwen3,64.534645,380.075948,433.095598,258.430765,69.236501,372.747064
ID_Qwen3,16.699008,116.218561,72.677371,21.817674,43.733264,127.139610
TA_Qwen3,2.741605,15.513642,3.063271,9.956398,9.944748,13.166703
EN_Qwen3,33.428698,43.983318,64.369847,52.554869,65.558487,59.187938

Display df std

         UQ TaCQ-EN TaCQ-TA TaCQ-ID TaCQ-SW TaCQ-ZH
ZH_Llama
SW_Llama
ID_Llama
TA_Llama
EN_Llama
ZH_Aya        12.84    5.15   15.79    4.07    0.39
SW_Aya        233.9   52.02   161.9    8.99   306.7
ID_Aya         4.41    9.13    2.48    2.53   17.78
TA_Aya         1.43    0.01    0.36    0.19    0.98
EN_Aya         0.22    1.18    0.47    1.53    1.51
ZH_Qwen3       3.32    2.31    4.75   10.10    0.75
SW_Qwen3      10.56   144.2   23.81    1.53   15.01
ID_Qwen3       3.52   14.03    0.17    0.60    5.78
TA_Qwen3       0.67    0.01    0.82    0.50    1.54
EN_Qwen3       0.32    0.46    0.53    0.46    0.91

Writing to pdf ...

#### 3x Run + SINQ

In [8]:
import numpy as np
import re
def perplexity_heatmap_deliver_vertical_sinq(eval_languages, runs, base_models, quantization_technique, bit_width, eval_dataset, custom_title="", display_mean=True, compile=False, show_subline=True, hf_evaluate=False, zscore_threshold=1, gmean_aggregate=False, two_color=True, display_colorbar=True, embed_sinq=True, write_pdf=""):
  language_sort = {
      # # Flores Plus
      # "eng_Latn": 0, "fra_Latn": 1, "hin_Deva": 2, "npi_Deva": 3, "tam_Taml": 6, "tel_Telu": 7, "ind_Latn": 8, "zsm_Latn": 9, "swh_Latn": 10, "yor_Latn": 11, "cmn_Hans": 12, "jpn_Jpan": 13, "kor_Hang": 14, "arb_Arab" : 15,\
      # Wikipedia
      "en": 0, "fr": 1, "hi": 2, "ne": 3, "ta": 6, "te": 7, "id": 8, "ms": 9, "sw": 10, "yo": 11, "zh": 12, "ja": 13, "ko": 14, "ar": 15,\
      # INCLUDE
      "french": 1, "hindi": 2, "nepali": 3, "albanian": 4, "tamil": 6, "telugu": 7, "indonesian": 8, "malay": 9, "chinese": 12, "japanese": 13, "korean": 14, "arabic": 15,\
      # Global MMLU Lite
      "en": 0, "fr": 1, "hi": 2, "bn": 5, "id": 8, "sw": 10, "yo": 11, "zh": 12, "ja": 13, "ko": 14, "ar": 15,
  } # Add floresplus evals, and count their respective language's family
  family_counter = []
  if eval_dataset == 'floresplus':
    # flores_plus_add = ["afr_Latn", "dan_Latn", "deu_Latn", "eng_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"]
    flores_plus_add = ["eng_Latn", "tpi_Latn", "afr_Latn", "deu_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "ydd_Hebr", "dan_Latn", "fao_Latn", "isl_Latn", "nno_Latn", "nob_Latn", "swe_Latn"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 0 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
    flores_plus_add = ["kan_Knda", "mal_Mlym", "tam_Taml", "tel_Telu"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 6 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
    # flores_plus_add = ["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "ind_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"]
    flores_plus_add = ["ind_Latn", "zsm_Latn", "bjn_Latn", "min_Latn", "ace_Latn", "ban_Latn", "bug_Latn", "jav_Latn", "sun_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "fil_Latn", "war_Latn"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 8 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
    flores_plus_add = ["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "swh_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 10 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
    flores_plus_add = ["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant", "cmn_Hans"]
    for index, lang in enumerate(flores_plus_add):
      language_sort[lang] = 12 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in flores_plus_add]))
  elif eval_dataset == 'wikipedia':
    wikipedia_add = ["en", "de", "nl"]
    for index, lang in enumerate(wikipedia_add):
      language_sort[lang] = 0 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in wikipedia_add]))
    wikipedia_add = ["ml", "ta", "te"]
    for index, lang in enumerate(wikipedia_add):
      language_sort[lang] = 6 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in wikipedia_add]))
    wikipedia_add = ["id", "tl", "ms"]
    for index, lang in enumerate(wikipedia_add):
      language_sort[lang] = 8 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in wikipedia_add]))
    wikipedia_add = ["sw", "lg", "yo"]
    for index, lang in enumerate(wikipedia_add):
      language_sort[lang] = 10 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in wikipedia_add]))
    wikipedia_add = ["bo", "my", "zh"]
    for index, lang in enumerate(wikipedia_add):
      language_sort[lang] = 12 + index / 100
    if not compile:
      family_counter.append(sum([True if i in eval_languages else False for i in wikipedia_add]))
  eval_languages = list(sorted(eval_languages, key=lambda x: language_sort.get(x, 100)))
  # print(eval_languages)

  columns = ["Base Model", "Quantization Technique", "Bit Width", "Calibration Language"]
  columns.extend(eval_languages)
  custom_sort = {'Unquantized': 0, 'English': 1, 'Tamil': 2, 'Indonesian': 3, 'Swahili': 4, 'Chinese': 5, 'Sinq': 0.5,\
                 'Unquantized': 0, 'gptq': 1, 'slimllm': 2, 'tacq': 3, 'sinq': 0.5,\
                 "Qwen/Qwen3-8B": 0, "CohereLabs/aya-expanse-8b": 1, "meta-llama/Llama-3.1-8B-Instruct": 2, "Qwen/Qwen3-14B": 3}

  calib_label = {"English": "EN", "Tamil": "TA", "Indonesian": "ID", "Swahili": "SW", "Chinese": "ZH", "Sinq": "SINQ"}
  base_model_label = {"Qwen/Qwen3-8B": "Qwen3", "CohereLabs/aya-expanse-8b": "Aya", "meta-llama/Llama-3.1-8B-Instruct": "Llama", "Qwen/Qwen3-14B": "Qwen3 14B"}
  quantization_technique_label = {"UQ": "Unquantized", "gptq": "GPTQ", "slimllm": "SliM-LLM", "tacq": "TaCQ", "sinq": "SINQ"}
  eval_label = {
      # # Flores Plus
      "eng_Latn": "EN", "fra_Latn": "FR", "hin_Deva": "HI", "npi_Deva": "NE", "tam_Taml": "TA", "tel_Telu": "TE", "ind_Latn": "ID", "zsm_Latn": "ZSM", "swh_Latn": "SW", "yor_Latn": "YO", "cmn_Hans": "ZH", "jpn_Jpan": "JA", "kor_Hang": "KO", "arb_Arab" : "AR",\
      "ace_Latn": "ACE", "ban_Latn": "BAN", "bjn_Latn": "BJN", "bug_Latn": "BUG", "ceb_Latn": "CEB", "fij_Latn": "FIJ", "ilo_Latn": "ILO", "jav_Latn": "JAV", "min_Latn": "MIN", "plt_Latn": "PLT", "mri_Latn": "MRI", "pag_Latn": "PAG", "smo_Latn": "SMO", "sun_Latn": "SUN", "fil_Latn": "FIL", "war_Latn": "WAR",\
      # Wikipedia
      "en": "EN", "fr": "FR", "hi": "HI", "ne": "NE", "ta": "TA", "te": "TE", "id": "ID", "ms": "MS", "sw": "SW", "yo": "YO", "zh": "ZH", "ja": "JA", "ko": "KO", "ar": "AR",\
      # INCLUDE
      "french": "FR", "hindi": "HI", "nepali": "NE", "albanian": "SQ", "tamil": "TA", "telugu": "TE", "indonesian": "ID", "malay": "MS", "chinese": "ZH", "japanese": "JA", "korean": "KO", "arabic": "AR",\
      # Global MMLU Lite
      "en": "EN", "fr": "FR", "hi": "HI", "bn": "BN", "id": "ID", "sw": "SW", "yo": "YO", "zh": "ZH", "ja": "JA", "ko": "KO", "ar": "AR",
      # Multi Blimp
      "eng": "EN", "tam": "TA", "idn": "ID", "swa": "SW", "zhoblimp": "ZH",
      # # Belebele
      # "eng_Latn": "EN", "nld_Latn": "NL", "deu_Latn": "DE", "mal_Mlym": "ML", "tam_Taml": "TA", "tel_Telu": "TE", "ind_Latn": "ID", "tgl_Latn": "TE", "zsm_Latn": "MS", "swh_Latn": "SW", "yor_Latn": "YO", "lug_Latn": "LG", "bod_Tibt": "BO", "mya_Mymr": "MY", "zho_Hans": "ZH",
  }

  data_acc = []
  data_nancount = []

  data_gptq = []
  data_slimllm = []
  data_tacq = []

  # import numpy as np
  # data_slimllm.append(["-", "CohereLabs/aya-expanse-8b", "slimllm", "4-bit", "Tamil"] + [np.nan for _ in eval_languages])

  unquantized_data_acc = []

  # Iterate over the runs and print details
  for run in runs:
      config = run.config
      summary = run.summary

      if config["calibration_language"] == "WuuChinese":
        continue
      # Special case for SINQ, treat its calib lang as sinq
      if config["quantization_technique"] == "sinq":
        config["calibration_language"] = "Sinq"

      run_data_acc = []
      run_data_nancount = []
      run_data_acc.extend([run.config["base_model"], config["quantization_technique"], config["bit_width"], config["calibration_language"]])
      run_data_nancount.extend([run.config["base_model"], config["quantization_technique"], config["bit_width"], config["calibration_language"]])
      if not hf_evaluate:
        for lang in eval_languages:
          if lang in ["zh", "Chinese", "cmn_Hans", "ja", "Japanese", "jpn_Jpan", "bo", "Tibetan", "bod_Tibt", "dz", "Dzongkha", "dzo_Tibt", "Yue Chinese", "yue_Hant"]:
            acc = run.summary.get(f"{eval_dataset.lower()}_byte_acc_{lang}", None)
            nancount = run.summary.get(f"{eval_dataset.lower()}_nan_count_{lang}", 0)
            if acc:
              # acc = math.pow(acc, 1/3)
              pass
            run_data_acc.append(acc)
            run_data_nancount.append(nancount)
          else:
            run_data_acc.append(run.summary.get(f"{eval_dataset.lower()}_token_perplexity_{lang}",
                                                run.summary.get(f"{eval_dataset.lower()}_word_acc_{lang}", None)
                                                ))
            run_data_nancount.append(run.summary.get(f"{eval_dataset.lower()}_nan_count_{lang}", 0))
      elif hf_evaluate:
        for lang in eval_languages:
          if gmean_aggregate:
            run_data_acc.append(run.summary.get(f"{eval_dataset.lower()}_gmean_perplexity_{lang}",
                                                run.summary.get(f"{eval_dataset.lower()}_word_acc_{lang}", None)
                                                ))
          else:
            run_data_acc.append(run.summary.get(f"{eval_dataset.lower()}_token_perplexity_{lang}",
                                                run.summary.get(f"{eval_dataset.lower()}_word_acc_{lang}", None)
                                                ))
          run_data_nancount.append(run.summary.get(f"{eval_dataset.lower()}_nancount_{lang}", 0))
      if config["quantization_technique"] == "Unquantized":
        unquantized_data_acc.append(run_data_acc)
        # data_nancount.append(run_data_nancount)
      elif config["quantization_technique"] == "gptq":
        data_gptq.append(run_data_acc)
        # data_nancount.append(run_data_nancount)
      elif config["quantization_technique"] == "slimllm":
        data_slimllm.append(run_data_acc)
        # data_nancount.append(run_data_nancount)
      elif config["quantization_technique"] == "tacq":
        data_tacq.append(run_data_acc)
        # data_nancount.append(run_data_nancount)
      elif config["quantization_technique"] == "sinq":
        run_data_acc[1] = "gptq"
        data_gptq.append(run_data_acc.copy())
        run_data_acc[1] = "slimllm"
        data_slimllm.append(run_data_acc.copy())
        run_data_acc[1] = "tacq"
        data_tacq.append(run_data_acc.copy())

  # make sure sinq is not the only datum in each quant data, check by the calib langs
  if embed_sinq:
    calib_langs = set([datum[3] for datum in data_gptq])
    if len(calib_langs) == 1 and "Sinq" in calib_langs:
      data_gptq = []
    calib_langs = set([datum[3] for datum in data_slimllm])
    if len(calib_langs) == 1 and "Sinq" in calib_langs:
      data_slimllm = []
    calib_langs = set([datum[3] for datum in data_tacq])
    if len(calib_langs) == 1 and "Sinq" in calib_langs:
      data_tacq = []

  df_unquantized_acc_chief = pd.DataFrame(unquantized_data_acc, columns=columns)
  df_gptq_chief = pd.DataFrame(data_gptq, columns=columns).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_slimllm_chief = pd.DataFrame(data_slimllm, columns=columns).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_tacq_chief = pd.DataFrame(data_tacq, columns=columns).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))

  display(pd.concat([df_unquantized_acc_chief, df_gptq_chief, df_slimllm_chief, df_tacq_chief], axis=0))

  # with pd.option_context('display.max_rows', None):

  # Unquantized
  df_unquantized_acc_chief_std = df_unquantized_acc_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std")

  # GPTQ agg
  df_gptq_chief_std = df_gptq_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std", ddof=0).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_gptq_chief = df_gptq_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("mean").sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))

  # Slim agg
  df_slimllm_chief_std = df_slimllm_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std", ddof=0).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_slimllm_chief = df_slimllm_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("mean").sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))

  # Tacq agg
  df_tacq_chief_std = df_tacq_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std", ddof=0).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_tacq_chief = df_tacq_chief.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("mean").sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  with pd.option_context('display.max_rows', None):
    display(df_tacq_chief_std)
  display(df_gptq_chief.columns)

  # display(df_gptq_chief_acc)
  # display(df_gptq_chief_std)

  df_gptq_chief[df_gptq_chief.columns[4:]] = df_gptq_chief[df_gptq_chief.columns[4:]].astype(float)
  df_slimllm_chief[df_slimllm_chief.columns[4:]] = df_slimllm_chief[df_slimllm_chief.columns[4:]].astype(float)
  df_tacq_chief[df_tacq_chief.columns[4:]] = df_tacq_chief[df_tacq_chief.columns[4:]].astype(float)
  df_unquantized_acc_chief[df_unquantized_acc_chief.columns[4:]] = df_unquantized_acc_chief[df_unquantized_acc_chief.columns[4:]].astype(float)

  # Easying aggregate calculation
  # Perplexity related, change order of PPL
  df_gptq_chief.iloc[:, 4:] = df_gptq_chief.iloc[:, 4:].apply(np.log10)
  df_slimllm_chief.iloc[:, 4:] = df_slimllm_chief.iloc[:, 4:].apply(np.log10)
  df_tacq_chief.iloc[:, 4:] = df_tacq_chief.iloc[:, 4:].apply(np.log10)
  df_unquantized_acc_chief.iloc[:, 4:] = df_unquantized_acc_chief.iloc[:, 4:].apply(np.log10)


  fig = go.Figure()

  df_chief = pd.DataFrame([])
  df_chief_std = pd.DataFrame([])
  df_zscore_chief = pd.DataFrame([])
  index_border_chief = [(0, 0)]
  # for base_model in ["CohereLabs/aya-expanse-8b"]:
  for base_model in base_models:
    print(f"start model: {base_model}")
    df_gptq = df_gptq_chief.loc[df_gptq_chief["Base Model"] == base_model]
    df_slimllm = df_slimllm_chief.loc[df_slimllm_chief["Base Model"] == base_model]
    df_tacq = df_tacq_chief.loc[df_tacq_chief["Base Model"] == base_model]
    df_unquantized_acc = df_unquantized_acc_chief.loc[df_unquantized_acc_chief["Base Model"] == base_model]
    df_gptq_std = df_gptq_chief_std.loc[df_gptq_chief_std["Base Model"] == base_model]
    df_slimllm_std = df_slimllm_chief_std.loc[df_slimllm_chief_std["Base Model"] == base_model]
    df_tacq_std = df_tacq_chief_std.loc[df_tacq_chief_std["Base Model"] == base_model]
    df_unquantized_acc_std = df_unquantized_acc_chief_std.loc[df_unquantized_acc_chief_std["Base Model"] == base_model]
    display(df_gptq)

    # display(df_unquantized_acc)
    base_model = base_model_label[base_model]

    df_gptq_std = df_gptq_std.iloc[:, 4:].T.rename(df_gptq_std['Quantization Technique'].apply(lambda x: quantization_technique_label.get(x, x)) + '-' + df_gptq_std['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    df_slimllm_std = df_slimllm_std.iloc[:, 4:].T.rename(df_slimllm_std['Quantization Technique'].apply(lambda x: quantization_technique_label.get(x, x)) + '-' + df_slimllm_std['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    df_tacq_std = df_tacq_std.iloc[:, 4:].T.rename(df_tacq_std['Quantization Technique'].apply(lambda x: quantization_technique_label.get(x, x)) + '-' + df_tacq_std['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    df_unquantized_acc_std = df_unquantized_acc_std.iloc[:, 4:].T.rename(lambda x: "UQ", axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')

    # Take only the result and reformat the indices
    # df_gptq = df_gptq.iloc[:, 5:].sub(df_unquantized_acc.iloc[:, 5:].values).T.rename(df_gptq['Quantization Technique'].apply(lambda x: x[0].upper()) + '-' + df_gptq['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    df_gptq = df_gptq.iloc[:, 4:].T.rename(df_gptq['Quantization Technique'].apply(lambda x: quantization_technique_label.get(x, x)) + '-' + df_gptq['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    if display_mean:
      df_gptq = pd.concat([df_gptq.T, df_gptq.mean(axis=0).to_frame('Mean')], axis=1).T
    df_gptq = df_gptq.astype(float)
    display(df_gptq)

    # df_slimllm = df_slimllm.iloc[:, 5:].sub(df_unquantized_acc.iloc[:, 5:].values).T.rename(df_slimllm['Quantization Technique'].apply(lambda x: x[0].upper()) + '-' + df_slimllm['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    df_slimllm = df_slimllm.iloc[:, 4:].T.rename(df_slimllm['Quantization Technique'].apply(lambda x: quantization_technique_label.get(x, x)) + '-' + df_slimllm['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    if display_mean:
      df_slimllm = pd.concat([df_slimllm.T, df_slimllm.mean(axis=0).to_frame('Mean')], axis=1).T
    df_slimllm = df_slimllm.astype(float)

    # df_tacq = df_tacq.iloc[:, 5:].sub(df_unquantized_acc.iloc[:, 5:].values).T.rename(df_tacq['Quantization Technique'].apply(lambda x: x[0].upper()) + '-' + df_tacq['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    df_tacq = df_tacq.iloc[:, 4:].T.rename(df_tacq['Quantization Technique'].apply(lambda x: quantization_technique_label.get(x, x)) + '-' + df_tacq['Calibration Language'].apply(lambda x: calib_label[x]), axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    if display_mean:
      df_tacq = pd.concat([df_tacq.T, df_tacq.mean(axis=0).to_frame('Mean')], axis=1).T
    df_tacq = df_tacq.astype(float)

    df_unquantized_acc = df_unquantized_acc.iloc[:, 4:].T.rename(lambda x: "UQ", axis='columns').rename(lambda x: eval_label.get(x, x) + "_" + base_model, axis='index')
    if display_mean:
      df_unquantized_acc = pd.concat([df_unquantized_acc, df_unquantized_acc.mean(axis=0).to_frame(f'Mean_{base_model}').T], axis=0)
    df = pd.concat([df_gptq, df_slimllm, df_tacq], axis=1)
    df_std = pd.concat([df_gptq_std, df_slimllm_std, df_tacq_std], axis=1)
    df_mean_quantized = df.mean(axis=1).to_frame('Mean of Quantized')
    # display(df_unquantized_acc)

    for iter, (index_row, index_col) in enumerate([df_unquantized_acc.shape, df_gptq.shape, df_slimllm.shape, df_tacq.shape]):
      if iter != 0:
        index_row = 0
      index_border_chief.append((index_border_chief[-1][0] + index_row, index_border_chief[-1][1] + index_col))

    from scipy.stats import zscore
    df_zscore_gptq = pd.DataFrame(zscore(df_gptq, axis=1, nan_policy='omit'), columns=df_gptq.columns, index=df_gptq.index)
    df_zscore_slimllm = pd.DataFrame(zscore(df_slimllm, axis=1, nan_policy='omit'), columns=df_slimllm.columns, index=df_slimllm.index)
    df_zscore_tacq = pd.DataFrame(zscore(df_tacq, axis=1, nan_policy='omit'), columns=df_tacq.columns, index=df_tacq.index)

    # Skip mean of quantized
    df_zscore = pd.concat([pd.Series(np.zeros_like(df_zscore_tacq.index), index=df_zscore_tacq.index, name="UQ"), df_zscore_gptq, df_zscore_slimllm, df_zscore_tacq], axis=1)

    df = pd.concat([df_unquantized_acc, df], axis=1)
    df_chief = pd.concat([df_chief, df], axis=0)
    df_zscore_chief = pd.concat([df_zscore_chief, df_zscore], axis=0)

    df_std = pd.concat([df_unquantized_acc_std, df_std], axis=1)
    df_chief_std = pd.concat([df_chief_std, df_std], axis=0)

  # Revariable for onness usage of df, we was using chief for the sake of differentiating between chief and iter df
  df = df_chief
  df_std = df_chief_std
  df_zscore = df_zscore_chief
  df = df.rename(lambda x: eval_label.get(x, x), axis=0)
  df_std = df_std.rename(lambda x: eval_label.get(x, x), axis=0)
  df_zscore = df_zscore.rename(lambda x: eval_label.get(x, x), axis=0)
  # display(df)
  # display(df_zscore)

  # Rebase the number
  df = df.apply(lambda x: 10 ** x)

  # display(df)
  # display(df_zscore)
  if not display_mean:
    df = df.reindex(index=df.index[::-1])
    df_std = df_std.reindex(index=df_std.index[::-1])
    df_zscore = df_zscore.reindex(index=df_zscore.index[::-1])
  display(df)
  display(df_std)

  # df_text = df.copy().map(lambda x: f"x10^{x:.1f}" if not np.isnan(x) else "-")
  # df_text = df.copy().map(lambda x: f"{(10**x):.2f}" if x < 3 else f"{(10**x):.1e}" if not np.isnan(x) else "-")
  df_std = df_std.map(lambda x: f"{x:.2f}" if 0 < x < 100 else f"{x:.1f}" if 0 < x < 1000 else re.sub(r'([eE][+-])0+(?=\d)', r'\1', f"{x:.1e}") if (not np.isnan(x) and not x == 0) else "")
  df_text = df.copy().map(lambda x: f"{x:.2f}" if x < 100 else f"{x:.1f}" if x < 1000 else re.sub(r'([eE][+-])0+(?=\d)', r'\1', f"{x:.1e}") if not np.isnan(x) else "-")
  # df_text = list(zip(df_text.values, df_std.values))
  print("## Shape")
  print(f"df text: {df_text.shape}")
  print(f"df std: {df_std.shape}")
  df_text = [list(zip(x, y)) for x, y in list(zip(df_text.values.tolist(), df_std.values.tolist()))]
  # df_text.iloc[:, 0] = df_text.iloc[:, 0].apply(lambda x: x[1:])

  # Color palette use this: Green: https://colordesigner.io/gradient-generator from 255, 255, 255 to 6, 54, 21, Red: https://colordesigner.io/gradient-generator from 255, 255, 255 to 214, 39, 40
  def exact_zscore_scale(z, df_zscore):
    return (z - df_zscore.min(axis=None)) / (df_zscore.max(axis=None) - df_zscore.min(axis=None))
  # Add 0, then iteratively add green and red until it touch min 0 or max 1
  colorscale = []
  # If light = good, dark = bad
  if not two_color:
    colorscale = [[0, 'rgba(255, 255, 255, 0.85)'], [1, 'rgba(214, 39, 40, 0.85)']]
  # For two color signaling, e.g. red = bad, green = good
  else:
    colorscale = [[exact_zscore_scale(0, df_zscore), 'rgba(255, 255, 255, 0.85)']]
    # Green for negativee z   1. Three scale different color, 2. Normal, 3. Thresholded z-score
    if zscore_threshold >= 1:
      color_zip = zip([-1+10**-5, -1, -2, -3], ['rgba(255, 255, 255, 0.85)', 'rgba(144, 166, 151, 0.85)', 'rgba(61, 99, 73, 0.85)', 'rgba(6,54,21, 0.85)'])
    elif zscore_threshold >= 1/2:
      color_zip = zip([-1/2+10**-5, -1/2, -2, -3], ['rgba(255, 255, 255, 0.85)', 'rgba(144, 166, 151, 0.85)', 'rgba(61, 99, 73, 0.85)', 'rgba(6,54,21, 0.85)'])
    else:
      # color_zip = zip([-1, -2, -3], ['rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)'])
      color_zip = zip([-3], ['rgba(6,54,21, 0.85)'])
    # for z, color in zip([1, 2, 3], ['rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)']):
    # for z, color in zip([1, 2, 3], ['rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)']):
    for z, color in color_zip:
    # for z, color in zip([-10**-5, -1, -1-10**-5, -2, -3], ['rgba(0,255,255, 0.85)', 'rgba(0,255,255, 0.85)', 'rgba(6,54,21, 0.85)', 'rgba(6,54,21, 0.85)', 'rgba(191,139,255, 0.85)']):
    # for z, color in zip([-1, -1-10**(-5), -2], ['rgba(144, 166, 151, 0.85)', 'rgba(89, 121, 99, 0.85)', 'rgba(6,54,21, 0.85)']):
    # for z, color in zip([-1+10**-5, -1, -2, -3], ['rgba(255, 255, 255, 0.85)', 'rgba(144, 166, 151, 0.85)', 'rgba(61, 99, 73, 0.85)', 'rgba(6,54,21, 0.85)']):
      z_scale = exact_zscore_scale(z, df_zscore)
      colorscale.insert(0, [max(0, z_scale), color])
      if z_scale < 0:
        break
    # Red for positive z
    if zscore_threshold >= 1:
      color_zip = zip([1-10**-5, 1, 2, 3], ['rgba(255, 255, 255, 0.85)', 'rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)'])
    elif zscore_threshold >= 1/2:
      color_zip = zip([1/2-10**-5, 1/2, 2, 3], ['rgba(255, 255, 255, 0.85)', 'rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)'])
    else:
      # color_zip = zip([1, 2, 3], ['rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)'])
      color_zip = zip([3], ['rgba(214, 39, 40, 0.85)'])
    # for z, color in zip([1, 2, 3], ['rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)']):
    # for z, color in zip([1, 2, 3], ['rgba(228, 111, 112, 0.85)', 'rgba(223, 87, 88, 0.85)', 'rgba(214, 39, 40, 0.85)']):
    for z, color in color_zip:
      z_scale = exact_zscore_scale(z, df_zscore)
      colorscale.append([min(1, z_scale), color])
      if z_scale > 1:
        break
  print("Display df")
  display(df)
  print("Display df std")
  display(df_std)
  # Helper how much space to differentiate each SINQ
  convert_to_space = {
      "UQ": '',
      "GPTQ": '',
      "SliM": ' ',
      "TaCQ": '  ',
  }
  fig = go.Figure(data=go.Heatmap(
                      z=df_zscore,
                      x=[[f"{convert_to_space.get(col_name.split('-')[0])}SINQ{convert_to_space.get(col_name.split('-')[0])}" if col_name.split("-")[-1] == "SINQ" else col_name.split("-")[0] if col_name != "UQ" else "16-bit" for col_name in df_zscore.columns],
                       ["-" if col_name.split("-")[-1] == "SINQ" else col_name.split("-")[-1] if col_name != "UQ" else "-" for col_name in df_zscore.columns]],
                      # Trying to rotate -90 for y axis, but alas
                      # y=[[f"""<span style='rotate: 0.5turn; display: inline-block;'> {idx_name.split("_")[-1]} </span>""" for idx_name in df_zscore.index],
                      #  [f"""<span style='rotate: -90deg;'> {idx_name.split("_")[-0]} </span>""" for idx_name in df_zscore.index]],
                      y=[[f"""{idx_name.split("_")[-1]}""" for idx_name in df_zscore.index],
                       [f"""{idx_name.split("_")[-0]}""" for idx_name in df_zscore.index]],
                      # text=[list(zip(x, y)) for x, y in list(zip(pd.concat([df_unquantized_acc, df, df_mean_quantized], axis=0).T.values.tolist(), df_nancount_all.T.values.tolist()))],
                      text=df_text,
                      # texttemplate="×10^%{text:.1f}",
                      texttemplate="%{text[0]}<sub>%{text[1]}</sub>",
                      # colorscale='Viridis',
                      # colorscale= [[0, 'rgba(6,54,21, 0.85)'],
                      #               [(0 - df_zscore.min(axis=None)) / (df_zscore.max(axis=None) - df_zscore.min(axis=None)), 'rgba(255, 255, 255, 0.85)'],
                      #               [1, 'rgba(214, 39, 40, 0.85)']],
                      colorscale=colorscale,
                      # colorbar=dict(title='Z-score'),
                      textfont={"size":28 if bit_width == 4 else 22 if bit_width == 3 else 17, "family": "Arial Black"},
                  ))
  # if bit_width == 4:
  fig.update_layout(
      xaxis=dict(title_font=dict(size=18), tickfont=dict(size=18)),
      yaxis=dict(title_font=dict(size=18), tickfont=dict(size=18))
  )
  # print(colorscale)

  # Horizontal each Eval Languages
  row_gptq, col_gptq = df_gptq.shape
  row_slimllm, col_slimllm = df_slimllm.shape
  row_tacq, col_tacq = df_tacq.shape
  row, col = df_zscore.shape
  offset_mean = 0 if display_mean else 1
  # Horizontal Line
  fig.add_shape(type="line",
                x0=-0.5, y0=row+offset_mean-1.5, x1=col-0.5, y1=row+offset_mean-1.5,
                line=dict(color="black", width = 1),
                )
  # # Vertical Line
  # fig.add_shape(type="line",
  #               x0=col-1.5, y0=-0.5, x1=col-1.5, y1=row-1.5,
  #               line=dict(color="black", width = 5),
  #               )
  # Vertical Each Quant Tech
  # print(index_border_chief)
  for (row_each, col_each) in index_border_chief[:5]:
    fig.add_shape(type="line",
                  x0=col_each-0.5, y0=-0.5, x1=col_each-0.5, y1=row+offset_mean-1.5,
                  line=dict(color="black", width = 5),
                  )
  # Horizontal Each Quant Tech
  for (row_each, col_each) in index_border_chief:
    fig.add_shape(type="line",
                  x0=-0.5, y0=row_each-0.5, x1=col-0.5, y1=row_each-0.5,
                  line=dict(color="black", width = 1),
                  )
  if show_subline:
    if not display_mean:
      family_counter = list(reversed(family_counter))
    # Horizontal Each Family Language Evaluation
    row_cum = 0
    # for row_each in family_counter:
    for row_each in family_counter * len(base_models):
      row_cum += row_each
      fig.add_shape(type="line",
                    x0=-0.5, y0=row_cum-0.5, x1=col-0.5, y1=row_cum-0.5,
                    line=dict(color="black", width = 1),
                    )

  fig.update_xaxes(automargin=False)
  fig.update_yaxes(automargin=False)
  fig.update_layout(
      # title_text=f"{base_model} {custom_title} {eval_dataset} (Max 1.0, +other language improve): Delta acc with Unquantized of <b>{quantization_technique} {bit_width}-bit</b> model",
      xaxis_title_text='Quantization Technique - Calibration Language',
      yaxis_title_text='Base Model - Eval Language',
      margin=dict(t=85, b=10 if write_pdf else 0, l=160, r=110 if display_colorbar else 0)
  ) # top 70 != 4bit else 90, left 120 != 4bit else 165
  fig.update_layout(coloraxis_colorbar_title_side="right")
  if not display_mean:
    fig.update_xaxes(side="top")

  fig.layout.height = 85 + 35 * row + (10 if write_pdf else 0)
  fig.layout.width = 160 + 89 * col + (110 if display_colorbar else 0)

  # Color bar annotation
  if not display_colorbar:
    fig.update_traces(showscale=False)
  if display_colorbar:
    fig.update_layout(
        # margin=dict(r=150),
        # ^^ making a bit of space for the annotation
        annotations=[
            dict(
                text="Z-score",
                font_size=20,
                font_family='Arial',
                # font_color='red',
                textangle=90,
                showarrow=False,
                # ^^ appearance
                xref="paper",
                yref="paper",
                x=1 + (5 + 10 * col)/(fig.layout.margin.l + fig.layout.width + fig.layout.margin.r),
                y=0.5,
                # ^^ position
            ),
        ]
    )

  # fig.update_traces(showscale=False)
  # fig.update_layout(yaxis_visible=False, yaxis_showticklabels=False)

  fig.show()
  # print(fig)

  if write_pdf:
    print(f"Writing to pdf ...")
    fig.write_image(write_pdf)

##### All data

In [9]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [4]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"config.bit_width": f"{bit_width}-bit"},
                            {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            # {"created_at": {"$lt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            {"$not": {"$and": [{"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}, {"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}]}}
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            {"config.bit_width": f"{bit_width}-bit"},
                            # {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            # {"config.base_model": base_model},
                            # {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            # {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$gt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                              # {"config.base_model": base_model},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                          ]}
                      ]}
                  )

  eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
  # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
  # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
  # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
  # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
  # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

  # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
  perplexity_heatmap_deliver_vertical_sinq(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, embed_sinq=True, write_pdf=f"ablation_floresplus_{bit_width}bit_sinq_all_vert_final.pdf")

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
15,Qwen/Qwen3-8B,gptq,4-bit,Sinq,35.693894,2.847228,17.717172,73.394102,52.279770
0,Qwen/Qwen3-8B,gptq,4-bit,English,38.633773,2.903144,18.795383,81.519027,54.471988
2,Qwen/Qwen3-8B,gptq,4-bit,Tamil,36.874922,2.789352,18.045387,80.639509,52.047636
1,Qwen/Qwen3-8B,gptq,4-bit,Indonesian,36.307482,2.869462,17.537566,75.503067,52.100443
3,Qwen/Qwen3-8B,gptq,4-bit,Swahili,36.782606,2.862192,18.727565,71.522493,52.984904
4,Qwen/Qwen3-8B,gptq,4-bit,Chinese,36.791005,2.921814,17.943838,78.501095,52.133661
16,CohereLabs/aya-expanse-8b,gptq,4-bit,Sinq,55.876352,4.002676,98.200647,394.071986,122.265194
5,CohereLabs/aya-expanse-8b,gptq,4-bit,English,50.815876,3.947913,89.978133,401.770728,113.312037
7,CohereLabs/aya-expanse-8b,gptq,4-bit,Tamil,51.355844,3.796851,90.784244,373.873691,112.280232
6,CohereLabs/aya-expanse-8b,gptq,4-bit,Indonesian,52.137953,3.977342,90.535852,365.351107,113.168497
8,CohereLabs/aya-expanse-8b,gptq,4-bit,Swahili,50.556806,3.900542,89.279740,352.421007,112.105412
9,CohereLabs/aya-expanse-8b,gptq,4-bit,Chinese,52.413353,3.929984,92.005672,381.202734,113.046247
17,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Sinq,43.628489,2.412915,25.845251,32.918649,39.595530
10,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,English,47.372066,2.503244,27.111507,35.268858,40.062125
12,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Tamil,46.727688,2.341632,27.035368,34.343137,39.947466
11,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Indonesian,46.340421,2.454821,25.609484,33.018261,40.115798
13,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Swahili,46.679481,2.453562,26.443130,31.212913,40.419192
14,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Chinese,46.697379,2.436780,27.025912,34.342650,38.331823
13,Qwen/Qwen3-8B,slimllm,4-bit,Sinq,35.693894,2.847228,17.717172,73.394102,52.279770
0,Qwen/Qwen3-8B,slimllm,4-bit,English,34.260498,2.958074,17.888351,79.743173,49.544540
2,Qwen/Qwen3-8B,slimllm,4-bit,Tamil,36.234922,2.776822,18.097900,78.928706,50.708137
1,Qwen/Qwen3-8B,slimllm,4-bit,Indonesian,34.633644,2.891498,17.211146,77.379406,49.841062
3,Qwen/Qwen3-8B,slimllm,4-bit,Swahili,34.731503,2.901018,17.629107,63.984313,49.638112
4,Qwen/Qwen3-8B,slimllm,4-bit,Chinese,35.165068,2.918109,18.043827,78.800577,47.496192
14,CohereLabs/aya-expanse-8b,slimllm,4-bit,Sinq,55.876352,4.002676,98.200647,394.071986,122.265194
5,CohereLabs/aya-expanse-8b,slimllm,4-bit,English,54.706773,4.021575,98.354503,397.648200,124.485867
6,CohereLabs/aya-expanse-8b,slimllm,4-bit,Indonesian,55.686326,3.975950,93.870980,372.462067,122.105721
7,CohereLabs/aya-expanse-8b,slimllm,4-bit,Swahili,55.946115,3.920454,97.055222,337.157383,123.359929
8,CohereLabs/aya-expanse-8b,slimllm,4-bit,Chinese,55.432520,3.954161,98.401795,412.249550,117.615823
15,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Sinq,43.628489,2.412915,25.845251,32.918649,39.595530
9,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,English,43.532462,2.695015,28.568594,36.902012,41.523714
10,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Indonesian,44.632579,2.735899,26.986952,37.360703,44.224801
11,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Swahili,45.423450,2.699435,28.200670,32.886215,46.296442
12,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Chinese,44.928034,2.555277,27.777874,35.678429,38.107827
15,Qwen/Qwen3-8B,tacq,4-bit,Sinq,35.693894,2.847228,17.717172,73.394102,52.279770
0,Qwen/Qwen3-8B,tacq,4-bit,English,34.147866,2.870331,17.424552,74.335601,48.763523
2,Qwen/Qwen3-8B,tacq,4-bit,Tamil,34.711885,2.758863,17.336806,73.351131,48.556783
1,Qwen/Qwen3-8B,tacq,4-bit,Indonesian,35.199599,2.878214,16.914091,73.971753,48.985351
3,Qwen/Qwen3-8B,tacq,4-bit,Swahili,34.439505,2.856956,17.086451,64.984794,48.547595
4,Qwen/Qwen3-8B,tacq,4-bit,Chinese,34.218867,2.906739,17.528538,73.939017,47.282614
16,CohereLabs/aya-expanse-8b,tacq,4-bit,Sinq,55.876352,4.002676,98.200647,394.071986,122.265194
5,CohereLabs/aya-expanse-8b,tacq,4-bit,English,55.022220,3.980362,96.781066,388.558360,120.301677
7,CohereLabs/aya-expanse-8b,tacq,4-bit,Tamil,55.689060,3.848132,97.586160,389.291678,120.618816
6,CohereLabs/aya-expanse-8b,tacq,4-bit,Indonesian,55.559975,3.942369,95.089391,381.536862,119.716704
8,CohereLabs/aya-expanse-8b,tacq,4-bit,Swahili,55.820594,3.988709,97.101196,364.872794,121.515856
9,CohereLabs/aya-expanse-8b,tacq,4-bit,Chinese,55.483941,3.928528,96.739712,411.201310,116.573491
17,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Sinq,43.628489,2.412915,25.845251,32.918649,39.595530
10,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,English,45.535295,2.503889,27.187312,34.456392,40.119780
12,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Tamil,46.511978,2.345541,27.168395,33.305476,39.193255
11,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Indonesian,46.849139,2.457776,25.944766,32.882074,40.222063
13,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Swahili,46.166003,2.460396,26.501118,30.807823,39.940935
14,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Chinese,45.672605,2.424910,27.072293,33.288619,37.424322

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
9,Qwen/Qwen3-8B,tacq,Sinq,4-bit,0.0,0.0,0.0,0.0,0.0
7,Qwen/Qwen3-8B,tacq,English,4-bit,0.0,0.0,0.0,0.0,0.0
11,Qwen/Qwen3-8B,tacq,Tamil,4-bit,0.0,0.0,0.0,0.0,0.0
8,Qwen/Qwen3-8B,tacq,Indonesian,4-bit,0.0,0.0,0.0,0.0,0.0
10,Qwen/Qwen3-8B,tacq,Swahili,4-bit,0.0,0.0,0.0,0.0,0.0
6,Qwen/Qwen3-8B,tacq,Chinese,4-bit,0.0,0.0,0.0,0.0,0.0
3,CohereLabs/aya-expanse-8b,tacq,Sinq,4-bit,0.0,0.0,0.0,0.0,0.0
1,CohereLabs/aya-expanse-8b,tacq,English,4-bit,0.0,0.0,0.0,0.0,0.0
5,CohereLabs/aya-expanse-8b,tacq,Tamil,4-bit,0.0,0.0,0.0,0.0,0.0
2,CohereLabs/aya-expanse-8b,tacq,Indonesian,4-bit,0.0,0.0,0.0,0.0,0.0
4,CohereLabs/aya-expanse-8b,tacq,Swahili,4-bit,0.0,0.0,0.0,0.0,0.0
0,CohereLabs/aya-expanse-8b,tacq,Chinese,4-bit,0.0,0.0,0.0,0.0,0.0
15,meta-llama/Llama-3.1-8B-Instruct,tacq,Sinq,4-bit,0.0,0.0,0.0,0.0,0.0
13,meta-llama/Llama-3.1-8B-Instruct,tacq,English,4-bit,0.0,0.0,0.0,0.0,0.0
17,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,4-bit,0.0,0.0,0.0,0.0,0.0
14,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,4-bit,0.0,0.0,0.0,0.0,0.0
16,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,4-bit,0.0,0.0,0.0,0.0,0.0
12,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,4-bit,0.0,0.0,0.0,0.0,0.0

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
9,Qwen/Qwen3-8B,gptq,Sinq,4-bit,1.552594,0.454422,1.248394,1.865661,1.718334
7,Qwen/Qwen3-8B,gptq,English,4-bit,1.586967,0.462869,1.274051,1.911259,1.736173
11,Qwen/Qwen3-8B,gptq,Tamil,4-bit,1.566731,0.445503,1.256366,1.906548,1.716401
8,Qwen/Qwen3-8B,gptq,Indonesian,4-bit,1.559996,0.457800,1.243969,1.877965,1.716841
10,Qwen/Qwen3-8B,gptq,Swahili,4-bit,1.565642,0.456699,1.272481,1.854443,1.724152
6,Qwen/Qwen3-8B,gptq,Chinese,4-bit,1.565742,0.465653,1.253915,1.894876,1.717118

          GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3   1.552594  1.586967  1.566731  1.559996  1.565642  1.565742
TA_Qwen3   0.454422  0.462869  0.445503  0.457800  0.456699  0.465653
ID_Qwen3   1.248394  1.274051  1.256366  1.243969  1.272481  1.253915
SW_Qwen3   1.865661  1.911259  1.906548  1.877965  1.854443  1.894876
ZH_Qwen3   1.718334  1.736173  1.716401  1.716841  1.724152  1.717118

start model: CohereLabs/aya-expanse-8b

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
3,CohereLabs/aya-expanse-8b,gptq,Sinq,4-bit,1.747228,0.602350,1.992114,2.595576,2.087303
1,CohereLabs/aya-expanse-8b,gptq,English,4-bit,1.705999,0.596368,1.954137,2.603978,2.054276
5,CohereLabs/aya-expanse-8b,gptq,Tamil,4-bit,1.710590,0.579424,1.958010,2.572725,2.050303
2,CohereLabs/aya-expanse-8b,gptq,Indonesian,4-bit,1.717154,0.599593,1.956821,2.562710,2.053726
4,CohereLabs/aya-expanse-8b,gptq,Swahili,4-bit,1.703780,0.591125,1.950753,2.547062,2.049627
0,CohereLabs/aya-expanse-8b,gptq,Chinese,4-bit,1.719442,0.594391,1.963815,2.581156,2.053256

        GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Aya   1.747228  1.705999  1.710590  1.717154  1.703780  1.719442
TA_Aya   0.602350  0.596368  0.579424  0.599593  0.591125  0.594391
ID_Aya   1.992114  1.954137  1.958010  1.956821  1.950753  1.963815
SW_Aya   2.595576  2.603978  2.572725  2.562710  2.547062  2.581156
ZH_Aya   2.087303  2.054276  2.050303  2.053726  2.049627  2.053256

start model: meta-llama/Llama-3.1-8B-Instruct

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
15,meta-llama/Llama-3.1-8B-Instruct,gptq,Sinq,4-bit,1.639770,0.382542,1.412381,1.517442,1.597646
13,meta-llama/Llama-3.1-8B-Instruct,gptq,English,4-bit,1.675522,0.398503,1.433154,1.547391,1.602734
17,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,4-bit,1.669574,0.369519,1.431932,1.535840,1.601489
14,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,4-bit,1.665960,0.390020,1.408401,1.518754,1.603315
16,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,4-bit,1.669126,0.389797,1.422313,1.494334,1.606588
12,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,4-bit,1.669293,0.386816,1.431780,1.535834,1.583559

          GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Llama   1.639770  1.675522  1.669574  1.665960  1.669126  1.669293
TA_Llama   0.382542  0.398503  0.369519  0.390020  0.389797  0.386816
ID_Llama   1.412381  1.433154  1.431932  1.408401  1.422313  1.431780
SW_Llama   1.517442  1.547391  1.535840  1.518754  1.494334  1.535834
ZH_Llama   1.597646  1.602734  1.601489  1.603315  1.606588  1.583559

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,39.595530,40.062125,39.947466,40.115798,40.419192,38.331823,39.595530,41.523714,NaN,44.224801,46.296442,38.107827,39.595530,40.119780,39.193255,40.222063,39.940935,37.424322
SW_Llama,30.056285,32.918649,35.268858,34.343137,33.018261,31.212913,34.342650,32.918649,36.902012,NaN,37.360703,32.886215,35.678429,32.918649,34.456392,33.305476,32.882074,30.807823,33.288619
ID_Llama,24.823783,25.845251,27.111507,27.035368,25.609484,26.443130,27.025912,25.845251,28.568594,NaN,26.986952,28.200670,27.777874,25.845251,27.187312,27.168395,25.944766,26.501118,27.072293
TA_Llama,2.311781,2.412915,2.503244,2.341632,2.454821,2.453562,2.436780,2.412915,2.695015,NaN,2.735899,2.699435,2.555277,2.412915,2.503889,2.345541,2.457776,2.460396,2.424910
EN_Llama,45.105214,43.628489,47.372066,46.727688,46.340421,46.679481,46.697379,43.628489,43.532462,NaN,44.632579,45.423450,44.928034,43.628489,45.535295,46.511978,46.849139,46.166003,45.672605
ZH_Aya,112.084228,122.265194,113.312037,112.280232,113.168497,112.105412,113.046247,122.265194,124.485867,NaN,122.105721,123.359929,117.615823,122.265194,120.301677,120.618816,119.716704,121.515856,116.573491
SW_Aya,347.245294,394.071986,401.770728,373.873691,365.351107,352.421007,381.202734,394.071986,397.648200,NaN,372.462067,337.157383,412.249550,394.071986,388.558360,389.291678,381.536862,364.872794,411.201310
ID_Aya,92.363250,98.200647,89.978133,90.784244,90.535852,89.279740,92.005672,98.200647,98.354503,NaN,93.870980,97.055222,98.401795,98.200647,96.781066,97.586160,95.089391,97.101196,96.739712
TA_Aya,3.798334,4.002676,3.947913,3.796851,3.977342,3.900542,3.929984,4.002676,4.021575,NaN,3.975950,3.920454,3.954161,4.002676,3.980362,3.848132,3.942369,3.988709,3.928528
EN_Aya,53.754913,55.876352,50.815876,51.355844,52.137953,50.556806,52.413353,55.876352,54.706773,NaN,55.686326,55.946115,55.432520,55.876352,55.022220,55.689060,55.559975,55.820594,55.483941
ZH_Qwen3,46.980806,52.279770,54.471988,52.047636,52.100443,52.984904,52.133661,52.279770,49.544540,50.708137,49.841062,49.638112,47.496192,52.279770,48.763523,48.556783,48.985351,48.547595,47.282614
SW_Qwen3,64.534645,73.394102,81.519027,80.639509,75.503067,71.522493,78.501095,73.394102,79.743173,78.928706,77.379406,63.984313,78.800577,73.394102,74.335601,73.351131,73.971753,64.984794,73.939017
ID_Qwen3,16.699008,17.717172,18.795383,18.045387,17.537566,18.727565,17.943838,17.717172,17.888351,18.097900,17.211146,17.629107,18.043827,17.717172,17.424552,17.336806,16.914091,17.086451,17.528538
TA_Qwen3,2.741605,2.847228,2.903144,2.789352,2.869462,2.862192,2.921814,2.847228,2.958074,2.776822,2.891498,2.901018,2.918109,2.847228,2.870331,2.758863,2.878214,2.856956,2.906739
EN_Qwen3,33.428698,35.693894,38.633773,36.874922,36.307482,36.782606,36.791005,35.693894,34.260498,36.234922,34.633644,34.731503,35.165068,35.693894,34.147866,34.711885,35.199599,34.439505,34.218867

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SW_Llama,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ID_Llama,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TA_Llama,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EN_Llama,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZH_Aya,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SW_Aya,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ID_Aya,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TA_Aya,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EN_Aya,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZH_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SW_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ID_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TA_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EN_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Shape
df text: (15, 19)
df std: (15, 19)
Display df

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,39.595530,40.062125,39.947466,40.115798,40.419192,38.331823,39.595530,41.523714,NaN,44.224801,46.296442,38.107827,39.595530,40.119780,39.193255,40.222063,39.940935,37.424322
SW_Llama,30.056285,32.918649,35.268858,34.343137,33.018261,31.212913,34.342650,32.918649,36.902012,NaN,37.360703,32.886215,35.678429,32.918649,34.456392,33.305476,32.882074,30.807823,33.288619
ID_Llama,24.823783,25.845251,27.111507,27.035368,25.609484,26.443130,27.025912,25.845251,28.568594,NaN,26.986952,28.200670,27.777874,25.845251,27.187312,27.168395,25.944766,26.501118,27.072293
TA_Llama,2.311781,2.412915,2.503244,2.341632,2.454821,2.453562,2.436780,2.412915,2.695015,NaN,2.735899,2.699435,2.555277,2.412915,2.503889,2.345541,2.457776,2.460396,2.424910
EN_Llama,45.105214,43.628489,47.372066,46.727688,46.340421,46.679481,46.697379,43.628489,43.532462,NaN,44.632579,45.423450,44.928034,43.628489,45.535295,46.511978,46.849139,46.166003,45.672605
ZH_Aya,112.084228,122.265194,113.312037,112.280232,113.168497,112.105412,113.046247,122.265194,124.485867,NaN,122.105721,123.359929,117.615823,122.265194,120.301677,120.618816,119.716704,121.515856,116.573491
SW_Aya,347.245294,394.071986,401.770728,373.873691,365.351107,352.421007,381.202734,394.071986,397.648200,NaN,372.462067,337.157383,412.249550,394.071986,388.558360,389.291678,381.536862,364.872794,411.201310
ID_Aya,92.363250,98.200647,89.978133,90.784244,90.535852,89.279740,92.005672,98.200647,98.354503,NaN,93.870980,97.055222,98.401795,98.200647,96.781066,97.586160,95.089391,97.101196,96.739712
TA_Aya,3.798334,4.002676,3.947913,3.796851,3.977342,3.900542,3.929984,4.002676,4.021575,NaN,3.975950,3.920454,3.954161,4.002676,3.980362,3.848132,3.942369,3.988709,3.928528
EN_Aya,53.754913,55.876352,50.815876,51.355844,52.137953,50.556806,52.413353,55.876352,54.706773,NaN,55.686326,55.946115,55.432520,55.876352,55.022220,55.689060,55.559975,55.820594,55.483941
ZH_Qwen3,46.980806,52.279770,54.471988,52.047636,52.100443,52.984904,52.133661,52.279770,49.544540,50.708137,49.841062,49.638112,47.496192,52.279770,48.763523,48.556783,48.985351,48.547595,47.282614
SW_Qwen3,64.534645,73.394102,81.519027,80.639509,75.503067,71.522493,78.501095,73.394102,79.743173,78.928706,77.379406,63.984313,78.800577,73.394102,74.335601,73.351131,73.971753,64.984794,73.939017
ID_Qwen3,16.699008,17.717172,18.795383,18.045387,17.537566,18.727565,17.943838,17.717172,17.888351,18.097900,17.211146,17.629107,18.043827,17.717172,17.424552,17.336806,16.914091,17.086451,17.528538
TA_Qwen3,2.741605,2.847228,2.903144,2.789352,2.869462,2.862192,2.921814,2.847228,2.958074,2.776822,2.891498,2.901018,2.918109,2.847228,2.870331,2.758863,2.878214,2.856956,2.906739
EN_Qwen3,33.428698,35.693894,38.633773,36.874922,36.307482,36.782606,36.791005,35.693894,34.260498,36.234922,34.633644,34.731503,35.165068,35.693894,34.147866,34.711885,35.199599,34.439505,34.218867

Display df std

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,,,,,,,,,,,,,,,,,,,
SW_Llama,,,,,,,,,,,,,,,,,,,
ID_Llama,,,,,,,,,,,,,,,,,,,
TA_Llama,,,,,,,,,,,,,,,,,,,
EN_Llama,,,,,,,,,,,,,,,,,,,
ZH_Aya,,,,,,,,,,,,,,,,,,,
SW_Aya,,,,,,,,,,,,,,,,,,,
ID_Aya,,,,,,,,,,,,,,,,,,,
TA_Aya,,,,,,,,,,,,,,,,,,,
EN_Aya,,,,,,,,,,,,,,,,,,,
ZH_Qwen3,,,,,,,,,,,,,,,,,,,
SW_Qwen3,,,,,,,,,,,,,,,,,,,
ID_Qwen3,,,,,,,,,,,,,,,,,,,
TA_Qwen3,,,,,,,,,,,,,,,,,,,
EN_Qwen3,,,,,,,,,,,,,,,,,,,

Writing to pdf ...

In [10]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [3]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"config.bit_width": f"{bit_width}-bit"},
                            {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            # {"created_at": {"$lt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            {"$not": {"$and": [{"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}, {"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}]}}
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            {"config.bit_width": f"{bit_width}-bit"},
                            # {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            # {"config.base_model": base_model},
                            # {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            # {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$gt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                              # {"config.base_model": base_model},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                          ]}
                      ]}
                  )

  eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
  # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
  # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
  # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
  # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
  # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

  # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
  perplexity_heatmap_deliver_vertical_sinq(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, embed_sinq=True, write_pdf=f"ablation_floresplus_{bit_width}bit_sinq_all_vert_final.pdf")

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
31,Qwen/Qwen3-8B,gptq,3-bit,Sinq,53.160308,3.835802,27.044173,170.134416,75.035734
0,Qwen/Qwen3-8B,gptq,3-bit,English,40.188512,4.329966,24.304464,160.417519,62.901249
...,...,...,...,...,...,...,...,...,...
28,Qwen/Qwen3-14B,tacq,3-bit,English,33.208545,3.341025,18.200096,83.344899,48.417162
30,Qwen/Qwen3-14B,tacq,3-bit,Tamil,39.802250,2.560754,16.792030,74.304802,48.441249
29,Qwen/Qwen3-14B,tacq,3-bit,Indonesian,34.557319,2.920792,15.548666,66.936384,49.449916
32,Qwen/Qwen3-14B,tacq,3-bit,Swahili,NaN,NaN,NaN,NaN,NaN
33,Qwen/Qwen3-14B,tacq,3-bit,Chinese,NaN,NaN,NaN,NaN,NaN

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
15,Qwen/Qwen3-8B,tacq,Sinq,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
13,Qwen/Qwen3-8B,tacq,English,3-bit,0.151631,0.039473,0.103480,2.745665,0.322409
17,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.787157,0.004207,0.143836,1.245594,0.341394
14,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.473008,0.012477,0.037528,5.156465,0.841770
16,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.002507,0.024800,0.039048,0.484618,0.440133
12,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.376958,0.038915,0.161324,2.276247,0.174826
3,CohereLabs/aya-expanse-8b,tacq,Sinq,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
1,CohereLabs/aya-expanse-8b,tacq,English,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
5,CohereLabs/aya-expanse-8b,tacq,Tamil,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
2,CohereLabs/aya-expanse-8b,tacq,Indonesian,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
4,CohereLabs/aya-expanse-8b,tacq,Swahili,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
0,CohereLabs/aya-expanse-8b,tacq,Chinese,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
21,meta-llama/Llama-3.1-8B-Instruct,tacq,Sinq,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
19,meta-llama/Llama-3.1-8B-Instruct,tacq,English,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
23,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
20,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
22,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
18,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
9,Qwen/Qwen3-14B,tacq,Sinq,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
7,Qwen/Qwen3-14B,tacq,English,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
11,Qwen/Qwen3-14B,tacq,Tamil,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
8,Qwen/Qwen3-14B,tacq,Indonesian,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
10,Qwen/Qwen3-14B,tacq,Swahili,3-bit,NaN,NaN,NaN,NaN,NaN
6,Qwen/Qwen3-14B,tacq,Chinese,3-bit,NaN,NaN,NaN,NaN,NaN

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
15,Qwen/Qwen3-8B,gptq,Sinq,3-bit,1.725587,0.583856,1.432074,2.230792,1.875268
13,Qwen/Qwen3-8B,gptq,English,3-bit,1.607722,0.631171,1.395688,2.210527,1.804371
17,Qwen/Qwen3-8B,gptq,Tamil,3-bit,1.629727,0.466045,1.362567,2.151944,1.807234
14,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,1.632738,0.578527,1.280456,2.135591,1.797347
16,Qwen/Qwen3-8B,gptq,Swahili,3-bit,1.644914,0.571095,1.347168,1.898244,1.813504
12,Qwen/Qwen3-8B,gptq,Chinese,3-bit,1.612060,0.622343,1.395127,2.209036,1.747992

          GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3   1.725587  1.607722  1.629727  1.632738  1.644914  1.612060
TA_Qwen3   0.583856  0.631171  0.466045  0.578527  0.571095  0.622343
ID_Qwen3   1.432074  1.395688  1.362567  1.280456  1.347168  1.395127
SW_Qwen3   2.230792  2.210527  2.151944  2.135591  1.898244  2.209036
ZH_Qwen3   1.875268  1.804371  1.807234  1.797347  1.813504  1.747992

start model: CohereLabs/aya-expanse-8b

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
3,CohereLabs/aya-expanse-8b,gptq,Sinq,3-bit,1.780293,0.665409,2.033566,2.777006,2.128725
1,CohereLabs/aya-expanse-8b,gptq,English,3-bit,1.745987,0.739545,2.089555,2.846302,2.230725
5,CohereLabs/aya-expanse-8b,gptq,Tamil,3-bit,1.778123,0.595794,2.231180,2.937859,2.419087
2,CohereLabs/aya-expanse-8b,gptq,Indonesian,3-bit,1.765901,0.693843,2.004118,2.779111,2.180825
4,CohereLabs/aya-expanse-8b,gptq,Swahili,3-bit,1.754975,0.690446,2.039433,2.587162,2.186465
0,CohereLabs/aya-expanse-8b,gptq,Chinese,3-bit,1.751977,0.703135,2.034968,2.798352,2.093529

        GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Aya   1.780293  1.745987  1.778123  1.765901  1.754975  1.751977
TA_Aya   0.665409  0.739545  0.595794  0.693843  0.690446  0.703135
ID_Aya   2.033566  2.089555  2.231180  2.004118  2.039433  2.034968
SW_Aya   2.777006  2.846302  2.937859  2.779111  2.587162  2.798352
ZH_Aya   2.128725  2.230725  2.419087  2.180825  2.186465  2.093529

start model: meta-llama/Llama-3.1-8B-Instruct

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
21,meta-llama/Llama-3.1-8B-Instruct,gptq,Sinq,3-bit,1.703749,0.507079,1.557842,1.737537,1.704134
19,meta-llama/Llama-3.1-8B-Instruct,gptq,English,3-bit,1.732418,0.664582,1.690503,1.882521,1.818931
23,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,3-bit,1.755687,0.394067,1.631653,1.802044,1.760409
20,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,3-bit,1.753148,0.581291,1.506698,1.736565,1.793859
22,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,3-bit,1.740410,0.584530,1.584676,1.567509,1.796857
18,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,3-bit,1.749177,0.564655,1.657761,1.846888,1.656961

          GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Llama   1.703749  1.732418  1.755687  1.753148  1.740410  1.749177
TA_Llama   0.507079  0.664582  0.394067  0.581291  0.584530  0.564655
ID_Llama   1.557842  1.690503  1.631653  1.506698  1.584676  1.657761
SW_Llama   1.737537  1.882521  1.802044  1.736565  1.567509  1.846888
ZH_Llama   1.704134  1.818931  1.760409  1.793859  1.796857  1.656961

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,50.598038,65.906926,57.598253,62.209873,62.640825,45.390110,50.598038,107.699684,NaN,68.901162,493.790219,44.496971,50.598038,57.113641,48.481814,52.050964,56.756861,41.277322
SW_Llama,30.056285,54.643300,76.299433,63.393429,54.521151,36.941053,70.289028,54.643300,140.046129,NaN,64.677236,127.097711,79.511096,54.643300,56.283017,46.878139,43.463953,34.765476,50.868524
ID_Llama,24.823783,36.127868,49.034587,42.820579,32.114254,38.430521,45.473741,36.127868,80.624982,NaN,33.437626,237.449086,52.094113,36.127868,39.772587,35.062178,28.618159,34.721147,35.462255
TA_Llama,2.311781,3.214247,4.619366,2.477804,3.813212,3.841755,3.669907,3.214247,6.090120,NaN,4.954544,8.438959,3.885786,3.214247,4.269030,2.430107,3.463090,3.554056,3.123373
EN_Llama,45.105214,50.553287,54.002999,56.975352,56.643278,55.005956,56.127699,50.553287,51.661761,NaN,52.608449,82.705680,55.081591,50.553287,48.270659,50.732388,50.051469,51.241933,50.027819
ZH_Aya,112.084228,134.500910,170.108220,262.474523,151.644070,153.626228,124.030659,134.500910,153.807992,NaN,148.348093,152.570887,127.689433,134.500910,132.582898,135.092829,132.251605,139.732992,119.321911
SW_Aya,347.245294,598.420257,701.944022,866.680681,601.327532,386.510893,628.567549,598.420257,694.409390,NaN,581.597703,372.344141,698.011042,598.420257,488.415269,494.785107,505.833186,351.026762,561.057641
ID_Aya,92.363250,108.035480,122.900772,170.286285,100.952621,109.504752,108.384593,108.035480,128.241772,NaN,106.431040,117.153934,123.701714,108.035480,104.218850,107.600928,96.903556,105.485363,106.001720
TA_Aya,3.798334,4.628170,5.489648,3.942703,4.941318,4.902821,5.048185,4.628170,5.190608,NaN,4.846758,4.707457,4.957356,4.628170,4.598233,3.914037,4.432267,4.394636,4.441016
EN_Aya,53.754913,60.296624,55.716955,59.996131,58.331153,56.882036,56.490654,60.296624,70.334848,NaN,70.159288,71.447728,71.276244,60.296624,56.603639,59.778306,57.988980,59.710328,58.374838
ZH_Qwen3,46.980806,75.035734,63.733939,64.155454,62.711432,65.088417,55.974740,75.035734,64.712779,63.478865,64.819501,68.373666,55.552981,75.035734,53.220909,54.118815,53.634716,53.881667,48.014369
SW_Qwen3,64.534645,170.134416,162.378025,141.887540,136.644195,79.112232,161.821596,170.134416,164.318719,145.458323,137.722535,74.107588,179.623959,170.134416,118.216036,104.766815,103.911624,65.999048,115.434023
ID_Qwen3,16.699008,27.044173,24.870707,23.044479,19.074604,22.241715,24.838596,27.044173,26.285258,23.784272,18.983927,22.583907,27.751146,27.044173,21.206783,19.529220,17.453221,19.180347,21.117769
TA_Qwen3,2.741605,3.835802,4.277311,2.924455,3.789021,3.724733,4.191249,3.835802,4.949053,2.907458,4.009722,3.971942,4.454546,3.835802,3.795672,2.791451,3.444308,3.318586,3.607402
EN_Qwen3,33.428698,53.160308,40.524927,42.631171,42.927773,44.148314,40.931761,53.160308,38.188459,46.080950,41.845462,44.450209,43.978831,53.160308,34.863418,37.812257,36.722366,37.237706,36.611705

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,NaN,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,NaN,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
SW_Llama,NaN,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,NaN,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
ID_Llama,NaN,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,NaN,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
TA_Llama,NaN,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,NaN,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
EN_Llama,NaN,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,NaN,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
ZH_Aya,NaN,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,NaN,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
SW_Aya,NaN,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,NaN,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
ID_Aya,NaN,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,NaN,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
TA_Aya,NaN,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,NaN,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
EN_Aya,NaN,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,NaN,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
ZH_Qwen3,NaN,0.0,0.762469,1.199933,0.438954,0.915603,0.699321,0.0,1.569024,0.967564,0.703321,0.920051,0.816734,0.0,0.322409,0.341394,0.841770,0.440133,0.174826
SW_Qwen3,NaN,0.0,2.804047,1.705260,4.757503,1.136555,11.736552,0.0,5.456480,7.633938,3.363059,0.710285,8.254401,0.0,2.745665,1.245594,5.156465,0.484618,2.276247
ID_Qwen3,NaN,0.0,0.592639,0.309636,0.077459,0.416378,0.069389,0.0,0.226093,0.529658,0.032012,0.344655,1.071688,0.0,0.103480,0.143836,0.037528,0.039048,0.161324
TA_Qwen3,NaN,0.0,0.039836,0.009243,0.099452,0.038960,0.100104,0.0,0.088046,0.005034,0.035343,0.022603,0.200087,0.0,0.039473,0.004207,0.012477,0.024800,0.038915
EN_Qwen3,NaN,0.0,0.317008,0.469939,0.385773,1.013781,0.251571,0.0,0.269588,1.339904,0.682738,0.871159,1.062842,0.0,0.151631,0.787157,0.473008,0.002507,0.376958

## Shape
df text: (15, 19)
df std: (15, 19)
Display df

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,50.598038,65.906926,57.598253,62.209873,62.640825,45.390110,50.598038,107.699684,NaN,68.901162,493.790219,44.496971,50.598038,57.113641,48.481814,52.050964,56.756861,41.277322
SW_Llama,30.056285,54.643300,76.299433,63.393429,54.521151,36.941053,70.289028,54.643300,140.046129,NaN,64.677236,127.097711,79.511096,54.643300,56.283017,46.878139,43.463953,34.765476,50.868524
ID_Llama,24.823783,36.127868,49.034587,42.820579,32.114254,38.430521,45.473741,36.127868,80.624982,NaN,33.437626,237.449086,52.094113,36.127868,39.772587,35.062178,28.618159,34.721147,35.462255
TA_Llama,2.311781,3.214247,4.619366,2.477804,3.813212,3.841755,3.669907,3.214247,6.090120,NaN,4.954544,8.438959,3.885786,3.214247,4.269030,2.430107,3.463090,3.554056,3.123373
EN_Llama,45.105214,50.553287,54.002999,56.975352,56.643278,55.005956,56.127699,50.553287,51.661761,NaN,52.608449,82.705680,55.081591,50.553287,48.270659,50.732388,50.051469,51.241933,50.027819
ZH_Aya,112.084228,134.500910,170.108220,262.474523,151.644070,153.626228,124.030659,134.500910,153.807992,NaN,148.348093,152.570887,127.689433,134.500910,132.582898,135.092829,132.251605,139.732992,119.321911
SW_Aya,347.245294,598.420257,701.944022,866.680681,601.327532,386.510893,628.567549,598.420257,694.409390,NaN,581.597703,372.344141,698.011042,598.420257,488.415269,494.785107,505.833186,351.026762,561.057641
ID_Aya,92.363250,108.035480,122.900772,170.286285,100.952621,109.504752,108.384593,108.035480,128.241772,NaN,106.431040,117.153934,123.701714,108.035480,104.218850,107.600928,96.903556,105.485363,106.001720
TA_Aya,3.798334,4.628170,5.489648,3.942703,4.941318,4.902821,5.048185,4.628170,5.190608,NaN,4.846758,4.707457,4.957356,4.628170,4.598233,3.914037,4.432267,4.394636,4.441016
EN_Aya,53.754913,60.296624,55.716955,59.996131,58.331153,56.882036,56.490654,60.296624,70.334848,NaN,70.159288,71.447728,71.276244,60.296624,56.603639,59.778306,57.988980,59.710328,58.374838
ZH_Qwen3,46.980806,75.035734,63.733939,64.155454,62.711432,65.088417,55.974740,75.035734,64.712779,63.478865,64.819501,68.373666,55.552981,75.035734,53.220909,54.118815,53.634716,53.881667,48.014369
SW_Qwen3,64.534645,170.134416,162.378025,141.887540,136.644195,79.112232,161.821596,170.134416,164.318719,145.458323,137.722535,74.107588,179.623959,170.134416,118.216036,104.766815,103.911624,65.999048,115.434023
ID_Qwen3,16.699008,27.044173,24.870707,23.044479,19.074604,22.241715,24.838596,27.044173,26.285258,23.784272,18.983927,22.583907,27.751146,27.044173,21.206783,19.529220,17.453221,19.180347,21.117769
TA_Qwen3,2.741605,3.835802,4.277311,2.924455,3.789021,3.724733,4.191249,3.835802,4.949053,2.907458,4.009722,3.971942,4.454546,3.835802,3.795672,2.791451,3.444308,3.318586,3.607402
EN_Qwen3,33.428698,53.160308,40.524927,42.631171,42.927773,44.148314,40.931761,53.160308,38.188459,46.080950,41.845462,44.450209,43.978831,53.160308,34.863418,37.812257,36.722366,37.237706,36.611705

Display df std

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,,,,,,,,,,,,,,,,,,,
SW_Llama,,,,,,,,,,,,,,,,,,,
ID_Llama,,,,,,,,,,,,,,,,,,,
TA_Llama,,,,,,,,,,,,,,,,,,,
EN_Llama,,,,,,,,,,,,,,,,,,,
ZH_Aya,,,,,,,,,,,,,,,,,,,
SW_Aya,,,,,,,,,,,,,,,,,,,
ID_Aya,,,,,,,,,,,,,,,,,,,
TA_Aya,,,,,,,,,,,,,,,,,,,
EN_Aya,,,,,,,,,,,,,,,,,,,
ZH_Qwen3,,,0.76,1.20,0.44,0.92,0.70,,1.57,0.97,0.70,0.92,0.82,,0.32,0.34,0.84,0.44,0.17
SW_Qwen3,,,2.80,1.71,4.76,1.14,11.74,,5.46,7.63,3.36,0.71,8.25,,2.75,1.25,5.16,0.48,2.28
ID_Qwen3,,,0.59,0.31,0.08,0.42,0.07,,0.23,0.53,0.03,0.34,1.07,,0.10,0.14,0.04,0.04,0.16
TA_Qwen3,,,0.04,0.01,0.10,0.04,0.10,,0.09,0.01,0.04,0.02,0.20,,0.04,0.00,0.01,0.02,0.04
EN_Qwen3,,,0.32,0.47,0.39,1.01,0.25,,0.27,1.34,0.68,0.87,1.06,,0.15,0.79,0.47,0.00,0.38

Writing to pdf ...

In [11]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"config.bit_width": f"{bit_width}-bit"},
                            {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            # {"config.base_model": base_model},
                            {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            # {"created_at": {"$lt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            {"$not": {"$and": [{"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}, {"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}]}}
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            {"config.bit_width": f"{bit_width}-bit"},
                            # {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            # {"config.base_model": base_model},
                            # {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            # {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$gt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                              # {"config.base_model": base_model},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                          ]}
                      ]}
                  )

  eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
  # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
  # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
  # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
  # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
  # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

  # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
  perplexity_heatmap_deliver_vertical_sinq(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, embed_sinq=True, write_pdf=f"ablation_floresplus_{bit_width}bit_sinq_all_vert_final.pdf")

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,1.669901e+01,6.453465e+01,4.698081e+01
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,9.236325e+01,3.472453e+02,1.120842e+02
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,2.482378e+01,3.005629e+01,3.682178e+01
41,Qwen/Qwen3-8B,gptq,2-bit,Sinq,778028.489669,221688.724629,4.557271e+06,4.380327e+06,2.175599e+06
0,Qwen/Qwen3-8B,gptq,2-bit,English,13062.876244,48256.105485,3.985446e+04,3.823152e+04,3.428624e+04
...,...,...,...,...,...,...,...,...,...
38,Qwen/Qwen3-14B,tacq,2-bit,English,42.305540,17.766269,1.094552e+02,3.921057e+02,1.040427e+02
40,Qwen/Qwen3-14B,tacq,2-bit,Tamil,127.865788,2.734088,4.718777e+01,3.796860e+02,8.750628e+01
39,Qwen/Qwen3-14B,tacq,2-bit,Indonesian,55.124529,8.474698,1.805037e+01,2.543852e+02,8.970690e+01
52,Qwen/Qwen3-14B,tacq,2-bit,Swahili,NaN,NaN,NaN,NaN,NaN
53,Qwen/Qwen3-14B,tacq,2-bit,Chinese,NaN,NaN,NaN,NaN,NaN

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
15,Qwen/Qwen3-8B,tacq,Sinq,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
13,Qwen/Qwen3-8B,tacq,English,2-bit,0.323566,0.665306,3.515737,10.556345,3.317178
17,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.461728,0.010456,14.028029,144.154089,2.312004
14,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.534628,0.818386,0.167729,23.810479,4.750264
16,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.458314,0.499177,0.602931,1.532377,10.103402
12,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.907797,1.544423,5.781454,15.010444,0.752618
3,CohereLabs/aya-expanse-8b,tacq,Sinq,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
1,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.218186,1.433973,4.411970,233.931693,12.841869
5,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,1.176844,0.012800,9.131215,52.022620,5.145499
2,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.472105,0.360203,2.482059,161.906780,15.790946
4,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,1.532074,0.192958,2.532162,8.991836,4.074086
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,1.514478,0.978149,17.780479,306.709847,0.387395
21,meta-llama/Llama-3.1-8B-Instruct,tacq,Sinq,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
19,meta-llama/Llama-3.1-8B-Instruct,tacq,English,2-bit,3.115804,28.764438,149.125005,137.682512,133.037240
23,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,2-bit,9.278792,0.024770,10.450561,45.485010,30.465575
20,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,2-bit,4.389815,3.243741,0.475489,4.651333,7.063266
22,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,2-bit,4.119721,0.267766,15.125315,0.983412,283.980355
18,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,2-bit,4.080786,0.011557,69.982867,31.146280,2.898195
9,Qwen/Qwen3-14B,tacq,Sinq,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
7,Qwen/Qwen3-14B,tacq,English,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
11,Qwen/Qwen3-14B,tacq,Tamil,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
8,Qwen/Qwen3-14B,tacq,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
10,Qwen/Qwen3-14B,tacq,Swahili,2-bit,NaN,NaN,NaN,NaN,NaN
6,Qwen/Qwen3-14B,tacq,Chinese,2-bit,NaN,NaN,NaN,NaN,NaN

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
15,Qwen/Qwen3-8B,gptq,Sinq,2-bit,5.890996,5.345744,6.658705,6.641507,6.337579
13,Qwen/Qwen3-8B,gptq,English,2-bit,4.108156,4.662199,4.593693,4.606363,4.596503
17,Qwen/Qwen3-8B,gptq,Tamil,2-bit,4.642051,0.873260,4.664672,4.670482,4.531575
14,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,4.544935,4.508749,3.226292,4.541529,4.624799
16,Qwen/Qwen3-8B,gptq,Swahili,2-bit,4.643958,4.572244,4.622783,3.166420,4.405375
12,Qwen/Qwen3-8B,gptq,Chinese,2-bit,4.489204,4.365599,4.580982,4.616916,4.249957

          GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3   5.890996  4.108156  4.642051  4.544935  4.643958  4.489204
TA_Qwen3   5.345744  4.662199  0.873260  4.508749  4.572244  4.365599
ID_Qwen3   6.658705  4.593693  4.664672  3.226292  4.622783  4.580982
SW_Qwen3   6.641507  4.606363  4.670482  4.541529  3.166420  4.616916
ZH_Qwen3   6.337579  4.596503  4.531575  4.624799  4.405375  4.249957

start model: CohereLabs/aya-expanse-8b

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
3,CohereLabs/aya-expanse-8b,gptq,Sinq,2-bit,2.557166,1.932225,3.287222,4.060748,3.452489
1,CohereLabs/aya-expanse-8b,gptq,English,2-bit,2.383521,4.348801,3.784685,4.346861,4.282580
5,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,2.872552,0.808635,3.811151,4.341208,3.967499
2,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,2.718155,3.623270,2.737043,4.152934,3.997845
4,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,2.916441,3.176520,3.635588,3.201836,4.169309
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,3.002846,3.626023,3.789999,4.319220,3.012777

        GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Aya   2.557166  2.383521  2.872552  2.718155  2.916441  3.002846
TA_Aya   1.932225  4.348801  0.808635  3.623270  3.176520  3.626023
ID_Aya   3.287222  3.784685  3.811151  2.737043  3.635588  3.789999
SW_Aya   4.060748  4.346861  4.341208  4.152934  3.201836  4.319220
ZH_Aya   3.452489  4.282580  3.967499  3.997845  4.169309  3.012777

start model: meta-llama/Llama-3.1-8B-Instruct

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
21,meta-llama/Llama-3.1-8B-Instruct,gptq,Sinq,2-bit,3.917076,4.673199,4.890831,4.949360,4.508026
19,meta-llama/Llama-3.1-8B-Instruct,gptq,English,2-bit,3.108296,5.665178,4.615812,4.586806,4.723760
23,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,2-bit,3.938442,1.040648,4.654784,4.735744,4.492468
20,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,2-bit,3.826881,5.110111,3.389199,4.331666,4.670681
22,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,2-bit,3.932406,5.604406,4.393071,3.413207,4.765714
18,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,2-bit,3.890824,4.770100,4.699477,4.694667,3.503999

          GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Llama   3.917076  3.108296  3.938442  3.826881  3.932406  3.890824
TA_Llama   4.673199  5.665178  1.040648  5.110111  5.604406  4.770100
ID_Llama   4.890831  4.615812  4.654784  3.389199  4.393071  4.699477
SW_Llama   4.949360  4.586806  4.735744  4.331666  3.413207  4.694667
ZH_Llama   4.508026  4.723760  4.492468  4.670681  4.765714  3.503999

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,3.221260e+04,52937.025188,31079.064005,46846.875085,58306.035056,3191.528221,3.221260e+04,6.502951e+06,NaN,1.828967e+06,2.602418e+06,3788.615196,3.221260e+04,831.292973,245.952841,374.675809,872.837297,65.893885
SW_Llama,30.056285,8.899394e+04,38619.420435,54418.192756,21461.796460,2589.449002,49507.095252,8.899394e+04,3.413639e+04,NaN,1.968422e+04,5.162781e+04,35005.098924,8.899394e+04,560.461792,284.107680,213.018242,44.153591,438.002381
ID_Llama,24.823783,7.777345e+04,41286.884848,45163.124564,2450.187930,24721.264360,50058.363746,7.777345e+04,5.692653e+04,NaN,4.410187e+04,9.081436e+04,63450.902216,7.777345e+04,558.862629,244.421507,48.206539,151.038203,411.683272
TA_Llama,2.311781,4.711932e+04,462570.732187,10.981143,128857.950967,402166.581074,58897.957168,4.711932e+04,8.326694e+06,NaN,2.886942e+06,1.401443e+06,132852.344038,4.711932e+04,70.142513,2.766078,14.534124,16.163262,8.765659
EN_Llama,45.105214,8.261823e+03,1283.204545,8678.450527,6712.454060,8558.666771,7777.211806,8.261823e+03,9.628502e+02,NaN,1.449435e+04,3.808274e+04,13740.636867,8.261823e+03,74.420949,113.737093,99.134160,112.516157,106.758411
ZH_Aya,112.084228,2.834583e+03,19168.145370,9278.960985,9950.510277,14767.553330,1029.857317,2.834583e+03,7.409755e+06,NaN,1.631137e+06,1.004871e+06,274.084188,2.834583e+03,360.637008,275.617452,292.760948,406.131890,135.838040
SW_Aya,347.245294,1.150134e+04,22225.967596,21938.558958,14221.136656,1591.607966,20855.464249,1.150134e+04,9.978332e+03,NaN,5.561333e+03,4.189173e+02,50822.574116,1.150134e+04,1588.158444,1544.971890,1344.702942,332.042594,2235.354059
ID_Aya,92.363250,1.937413e+03,6090.955316,6473.671674,545.811702,4321.037729,6165.939366,1.937413e+03,4.766603e+04,NaN,2.328256e+02,1.044489e+03,484718.872812,1.937413e+03,306.205275,225.322198,117.137641,202.212119,297.658705
TA_Aya,3.798334,8.555107e+01,22325.499442,6.436282,4200.197925,1501.481445,4226.914393,8.555107e+01,4.110211e+05,NaN,4.490107e+05,6.071352e+05,290134.141033,8.555107e+01,14.739504,4.049754,12.200776,10.231536,12.421246
EN_Aya,53.754913,3.607169e+02,241.836277,745.679240,522.582423,824.976137,1006.574886,3.607169e+02,1.366964e+02,NaN,2.688014e+02,3.345557e+02,4622.001841,3.607169e+02,69.141747,93.205527,80.995250,97.275513,85.909020
ZH_Qwen3,46.980806,2.175599e+06,39491.465990,34007.536689,42150.094142,25431.655621,17781.024879,2.175599e+06,6.674189e+05,60166.327417,4.113642e+05,6.278313e+05,360.020385,2.175599e+06,146.704354,119.462250,122.105214,176.318815,63.072371
SW_Qwen3,64.534645,4.380327e+06,40398.302421,46825.504463,34796.007236,1466.964319,41391.915611,4.380327e+06,6.726278e+03,6525.812005,2.713585e+03,5.398065e+02,19233.229068,4.380327e+06,380.075948,433.095598,258.430765,69.236501,372.747064
ID_Qwen3,16.699008,4.557271e+06,39236.778388,46203.199536,1683.806307,41954.948059,38104.965297,4.557271e+06,2.493904e+03,11464.605865,1.232482e+02,7.012918e+02,18727.617100,4.557271e+06,116.218561,72.677371,21.817674,43.733264,127.139610
TA_Qwen3,2.741605,2.216887e+05,45940.807067,7.468949,32266.297200,37346.013068,23205.924496,2.216887e+05,1.476803e+04,4.442923,1.200714e+04,6.139446e+03,25621.911270,2.216887e+05,15.513642,3.063271,9.956398,9.944748,13.166703
EN_Qwen3,33.428698,7.780285e+05,12827.901762,43858.254034,35069.944932,44051.236215,30846.394995,7.780285e+05,1.515746e+02,6890.433754,1.077302e+03,2.003619e+03,5742.270277,7.780285e+05,43.983318,64.369847,52.554869,65.558487,59.187938

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,NaN,0.0,13902.306426,642.794567,10300.464859,11728.335010,56.509159,0.0,5.325304e+06,NaN,60825.148554,1.320123e+06,1381.048524,0.0,133.037240,30.465575,7.063266,283.980355,2.898195
SW_Llama,NaN,0.0,4372.904715,8115.903560,1995.477406,1476.872030,6630.425511,0.0,1.430034e+04,NaN,14193.675815,1.634358e+04,14671.177536,0.0,137.682512,45.485010,4.651333,0.983412,31.146280
ID_Llama,NaN,0.0,9347.511733,6317.020512,317.796183,2408.903746,14456.353815,0.0,3.341413e+04,NaN,39536.183254,3.454913e+04,8781.431135,0.0,149.125005,10.450561,0.475489,15.125315,69.982867
TA_Llama,NaN,0.0,0.000000,1.455488,0.000000,0.000000,1543.022412,0.0,4.932056e+06,NaN,94130.400032,8.095470e+05,79972.668145,0.0,28.764438,0.024770,3.243741,0.267766,0.011557
EN_Llama,NaN,0.0,17.189524,201.289120,589.302232,1919.202975,97.149477,0.0,3.474801e+02,NaN,10152.523277,8.948106e+03,6742.771768,0.0,3.115804,9.278792,4.389815,4.119721,4.080786
ZH_Aya,NaN,0.0,1543.522189,1302.353438,866.080047,1180.853398,18.945158,0.0,1.202363e+06,NaN,416931.507561,6.481870e+05,13.882118,0.0,12.841869,5.145499,15.790946,4.074086,0.387395
SW_Aya,NaN,0.0,1277.195624,2050.239999,1152.198626,33.017260,2340.085532,0.0,2.119860e+03,NaN,1141.379148,3.752367e+01,26373.980905,0.0,233.931693,52.022620,161.906780,8.991836,306.709847
ID_Aya,NaN,0.0,785.551907,453.403569,36.465574,597.968991,748.488685,0.0,1.619160e+04,NaN,10.858010,4.074973e+02,46527.414954,0.0,4.411970,9.131215,2.482059,2.532162,17.780479
TA_Aya,NaN,0.0,6727.004278,0.242481,1013.398744,576.594778,1135.284190,0.0,2.832218e+05,NaN,322783.452104,8.287334e+05,268700.417046,0.0,1.433973,0.012800,0.360203,0.192958,0.978149
EN_Aya,NaN,0.0,6.347335,60.775949,25.456456,80.773855,75.660850,0.0,8.647104e+00,NaN,22.655564,1.172476e+02,3534.650256,0.0,0.218186,1.176844,0.472105,1.532074,1.514478
ZH_Qwen3,NaN,0.0,4322.025321,12652.174248,1814.625584,214.562658,1521.218809,0.0,2.613922e+05,23070.095350,136201.928434,5.620394e+05,44.890879,0.0,3.317178,2.312004,4.750264,10.103402,0.752618
SW_Qwen3,NaN,0.0,1545.126299,41.811051,3225.378802,119.318857,6205.821677,0.0,9.155808e+02,1344.498076,1229.939922,1.528529e+02,6050.793892,0.0,10.556345,144.154089,23.810479,1.532377,15.010444
ID_Qwen3,NaN,0.0,607.573270,5893.246746,463.524607,2132.436617,4590.185765,0.0,4.345302e+02,2181.571725,64.114112,6.368716e+01,5190.682069,0.0,3.515737,14.028029,0.167729,0.602931,5.781454
TA_Qwen3,NaN,0.0,3672.782474,0.417630,3505.411760,1535.747660,1813.483650,0.0,9.351708e+03,0.104889,11122.033868,4.051682e+03,16018.499530,0.0,0.665306,0.010456,0.818386,0.499177,1.544423
EN_Qwen3,NaN,0.0,269.191572,3137.501577,1463.765358,1602.262531,492.546412,0.0,1.519971e+01,2585.158544,570.476116,8.127715e+02,2266.421583,0.0,0.323566,0.461728,0.534628,0.458314,0.907797

## Shape
df text: (15, 19)
df std: (15, 19)
Display df

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,3.221260e+04,52937.025188,31079.064005,46846.875085,58306.035056,3191.528221,3.221260e+04,6.502951e+06,NaN,1.828967e+06,2.602418e+06,3788.615196,3.221260e+04,831.292973,245.952841,374.675809,872.837297,65.893885
SW_Llama,30.056285,8.899394e+04,38619.420435,54418.192756,21461.796460,2589.449002,49507.095252,8.899394e+04,3.413639e+04,NaN,1.968422e+04,5.162781e+04,35005.098924,8.899394e+04,560.461792,284.107680,213.018242,44.153591,438.002381
ID_Llama,24.823783,7.777345e+04,41286.884848,45163.124564,2450.187930,24721.264360,50058.363746,7.777345e+04,5.692653e+04,NaN,4.410187e+04,9.081436e+04,63450.902216,7.777345e+04,558.862629,244.421507,48.206539,151.038203,411.683272
TA_Llama,2.311781,4.711932e+04,462570.732187,10.981143,128857.950967,402166.581074,58897.957168,4.711932e+04,8.326694e+06,NaN,2.886942e+06,1.401443e+06,132852.344038,4.711932e+04,70.142513,2.766078,14.534124,16.163262,8.765659
EN_Llama,45.105214,8.261823e+03,1283.204545,8678.450527,6712.454060,8558.666771,7777.211806,8.261823e+03,9.628502e+02,NaN,1.449435e+04,3.808274e+04,13740.636867,8.261823e+03,74.420949,113.737093,99.134160,112.516157,106.758411
ZH_Aya,112.084228,2.834583e+03,19168.145370,9278.960985,9950.510277,14767.553330,1029.857317,2.834583e+03,7.409755e+06,NaN,1.631137e+06,1.004871e+06,274.084188,2.834583e+03,360.637008,275.617452,292.760948,406.131890,135.838040
SW_Aya,347.245294,1.150134e+04,22225.967596,21938.558958,14221.136656,1591.607966,20855.464249,1.150134e+04,9.978332e+03,NaN,5.561333e+03,4.189173e+02,50822.574116,1.150134e+04,1588.158444,1544.971890,1344.702942,332.042594,2235.354059
ID_Aya,92.363250,1.937413e+03,6090.955316,6473.671674,545.811702,4321.037729,6165.939366,1.937413e+03,4.766603e+04,NaN,2.328256e+02,1.044489e+03,484718.872812,1.937413e+03,306.205275,225.322198,117.137641,202.212119,297.658705
TA_Aya,3.798334,8.555107e+01,22325.499442,6.436282,4200.197925,1501.481445,4226.914393,8.555107e+01,4.110211e+05,NaN,4.490107e+05,6.071352e+05,290134.141033,8.555107e+01,14.739504,4.049754,12.200776,10.231536,12.421246
EN_Aya,53.754913,3.607169e+02,241.836277,745.679240,522.582423,824.976137,1006.574886,3.607169e+02,1.366964e+02,NaN,2.688014e+02,3.345557e+02,4622.001841,3.607169e+02,69.141747,93.205527,80.995250,97.275513,85.909020
ZH_Qwen3,46.980806,2.175599e+06,39491.465990,34007.536689,42150.094142,25431.655621,17781.024879,2.175599e+06,6.674189e+05,60166.327417,4.113642e+05,6.278313e+05,360.020385,2.175599e+06,146.704354,119.462250,122.105214,176.318815,63.072371
SW_Qwen3,64.534645,4.380327e+06,40398.302421,46825.504463,34796.007236,1466.964319,41391.915611,4.380327e+06,6.726278e+03,6525.812005,2.713585e+03,5.398065e+02,19233.229068,4.380327e+06,380.075948,433.095598,258.430765,69.236501,372.747064
ID_Qwen3,16.699008,4.557271e+06,39236.778388,46203.199536,1683.806307,41954.948059,38104.965297,4.557271e+06,2.493904e+03,11464.605865,1.232482e+02,7.012918e+02,18727.617100,4.557271e+06,116.218561,72.677371,21.817674,43.733264,127.139610
TA_Qwen3,2.741605,2.216887e+05,45940.807067,7.468949,32266.297200,37346.013068,23205.924496,2.216887e+05,1.476803e+04,4.442923,1.200714e+04,6.139446e+03,25621.911270,2.216887e+05,15.513642,3.063271,9.956398,9.944748,13.166703
EN_Qwen3,33.428698,7.780285e+05,12827.901762,43858.254034,35069.944932,44051.236215,30846.394995,7.780285e+05,1.515746e+02,6890.433754,1.077302e+03,2.003619e+03,5742.270277,7.780285e+05,43.983318,64.369847,52.554869,65.558487,59.187938

Display df std

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,,,1.4e+4,642.8,1.0e+4,1.2e+4,56.51,,5.3e+6,,6.1e+4,1.3e+6,1.4e+3,,133.0,30.47,7.06,284.0,2.90
SW_Llama,,,4.4e+3,8.1e+3,2.0e+3,1.5e+3,6.6e+3,,1.4e+4,,1.4e+4,1.6e+4,1.5e+4,,137.7,45.49,4.65,0.98,31.15
ID_Llama,,,9.3e+3,6.3e+3,317.8,2.4e+3,1.4e+4,,3.3e+4,,4.0e+4,3.5e+4,8.8e+3,,149.1,10.45,0.48,15.13,69.98
TA_Llama,,,,1.46,,,1.5e+3,,4.9e+6,,9.4e+4,8.1e+5,8.0e+4,,28.76,0.02,3.24,0.27,0.01
EN_Llama,,,17.19,201.3,589.3,1.9e+3,97.15,,347.5,,1.0e+4,8.9e+3,6.7e+3,,3.12,9.28,4.39,4.12,4.08
ZH_Aya,,,1.5e+3,1.3e+3,866.1,1.2e+3,18.95,,1.2e+6,,4.2e+5,6.5e+5,13.88,,12.84,5.15,15.79,4.07,0.39
SW_Aya,,,1.3e+3,2.1e+3,1.2e+3,33.02,2.3e+3,,2.1e+3,,1.1e+3,37.52,2.6e+4,,233.9,52.02,161.9,8.99,306.7
ID_Aya,,,785.6,453.4,36.47,598.0,748.5,,1.6e+4,,10.86,407.5,4.7e+4,,4.41,9.13,2.48,2.53,17.78
TA_Aya,,,6.7e+3,0.24,1.0e+3,576.6,1.1e+3,,2.8e+5,,3.2e+5,8.3e+5,2.7e+5,,1.43,0.01,0.36,0.19,0.98
EN_Aya,,,6.35,60.78,25.46,80.77,75.66,,8.65,,22.66,117.2,3.5e+3,,0.22,1.18,0.47,1.53,1.51
ZH_Qwen3,,,4.3e+3,1.3e+4,1.8e+3,214.6,1.5e+3,,2.6e+5,2.3e+4,1.4e+5,5.6e+5,44.89,,3.32,2.31,4.75,10.10,0.75
SW_Qwen3,,,1.5e+3,41.81,3.2e+3,119.3,6.2e+3,,915.6,1.3e+3,1.2e+3,152.9,6.1e+3,,10.56,144.2,23.81,1.53,15.01
ID_Qwen3,,,607.6,5.9e+3,463.5,2.1e+3,4.6e+3,,434.5,2.2e+3,64.11,63.69,5.2e+3,,3.52,14.03,0.17,0.60,5.78
TA_Qwen3,,,3.7e+3,0.42,3.5e+3,1.5e+3,1.8e+3,,9.4e+3,0.10,1.1e+4,4.1e+3,1.6e+4,,0.67,0.01,0.82,0.50,1.54
EN_Qwen3,,,269.2,3.1e+3,1.5e+3,1.6e+3,492.5,,15.20,2.6e+3,570.5,812.8,2.3e+3,,0.32,0.46,0.53,0.46,0.91

Writing to pdf ...

###### Qwen3-14B

In [17]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [3]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"config.bit_width": f"{bit_width}-bit"},
                            {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            {"config.base_model": "Qwen/Qwen3-14B"},
                            {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            {"$not": {"$and": [{"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}, {"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}]}}
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            {"config.bit_width": f"{bit_width}-bit"},
                            # {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            {"config.base_model": "Qwen/Qwen3-14B"},
                            # {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            # {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$gt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-07-01'}},
                          ]}
                      ]}
                  )

  eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
  # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
  # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
  # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
  # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
  # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

  # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
  perplexity_heatmap_deliver_vertical_sinq(eval_languages, runs, ["Qwen/Qwen3-14B"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, embed_sinq=True, write_pdf=f"ablation_floresplus_14b_{bit_width}bit_sinq_all_vert_final.pdf")

/tmp/ipykernel_5078/1242997687.py:187: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-14B,Unquantized,32-bit,Unquantized,31.906740,2.528679,15.144081,46.729738,44.586565
6,Qwen/Qwen3-14B,gptq,3-bit,Sinq,65.452441,3.086842,22.252021,140.257758,58.400786
0,Qwen/Qwen3-14B,gptq,3-bit,English,36.570983,3.434160,19.298548,106.342203,54.280184
1,Qwen/Qwen3-14B,gptq,3-bit,English,NaN,NaN,NaN,NaN,NaN
2,Qwen/Qwen3-14B,gptq,3-bit,English,NaN,NaN,NaN,NaN,NaN
7,Qwen/Qwen3-14B,gptq,3-bit,Tamil,39.736187,2.653994,18.600899,101.042983,53.330655
3,Qwen/Qwen3-14B,gptq,3-bit,Indonesian,38.121960,3.113559,16.842957,87.253248,54.865941
4,Qwen/Qwen3-14B,gptq,3-bit,Indonesian,NaN,NaN,NaN,NaN,NaN
5,Qwen/Qwen3-14B,gptq,3-bit,Indonesian,NaN,NaN,NaN,NaN,NaN
8,Qwen/Qwen3-14B,gptq,3-bit,Swahili,37.600310,3.034574,18.033382,53.112277,54.543040
9,Qwen/Qwen3-14B,gptq,3-bit,Chinese,37.183523,3.251492,19.419783,102.708718,49.925631
3,Qwen/Qwen3-14B,tacq,3-bit,Sinq,65.452441,3.086842,22.252021,140.257758,58.400786
0,Qwen/Qwen3-14B,tacq,3-bit,English,33.208545,3.341025,18.200096,83.344899,48.417162
2,Qwen/Qwen3-14B,tacq,3-bit,Tamil,39.802250,2.560754,16.792030,74.304802,48.441249
1,Qwen/Qwen3-14B,tacq,3-bit,Indonesian,34.557319,2.920792,15.548666,66.936384,49.449916
4,Qwen/Qwen3-14B,tacq,3-bit,Swahili,34.834344,2.839776,16.301946,46.640123,49.457979
5,Qwen/Qwen3-14B,tacq,3-bit,Chinese,34.466696,3.098871,17.858717,81.958071,45.356019

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
3,Qwen/Qwen3-14B,tacq,Sinq,3-bit,0.0,0.0,0.0,0.0,0.0
1,Qwen/Qwen3-14B,tacq,English,3-bit,0.0,0.0,0.0,0.0,0.0
5,Qwen/Qwen3-14B,tacq,Tamil,3-bit,0.0,0.0,0.0,0.0,0.0
2,Qwen/Qwen3-14B,tacq,Indonesian,3-bit,0.0,0.0,0.0,0.0,0.0
4,Qwen/Qwen3-14B,tacq,Swahili,3-bit,0.0,0.0,0.0,0.0,0.0
0,Qwen/Qwen3-14B,tacq,Chinese,3-bit,0.0,0.0,0.0,0.0,0.0

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-14B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
3,Qwen/Qwen3-14B,gptq,Sinq,3-bit,1.815926,0.489514,1.347369,2.146927,1.766419
1,Qwen/Qwen3-14B,gptq,English,3-bit,1.563137,0.535821,1.285525,2.026706,1.734641
5,Qwen/Qwen3-14B,gptq,Tamil,3-bit,1.599186,0.423900,1.269534,2.004506,1.726977
2,Qwen/Qwen3-14B,gptq,Indonesian,3-bit,1.581175,0.493257,1.226418,1.940782,1.739303
4,Qwen/Qwen3-14B,gptq,Swahili,3-bit,1.575191,0.482098,1.256077,1.725195,1.736739
0,Qwen/Qwen3-14B,gptq,Chinese,3-bit,1.570351,0.512083,1.288244,2.011607,1.698324

              GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3 14B   1.815926  1.563137  1.599186  1.581175  1.575191  1.570351
TA_Qwen3 14B   0.489514  0.535821  0.423900  0.493257  0.482098  0.512083
ID_Qwen3 14B   1.347369  1.285525  1.269534  1.226418  1.256077  1.288244
SW_Qwen3 14B   2.146927  2.026706  2.004506  1.940782  1.725195  2.011607
ZH_Qwen3 14B   1.766419  1.734641  1.726977  1.739303  1.736739  1.698324

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Qwen3 14B,44.586565,58.400786,54.280184,53.330655,54.865941,54.543040,49.925631,58.400786,48.417162,48.441249,49.449916,49.457979,45.356019
SW_Qwen3 14B,46.729738,140.257758,106.342203,101.042983,87.253248,53.112277,102.708718,140.257758,83.344899,74.304802,66.936384,46.640123,81.958071
ID_Qwen3 14B,15.144081,22.252021,19.298548,18.600899,16.842957,18.033382,19.419783,22.252021,18.200096,16.792030,15.548666,16.301946,17.858717
TA_Qwen3 14B,2.528679,3.086842,3.434160,2.653994,3.113559,3.034574,3.251492,3.086842,3.341025,2.560754,2.920792,2.839776,3.098871
EN_Qwen3 14B,31.906740,65.452441,36.570983,39.736187,38.121960,37.600310,37.183523,65.452441,33.208545,39.802250,34.557319,34.834344,34.466696

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Qwen3 14B,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SW_Qwen3 14B,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ID_Qwen3 14B,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TA_Qwen3 14B,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EN_Qwen3 14B,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Shape
df text: (5, 13)
df std: (5, 13)
Display df

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Qwen3 14B,44.586565,58.400786,54.280184,53.330655,54.865941,54.543040,49.925631,58.400786,48.417162,48.441249,49.449916,49.457979,45.356019
SW_Qwen3 14B,46.729738,140.257758,106.342203,101.042983,87.253248,53.112277,102.708718,140.257758,83.344899,74.304802,66.936384,46.640123,81.958071
ID_Qwen3 14B,15.144081,22.252021,19.298548,18.600899,16.842957,18.033382,19.419783,22.252021,18.200096,16.792030,15.548666,16.301946,17.858717
TA_Qwen3 14B,2.528679,3.086842,3.434160,2.653994,3.113559,3.034574,3.251492,3.086842,3.341025,2.560754,2.920792,2.839776,3.098871
EN_Qwen3 14B,31.906740,65.452441,36.570983,39.736187,38.121960,37.600310,37.183523,65.452441,33.208545,39.802250,34.557319,34.834344,34.466696

Display df std

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Qwen3 14B,,,,,,,,,,,,,
SW_Qwen3 14B,,,,,,,,,,,,,
ID_Qwen3 14B,,,,,,,,,,,,,
TA_Qwen3 14B,,,,,,,,,,,,,
EN_Qwen3 14B,,,,,,,,,,,,,

Writing to pdf ...

In [15]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"config.bit_width": f"{bit_width}-bit"},
                            {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            {"config.base_model": "Qwen/Qwen3-14B"},
                            {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            {"$not": {"$and": [{"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}, {"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}]}}
                          ]
                          },
                          { "$and": [
                            {"config.quantization_technique": "sinq"},
                            {"config.bit_width": f"{bit_width}-bit"},
                            # {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            {"config.base_model": "Qwen/Qwen3-14B"},
                            # {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            # {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$gt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                              {"config.base_model": "Qwen/Qwen3-14B"},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-07-01'}},
                          ]}
                      ]}
                  )

  eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
  # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
  # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
  # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
  # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
  # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

  # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
  perplexity_heatmap_deliver_vertical_sinq(eval_languages, runs, ["Qwen/Qwen3-14B"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, embed_sinq=True, write_pdf=f"ablation_floresplus_14b_{bit_width}bit_sinq_all_vert_final.pdf")

/tmp/ipykernel_5078/1242997687.py:187: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-14B,Unquantized,32-bit,Unquantized,31.906740,2.528679,15.144081,46.729738,44.586565
6,Qwen/Qwen3-14B,gptq,2-bit,Sinq,93245.028692,3703.413056,21716.156280,189746.386430,134401.759076
0,Qwen/Qwen3-14B,gptq,2-bit,English,NaN,NaN,NaN,NaN,NaN
1,Qwen/Qwen3-14B,gptq,2-bit,English,NaN,NaN,NaN,NaN,NaN
7,Qwen/Qwen3-14B,gptq,2-bit,English,1731.421552,126724.181707,15134.717731,63182.296317,98882.102925
4,Qwen/Qwen3-14B,gptq,2-bit,Tamil,NaN,NaN,NaN,NaN,NaN
5,Qwen/Qwen3-14B,gptq,2-bit,Tamil,NaN,NaN,NaN,NaN,NaN
9,Qwen/Qwen3-14B,gptq,2-bit,Tamil,58067.513363,4.540477,8132.349136,16367.378790,126329.283396
2,Qwen/Qwen3-14B,gptq,2-bit,Indonesian,NaN,NaN,NaN,NaN,NaN
3,Qwen/Qwen3-14B,gptq,2-bit,Indonesian,NaN,NaN,NaN,NaN,NaN
8,Qwen/Qwen3-14B,gptq,2-bit,Indonesian,9109.144965,509.449465,105.458845,5962.964127,59876.095003
10,Qwen/Qwen3-14B,gptq,2-bit,Swahili,40439.801741,348.604903,6430.714809,306.922576,187673.707091
11,Qwen/Qwen3-14B,gptq,2-bit,Chinese,7391.931214,13161.527566,15931.801910,57565.977822,2048.140191
3,Qwen/Qwen3-14B,tacq,2-bit,Sinq,93245.028692,3703.413056,21716.156280,189746.386430,134401.759076
0,Qwen/Qwen3-14B,tacq,2-bit,English,42.305540,17.766269,109.455182,392.105679,104.042738
2,Qwen/Qwen3-14B,tacq,2-bit,Tamil,127.865788,2.734088,47.187771,379.686037,87.506276
1,Qwen/Qwen3-14B,tacq,2-bit,Indonesian,55.124529,8.474698,18.050369,254.385204,89.706897
4,Qwen/Qwen3-14B,tacq,2-bit,Swahili,65.045889,9.076365,30.467371,49.380839,113.418869
5,Qwen/Qwen3-14B,tacq,2-bit,Chinese,56.342883,19.457560,100.802627,438.827932,53.193292

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
3,Qwen/Qwen3-14B,tacq,Sinq,2-bit,0.0,0.0,0.0,0.0,0.0
1,Qwen/Qwen3-14B,tacq,English,2-bit,0.0,0.0,0.0,0.0,0.0
5,Qwen/Qwen3-14B,tacq,Tamil,2-bit,0.0,0.0,0.0,0.0,0.0
2,Qwen/Qwen3-14B,tacq,Indonesian,2-bit,0.0,0.0,0.0,0.0,0.0
4,Qwen/Qwen3-14B,tacq,Swahili,2-bit,0.0,0.0,0.0,0.0,0.0
0,Qwen/Qwen3-14B,tacq,Chinese,2-bit,0.0,0.0,0.0,0.0,0.0

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-14B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
3,Qwen/Qwen3-14B,gptq,Sinq,2-bit,4.969626,3.568602,4.336783,5.278174,5.128405
1,Qwen/Qwen3-14B,gptq,English,2-bit,3.238403,5.102859,4.179974,4.800595,4.995118
5,Qwen/Qwen3-14B,gptq,Tamil,2-bit,4.763933,0.657101,3.910216,4.213979,5.101504
2,Qwen/Qwen3-14B,gptq,Indonesian,2-bit,3.959478,2.707101,2.023083,3.775462,4.777253
4,Qwen/Qwen3-14B,gptq,Swahili,2-bit,4.606809,2.542333,3.808259,2.487029,5.273403
0,Qwen/Qwen3-14B,gptq,Chinese,2-bit,3.868758,4.119306,4.202265,4.760166,3.311360

              GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3 14B   4.969626  3.238403  4.763933  3.959478  4.606809  3.868758
TA_Qwen3 14B   3.568602  5.102859  0.657101  2.707101  2.542333  4.119306
ID_Qwen3 14B   4.336783  4.179974  3.910216  2.023083  3.808259  4.202265
SW_Qwen3 14B   5.278174  4.800595  4.213979  3.775462  2.487029  4.760166
ZH_Qwen3 14B   5.128405  4.995118  5.101504  4.777253  5.273403  3.311360

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Qwen3 14B,44.586565,134401.759076,98882.102925,126329.283396,59876.095003,187673.707091,2048.140191,134401.759076,104.042738,87.506276,89.706897,113.418869,53.193292
SW_Qwen3 14B,46.729738,189746.386430,63182.296317,16367.378790,5962.964127,306.922576,57565.977822,189746.386430,392.105679,379.686037,254.385204,49.380839,438.827932
ID_Qwen3 14B,15.144081,21716.156280,15134.717731,8132.349136,105.458845,6430.714809,15931.801910,21716.156280,109.455182,47.187771,18.050369,30.467371,100.802627
TA_Qwen3 14B,2.528679,3703.413056,126724.181707,4.540477,509.449465,348.604903,13161.527566,3703.413056,17.766269,2.734088,8.474698,9.076365,19.457560
EN_Qwen3 14B,31.906740,93245.028692,1731.421552,58067.513363,9109.144965,40439.801741,7391.931214,93245.028692,42.305540,127.865788,55.124529,65.045889,56.342883

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Qwen3 14B,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SW_Qwen3 14B,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ID_Qwen3 14B,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TA_Qwen3 14B,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EN_Qwen3 14B,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Shape
df text: (5, 13)
df std: (5, 13)
Display df

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Qwen3 14B,44.586565,134401.759076,98882.102925,126329.283396,59876.095003,187673.707091,2048.140191,134401.759076,104.042738,87.506276,89.706897,113.418869,53.193292
SW_Qwen3 14B,46.729738,189746.386430,63182.296317,16367.378790,5962.964127,306.922576,57565.977822,189746.386430,392.105679,379.686037,254.385204,49.380839,438.827932
ID_Qwen3 14B,15.144081,21716.156280,15134.717731,8132.349136,105.458845,6430.714809,15931.801910,21716.156280,109.455182,47.187771,18.050369,30.467371,100.802627
TA_Qwen3 14B,2.528679,3703.413056,126724.181707,4.540477,509.449465,348.604903,13161.527566,3703.413056,17.766269,2.734088,8.474698,9.076365,19.457560
EN_Qwen3 14B,31.906740,93245.028692,1731.421552,58067.513363,9109.144965,40439.801741,7391.931214,93245.028692,42.305540,127.865788,55.124529,65.045889,56.342883

Display df std

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Qwen3 14B,,,,,,,,,,,,,
SW_Qwen3 14B,,,,,,,,,,,,,
ID_Qwen3 14B,,,,,,,,,,,,,
TA_Qwen3 14B,,,,,,,,,,,,,
EN_Qwen3 14B,,,,,,,,,,,,,

Writing to pdf ...

##### All data - Each Quant

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [4]:
  for quantization_technique in ["gptq", "slimllm", "tacq"]:
    runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                    filters={"$or": [
                            { "$and": [
                              {"config.quantization_technique": quantization_technique.lower()},
                              {"config.bit_width": f"{bit_width}-bit"},
                              {"config.num_calibration_samples": 128},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"$or": [
                                {"config.evaluation_dataset": f"floresplus-evaluate"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                              ]},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                              {"created_at": {"$gt": '2026-01-15'}},
                              # {"created_at": {"$lt": '2026-07-01'}},
                              # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                              # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"$not": {"$and": [{"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}, {"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}]}}
                            ]
                            },
                            { "$and": [
                              {"config.quantization_technique": "sinq"},
                              {"config.bit_width": f"{bit_width}-bit"},
                              # {"config.num_calibration_samples": 128},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"$or": [
                                {"config.evaluation_dataset": f"floresplus-evaluate"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                              ]},
                              # {"config.base_model": base_model},
                              # {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                              # {"created_at": {"$gt": '2026-01-15'}},
                              {"created_at": {"$gt": '2026-07-01'}},
                              # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                              # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            ]
                            },
                            { "$and" : [
                                {"config.quantization_technique": "Unquantized"},
                                # {"config.evaluation_dataset": evaluation_dataset},
                                {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                                # {"config.base_model": base_model},
                              # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                              # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                                {"config.enable_thinking": False},
                                {"config.output_type": "perplexity"},
                              {"created_at": {"$gt": '2026-01-15'}},
                              {"created_at": {"$lt": '2026-07-01'}},
                            ]}
                        ]}
                    )

    eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
    # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
    # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
    # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
    # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
    # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

    # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
    perplexity_heatmap_deliver_vertical_sinq(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, embed_sinq=True, write_pdf=f"ablation_floresplus_{bit_width}bit_{quantization_technique}_all_vert_final.pdf")

/tmp/ipykernel_3071/1242997687.py:187: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
15,Qwen/Qwen3-8B,gptq,4-bit,Sinq,35.693894,2.847228,17.717172,73.394102,52.279770
0,Qwen/Qwen3-8B,gptq,4-bit,English,38.633773,2.903144,18.795383,81.519027,54.471988
2,Qwen/Qwen3-8B,gptq,4-bit,Tamil,36.874922,2.789352,18.045387,80.639509,52.047636
1,Qwen/Qwen3-8B,gptq,4-bit,Indonesian,36.307482,2.869462,17.537566,75.503067,52.100443
3,Qwen/Qwen3-8B,gptq,4-bit,Swahili,36.782606,2.862192,18.727565,71.522493,52.984904
4,Qwen/Qwen3-8B,gptq,4-bit,Chinese,36.791005,2.921814,17.943838,78.501095,52.133661
16,CohereLabs/aya-expanse-8b,gptq,4-bit,Sinq,55.876352,4.002676,98.200647,394.071986,122.265194
5,CohereLabs/aya-expanse-8b,gptq,4-bit,English,50.815876,3.947913,89.978133,401.770728,113.312037
7,CohereLabs/aya-expanse-8b,gptq,4-bit,Tamil,51.355844,3.796851,90.784244,373.873691,112.280232
6,CohereLabs/aya-expanse-8b,gptq,4-bit,Indonesian,52.137953,3.977342,90.535852,365.351107,113.168497
8,CohereLabs/aya-expanse-8b,gptq,4-bit,Swahili,50.556806,3.900542,89.279740,352.421007,112.105412
9,CohereLabs/aya-expanse-8b,gptq,4-bit,Chinese,52.413353,3.929984,92.005672,381.202734,113.046247
17,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Sinq,43.628489,2.412915,25.845251,32.918649,39.595530
10,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,English,47.372066,2.503244,27.111507,35.268858,40.062125
12,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Tamil,46.727688,2.341632,27.035368,34.343137,39.947466
11,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Indonesian,46.340421,2.454821,25.609484,33.018261,40.115798
13,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Swahili,46.679481,2.453562,26.443130,31.212913,40.419192
14,meta-llama/Llama-3.1-8B-Instruct,gptq,4-bit,Chinese,46.697379,2.436780,27.025912,34.342650,38.331823

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
9,Qwen/Qwen3-8B,gptq,Sinq,4-bit,1.552594,0.454422,1.248394,1.865661,1.718334
7,Qwen/Qwen3-8B,gptq,English,4-bit,1.586967,0.462869,1.274051,1.911259,1.736173
11,Qwen/Qwen3-8B,gptq,Tamil,4-bit,1.566731,0.445503,1.256366,1.906548,1.716401
8,Qwen/Qwen3-8B,gptq,Indonesian,4-bit,1.559996,0.457800,1.243969,1.877965,1.716841
10,Qwen/Qwen3-8B,gptq,Swahili,4-bit,1.565642,0.456699,1.272481,1.854443,1.724152
6,Qwen/Qwen3-8B,gptq,Chinese,4-bit,1.565742,0.465653,1.253915,1.894876,1.717118

          GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3   1.552594  1.586967  1.566731  1.559996  1.565642  1.565742
TA_Qwen3   0.454422  0.462869  0.445503  0.457800  0.456699  0.465653
ID_Qwen3   1.248394  1.274051  1.256366  1.243969  1.272481  1.253915
SW_Qwen3   1.865661  1.911259  1.906548  1.877965  1.854443  1.894876
ZH_Qwen3   1.718334  1.736173  1.716401  1.716841  1.724152  1.717118

start model: CohereLabs/aya-expanse-8b

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
3,CohereLabs/aya-expanse-8b,gptq,Sinq,4-bit,1.747228,0.602350,1.992114,2.595576,2.087303
1,CohereLabs/aya-expanse-8b,gptq,English,4-bit,1.705999,0.596368,1.954137,2.603978,2.054276
5,CohereLabs/aya-expanse-8b,gptq,Tamil,4-bit,1.710590,0.579424,1.958010,2.572725,2.050303
2,CohereLabs/aya-expanse-8b,gptq,Indonesian,4-bit,1.717154,0.599593,1.956821,2.562710,2.053726
4,CohereLabs/aya-expanse-8b,gptq,Swahili,4-bit,1.703780,0.591125,1.950753,2.547062,2.049627
0,CohereLabs/aya-expanse-8b,gptq,Chinese,4-bit,1.719442,0.594391,1.963815,2.581156,2.053256

        GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Aya   1.747228  1.705999  1.710590  1.717154  1.703780  1.719442
TA_Aya   0.602350  0.596368  0.579424  0.599593  0.591125  0.594391
ID_Aya   1.992114  1.954137  1.958010  1.956821  1.950753  1.963815
SW_Aya   2.595576  2.603978  2.572725  2.562710  2.547062  2.581156
ZH_Aya   2.087303  2.054276  2.050303  2.053726  2.049627  2.053256

start model: meta-llama/Llama-3.1-8B-Instruct

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
15,meta-llama/Llama-3.1-8B-Instruct,gptq,Sinq,4-bit,1.639770,0.382542,1.412381,1.517442,1.597646
13,meta-llama/Llama-3.1-8B-Instruct,gptq,English,4-bit,1.675522,0.398503,1.433154,1.547391,1.602734
17,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,4-bit,1.669574,0.369519,1.431932,1.535840,1.601489
14,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,4-bit,1.665960,0.390020,1.408401,1.518754,1.603315
16,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,4-bit,1.669126,0.389797,1.422313,1.494334,1.606588
12,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,4-bit,1.669293,0.386816,1.431780,1.535834,1.583559

          GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Llama   1.639770  1.675522  1.669574  1.665960  1.669126  1.669293
TA_Llama   0.382542  0.398503  0.369519  0.390020  0.389797  0.386816
ID_Llama   1.412381  1.433154  1.431932  1.408401  1.422313  1.431780
SW_Llama   1.517442  1.547391  1.535840  1.518754  1.494334  1.535834
ZH_Llama   1.597646  1.602734  1.601489  1.603315  1.606588  1.583559

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH
ZH_Llama,36.821779,39.595530,40.062125,39.947466,40.115798,40.419192,38.331823
SW_Llama,30.056285,32.918649,35.268858,34.343137,33.018261,31.212913,34.342650
ID_Llama,24.823783,25.845251,27.111507,27.035368,25.609484,26.443130,27.025912
TA_Llama,2.311781,2.412915,2.503244,2.341632,2.454821,2.453562,2.436780
EN_Llama,45.105214,43.628489,47.372066,46.727688,46.340421,46.679481,46.697379
ZH_Aya,112.084228,122.265194,113.312037,112.280232,113.168497,112.105412,113.046247
SW_Aya,347.245294,394.071986,401.770728,373.873691,365.351107,352.421007,381.202734
ID_Aya,92.363250,98.200647,89.978133,90.784244,90.535852,89.279740,92.005672
TA_Aya,3.798334,4.002676,3.947913,3.796851,3.977342,3.900542,3.929984
EN_Aya,53.754913,55.876352,50.815876,51.355844,52.137953,50.556806,52.413353
ZH_Qwen3,46.980806,52.279770,54.471988,52.047636,52.100443,52.984904,52.133661
SW_Qwen3,64.534645,73.394102,81.519027,80.639509,75.503067,71.522493,78.501095
ID_Qwen3,16.699008,17.717172,18.795383,18.045387,17.537566,18.727565,17.943838
TA_Qwen3,2.741605,2.847228,2.903144,2.789352,2.869462,2.862192,2.921814
EN_Qwen3,33.428698,35.693894,38.633773,36.874922,36.307482,36.782606,36.791005

          UQ  GPTQ-SINQ  GPTQ-EN  GPTQ-TA  GPTQ-ID  GPTQ-SW  GPTQ-ZH
ZH_Llama NaN        0.0      0.0      0.0      0.0      0.0      0.0
SW_Llama NaN        0.0      0.0      0.0      0.0      0.0      0.0
ID_Llama NaN        0.0      0.0      0.0      0.0      0.0      0.0
TA_Llama NaN        0.0      0.0      0.0      0.0      0.0      0.0
EN_Llama NaN        0.0      0.0      0.0      0.0      0.0      0.0
ZH_Aya   NaN        0.0      0.0      0.0      0.0      0.0      0.0
SW_Aya   NaN        0.0      0.0      0.0      0.0      0.0      0.0
ID_Aya   NaN        0.0      0.0      0.0      0.0      0.0      0.0
TA_Aya   NaN        0.0      0.0      0.0      0.0      0.0      0.0
EN_Aya   NaN        0.0      0.0      0.0      0.0      0.0      0.0
ZH_Qwen3 NaN        0.0      0.0      0.0      0.0      0.0      0.0
SW_Qwen3 NaN        0.0      0.0      0.0      0.0      0.0      0.0
ID_Qwen3 NaN        0.0      0.0      0.0      0.0      0.0      0.0
TA_Qwen3 NaN        0.0      0.0      0.0      0.0      0.0      0.0
EN_Qwen3 NaN        0.0      0.0      0.0      0.0      0.0      0.0

## Shape
df text: (15, 7)
df std: (15, 7)
Display df

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH
ZH_Llama,36.821779,39.595530,40.062125,39.947466,40.115798,40.419192,38.331823
SW_Llama,30.056285,32.918649,35.268858,34.343137,33.018261,31.212913,34.342650
ID_Llama,24.823783,25.845251,27.111507,27.035368,25.609484,26.443130,27.025912
TA_Llama,2.311781,2.412915,2.503244,2.341632,2.454821,2.453562,2.436780
EN_Llama,45.105214,43.628489,47.372066,46.727688,46.340421,46.679481,46.697379
ZH_Aya,112.084228,122.265194,113.312037,112.280232,113.168497,112.105412,113.046247
SW_Aya,347.245294,394.071986,401.770728,373.873691,365.351107,352.421007,381.202734
ID_Aya,92.363250,98.200647,89.978133,90.784244,90.535852,89.279740,92.005672
TA_Aya,3.798334,4.002676,3.947913,3.796851,3.977342,3.900542,3.929984
EN_Aya,53.754913,55.876352,50.815876,51.355844,52.137953,50.556806,52.413353
ZH_Qwen3,46.980806,52.279770,54.471988,52.047636,52.100443,52.984904,52.133661
SW_Qwen3,64.534645,73.394102,81.519027,80.639509,75.503067,71.522493,78.501095
ID_Qwen3,16.699008,17.717172,18.795383,18.045387,17.537566,18.727565,17.943838
TA_Qwen3,2.741605,2.847228,2.903144,2.789352,2.869462,2.862192,2.921814
EN_Qwen3,33.428698,35.693894,38.633773,36.874922,36.307482,36.782606,36.791005

Display df std

         UQ GPTQ-SINQ GPTQ-EN GPTQ-TA GPTQ-ID GPTQ-SW GPTQ-ZH
ZH_Llama
SW_Llama
ID_Llama
TA_Llama
EN_Llama
ZH_Aya
SW_Aya
ID_Aya
TA_Aya
EN_Aya
ZH_Qwen3
SW_Qwen3
ID_Qwen3
TA_Qwen3
EN_Qwen3

Writing to pdf ...

/tmp/ipykernel_3071/1242997687.py:187: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
13,Qwen/Qwen3-8B,slimllm,4-bit,Sinq,35.693894,2.847228,17.717172,73.394102,52.279770
0,Qwen/Qwen3-8B,slimllm,4-bit,English,34.260498,2.958074,17.888351,79.743173,49.544540
2,Qwen/Qwen3-8B,slimllm,4-bit,Tamil,36.234922,2.776822,18.097900,78.928706,50.708137
1,Qwen/Qwen3-8B,slimllm,4-bit,Indonesian,34.633644,2.891498,17.211146,77.379406,49.841062
3,Qwen/Qwen3-8B,slimllm,4-bit,Swahili,34.731503,2.901018,17.629107,63.984313,49.638112
4,Qwen/Qwen3-8B,slimllm,4-bit,Chinese,35.165068,2.918109,18.043827,78.800577,47.496192
14,CohereLabs/aya-expanse-8b,slimllm,4-bit,Sinq,55.876352,4.002676,98.200647,394.071986,122.265194
5,CohereLabs/aya-expanse-8b,slimllm,4-bit,English,54.706773,4.021575,98.354503,397.648200,124.485867
6,CohereLabs/aya-expanse-8b,slimllm,4-bit,Indonesian,55.686326,3.975950,93.870980,372.462067,122.105721
7,CohereLabs/aya-expanse-8b,slimllm,4-bit,Swahili,55.946115,3.920454,97.055222,337.157383,123.359929
8,CohereLabs/aya-expanse-8b,slimllm,4-bit,Chinese,55.432520,3.954161,98.401795,412.249550,117.615823
15,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Sinq,43.628489,2.412915,25.845251,32.918649,39.595530
9,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,English,43.532462,2.695015,28.568594,36.902012,41.523714
10,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Indonesian,44.632579,2.735899,26.986952,37.360703,44.224801
11,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Swahili,45.423450,2.699435,28.200670,32.886215,46.296442
12,meta-llama/Llama-3.1-8B-Instruct,slimllm,4-bit,Chinese,44.928034,2.555277,27.777874,35.678429,38.107827

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Qwen3, TA_Qwen3, ID_Qwen3, SW_Qwen3, ZH_Qwen3]

start model: CohereLabs/aya-expanse-8b

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Aya, TA_Aya, ID_Aya, SW_Aya, ZH_Aya]

start model: meta-llama/Llama-3.1-8B-Instruct

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Llama, TA_Llama, ID_Llama, SW_Llama, ZH_Llama]

,UQ,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,36.821779,39.595530,41.523714,NaN,44.224801,46.296442,38.107827
SW_Llama,30.056285,32.918649,36.902012,NaN,37.360703,32.886215,35.678429
ID_Llama,24.823783,25.845251,28.568594,NaN,26.986952,28.200670,27.777874
TA_Llama,2.311781,2.412915,2.695015,NaN,2.735899,2.699435,2.555277
EN_Llama,45.105214,43.628489,43.532462,NaN,44.632579,45.423450,44.928034
ZH_Aya,112.084228,122.265194,124.485867,NaN,122.105721,123.359929,117.615823
SW_Aya,347.245294,394.071986,397.648200,NaN,372.462067,337.157383,412.249550
ID_Aya,92.363250,98.200647,98.354503,NaN,93.870980,97.055222,98.401795
TA_Aya,3.798334,4.002676,4.021575,NaN,3.975950,3.920454,3.954161
EN_Aya,53.754913,55.876352,54.706773,NaN,55.686326,55.946115,55.432520
ZH_Qwen3,46.980806,52.279770,49.544540,50.708137,49.841062,49.638112,47.496192
SW_Qwen3,64.534645,73.394102,79.743173,78.928706,77.379406,63.984313,78.800577
ID_Qwen3,16.699008,17.717172,17.888351,18.097900,17.211146,17.629107,18.043827
TA_Qwen3,2.741605,2.847228,2.958074,2.776822,2.891498,2.901018,2.918109
EN_Qwen3,33.428698,35.693894,34.260498,36.234922,34.633644,34.731503,35.165068

,UQ,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,NaN,0.0,0.0,NaN,0.0,0.0,0.0
SW_Llama,NaN,0.0,0.0,NaN,0.0,0.0,0.0
ID_Llama,NaN,0.0,0.0,NaN,0.0,0.0,0.0
TA_Llama,NaN,0.0,0.0,NaN,0.0,0.0,0.0
EN_Llama,NaN,0.0,0.0,NaN,0.0,0.0,0.0
ZH_Aya,NaN,0.0,0.0,NaN,0.0,0.0,0.0
SW_Aya,NaN,0.0,0.0,NaN,0.0,0.0,0.0
ID_Aya,NaN,0.0,0.0,NaN,0.0,0.0,0.0
TA_Aya,NaN,0.0,0.0,NaN,0.0,0.0,0.0
EN_Aya,NaN,0.0,0.0,NaN,0.0,0.0,0.0
ZH_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0
SW_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0
ID_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0
TA_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0
EN_Qwen3,NaN,0.0,0.0,0.0,0.0,0.0,0.0

## Shape
df text: (15, 7)
df std: (15, 7)
Display df

,UQ,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,36.821779,39.595530,41.523714,NaN,44.224801,46.296442,38.107827
SW_Llama,30.056285,32.918649,36.902012,NaN,37.360703,32.886215,35.678429
ID_Llama,24.823783,25.845251,28.568594,NaN,26.986952,28.200670,27.777874
TA_Llama,2.311781,2.412915,2.695015,NaN,2.735899,2.699435,2.555277
EN_Llama,45.105214,43.628489,43.532462,NaN,44.632579,45.423450,44.928034
ZH_Aya,112.084228,122.265194,124.485867,NaN,122.105721,123.359929,117.615823
SW_Aya,347.245294,394.071986,397.648200,NaN,372.462067,337.157383,412.249550
ID_Aya,92.363250,98.200647,98.354503,NaN,93.870980,97.055222,98.401795
TA_Aya,3.798334,4.002676,4.021575,NaN,3.975950,3.920454,3.954161
EN_Aya,53.754913,55.876352,54.706773,NaN,55.686326,55.946115,55.432520
ZH_Qwen3,46.980806,52.279770,49.544540,50.708137,49.841062,49.638112,47.496192
SW_Qwen3,64.534645,73.394102,79.743173,78.928706,77.379406,63.984313,78.800577
ID_Qwen3,16.699008,17.717172,17.888351,18.097900,17.211146,17.629107,18.043827
TA_Qwen3,2.741605,2.847228,2.958074,2.776822,2.891498,2.901018,2.918109
EN_Qwen3,33.428698,35.693894,34.260498,36.234922,34.633644,34.731503,35.165068

Display df std

,UQ,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,,,,,,,
SW_Llama,,,,,,,
ID_Llama,,,,,,,
TA_Llama,,,,,,,
EN_Llama,,,,,,,
ZH_Aya,,,,,,,
SW_Aya,,,,,,,
ID_Aya,,,,,,,
TA_Aya,,,,,,,
EN_Aya,,,,,,,
ZH_Qwen3,,,,,,,
SW_Qwen3,,,,,,,
ID_Qwen3,,,,,,,
TA_Qwen3,,,,,,,
EN_Qwen3,,,,,,,

Writing to pdf ...

/tmp/ipykernel_3071/1242997687.py:187: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
15,Qwen/Qwen3-8B,tacq,4-bit,Sinq,35.693894,2.847228,17.717172,73.394102,52.279770
0,Qwen/Qwen3-8B,tacq,4-bit,English,34.147866,2.870331,17.424552,74.335601,48.763523
2,Qwen/Qwen3-8B,tacq,4-bit,Tamil,34.711885,2.758863,17.336806,73.351131,48.556783
1,Qwen/Qwen3-8B,tacq,4-bit,Indonesian,35.199599,2.878214,16.914091,73.971753,48.985351
3,Qwen/Qwen3-8B,tacq,4-bit,Swahili,34.439505,2.856956,17.086451,64.984794,48.547595
4,Qwen/Qwen3-8B,tacq,4-bit,Chinese,34.218867,2.906739,17.528538,73.939017,47.282614
16,CohereLabs/aya-expanse-8b,tacq,4-bit,Sinq,55.876352,4.002676,98.200647,394.071986,122.265194
5,CohereLabs/aya-expanse-8b,tacq,4-bit,English,55.022220,3.980362,96.781066,388.558360,120.301677
7,CohereLabs/aya-expanse-8b,tacq,4-bit,Tamil,55.689060,3.848132,97.586160,389.291678,120.618816
6,CohereLabs/aya-expanse-8b,tacq,4-bit,Indonesian,55.559975,3.942369,95.089391,381.536862,119.716704
8,CohereLabs/aya-expanse-8b,tacq,4-bit,Swahili,55.820594,3.988709,97.101196,364.872794,121.515856
9,CohereLabs/aya-expanse-8b,tacq,4-bit,Chinese,55.483941,3.928528,96.739712,411.201310,116.573491
17,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Sinq,43.628489,2.412915,25.845251,32.918649,39.595530
10,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,English,45.535295,2.503889,27.187312,34.456392,40.119780
12,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Tamil,46.511978,2.345541,27.168395,33.305476,39.193255
11,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Indonesian,46.849139,2.457776,25.944766,32.882074,40.222063
13,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Swahili,46.166003,2.460396,26.501118,30.807823,39.940935
14,meta-llama/Llama-3.1-8B-Instruct,tacq,4-bit,Chinese,45.672605,2.424910,27.072293,33.288619,37.424322

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
9,Qwen/Qwen3-8B,tacq,Sinq,4-bit,0.0,0.0,0.0,0.0,0.0
7,Qwen/Qwen3-8B,tacq,English,4-bit,0.0,0.0,0.0,0.0,0.0
11,Qwen/Qwen3-8B,tacq,Tamil,4-bit,0.0,0.0,0.0,0.0,0.0
8,Qwen/Qwen3-8B,tacq,Indonesian,4-bit,0.0,0.0,0.0,0.0,0.0
10,Qwen/Qwen3-8B,tacq,Swahili,4-bit,0.0,0.0,0.0,0.0,0.0
6,Qwen/Qwen3-8B,tacq,Chinese,4-bit,0.0,0.0,0.0,0.0,0.0
3,CohereLabs/aya-expanse-8b,tacq,Sinq,4-bit,0.0,0.0,0.0,0.0,0.0
1,CohereLabs/aya-expanse-8b,tacq,English,4-bit,0.0,0.0,0.0,0.0,0.0
5,CohereLabs/aya-expanse-8b,tacq,Tamil,4-bit,0.0,0.0,0.0,0.0,0.0
2,CohereLabs/aya-expanse-8b,tacq,Indonesian,4-bit,0.0,0.0,0.0,0.0,0.0
4,CohereLabs/aya-expanse-8b,tacq,Swahili,4-bit,0.0,0.0,0.0,0.0,0.0
0,CohereLabs/aya-expanse-8b,tacq,Chinese,4-bit,0.0,0.0,0.0,0.0,0.0
15,meta-llama/Llama-3.1-8B-Instruct,tacq,Sinq,4-bit,0.0,0.0,0.0,0.0,0.0
13,meta-llama/Llama-3.1-8B-Instruct,tacq,English,4-bit,0.0,0.0,0.0,0.0,0.0
17,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,4-bit,0.0,0.0,0.0,0.0,0.0
14,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,4-bit,0.0,0.0,0.0,0.0,0.0
16,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,4-bit,0.0,0.0,0.0,0.0,0.0
12,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,4-bit,0.0,0.0,0.0,0.0,0.0

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Qwen3, TA_Qwen3, ID_Qwen3, SW_Qwen3, ZH_Qwen3]

start model: CohereLabs/aya-expanse-8b

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Aya, TA_Aya, ID_Aya, SW_Aya, ZH_Aya]

start model: meta-llama/Llama-3.1-8B-Instruct

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Llama, TA_Llama, ID_Llama, SW_Llama, ZH_Llama]

,UQ,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,39.595530,40.119780,39.193255,40.222063,39.940935,37.424322
SW_Llama,30.056285,32.918649,34.456392,33.305476,32.882074,30.807823,33.288619
ID_Llama,24.823783,25.845251,27.187312,27.168395,25.944766,26.501118,27.072293
TA_Llama,2.311781,2.412915,2.503889,2.345541,2.457776,2.460396,2.424910
EN_Llama,45.105214,43.628489,45.535295,46.511978,46.849139,46.166003,45.672605
ZH_Aya,112.084228,122.265194,120.301677,120.618816,119.716704,121.515856,116.573491
SW_Aya,347.245294,394.071986,388.558360,389.291678,381.536862,364.872794,411.201310
ID_Aya,92.363250,98.200647,96.781066,97.586160,95.089391,97.101196,96.739712
TA_Aya,3.798334,4.002676,3.980362,3.848132,3.942369,3.988709,3.928528
EN_Aya,53.754913,55.876352,55.022220,55.689060,55.559975,55.820594,55.483941
ZH_Qwen3,46.980806,52.279770,48.763523,48.556783,48.985351,48.547595,47.282614
SW_Qwen3,64.534645,73.394102,74.335601,73.351131,73.971753,64.984794,73.939017
ID_Qwen3,16.699008,17.717172,17.424552,17.336806,16.914091,17.086451,17.528538
TA_Qwen3,2.741605,2.847228,2.870331,2.758863,2.878214,2.856956,2.906739
EN_Qwen3,33.428698,35.693894,34.147866,34.711885,35.199599,34.439505,34.218867

          UQ  TaCQ-SINQ  TaCQ-EN  TaCQ-TA  TaCQ-ID  TaCQ-SW  TaCQ-ZH
ZH_Llama NaN        0.0      0.0      0.0      0.0      0.0      0.0
SW_Llama NaN        0.0      0.0      0.0      0.0      0.0      0.0
ID_Llama NaN        0.0      0.0      0.0      0.0      0.0      0.0
TA_Llama NaN        0.0      0.0      0.0      0.0      0.0      0.0
EN_Llama NaN        0.0      0.0      0.0      0.0      0.0      0.0
ZH_Aya   NaN        0.0      0.0      0.0      0.0      0.0      0.0
SW_Aya   NaN        0.0      0.0      0.0      0.0      0.0      0.0
ID_Aya   NaN        0.0      0.0      0.0      0.0      0.0      0.0
TA_Aya   NaN        0.0      0.0      0.0      0.0      0.0      0.0
EN_Aya   NaN        0.0      0.0      0.0      0.0      0.0      0.0
ZH_Qwen3 NaN        0.0      0.0      0.0      0.0      0.0      0.0
SW_Qwen3 NaN        0.0      0.0      0.0      0.0      0.0      0.0
ID_Qwen3 NaN        0.0      0.0      0.0      0.0      0.0      0.0
TA_Qwen3 NaN        0.0      0.0      0.0      0.0      0.0      0.0
EN_Qwen3 NaN        0.0      0.0      0.0      0.0      0.0      0.0

## Shape
df text: (15, 7)
df std: (15, 7)
Display df

,UQ,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,39.595530,40.119780,39.193255,40.222063,39.940935,37.424322
SW_Llama,30.056285,32.918649,34.456392,33.305476,32.882074,30.807823,33.288619
ID_Llama,24.823783,25.845251,27.187312,27.168395,25.944766,26.501118,27.072293
TA_Llama,2.311781,2.412915,2.503889,2.345541,2.457776,2.460396,2.424910
EN_Llama,45.105214,43.628489,45.535295,46.511978,46.849139,46.166003,45.672605
ZH_Aya,112.084228,122.265194,120.301677,120.618816,119.716704,121.515856,116.573491
SW_Aya,347.245294,394.071986,388.558360,389.291678,381.536862,364.872794,411.201310
ID_Aya,92.363250,98.200647,96.781066,97.586160,95.089391,97.101196,96.739712
TA_Aya,3.798334,4.002676,3.980362,3.848132,3.942369,3.988709,3.928528
EN_Aya,53.754913,55.876352,55.022220,55.689060,55.559975,55.820594,55.483941
ZH_Qwen3,46.980806,52.279770,48.763523,48.556783,48.985351,48.547595,47.282614
SW_Qwen3,64.534645,73.394102,74.335601,73.351131,73.971753,64.984794,73.939017
ID_Qwen3,16.699008,17.717172,17.424552,17.336806,16.914091,17.086451,17.528538
TA_Qwen3,2.741605,2.847228,2.870331,2.758863,2.878214,2.856956,2.906739
EN_Qwen3,33.428698,35.693894,34.147866,34.711885,35.199599,34.439505,34.218867

Display df std

         UQ TaCQ-SINQ TaCQ-EN TaCQ-TA TaCQ-ID TaCQ-SW TaCQ-ZH
ZH_Llama
SW_Llama
ID_Llama
TA_Llama
EN_Llama
ZH_Aya
SW_Aya
ID_Aya
TA_Aya
EN_Aya
ZH_Qwen3
SW_Qwen3
ID_Qwen3
TA_Qwen3
EN_Qwen3

Writing to pdf ...

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [3]:
  for quantization_technique in ["gptq", "slimllm", "tacq"]:
    runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                    filters={"$or": [
                            { "$and": [
                              {"config.quantization_technique": quantization_technique.lower()},
                              {"config.bit_width": f"{bit_width}-bit"},
                              {"config.num_calibration_samples": 128},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"$or": [
                                {"config.evaluation_dataset": f"floresplus-evaluate"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                              ]},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                              {"created_at": {"$gt": '2026-01-15'}},
                              # {"created_at": {"$lt": '2026-07-01'}},
                              # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                              # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"$not": {"$and": [{"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}, {"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}]}}
                            ]
                            },
                            { "$and": [
                              {"config.quantization_technique": "sinq"},
                              {"config.bit_width": f"{bit_width}-bit"},
                              # {"config.num_calibration_samples": 128},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"$or": [
                                {"config.evaluation_dataset": f"floresplus-evaluate"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                              ]},
                              # {"config.base_model": base_model},
                              # {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                              # {"created_at": {"$gt": '2026-01-15'}},
                              {"created_at": {"$gt": '2026-07-01'}},
                              # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                              # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            ]
                            },
                            { "$and" : [
                                {"config.quantization_technique": "Unquantized"},
                                # {"config.evaluation_dataset": evaluation_dataset},
                                {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                                # {"config.base_model": base_model},
                              # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                              # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                                {"config.enable_thinking": False},
                                {"config.output_type": "perplexity"},
                              {"created_at": {"$gt": '2026-01-15'}},
                              {"created_at": {"$lt": '2026-07-01'}},
                            ]}
                        ]}
                    )

    eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
    # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
    # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
    # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
    # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
    # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

    # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
    perplexity_heatmap_deliver_vertical_sinq(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, embed_sinq=True, write_pdf=f"ablation_floresplus_{bit_width}bit_{quantization_technique}_all_vert_final.pdf")

/tmp/ipykernel_3071/1242997687.py:187: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
31,Qwen/Qwen3-8B,gptq,3-bit,Sinq,53.160308,3.835802,27.044173,170.134416,75.035734
0,Qwen/Qwen3-8B,gptq,3-bit,English,40.188512,4.329966,24.304464,160.417519,62.901249
15,Qwen/Qwen3-8B,gptq,3-bit,English,40.949766,4.233635,25.688953,160.373092,64.743586
16,Qwen/Qwen3-8B,gptq,3-bit,English,40.436502,4.268332,24.618706,166.343463,63.556982
2,Qwen/Qwen3-8B,gptq,3-bit,Tamil,42.012760,2.919523,22.620578,144.263196,62.475377
19,Qwen/Qwen3-8B,gptq,3-bit,Tamil,42.729569,2.937405,23.351523,141.058965,65.202294
20,Qwen/Qwen3-8B,gptq,3-bit,Tamil,43.151184,2.916437,23.161336,140.340460,64.788691
1,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,42.385494,3.915570,19.171946,143.357820,62.972576
17,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,43.250695,3.672597,18.982422,133.669715,62.093137
18,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,43.147129,3.778896,19.069444,132.905051,63.068583
3,Qwen/Qwen3-8B,gptq,3-bit,Swahili,44.786866,3.771811,22.734896,79.985090,66.249266
21,Qwen/Qwen3-8B,gptq,3-bit,Swahili,42.717366,3.676404,21.716492,77.506947,64.011188
22,Qwen/Qwen3-8B,gptq,3-bit,Swahili,44.940711,3.725982,22.273758,79.844660,65.004796
4,Qwen/Qwen3-8B,gptq,3-bit,Chinese,40.865351,4.132577,24.873793,151.040822,56.098754
23,Qwen/Qwen3-8B,gptq,3-bit,Chinese,41.267661,4.332161,24.900326,178.141356,56.762463
24,Qwen/Qwen3-8B,gptq,3-bit,Chinese,40.662271,4.109008,24.741668,156.282612,55.063003
32,CohereLabs/aya-expanse-8b,gptq,3-bit,Sinq,60.296624,4.628170,108.035480,598.420257,134.500910
5,CohereLabs/aya-expanse-8b,gptq,3-bit,English,55.716955,5.489648,122.900772,701.944022,170.108220
7,CohereLabs/aya-expanse-8b,gptq,3-bit,Tamil,59.996131,3.942703,170.286285,866.680681,262.474523
6,CohereLabs/aya-expanse-8b,gptq,3-bit,Indonesian,58.331153,4.941318,100.952621,601.327532,151.644070
8,CohereLabs/aya-expanse-8b,gptq,3-bit,Swahili,56.882036,4.902821,109.504752,386.510893,153.626228
9,CohereLabs/aya-expanse-8b,gptq,3-bit,Chinese,56.490654,5.048185,108.384593,628.567549,124.030659
33,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Sinq,50.553287,3.214247,36.127868,54.643300,50.598038
10,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,English,54.002999,4.619366,49.034587,76.299433,65.906926
12,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Tamil,56.975352,2.477804,42.820579,63.393429,57.598253
11,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Indonesian,56.643278,3.813212,32.114254,54.521151,62.209873
13,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Swahili,55.005956,3.841755,38.430521,36.941053,62.640825
14,meta-llama/Llama-3.1-8B-Instruct,gptq,3-bit,Chinese,56.127699,3.669907,45.473741,70.289028,45.390110
34,Qwen/Qwen3-14B,gptq,3-bit,Sinq,65.452441,3.086842,22.252021,140.257758,58.400786
25,Qwen/Qwen3-14B,gptq,3-bit,English,36.570983,3.434160,19.298548,106.342203,54.280184
26,Qwen/Qwen3-14B,gptq,3-bit,English,NaN,NaN,NaN,NaN,NaN
27,Qwen/Qwen3-14B,gptq,3-bit,English,NaN,NaN,NaN,NaN,NaN
35,Qwen/Qwen3-14B,gptq,3-bit,Tamil,39.736187,2.653994,18.600899,101.042983,53.330655
28,Qwen/Qwen3-14B,gptq,3-bit,Indonesian,38.121960,3.113559,16.842957,87.253248,54.865941
29,Qwen/Qwen3-14B,gptq,3-bit,Indonesian,NaN,NaN,NaN,NaN,NaN
30,Qwen/Qwen3-14B,gptq,3-bit,Indonesian,NaN,NaN,NaN,NaN,NaN
36,Qwen/Qwen3-14B,gptq,3-bit,Swahili,NaN,NaN,NaN,NaN,NaN
37,Qwen/Qwen3-14B,gptq,3-bit,Chinese,NaN,NaN,NaN,NaN,NaN

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
15,Qwen/Qwen3-8B,gptq,Sinq,3-bit,1.725587,0.583856,1.432074,2.230792,1.875268
13,Qwen/Qwen3-8B,gptq,English,3-bit,1.607722,0.631171,1.395688,2.210527,1.804371
17,Qwen/Qwen3-8B,gptq,Tamil,3-bit,1.629727,0.466045,1.362567,2.151944,1.807234
14,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,1.632738,0.578527,1.280456,2.135591,1.797347
16,Qwen/Qwen3-8B,gptq,Swahili,3-bit,1.644914,0.571095,1.347168,1.898244,1.813504
12,Qwen/Qwen3-8B,gptq,Chinese,3-bit,1.612060,0.622343,1.395127,2.209036,1.747992

          GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3   1.725587  1.607722  1.629727  1.632738  1.644914  1.612060
TA_Qwen3   0.583856  0.631171  0.466045  0.578527  0.571095  0.622343
ID_Qwen3   1.432074  1.395688  1.362567  1.280456  1.347168  1.395127
SW_Qwen3   2.230792  2.210527  2.151944  2.135591  1.898244  2.209036
ZH_Qwen3   1.875268  1.804371  1.807234  1.797347  1.813504  1.747992

start model: CohereLabs/aya-expanse-8b

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
3,CohereLabs/aya-expanse-8b,gptq,Sinq,3-bit,1.780293,0.665409,2.033566,2.777006,2.128725
1,CohereLabs/aya-expanse-8b,gptq,English,3-bit,1.745987,0.739545,2.089555,2.846302,2.230725
5,CohereLabs/aya-expanse-8b,gptq,Tamil,3-bit,1.778123,0.595794,2.231180,2.937859,2.419087
2,CohereLabs/aya-expanse-8b,gptq,Indonesian,3-bit,1.765901,0.693843,2.004118,2.779111,2.180825
4,CohereLabs/aya-expanse-8b,gptq,Swahili,3-bit,1.754975,0.690446,2.039433,2.587162,2.186465
0,CohereLabs/aya-expanse-8b,gptq,Chinese,3-bit,1.751977,0.703135,2.034968,2.798352,2.093529

        GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Aya   1.780293  1.745987  1.778123  1.765901  1.754975  1.751977
TA_Aya   0.665409  0.739545  0.595794  0.693843  0.690446  0.703135
ID_Aya   2.033566  2.089555  2.231180  2.004118  2.039433  2.034968
SW_Aya   2.777006  2.846302  2.937859  2.779111  2.587162  2.798352
ZH_Aya   2.128725  2.230725  2.419087  2.180825  2.186465  2.093529

start model: meta-llama/Llama-3.1-8B-Instruct

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
21,meta-llama/Llama-3.1-8B-Instruct,gptq,Sinq,3-bit,1.703749,0.507079,1.557842,1.737537,1.704134
19,meta-llama/Llama-3.1-8B-Instruct,gptq,English,3-bit,1.732418,0.664582,1.690503,1.882521,1.818931
23,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,3-bit,1.755687,0.394067,1.631653,1.802044,1.760409
20,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,3-bit,1.753148,0.581291,1.506698,1.736565,1.793859
22,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,3-bit,1.740410,0.584530,1.584676,1.567509,1.796857
18,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,3-bit,1.749177,0.564655,1.657761,1.846888,1.656961

          GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Llama   1.703749  1.732418  1.755687  1.753148  1.740410  1.749177
TA_Llama   0.507079  0.664582  0.394067  0.581291  0.584530  0.564655
ID_Llama   1.557842  1.690503  1.631653  1.506698  1.584676  1.657761
SW_Llama   1.737537  1.882521  1.802044  1.736565  1.567509  1.846888
ZH_Llama   1.704134  1.818931  1.760409  1.793859  1.796857  1.656961

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH
ZH_Llama,36.821779,50.598038,65.906926,57.598253,62.209873,62.640825,45.390110
SW_Llama,30.056285,54.643300,76.299433,63.393429,54.521151,36.941053,70.289028
ID_Llama,24.823783,36.127868,49.034587,42.820579,32.114254,38.430521,45.473741
TA_Llama,2.311781,3.214247,4.619366,2.477804,3.813212,3.841755,3.669907
EN_Llama,45.105214,50.553287,54.002999,56.975352,56.643278,55.005956,56.127699
ZH_Aya,112.084228,134.500910,170.108220,262.474523,151.644070,153.626228,124.030659
SW_Aya,347.245294,598.420257,701.944022,866.680681,601.327532,386.510893,628.567549
ID_Aya,92.363250,108.035480,122.900772,170.286285,100.952621,109.504752,108.384593
TA_Aya,3.798334,4.628170,5.489648,3.942703,4.941318,4.902821,5.048185
EN_Aya,53.754913,60.296624,55.716955,59.996131,58.331153,56.882036,56.490654
ZH_Qwen3,46.980806,75.035734,63.733939,64.155454,62.711432,65.088417,55.974740
SW_Qwen3,64.534645,170.134416,162.378025,141.887540,136.644195,79.112232,161.821596
ID_Qwen3,16.699008,27.044173,24.870707,23.044479,19.074604,22.241715,24.838596
TA_Qwen3,2.741605,3.835802,4.277311,2.924455,3.789021,3.724733,4.191249
EN_Qwen3,33.428698,53.160308,40.524927,42.631171,42.927773,44.148314,40.931761

          UQ  GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW    GPTQ-ZH
ZH_Llama NaN        0.0  0.000000  0.000000  0.000000  0.000000   0.000000
SW_Llama NaN        0.0  0.000000  0.000000  0.000000  0.000000   0.000000
ID_Llama NaN        0.0  0.000000  0.000000  0.000000  0.000000   0.000000
TA_Llama NaN        0.0  0.000000  0.000000  0.000000  0.000000   0.000000
EN_Llama NaN        0.0  0.000000  0.000000  0.000000  0.000000   0.000000
ZH_Aya   NaN        0.0  0.000000  0.000000  0.000000  0.000000   0.000000
SW_Aya   NaN        0.0  0.000000  0.000000  0.000000  0.000000   0.000000
ID_Aya   NaN        0.0  0.000000  0.000000  0.000000  0.000000   0.000000
TA_Aya   NaN        0.0  0.000000  0.000000  0.000000  0.000000   0.000000
EN_Aya   NaN        0.0  0.000000  0.000000  0.000000  0.000000   0.000000
ZH_Qwen3 NaN        0.0  0.762469  1.199933  0.438954  0.915603   0.699321
SW_Qwen3 NaN        0.0  2.804047  1.705260  4.757503  1.136555  11.736552
ID_Qwen3 NaN        0.0  0.592639  0.309636  0.077459  0.416378   0.069389
TA_Qwen3 NaN        0.0  0.039836  0.009243  0.099452  0.038960   0.100104
EN_Qwen3 NaN        0.0  0.317008  0.469939  0.385773  1.013781   0.251571

## Shape
df text: (15, 7)
df std: (15, 7)
Display df

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH
ZH_Llama,36.821779,50.598038,65.906926,57.598253,62.209873,62.640825,45.390110
SW_Llama,30.056285,54.643300,76.299433,63.393429,54.521151,36.941053,70.289028
ID_Llama,24.823783,36.127868,49.034587,42.820579,32.114254,38.430521,45.473741
TA_Llama,2.311781,3.214247,4.619366,2.477804,3.813212,3.841755,3.669907
EN_Llama,45.105214,50.553287,54.002999,56.975352,56.643278,55.005956,56.127699
ZH_Aya,112.084228,134.500910,170.108220,262.474523,151.644070,153.626228,124.030659
SW_Aya,347.245294,598.420257,701.944022,866.680681,601.327532,386.510893,628.567549
ID_Aya,92.363250,108.035480,122.900772,170.286285,100.952621,109.504752,108.384593
TA_Aya,3.798334,4.628170,5.489648,3.942703,4.941318,4.902821,5.048185
EN_Aya,53.754913,60.296624,55.716955,59.996131,58.331153,56.882036,56.490654
ZH_Qwen3,46.980806,75.035734,63.733939,64.155454,62.711432,65.088417,55.974740
SW_Qwen3,64.534645,170.134416,162.378025,141.887540,136.644195,79.112232,161.821596
ID_Qwen3,16.699008,27.044173,24.870707,23.044479,19.074604,22.241715,24.838596
TA_Qwen3,2.741605,3.835802,4.277311,2.924455,3.789021,3.724733,4.191249
EN_Qwen3,33.428698,53.160308,40.524927,42.631171,42.927773,44.148314,40.931761

Display df std

         UQ GPTQ-SINQ GPTQ-EN GPTQ-TA GPTQ-ID GPTQ-SW GPTQ-ZH
ZH_Llama
SW_Llama
ID_Llama
TA_Llama
EN_Llama
ZH_Aya
SW_Aya
ID_Aya
TA_Aya
EN_Aya
ZH_Qwen3                 0.76    1.20    0.44    0.92    0.70
SW_Qwen3                 2.80    1.71    4.76    1.14   11.74
ID_Qwen3                 0.59    0.31    0.08    0.42    0.07
TA_Qwen3                 0.04    0.01    0.10    0.04    0.10
EN_Qwen3                 0.32    0.47    0.39    1.01    0.25

Writing to pdf ...

/tmp/ipykernel_3071/1242997687.py:187: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
23,Qwen/Qwen3-8B,slimllm,3-bit,Sinq,53.160308,3.835802,27.044173,170.134416,75.035734
0,Qwen/Qwen3-8B,slimllm,3-bit,English,37.996881,5.016177,26.602903,168.990251,62.766314
13,Qwen/Qwen3-8B,slimllm,3-bit,English,37.998784,5.006315,26.158109,167.302009,64.763401
14,Qwen/Qwen3-8B,slimllm,3-bit,English,38.569713,4.824668,26.094763,156.663898,66.608623
2,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,44.634059,2.900774,23.035248,135.082451,62.115039
17,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,47.864063,2.908678,24.164053,148.063340,64.064579
18,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,45.744729,2.912922,24.153516,153.229178,64.256978
1,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,40.979761,3.987145,18.939585,135.638807,63.992288
15,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,42.648606,3.982393,18.998192,135.061858,65.711417
16,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,41.908018,4.059630,19.014005,142.466939,64.754799
3,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,45.255367,4.003747,22.944876,74.916424,68.855317
19,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,43.240062,3.958805,22.119773,74.219013,69.179620
20,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,44.855199,3.953273,22.687072,73.187326,67.086059
4,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,44.252408,4.236144,26.923226,168.427617,54.448928
21,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,45.122009,4.719561,29.264508,188.082925,56.398916
22,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,42.562075,4.407932,27.065704,182.361335,55.811099
24,CohereLabs/aya-expanse-8b,slimllm,3-bit,Sinq,60.296624,4.628170,108.035480,598.420257,134.500910
5,CohereLabs/aya-expanse-8b,slimllm,3-bit,English,70.334848,5.190608,128.241772,694.409390,153.807992
6,CohereLabs/aya-expanse-8b,slimllm,3-bit,Indonesian,70.159288,4.846758,106.431040,581.597703,148.348093
7,CohereLabs/aya-expanse-8b,slimllm,3-bit,Swahili,71.447728,4.707457,117.153934,372.344141,152.570887
8,CohereLabs/aya-expanse-8b,slimllm,3-bit,Chinese,71.276244,4.957356,123.701714,698.011042,127.689433
25,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Sinq,50.553287,3.214247,36.127868,54.643300,50.598038
9,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,English,51.661761,6.090120,80.624982,140.046129,107.699684
10,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Indonesian,52.608449,4.954544,33.437626,64.677236,68.901162
11,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Swahili,82.705680,8.438959,237.449086,127.097711,493.790219
12,meta-llama/Llama-3.1-8B-Instruct,slimllm,3-bit,Chinese,55.081591,3.885786,52.094113,79.511096,44.496971
26,Qwen/Qwen3-14B,slimllm,3-bit,Sinq,65.452441,3.086842,22.252021,140.257758,58.400786

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Qwen3, TA_Qwen3, ID_Qwen3, SW_Qwen3, ZH_Qwen3]

start model: CohereLabs/aya-expanse-8b

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Aya, TA_Aya, ID_Aya, SW_Aya, ZH_Aya]

start model: meta-llama/Llama-3.1-8B-Instruct

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Llama, TA_Llama, ID_Llama, SW_Llama, ZH_Llama]

,UQ,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,36.821779,50.598038,107.699684,NaN,68.901162,493.790219,44.496971
SW_Llama,30.056285,54.643300,140.046129,NaN,64.677236,127.097711,79.511096
ID_Llama,24.823783,36.127868,80.624982,NaN,33.437626,237.449086,52.094113
TA_Llama,2.311781,3.214247,6.090120,NaN,4.954544,8.438959,3.885786
EN_Llama,45.105214,50.553287,51.661761,NaN,52.608449,82.705680,55.081591
ZH_Aya,112.084228,134.500910,153.807992,NaN,148.348093,152.570887,127.689433
SW_Aya,347.245294,598.420257,694.409390,NaN,581.597703,372.344141,698.011042
ID_Aya,92.363250,108.035480,128.241772,NaN,106.431040,117.153934,123.701714
TA_Aya,3.798334,4.628170,5.190608,NaN,4.846758,4.707457,4.957356
EN_Aya,53.754913,60.296624,70.334848,NaN,70.159288,71.447728,71.276244
ZH_Qwen3,46.980806,75.035734,64.712779,63.478865,64.819501,68.373666,55.552981
SW_Qwen3,64.534645,170.134416,164.318719,145.458323,137.722535,74.107588,179.623959
ID_Qwen3,16.699008,27.044173,26.285258,23.784272,18.983927,22.583907,27.751146
TA_Qwen3,2.741605,3.835802,4.949053,2.907458,4.009722,3.971942,4.454546
EN_Qwen3,33.428698,53.160308,38.188459,46.080950,41.845462,44.450209,43.978831

,UQ,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,NaN,0.0,0.000000,NaN,0.000000,0.000000,0.000000
SW_Llama,NaN,0.0,0.000000,NaN,0.000000,0.000000,0.000000
ID_Llama,NaN,0.0,0.000000,NaN,0.000000,0.000000,0.000000
TA_Llama,NaN,0.0,0.000000,NaN,0.000000,0.000000,0.000000
EN_Llama,NaN,0.0,0.000000,NaN,0.000000,0.000000,0.000000
ZH_Aya,NaN,0.0,0.000000,NaN,0.000000,0.000000,0.000000
SW_Aya,NaN,0.0,0.000000,NaN,0.000000,0.000000,0.000000
ID_Aya,NaN,0.0,0.000000,NaN,0.000000,0.000000,0.000000
TA_Aya,NaN,0.0,0.000000,NaN,0.000000,0.000000,0.000000
EN_Aya,NaN,0.0,0.000000,NaN,0.000000,0.000000,0.000000
ZH_Qwen3,NaN,0.0,1.569024,0.967564,0.703321,0.920051,0.816734
SW_Qwen3,NaN,0.0,5.456480,7.633938,3.363059,0.710285,8.254401
ID_Qwen3,NaN,0.0,0.226093,0.529658,0.032012,0.344655,1.071688
TA_Qwen3,NaN,0.0,0.088046,0.005034,0.035343,0.022603,0.200087
EN_Qwen3,NaN,0.0,0.269588,1.339904,0.682738,0.871159,1.062842

## Shape
df text: (15, 7)
df std: (15, 7)
Display df

,UQ,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,36.821779,50.598038,107.699684,NaN,68.901162,493.790219,44.496971
SW_Llama,30.056285,54.643300,140.046129,NaN,64.677236,127.097711,79.511096
ID_Llama,24.823783,36.127868,80.624982,NaN,33.437626,237.449086,52.094113
TA_Llama,2.311781,3.214247,6.090120,NaN,4.954544,8.438959,3.885786
EN_Llama,45.105214,50.553287,51.661761,NaN,52.608449,82.705680,55.081591
ZH_Aya,112.084228,134.500910,153.807992,NaN,148.348093,152.570887,127.689433
SW_Aya,347.245294,598.420257,694.409390,NaN,581.597703,372.344141,698.011042
ID_Aya,92.363250,108.035480,128.241772,NaN,106.431040,117.153934,123.701714
TA_Aya,3.798334,4.628170,5.190608,NaN,4.846758,4.707457,4.957356
EN_Aya,53.754913,60.296624,70.334848,NaN,70.159288,71.447728,71.276244
ZH_Qwen3,46.980806,75.035734,64.712779,63.478865,64.819501,68.373666,55.552981
SW_Qwen3,64.534645,170.134416,164.318719,145.458323,137.722535,74.107588,179.623959
ID_Qwen3,16.699008,27.044173,26.285258,23.784272,18.983927,22.583907,27.751146
TA_Qwen3,2.741605,3.835802,4.949053,2.907458,4.009722,3.971942,4.454546
EN_Qwen3,33.428698,53.160308,38.188459,46.080950,41.845462,44.450209,43.978831

Display df std

,UQ,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,,,,,,,
SW_Llama,,,,,,,
ID_Llama,,,,,,,
TA_Llama,,,,,,,
EN_Llama,,,,,,,
ZH_Aya,,,,,,,
SW_Aya,,,,,,,
ID_Aya,,,,,,,
TA_Aya,,,,,,,
EN_Aya,,,,,,,
ZH_Qwen3,,,1.57,0.97,0.70,0.92,0.82
SW_Qwen3,,,5.46,7.63,3.36,0.71,8.25
ID_Qwen3,,,0.23,0.53,0.03,0.34,1.07
TA_Qwen3,,,0.09,0.01,0.04,0.02,0.20
EN_Qwen3,,,0.27,1.34,0.68,0.87,1.06

Writing to pdf ...

/tmp/ipykernel_3071/1242997687.py:187: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,16.699008,64.534645,46.980806
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,92.363250,347.245294,112.084228
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,24.823783,30.056285,36.821779
25,Qwen/Qwen3-8B,tacq,3-bit,Sinq,53.160308,3.835802,27.044173,170.134416,75.035734
0,Qwen/Qwen3-8B,tacq,3-bit,English,34.710002,3.851373,21.065718,117.199228,53.504737
15,Qwen/Qwen3-8B,tacq,3-bit,English,35.069878,3.771026,21.311044,115.479045,53.388031
16,Qwen/Qwen3-8B,tacq,3-bit,English,34.810374,3.764617,21.243588,121.969836,52.769961
2,Qwen/Qwen3-8B,tacq,3-bit,Tamil,38.876412,2.786321,19.325887,106.376712,54.060936
19,Qwen/Qwen3-8B,tacq,3-bit,Tamil,36.997150,2.796624,19.635890,104.581084,53.732649
20,Qwen/Qwen3-8B,tacq,3-bit,Tamil,37.563208,2.791408,19.625883,103.342648,54.562860
1,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,36.946025,3.450643,17.499579,102.484387,54.492987
17,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,36.064564,3.455403,17.407666,110.818460,52.491162
18,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,37.156511,3.426878,17.452419,98.432025,53.919998
3,Qwen/Qwen3-8B,tacq,3-bit,Swahili,37.239785,3.283538,19.188073,66.064982,53.378040
21,Qwen/Qwen3-8B,tacq,3-bit,Swahili,37.234178,3.334953,19.223837,65.375300,54.450253
22,Qwen/Qwen3-8B,tacq,3-bit,Swahili,37.239153,3.337267,19.129131,66.556862,53.816706
4,Qwen/Qwen3-8B,tacq,3-bit,Chinese,36.939861,3.656487,21.255791,117.447664,48.256635
23,Qwen/Qwen3-8B,tacq,3-bit,Chinese,36.811469,3.561307,21.206081,112.252142,47.935979
24,Qwen/Qwen3-8B,tacq,3-bit,Chinese,36.083784,3.604412,20.891435,116.602262,47.850495
26,CohereLabs/aya-expanse-8b,tacq,3-bit,Sinq,60.296624,4.628170,108.035480,598.420257,134.500910
5,CohereLabs/aya-expanse-8b,tacq,3-bit,English,56.603639,4.598233,104.218850,488.415269,132.582898
7,CohereLabs/aya-expanse-8b,tacq,3-bit,Tamil,59.778306,3.914037,107.600928,494.785107,135.092829
6,CohereLabs/aya-expanse-8b,tacq,3-bit,Indonesian,57.988980,4.432267,96.903556,505.833186,132.251605
8,CohereLabs/aya-expanse-8b,tacq,3-bit,Swahili,59.710328,4.394636,105.485363,351.026762,139.732992
9,CohereLabs/aya-expanse-8b,tacq,3-bit,Chinese,58.374838,4.441016,106.001720,561.057641,119.321911
27,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Sinq,50.553287,3.214247,36.127868,54.643300,50.598038
10,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,English,48.270659,4.269030,39.772587,56.283017,57.113641
12,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Tamil,50.732388,2.430107,35.062178,46.878139,48.481814
11,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Indonesian,50.051469,3.463090,28.618159,43.463953,52.050964
13,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Swahili,51.241933,3.554056,34.721147,34.765476,56.756861
14,meta-llama/Llama-3.1-8B-Instruct,tacq,3-bit,Chinese,50.027819,3.123373,35.462255,50.868524,41.277322
31,Qwen/Qwen3-14B,tacq,3-bit,Sinq,65.452441,3.086842,22.252021,140.257758,58.400786
28,Qwen/Qwen3-14B,tacq,3-bit,English,33.208545,3.341025,18.200096,83.344899,48.417162
30,Qwen/Qwen3-14B,tacq,3-bit,Tamil,39.802250,2.560754,16.792030,74.304802,48.441249
29,Qwen/Qwen3-14B,tacq,3-bit,Indonesian,34.557319,2.920792,15.548666,66.936384,49.449916
32,Qwen/Qwen3-14B,tacq,3-bit,Swahili,NaN,NaN,NaN,NaN,NaN
33,Qwen/Qwen3-14B,tacq,3-bit,Chinese,NaN,NaN,NaN,NaN,NaN

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
15,Qwen/Qwen3-8B,tacq,Sinq,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
13,Qwen/Qwen3-8B,tacq,English,3-bit,0.151631,0.039473,0.103480,2.745665,0.322409
17,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.787157,0.004207,0.143836,1.245594,0.341394
14,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.473008,0.012477,0.037528,5.156465,0.841770
16,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.002507,0.024800,0.039048,0.484618,0.440133
12,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.376958,0.038915,0.161324,2.276247,0.174826
3,CohereLabs/aya-expanse-8b,tacq,Sinq,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
1,CohereLabs/aya-expanse-8b,tacq,English,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
5,CohereLabs/aya-expanse-8b,tacq,Tamil,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
2,CohereLabs/aya-expanse-8b,tacq,Indonesian,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
4,CohereLabs/aya-expanse-8b,tacq,Swahili,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
0,CohereLabs/aya-expanse-8b,tacq,Chinese,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
21,meta-llama/Llama-3.1-8B-Instruct,tacq,Sinq,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
19,meta-llama/Llama-3.1-8B-Instruct,tacq,English,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
23,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
20,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
22,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
18,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
9,Qwen/Qwen3-14B,tacq,Sinq,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
7,Qwen/Qwen3-14B,tacq,English,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
11,Qwen/Qwen3-14B,tacq,Tamil,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
8,Qwen/Qwen3-14B,tacq,Indonesian,3-bit,0.000000,0.000000,0.000000,0.000000,0.000000
10,Qwen/Qwen3-14B,tacq,Swahili,3-bit,NaN,NaN,NaN,NaN,NaN
6,Qwen/Qwen3-14B,tacq,Chinese,3-bit,NaN,NaN,NaN,NaN,NaN

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Qwen3, TA_Qwen3, ID_Qwen3, SW_Qwen3, ZH_Qwen3]

start model: CohereLabs/aya-expanse-8b

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Aya, TA_Aya, ID_Aya, SW_Aya, ZH_Aya]

start model: meta-llama/Llama-3.1-8B-Instruct

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Llama, TA_Llama, ID_Llama, SW_Llama, ZH_Llama]

,UQ,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,50.598038,57.113641,48.481814,52.050964,56.756861,41.277322
SW_Llama,30.056285,54.643300,56.283017,46.878139,43.463953,34.765476,50.868524
ID_Llama,24.823783,36.127868,39.772587,35.062178,28.618159,34.721147,35.462255
TA_Llama,2.311781,3.214247,4.269030,2.430107,3.463090,3.554056,3.123373
EN_Llama,45.105214,50.553287,48.270659,50.732388,50.051469,51.241933,50.027819
ZH_Aya,112.084228,134.500910,132.582898,135.092829,132.251605,139.732992,119.321911
SW_Aya,347.245294,598.420257,488.415269,494.785107,505.833186,351.026762,561.057641
ID_Aya,92.363250,108.035480,104.218850,107.600928,96.903556,105.485363,106.001720
TA_Aya,3.798334,4.628170,4.598233,3.914037,4.432267,4.394636,4.441016
EN_Aya,53.754913,60.296624,56.603639,59.778306,57.988980,59.710328,58.374838
ZH_Qwen3,46.980806,75.035734,53.220909,54.118815,53.634716,53.881667,48.014369
SW_Qwen3,64.534645,170.134416,118.216036,104.766815,103.911624,65.999048,115.434023
ID_Qwen3,16.699008,27.044173,21.206783,19.529220,17.453221,19.180347,21.117769
TA_Qwen3,2.741605,3.835802,3.795672,2.791451,3.444308,3.318586,3.607402
EN_Qwen3,33.428698,53.160308,34.863418,37.812257,36.722366,37.237706,36.611705

          UQ  TaCQ-SINQ   TaCQ-EN   TaCQ-TA   TaCQ-ID   TaCQ-SW   TaCQ-ZH
ZH_Llama NaN        0.0  0.000000  0.000000  0.000000  0.000000  0.000000
SW_Llama NaN        0.0  0.000000  0.000000  0.000000  0.000000  0.000000
ID_Llama NaN        0.0  0.000000  0.000000  0.000000  0.000000  0.000000
TA_Llama NaN        0.0  0.000000  0.000000  0.000000  0.000000  0.000000
EN_Llama NaN        0.0  0.000000  0.000000  0.000000  0.000000  0.000000
ZH_Aya   NaN        0.0  0.000000  0.000000  0.000000  0.000000  0.000000
SW_Aya   NaN        0.0  0.000000  0.000000  0.000000  0.000000  0.000000
ID_Aya   NaN        0.0  0.000000  0.000000  0.000000  0.000000  0.000000
TA_Aya   NaN        0.0  0.000000  0.000000  0.000000  0.000000  0.000000
EN_Aya   NaN        0.0  0.000000  0.000000  0.000000  0.000000  0.000000
ZH_Qwen3 NaN        0.0  0.322409  0.341394  0.841770  0.440133  0.174826
SW_Qwen3 NaN        0.0  2.745665  1.245594  5.156465  0.484618  2.276247
ID_Qwen3 NaN        0.0  0.103480  0.143836  0.037528  0.039048  0.161324
TA_Qwen3 NaN        0.0  0.039473  0.004207  0.012477  0.024800  0.038915
EN_Qwen3 NaN        0.0  0.151631  0.787157  0.473008  0.002507  0.376958

## Shape
df text: (15, 7)
df std: (15, 7)
Display df

,UQ,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,50.598038,57.113641,48.481814,52.050964,56.756861,41.277322
SW_Llama,30.056285,54.643300,56.283017,46.878139,43.463953,34.765476,50.868524
ID_Llama,24.823783,36.127868,39.772587,35.062178,28.618159,34.721147,35.462255
TA_Llama,2.311781,3.214247,4.269030,2.430107,3.463090,3.554056,3.123373
EN_Llama,45.105214,50.553287,48.270659,50.732388,50.051469,51.241933,50.027819
ZH_Aya,112.084228,134.500910,132.582898,135.092829,132.251605,139.732992,119.321911
SW_Aya,347.245294,598.420257,488.415269,494.785107,505.833186,351.026762,561.057641
ID_Aya,92.363250,108.035480,104.218850,107.600928,96.903556,105.485363,106.001720
TA_Aya,3.798334,4.628170,4.598233,3.914037,4.432267,4.394636,4.441016
EN_Aya,53.754913,60.296624,56.603639,59.778306,57.988980,59.710328,58.374838
ZH_Qwen3,46.980806,75.035734,53.220909,54.118815,53.634716,53.881667,48.014369
SW_Qwen3,64.534645,170.134416,118.216036,104.766815,103.911624,65.999048,115.434023
ID_Qwen3,16.699008,27.044173,21.206783,19.529220,17.453221,19.180347,21.117769
TA_Qwen3,2.741605,3.835802,3.795672,2.791451,3.444308,3.318586,3.607402
EN_Qwen3,33.428698,53.160308,34.863418,37.812257,36.722366,37.237706,36.611705

Display df std

         UQ TaCQ-SINQ TaCQ-EN TaCQ-TA TaCQ-ID TaCQ-SW TaCQ-ZH
ZH_Llama
SW_Llama
ID_Llama
TA_Llama
EN_Llama
ZH_Aya
SW_Aya
ID_Aya
TA_Aya
EN_Aya
ZH_Qwen3                 0.32    0.34    0.84    0.44    0.17
SW_Qwen3                 2.75    1.25    5.16    0.48    2.28
ID_Qwen3                 0.10    0.14    0.04    0.04    0.16
TA_Qwen3                 0.04    0.00    0.01    0.02    0.04
EN_Qwen3                 0.15    0.79    0.47    0.00    0.38

Writing to pdf ...

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [2]:
  for quantization_technique in ["gptq", "slimllm", "tacq"]:
    runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                    filters={"$or": [
                            { "$and": [
                              {"config.quantization_technique": quantization_technique.lower()},
                              {"config.bit_width": f"{bit_width}-bit"},
                              {"config.num_calibration_samples": 128},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"$or": [
                                {"config.evaluation_dataset": f"floresplus-evaluate"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                              ]},
                              # {"config.base_model": base_model},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                              {"created_at": {"$gt": '2026-01-15'}},
                              # {"created_at": {"$lt": '2026-07-01'}},
                              # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                              # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              # {"$not": {"$and": [{"config.quantization_technique": "gptq"}, {"config.calibration_language": "Swahili"}]}}
                            ]
                            },
                            { "$and": [
                              {"config.quantization_technique": "sinq"},
                              {"config.bit_width": f"{bit_width}-bit"},
                              # {"config.num_calibration_samples": 128},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"$or": [
                                {"config.evaluation_dataset": f"floresplus-evaluate"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                                {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                              ]},
                              # {"config.base_model": base_model},
                              # {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                              # {"created_at": {"$gt": '2026-01-15'}},
                              {"created_at": {"$gt": '2026-07-01'}},
                              # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                              # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"$not": {"$and": [{"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}, {"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}]}}
                            ]
                            },
                            { "$and" : [
                                {"config.quantization_technique": "Unquantized"},
                                # {"config.evaluation_dataset": evaluation_dataset},
                                {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                                # {"config.base_model": base_model},
                              # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                              # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                                {"config.enable_thinking": False},
                                {"config.output_type": "perplexity"},
                              {"created_at": {"$gt": '2026-01-15'}},
                              {"created_at": {"$lt": '2026-07-01'}},
                            ]}
                        ]}
                    )

    eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
    # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
    # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
    # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
    # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
    # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

    # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
    perplexity_heatmap_deliver_vertical_sinq(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=True, two_color=False, display_colorbar=False, embed_sinq=True, write_pdf=f"ablation_floresplus_{bit_width}bit_{quantization_technique}_all_vert_final.pdf")

/tmp/ipykernel_3071/1242997687.py:187: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,1.669901e+01,6.453465e+01,4.698081e+01
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,9.236325e+01,3.472453e+02,1.120842e+02
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,2.482378e+01,3.005629e+01,3.682178e+01
41,Qwen/Qwen3-8B,gptq,2-bit,Sinq,778028.489669,221688.724629,4.557271e+06,4.380327e+06,2.175599e+06
0,Qwen/Qwen3-8B,gptq,2-bit,English,13062.876244,48256.105485,3.985446e+04,3.823152e+04,3.428624e+04
...,...,...,...,...,...,...,...,...,...
37,Qwen/Qwen3-14B,gptq,2-bit,Indonesian,NaN,NaN,NaN,NaN,NaN
38,Qwen/Qwen3-14B,gptq,2-bit,Indonesian,NaN,NaN,NaN,NaN,NaN
46,Qwen/Qwen3-14B,gptq,2-bit,Indonesian,9109.144965,509.449465,1.054588e+02,5.962964e+03,5.987610e+04
58,Qwen/Qwen3-14B,gptq,2-bit,Swahili,NaN,NaN,NaN,NaN,NaN
59,Qwen/Qwen3-14B,gptq,2-bit,Chinese,NaN,NaN,NaN,NaN,NaN

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
15,Qwen/Qwen3-8B,gptq,Sinq,2-bit,5.890996,5.345744,6.658705,6.641507,6.337579
13,Qwen/Qwen3-8B,gptq,English,2-bit,4.108156,4.662199,4.593693,4.606363,4.596503
17,Qwen/Qwen3-8B,gptq,Tamil,2-bit,4.642051,0.873260,4.664672,4.670482,4.531575
14,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,4.544935,4.508749,3.226292,4.541529,4.624799
16,Qwen/Qwen3-8B,gptq,Swahili,2-bit,4.643958,4.572244,4.622783,3.166420,4.405375
12,Qwen/Qwen3-8B,gptq,Chinese,2-bit,4.489204,4.365599,4.580982,4.616916,4.249957

          GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Qwen3   5.890996  4.108156  4.642051  4.544935  4.643958  4.489204
TA_Qwen3   5.345744  4.662199  0.873260  4.508749  4.572244  4.365599
ID_Qwen3   6.658705  4.593693  4.664672  3.226292  4.622783  4.580982
SW_Qwen3   6.641507  4.606363  4.670482  4.541529  3.166420  4.616916
ZH_Qwen3   6.337579  4.596503  4.531575  4.624799  4.405375  4.249957

start model: CohereLabs/aya-expanse-8b

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
3,CohereLabs/aya-expanse-8b,gptq,Sinq,2-bit,2.557166,1.932225,3.287222,4.060748,3.452489
1,CohereLabs/aya-expanse-8b,gptq,English,2-bit,2.383521,4.348801,3.784685,4.346861,4.282580
5,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,2.872552,0.808635,3.811151,4.341208,3.967499
2,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,2.718155,3.623270,2.737043,4.152934,3.997845
4,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,2.916441,3.176520,3.635588,3.201836,4.169309
0,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,3.002846,3.626023,3.789999,4.319220,3.012777

        GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Aya   2.557166  2.383521  2.872552  2.718155  2.916441  3.002846
TA_Aya   1.932225  4.348801  0.808635  3.623270  3.176520  3.626023
ID_Aya   3.287222  3.784685  3.811151  2.737043  3.635588  3.789999
SW_Aya   4.060748  4.346861  4.341208  4.152934  3.201836  4.319220
ZH_Aya   3.452489  4.282580  3.967499  3.997845  4.169309  3.012777

start model: meta-llama/Llama-3.1-8B-Instruct

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
21,meta-llama/Llama-3.1-8B-Instruct,gptq,Sinq,2-bit,3.917076,4.673199,4.890831,4.949360,4.508026
19,meta-llama/Llama-3.1-8B-Instruct,gptq,English,2-bit,3.108296,5.665178,4.615812,4.586806,4.723760
23,meta-llama/Llama-3.1-8B-Instruct,gptq,Tamil,2-bit,3.938442,1.040648,4.654784,4.735744,4.492468
20,meta-llama/Llama-3.1-8B-Instruct,gptq,Indonesian,2-bit,3.826881,5.110111,3.389199,4.331666,4.670681
22,meta-llama/Llama-3.1-8B-Instruct,gptq,Swahili,2-bit,3.932406,5.604406,4.393071,3.413207,4.765714
18,meta-llama/Llama-3.1-8B-Instruct,gptq,Chinese,2-bit,3.890824,4.770100,4.699477,4.694667,3.503999

          GPTQ-SINQ   GPTQ-EN   GPTQ-TA   GPTQ-ID   GPTQ-SW   GPTQ-ZH
EN_Llama   3.917076  3.108296  3.938442  3.826881  3.932406  3.890824
TA_Llama   4.673199  5.665178  1.040648  5.110111  5.604406  4.770100
ID_Llama   4.890831  4.615812  4.654784  3.389199  4.393071  4.699477
SW_Llama   4.949360  4.586806  4.735744  4.331666  3.413207  4.694667
ZH_Llama   4.508026  4.723760  4.492468  4.670681  4.765714  3.503999

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH
ZH_Llama,36.821779,3.221260e+04,52937.025188,31079.064005,46846.875085,58306.035056,3191.528221
SW_Llama,30.056285,8.899394e+04,38619.420435,54418.192756,21461.796460,2589.449002,49507.095252
ID_Llama,24.823783,7.777345e+04,41286.884848,45163.124564,2450.187930,24721.264360,50058.363746
TA_Llama,2.311781,4.711932e+04,462570.732187,10.981143,128857.950967,402166.581074,58897.957168
EN_Llama,45.105214,8.261823e+03,1283.204545,8678.450527,6712.454060,8558.666771,7777.211806
ZH_Aya,112.084228,2.834583e+03,19168.145370,9278.960985,9950.510277,14767.553330,1029.857317
SW_Aya,347.245294,1.150134e+04,22225.967596,21938.558958,14221.136656,1591.607966,20855.464249
ID_Aya,92.363250,1.937413e+03,6090.955316,6473.671674,545.811702,4321.037729,6165.939366
TA_Aya,3.798334,8.555107e+01,22325.499442,6.436282,4200.197925,1501.481445,4226.914393
EN_Aya,53.754913,3.607169e+02,241.836277,745.679240,522.582423,824.976137,1006.574886
ZH_Qwen3,46.980806,2.175599e+06,39491.465990,34007.536689,42150.094142,25431.655621,17781.024879
SW_Qwen3,64.534645,4.380327e+06,40398.302421,46825.504463,34796.007236,1466.964319,41391.915611
ID_Qwen3,16.699008,4.557271e+06,39236.778388,46203.199536,1683.806307,41954.948059,38104.965297
TA_Qwen3,2.741605,2.216887e+05,45940.807067,7.468949,32266.297200,37346.013068,23205.924496
EN_Qwen3,33.428698,7.780285e+05,12827.901762,43858.254034,35069.944932,44051.236215,30846.394995

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH
ZH_Llama,NaN,0.0,13902.306426,642.794567,10300.464859,11728.335010,56.509159
SW_Llama,NaN,0.0,4372.904715,8115.903560,1995.477406,1476.872030,6630.425511
ID_Llama,NaN,0.0,9347.511733,6317.020512,317.796183,2408.903746,14456.353815
TA_Llama,NaN,0.0,0.000000,1.455488,0.000000,0.000000,1543.022412
EN_Llama,NaN,0.0,17.189524,201.289120,589.302232,1919.202975,97.149477
ZH_Aya,NaN,0.0,1543.522189,1302.353438,866.080047,1180.853398,18.945158
SW_Aya,NaN,0.0,1277.195624,2050.239999,1152.198626,33.017260,2340.085532
ID_Aya,NaN,0.0,785.551907,453.403569,36.465574,597.968991,748.488685
TA_Aya,NaN,0.0,6727.004278,0.242481,1013.398744,576.594778,1135.284190
EN_Aya,NaN,0.0,6.347335,60.775949,25.456456,80.773855,75.660850
ZH_Qwen3,NaN,0.0,4322.025321,12652.174248,1814.625584,214.562658,1521.218809
SW_Qwen3,NaN,0.0,1545.126299,41.811051,3225.378802,119.318857,6205.821677
ID_Qwen3,NaN,0.0,607.573270,5893.246746,463.524607,2132.436617,4590.185765
TA_Qwen3,NaN,0.0,3672.782474,0.417630,3505.411760,1535.747660,1813.483650
EN_Qwen3,NaN,0.0,269.191572,3137.501577,1463.765358,1602.262531,492.546412

## Shape
df text: (15, 7)
df std: (15, 7)
Display df

,UQ,GPTQ-SINQ,GPTQ-EN,GPTQ-TA,GPTQ-ID,GPTQ-SW,GPTQ-ZH
ZH_Llama,36.821779,3.221260e+04,52937.025188,31079.064005,46846.875085,58306.035056,3191.528221
SW_Llama,30.056285,8.899394e+04,38619.420435,54418.192756,21461.796460,2589.449002,49507.095252
ID_Llama,24.823783,7.777345e+04,41286.884848,45163.124564,2450.187930,24721.264360,50058.363746
TA_Llama,2.311781,4.711932e+04,462570.732187,10.981143,128857.950967,402166.581074,58897.957168
EN_Llama,45.105214,8.261823e+03,1283.204545,8678.450527,6712.454060,8558.666771,7777.211806
ZH_Aya,112.084228,2.834583e+03,19168.145370,9278.960985,9950.510277,14767.553330,1029.857317
SW_Aya,347.245294,1.150134e+04,22225.967596,21938.558958,14221.136656,1591.607966,20855.464249
ID_Aya,92.363250,1.937413e+03,6090.955316,6473.671674,545.811702,4321.037729,6165.939366
TA_Aya,3.798334,8.555107e+01,22325.499442,6.436282,4200.197925,1501.481445,4226.914393
EN_Aya,53.754913,3.607169e+02,241.836277,745.679240,522.582423,824.976137,1006.574886
ZH_Qwen3,46.980806,2.175599e+06,39491.465990,34007.536689,42150.094142,25431.655621,17781.024879
SW_Qwen3,64.534645,4.380327e+06,40398.302421,46825.504463,34796.007236,1466.964319,41391.915611
ID_Qwen3,16.699008,4.557271e+06,39236.778388,46203.199536,1683.806307,41954.948059,38104.965297
TA_Qwen3,2.741605,2.216887e+05,45940.807067,7.468949,32266.297200,37346.013068,23205.924496
EN_Qwen3,33.428698,7.780285e+05,12827.901762,43858.254034,35069.944932,44051.236215,30846.394995

Display df std

         UQ GPTQ-SINQ GPTQ-EN GPTQ-TA GPTQ-ID GPTQ-SW GPTQ-ZH
ZH_Llama               1.4e+4   642.8  1.0e+4  1.2e+4   56.51
SW_Llama               4.4e+3  8.1e+3  2.0e+3  1.5e+3  6.6e+3
ID_Llama               9.3e+3  6.3e+3   317.8  2.4e+3  1.4e+4
TA_Llama                         1.46                  1.5e+3
EN_Llama                17.19   201.3   589.3  1.9e+3   97.15
ZH_Aya                 1.5e+3  1.3e+3   866.1  1.2e+3   18.95
SW_Aya                 1.3e+3  2.1e+3  1.2e+3   33.02  2.3e+3
ID_Aya                  785.6   453.4   36.47   598.0   748.5
TA_Aya                 6.7e+3    0.24  1.0e+3   576.6  1.1e+3
EN_Aya                   6.35   60.78   25.46   80.77   75.66
ZH_Qwen3               4.3e+3  1.3e+4  1.8e+3   214.6  1.5e+3
SW_Qwen3               1.5e+3   41.81  3.2e+3   119.3  6.2e+3
ID_Qwen3                607.6  5.9e+3   463.5  2.1e+3  4.6e+3
TA_Qwen3               3.7e+3    0.42  3.5e+3  1.5e+3  1.8e+3
EN_Qwen3                269.2  3.1e+3  1.5e+3  1.6e+3   492.5

Writing to pdf ...

/tmp/ipykernel_3071/1242997687.py:187: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605e+00,1.669901e+01,6.453465e+01,4.698081e+01
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334e+00,9.236325e+01,3.472453e+02,1.120842e+02
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781e+00,2.482378e+01,3.005629e+01,3.682178e+01
32,Qwen/Qwen3-8B,slimllm,2-bit,Sinq,778028.489669,2.216887e+05,4.557271e+06,4.380327e+06,2.175599e+06
0,Qwen/Qwen3-8B,slimllm,2-bit,English,136.421333,7.868718e+03,2.487644e+03,7.155156e+03,1.018849e+06
14,Qwen/Qwen3-8B,slimllm,2-bit,English,145.947709,8.446240e+03,1.964874e+03,5.453784e+03,3.923998e+05
15,Qwen/Qwen3-8B,slimllm,2-bit,English,172.354644,2.798914e+04,3.029195e+03,7.569894e+03,5.910075e+05
2,Qwen/Qwen3-8B,slimllm,2-bit,Tamil,9540.976268,4.296940e+00,8.528091e+03,6.611651e+03,9.224233e+04
18,Qwen/Qwen3-8B,slimllm,2-bit,Tamil,7745.881492,4.538700e+00,1.211339e+04,4.837904e+03,4.929471e+04
19,Qwen/Qwen3-8B,slimllm,2-bit,Tamil,3384.443502,4.493130e+00,1.375234e+04,8.127881e+03,3.896194e+04
1,Qwen/Qwen3-8B,slimllm,2-bit,Indonesian,1875.621188,2.773605e+04,2.137865e+02,4.277163e+03,6.036315e+05
16,Qwen/Qwen3-8B,slimllm,2-bit,Indonesian,577.247574,4.120298e+03,7.373207e+01,1.271837e+03,3.051602e+05
17,Qwen/Qwen3-8B,slimllm,2-bit,Indonesian,779.038622,4.165074e+03,8.222594e+01,2.591755e+03,3.253010e+05
3,Qwen/Qwen3-8B,slimllm,2-bit,Swahili,1295.647887,1.297831e+03,7.347905e+02,7.558348e+02,2.030617e+05
20,Qwen/Qwen3-8B,slimllm,2-bit,Swahili,1573.397731,1.121417e+04,7.569472e+02,4.384887e+02,2.583997e+05
21,Qwen/Qwen3-8B,slimllm,2-bit,Swahili,3141.810162,5.906339e+03,6.121376e+02,4.250960e+02,1.422033e+06
4,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,4070.391396,6.230998e+03,1.790185e+04,1.444119e+04,2.967870e+02
22,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,4209.958053,2.517425e+04,1.282359e+04,2.776891e+04,3.965303e+02
23,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,8946.461382,4.546049e+04,2.545741e+04,1.548959e+04,3.867438e+02
33,CohereLabs/aya-expanse-8b,slimllm,2-bit,Sinq,360.716854,8.555107e+01,1.937413e+03,1.150134e+04,2.834583e+03
5,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,126.665861,7.374725e+05,6.537847e+04,8.350373e+03,6.745728e+06
24,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,135.653633,4.487779e+05,2.624184e+04,8.612169e+03,6.386107e+06
25,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,147.769707,4.681287e+04,5.137779e+04,1.297245e+04,9.097430e+06
6,CohereLabs/aya-expanse-8b,slimllm,2-bit,Indonesian,242.230468,5.656487e+05,2.222441e+02,5.041660e+03,2.213893e+06
26,CohereLabs/aya-expanse-8b,slimllm,2-bit,Indonesian,266.582063,7.728964e+05,2.477532e+02,7.144640e+03,1.417499e+06
27,CohereLabs/aya-expanse-8b,slimllm,2-bit,Indonesian,297.591744,8.487007e+03,2.284797e+02,4.497699e+03,1.262017e+06
7,CohereLabs/aya-expanse-8b,slimllm,2-bit,Swahili,405.966345,1.778943e+06,1.264552e+03,4.404831e+02,1.380743e+06
28,CohereLabs/aya-expanse-8b,slimllm,2-bit,Swahili,428.449300,3.989524e+04,1.395717e+03,4.501252e+02,1.540993e+06
29,CohereLabs/aya-expanse-8b,slimllm,2-bit,Swahili,169.251393,2.567245e+03,4.731980e+02,3.661436e+02,9.287707e+04
8,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,9591.055847,6.648169e+05,5.477908e+05,8.804196e+04,2.636727e+02
30,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,2608.649296,4.793396e+04,4.369455e+05,3.431491e+04,2.648757e+02
31,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,1666.300382,1.576516e+05,4.694203e+05,3.011086e+04,2.937042e+02
34,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Sinq,8261.823109,4.711932e+04,7.777345e+04,8.899394e+04,3.221260e+04
9,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,English,1310.330378,1.325875e+07,9.034067e+04,4.843673e+04,1.182826e+07
36,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,English,615.370093,3.394638e+06,2.351240e+04,1.983606e+04,1.177646e+06
37,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,English,NaN,NaN,NaN,NaN,NaN
11,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Tamil,6547.364589,5.138218e+00,2.865796e+04,1.456242e+04,6.745050e+04
40,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Tamil,3136.642963,5.085275e+00,1.006170e+04,8.244832e+03,1.465876e+05
41,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Tamil,NaN,NaN,NaN,NaN,NaN
10,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Indonesian,24646.872946,2.981072e+06,8.363805e+04,3.387789e+04,1.889792e+06
38,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Indonesian,4341.826392,2.792811e+06,4.565684e+03,5.490541e+03,1.768142e+06
39,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Indonesian,NaN,NaN,NaN,NaN,NaN
12,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Swahili,47030.845866,5.918960e+05,1.253635e+05,6.797139e+04,3.922542e+06
42,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Swahili,29134.634647,2.210990e+06,5.626522e+04,3.528423e+04,1.282295e+06
43,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Swahili,NaN,NaN,NaN,NaN,NaN
13,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,6997.865099,2.128250e+05,5.466947e+04,2.033392e+04,2.407567e+03
44,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,20483.408636,5.287968e+04,7.223233e+04,4.967628e+04,5.169664e+03
45,meta-llama/Llama-3.1-8B-Instruct,slimllm,2-bit,Chinese,NaN,NaN,NaN,NaN,NaN
35,Qwen/Qwen3-14B,slimllm,2-bit,Sinq,93245.028692,3.703413e+03,2.171616e+04,1.897464e+05,1.344018e+05

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Qwen3, TA_Qwen3, ID_Qwen3, SW_Qwen3, ZH_Qwen3]

start model: CohereLabs/aya-expanse-8b

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Aya, TA_Aya, ID_Aya, SW_Aya, ZH_Aya]

start model: meta-llama/Llama-3.1-8B-Instruct

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Llama, TA_Llama, ID_Llama, SW_Llama, ZH_Llama]

,UQ,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,36.821779,3.221260e+04,6.502951e+06,107019.043708,1.828967e+06,2.602418e+06,3788.615196
SW_Llama,30.056285,8.899394e+04,3.413639e+04,11403.624830,1.968422e+04,5.162781e+04,35005.098924
ID_Llama,24.823783,7.777345e+04,5.692653e+04,19359.826880,4.410187e+04,9.081436e+04,63450.902216
TA_Llama,2.311781,4.711932e+04,8.326694e+06,5.111747,2.886942e+06,1.401443e+06,132852.344038
EN_Llama,45.105214,8.261823e+03,9.628502e+02,4842.003776,1.449435e+04,3.808274e+04,13740.636867
ZH_Aya,112.084228,2.834583e+03,7.409755e+06,NaN,1.631137e+06,1.004871e+06,274.084188
SW_Aya,347.245294,1.150134e+04,9.978332e+03,NaN,5.561333e+03,4.189173e+02,50822.574116
ID_Aya,92.363250,1.937413e+03,4.766603e+04,NaN,2.328256e+02,1.044489e+03,484718.872812
TA_Aya,3.798334,8.555107e+01,4.110211e+05,NaN,4.490107e+05,6.071352e+05,290134.141033
EN_Aya,53.754913,3.607169e+02,1.366964e+02,NaN,2.688014e+02,3.345557e+02,4622.001841
ZH_Qwen3,46.980806,2.175599e+06,6.674189e+05,60166.327417,4.113642e+05,6.278313e+05,360.020385
SW_Qwen3,64.534645,4.380327e+06,6.726278e+03,6525.812005,2.713585e+03,5.398065e+02,19233.229068
ID_Qwen3,16.699008,4.557271e+06,2.493904e+03,11464.605865,1.232482e+02,7.012918e+02,18727.617100
TA_Qwen3,2.741605,2.216887e+05,1.476803e+04,4.442923,1.200714e+04,6.139446e+03,25621.911270
EN_Qwen3,33.428698,7.780285e+05,1.515746e+02,6890.433754,1.077302e+03,2.003619e+03,5742.270277

,UQ,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,NaN,0.0,5.325304e+06,39568.541587,60825.148554,1.320123e+06,1381.048524
SW_Llama,NaN,0.0,1.430034e+04,3158.793270,14193.675815,1.634358e+04,14671.177536
ID_Llama,NaN,0.0,3.341413e+04,9298.130925,39536.183254,3.454913e+04,8781.431135
TA_Llama,NaN,0.0,4.932056e+06,0.026471,94130.400032,8.095470e+05,79972.668145
EN_Llama,NaN,0.0,3.474801e+02,1705.360813,10152.523277,8.948106e+03,6742.771768
ZH_Aya,NaN,0.0,1.202363e+06,NaN,416931.507561,6.481870e+05,13.882118
SW_Aya,NaN,0.0,2.119860e+03,NaN,1141.379148,3.752367e+01,26373.980905
ID_Aya,NaN,0.0,1.619160e+04,NaN,10.858010,4.074973e+02,46527.414954
TA_Aya,NaN,0.0,2.832218e+05,NaN,322783.452104,8.287334e+05,268700.417046
EN_Aya,NaN,0.0,8.647104e+00,NaN,22.655564,1.172476e+02,3534.650256
ZH_Qwen3,NaN,0.0,2.613922e+05,23070.095350,136201.928434,5.620394e+05,44.890879
SW_Qwen3,NaN,0.0,9.155808e+02,1344.498076,1229.939922,1.528529e+02,6050.793892
ID_Qwen3,NaN,0.0,4.345302e+02,2181.571725,64.114112,6.368716e+01,5190.682069
TA_Qwen3,NaN,0.0,9.351708e+03,0.104889,11122.033868,4.051682e+03,16018.499530
EN_Qwen3,NaN,0.0,1.519971e+01,2585.158544,570.476116,8.127715e+02,2266.421583

## Shape
df text: (15, 7)
df std: (15, 7)
Display df

,UQ,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,36.821779,3.221260e+04,6.502951e+06,107019.043708,1.828967e+06,2.602418e+06,3788.615196
SW_Llama,30.056285,8.899394e+04,3.413639e+04,11403.624830,1.968422e+04,5.162781e+04,35005.098924
ID_Llama,24.823783,7.777345e+04,5.692653e+04,19359.826880,4.410187e+04,9.081436e+04,63450.902216
TA_Llama,2.311781,4.711932e+04,8.326694e+06,5.111747,2.886942e+06,1.401443e+06,132852.344038
EN_Llama,45.105214,8.261823e+03,9.628502e+02,4842.003776,1.449435e+04,3.808274e+04,13740.636867
ZH_Aya,112.084228,2.834583e+03,7.409755e+06,NaN,1.631137e+06,1.004871e+06,274.084188
SW_Aya,347.245294,1.150134e+04,9.978332e+03,NaN,5.561333e+03,4.189173e+02,50822.574116
ID_Aya,92.363250,1.937413e+03,4.766603e+04,NaN,2.328256e+02,1.044489e+03,484718.872812
TA_Aya,3.798334,8.555107e+01,4.110211e+05,NaN,4.490107e+05,6.071352e+05,290134.141033
EN_Aya,53.754913,3.607169e+02,1.366964e+02,NaN,2.688014e+02,3.345557e+02,4622.001841
ZH_Qwen3,46.980806,2.175599e+06,6.674189e+05,60166.327417,4.113642e+05,6.278313e+05,360.020385
SW_Qwen3,64.534645,4.380327e+06,6.726278e+03,6525.812005,2.713585e+03,5.398065e+02,19233.229068
ID_Qwen3,16.699008,4.557271e+06,2.493904e+03,11464.605865,1.232482e+02,7.012918e+02,18727.617100
TA_Qwen3,2.741605,2.216887e+05,1.476803e+04,4.442923,1.200714e+04,6.139446e+03,25621.911270
EN_Qwen3,33.428698,7.780285e+05,1.515746e+02,6890.433754,1.077302e+03,2.003619e+03,5742.270277

Display df std

,UQ,SliM-LLM-SINQ,SliM-LLM-EN,SliM-LLM-TA,SliM-LLM-ID,SliM-LLM-SW,SliM-LLM-ZH
ZH_Llama,,,5.3e+6,4.0e+4,6.1e+4,1.3e+6,1.4e+3
SW_Llama,,,1.4e+4,3.2e+3,1.4e+4,1.6e+4,1.5e+4
ID_Llama,,,3.3e+4,9.3e+3,4.0e+4,3.5e+4,8.8e+3
TA_Llama,,,4.9e+6,0.03,9.4e+4,8.1e+5,8.0e+4
EN_Llama,,,347.5,1.7e+3,1.0e+4,8.9e+3,6.7e+3
ZH_Aya,,,1.2e+6,,4.2e+5,6.5e+5,13.88
SW_Aya,,,2.1e+3,,1.1e+3,37.52,2.6e+4
ID_Aya,,,1.6e+4,,10.86,407.5,4.7e+4
TA_Aya,,,2.8e+5,,3.2e+5,8.3e+5,2.7e+5
EN_Aya,,,8.65,,22.66,117.2,3.5e+3
ZH_Qwen3,,,2.6e+5,2.3e+4,1.4e+5,5.6e+5,44.89
SW_Qwen3,,,915.6,1.3e+3,1.2e+3,152.9,6.1e+3
ID_Qwen3,,,434.5,2.2e+3,64.11,63.69,5.2e+3
TA_Qwen3,,,9.4e+3,0.10,1.1e+4,4.1e+3,1.6e+4
EN_Qwen3,,,15.20,2.6e+3,570.5,812.8,2.3e+3

Writing to pdf ...

/tmp/ipykernel_3071/1242997687.py:187: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.428698,2.741605,1.669901e+01,6.453465e+01,4.698081e+01
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.754913,3.798334,9.236325e+01,3.472453e+02,1.120842e+02
2,meta-llama/Llama-3.1-8B-Instruct,Unquantized,32-bit,Unquantized,45.105214,2.311781,2.482378e+01,3.005629e+01,3.682178e+01
35,Qwen/Qwen3-8B,tacq,2-bit,Sinq,778028.489669,221688.724629,4.557271e+06,4.380327e+06,2.175599e+06
0,Qwen/Qwen3-8B,tacq,2-bit,English,44.433395,14.577590,1.186465e+02,3.915546e+02,1.439631e+02
15,Qwen/Qwen3-8B,tacq,2-bit,English,43.686757,15.899181,1.112470e+02,3.660701e+02,1.447781e+02
16,Qwen/Qwen3-8B,tacq,2-bit,English,43.829801,16.064154,1.187622e+02,3.826032e+02,1.513719e+02
2,Qwen/Qwen3-8B,tacq,2-bit,Tamil,63.757700,3.077032,9.251565e+01,6.368126e+02,1.187636e+02
19,Qwen/Qwen3-8B,tacq,2-bit,Tamil,64.479079,3.051704,6.286082e+01,3.379549e+02,1.225778e+02
20,Qwen/Qwen3-8B,tacq,2-bit,Tamil,64.872761,3.061076,6.265565e+01,3.245193e+02,1.170454e+02
1,Qwen/Qwen3-8B,tacq,2-bit,Indonesian,51.815953,11.100248,2.158458e+01,2.333827e+02,1.206662e+02
17,Qwen/Qwen3-8B,tacq,2-bit,Indonesian,53.063046,9.231703,2.189615e+01,2.904446e+02,1.171419e+02
18,Qwen/Qwen3-8B,tacq,2-bit,Indonesian,52.785607,9.537242,2.197229e+01,2.514649e+02,1.285076e+02
3,Qwen/Qwen3-8B,tacq,2-bit,Swahili,65.675437,9.829573,4.439997e+01,6.873770e+01,1.899219e+02
21,Qwen/Qwen3-8B,tacq,2-bit,Swahili,64.947907,9.399164,4.386026e+01,6.765952e+01,1.657312e+02
22,Qwen/Qwen3-8B,tacq,2-bit,Swahili,66.052117,10.605509,4.293957e+01,7.131228e+01,1.733034e+02
4,Qwen/Qwen3-8B,tacq,2-bit,Chinese,60.223406,11.664861,1.351631e+02,3.515302e+02,6.253647e+01
23,Qwen/Qwen3-8B,tacq,2-bit,Chinese,58.012939,12.544227,1.244902e+02,3.827612e+02,6.254392e+01
24,Qwen/Qwen3-8B,tacq,2-bit,Chinese,59.327470,15.291020,1.217656e+02,3.839498e+02,6.413672e+01
36,CohereLabs/aya-expanse-8b,tacq,2-bit,Sinq,360.716854,85.551069,1.937413e+03,1.150134e+04,2.834583e+03
5,CohereLabs/aya-expanse-8b,tacq,2-bit,English,69.124340,15.326975,3.054537e+02,1.488832e+03,3.520343e+02
25,CohereLabs/aya-expanse-8b,tacq,2-bit,English,69.417247,16.126714,3.119452e+02,1.911111e+03,3.787899e+02
26,CohereLabs/aya-expanse-8b,tacq,2-bit,English,68.883655,12.764824,3.012168e+02,1.364533e+03,3.510869e+02
7,CohereLabs/aya-expanse-8b,tacq,2-bit,Tamil,91.792128,4.032991,2.135607e+02,1.533151e+03,2.683513e+02
29,CohereLabs/aya-expanse-8b,tacq,2-bit,Tamil,94.673259,4.052219,2.265857e+02,1.613769e+03,2.789097e+02
30,CohereLabs/aya-expanse-8b,tacq,2-bit,Tamil,93.151194,4.064053,2.358202e+02,1.487996e+03,2.795914e+02
6,CohereLabs/aya-expanse-8b,tacq,2-bit,Indonesian,81.004478,11.747359,1.136346e+02,1.343617e+03,2.990833e+02
27,CohereLabs/aya-expanse-8b,tacq,2-bit,Indonesian,80.412482,12.628553,1.190832e+02,1.543538e+03,2.710511e+02
28,CohereLabs/aya-expanse-8b,tacq,2-bit,Indonesian,81.568789,12.226416,1.186951e+02,1.146954e+03,3.081484e+02
8,CohereLabs/aya-expanse-8b,tacq,2-bit,Swahili,97.776450,10.504047,2.042601e+02,3.425064e+02,4.104569e+02
31,CohereLabs/aya-expanse-8b,tacq,2-bit,Swahili,98.850604,10.082932,2.037322e+02,3.330686e+02,4.072660e+02
32,CohereLabs/aya-expanse-8b,tacq,2-bit,Swahili,95.199483,10.107628,1.986441e+02,3.205528e+02,4.006727e+02
9,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,87.566569,11.085941,2.872073e+02,2.165596e+03,1.363076e+02
33,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,86.254922,12.776039,3.226908e+02,2.640985e+03,1.358476e+02
34,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,83.905569,13.401760,2.830780e+02,1.899482e+03,1.353589e+02
37,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Sinq,8261.823109,47119.318143,7.777345e+04,8.899394e+04,3.221260e+04
10,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,English,71.305146,98.906951,4.097376e+02,4.227793e+02,6.982557e+02
42,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,English,77.536753,41.378075,7.079876e+02,6.981443e+02,9.643302e+02
43,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,English,NaN,NaN,NaN,NaN,NaN
12,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Tamil,123.015885,2.790848,2.548721e+02,3.295927e+02,2.764184e+02
46,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Tamil,104.458301,2.741309,2.339709e+02,2.386227e+02,2.154873e+02
47,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Tamil,NaN,NaN,NaN,NaN,NaN
11,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Indonesian,94.744345,11.290383,4.868203e+01,2.083669e+02,3.817391e+02
44,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Indonesian,103.523975,17.777866,4.773105e+01,2.176696e+02,3.676125e+02
45,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Indonesian,NaN,NaN,NaN,NaN,NaN
13,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Swahili,108.396437,15.895496,1.359129e+02,4.317018e+01,1.156818e+03
48,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Swahili,116.635878,16.431029,1.661635e+02,4.513700e+01,5.888569e+02
49,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Swahili,NaN,NaN,NaN,NaN,NaN
14,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,110.839197,8.777216,4.816661e+02,4.691487e+02,6.879208e+01
50,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,102.677625,8.754102,3.417004e+02,4.068561e+02,6.299569e+01
51,meta-llama/Llama-3.1-8B-Instruct,tacq,2-bit,Chinese,NaN,NaN,NaN,NaN,NaN
41,Qwen/Qwen3-14B,tacq,2-bit,Sinq,93245.028692,3703.413056,2.171616e+04,1.897464e+05,1.344018e+05
38,Qwen/Qwen3-14B,tacq,2-bit,English,42.305540,17.766269,1.094552e+02,3.921057e+02,1.040427e+02
40,Qwen/Qwen3-14B,tacq,2-bit,Tamil,127.865788,2.734088,4.718777e+01,3.796860e+02,8.750628e+01
39,Qwen/Qwen3-14B,tacq,2-bit,Indonesian,55.124529,8.474698,1.805037e+01,2.543852e+02,8.970690e+01
52,Qwen/Qwen3-14B,tacq,2-bit,Swahili,NaN,NaN,NaN,NaN,NaN
53,Qwen/Qwen3-14B,tacq,2-bit,Chinese,NaN,NaN,NaN,NaN,NaN

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
15,Qwen/Qwen3-8B,tacq,Sinq,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
13,Qwen/Qwen3-8B,tacq,English,2-bit,0.323566,0.665306,3.515737,10.556345,3.317178
17,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.461728,0.010456,14.028029,144.154089,2.312004
14,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.534628,0.818386,0.167729,23.810479,4.750264
16,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.458314,0.499177,0.602931,1.532377,10.103402
12,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.907797,1.544423,5.781454,15.010444,0.752618
3,CohereLabs/aya-expanse-8b,tacq,Sinq,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
1,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.218186,1.433973,4.411970,233.931693,12.841869
5,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,1.176844,0.012800,9.131215,52.022620,5.145499
2,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.472105,0.360203,2.482059,161.906780,15.790946
4,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,1.532074,0.192958,2.532162,8.991836,4.074086
0,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,1.514478,0.978149,17.780479,306.709847,0.387395
21,meta-llama/Llama-3.1-8B-Instruct,tacq,Sinq,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
19,meta-llama/Llama-3.1-8B-Instruct,tacq,English,2-bit,3.115804,28.764438,149.125005,137.682512,133.037240
23,meta-llama/Llama-3.1-8B-Instruct,tacq,Tamil,2-bit,9.278792,0.024770,10.450561,45.485010,30.465575
20,meta-llama/Llama-3.1-8B-Instruct,tacq,Indonesian,2-bit,4.389815,3.243741,0.475489,4.651333,7.063266
22,meta-llama/Llama-3.1-8B-Instruct,tacq,Swahili,2-bit,4.119721,0.267766,15.125315,0.983412,283.980355
18,meta-llama/Llama-3.1-8B-Instruct,tacq,Chinese,2-bit,4.080786,0.011557,69.982867,31.146280,2.898195
9,Qwen/Qwen3-14B,tacq,Sinq,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
7,Qwen/Qwen3-14B,tacq,English,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
11,Qwen/Qwen3-14B,tacq,Tamil,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
8,Qwen/Qwen3-14B,tacq,Indonesian,2-bit,0.000000,0.000000,0.000000,0.000000,0.000000
10,Qwen/Qwen3-14B,tacq,Swahili,2-bit,NaN,NaN,NaN,NaN,NaN
6,Qwen/Qwen3-14B,tacq,Chinese,2-bit,NaN,NaN,NaN,NaN,NaN

Index(['Base Model', 'Quantization Technique', 'Calibration Language',
       'Bit Width', 'eng_Latn', 'tam_Taml', 'ind_Latn', 'swh_Latn',
       'cmn_Hans'],
      dtype='object')

start model: Qwen/Qwen3-8B

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Qwen3, TA_Qwen3, ID_Qwen3, SW_Qwen3, ZH_Qwen3]

start model: CohereLabs/aya-expanse-8b

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Aya, TA_Aya, ID_Aya, SW_Aya, ZH_Aya]

start model: meta-llama/Llama-3.1-8B-Instruct

Empty DataFrame
Columns: [Base Model, Quantization Technique, Calibration Language, Bit Width, eng_Latn, tam_Taml, ind_Latn, swh_Latn, cmn_Hans]
Index: []

Empty DataFrame
Columns: []
Index: [EN_Llama, TA_Llama, ID_Llama, SW_Llama, ZH_Llama]

,UQ,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,3.221260e+04,831.292973,245.952841,374.675809,872.837297,65.893885
SW_Llama,30.056285,8.899394e+04,560.461792,284.107680,213.018242,44.153591,438.002381
ID_Llama,24.823783,7.777345e+04,558.862629,244.421507,48.206539,151.038203,411.683272
TA_Llama,2.311781,4.711932e+04,70.142513,2.766078,14.534124,16.163262,8.765659
EN_Llama,45.105214,8.261823e+03,74.420949,113.737093,99.134160,112.516157,106.758411
ZH_Aya,112.084228,2.834583e+03,360.637008,275.617452,292.760948,406.131890,135.838040
SW_Aya,347.245294,1.150134e+04,1588.158444,1544.971890,1344.702942,332.042594,2235.354059
ID_Aya,92.363250,1.937413e+03,306.205275,225.322198,117.137641,202.212119,297.658705
TA_Aya,3.798334,8.555107e+01,14.739504,4.049754,12.200776,10.231536,12.421246
EN_Aya,53.754913,3.607169e+02,69.141747,93.205527,80.995250,97.275513,85.909020
ZH_Qwen3,46.980806,2.175599e+06,146.704354,119.462250,122.105214,176.318815,63.072371
SW_Qwen3,64.534645,4.380327e+06,380.075948,433.095598,258.430765,69.236501,372.747064
ID_Qwen3,16.699008,4.557271e+06,116.218561,72.677371,21.817674,43.733264,127.139610
TA_Qwen3,2.741605,2.216887e+05,15.513642,3.063271,9.956398,9.944748,13.166703
EN_Qwen3,33.428698,7.780285e+05,43.983318,64.369847,52.554869,65.558487,59.187938

,UQ,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,NaN,0.0,133.037240,30.465575,7.063266,283.980355,2.898195
SW_Llama,NaN,0.0,137.682512,45.485010,4.651333,0.983412,31.146280
ID_Llama,NaN,0.0,149.125005,10.450561,0.475489,15.125315,69.982867
TA_Llama,NaN,0.0,28.764438,0.024770,3.243741,0.267766,0.011557
EN_Llama,NaN,0.0,3.115804,9.278792,4.389815,4.119721,4.080786
ZH_Aya,NaN,0.0,12.841869,5.145499,15.790946,4.074086,0.387395
SW_Aya,NaN,0.0,233.931693,52.022620,161.906780,8.991836,306.709847
ID_Aya,NaN,0.0,4.411970,9.131215,2.482059,2.532162,17.780479
TA_Aya,NaN,0.0,1.433973,0.012800,0.360203,0.192958,0.978149
EN_Aya,NaN,0.0,0.218186,1.176844,0.472105,1.532074,1.514478
ZH_Qwen3,NaN,0.0,3.317178,2.312004,4.750264,10.103402,0.752618
SW_Qwen3,NaN,0.0,10.556345,144.154089,23.810479,1.532377,15.010444
ID_Qwen3,NaN,0.0,3.515737,14.028029,0.167729,0.602931,5.781454
TA_Qwen3,NaN,0.0,0.665306,0.010456,0.818386,0.499177,1.544423
EN_Qwen3,NaN,0.0,0.323566,0.461728,0.534628,0.458314,0.907797

## Shape
df text: (15, 7)
df std: (15, 7)
Display df

,UQ,TaCQ-SINQ,TaCQ-EN,TaCQ-TA,TaCQ-ID,TaCQ-SW,TaCQ-ZH
ZH_Llama,36.821779,3.221260e+04,831.292973,245.952841,374.675809,872.837297,65.893885
SW_Llama,30.056285,8.899394e+04,560.461792,284.107680,213.018242,44.153591,438.002381
ID_Llama,24.823783,7.777345e+04,558.862629,244.421507,48.206539,151.038203,411.683272
TA_Llama,2.311781,4.711932e+04,70.142513,2.766078,14.534124,16.163262,8.765659
EN_Llama,45.105214,8.261823e+03,74.420949,113.737093,99.134160,112.516157,106.758411
ZH_Aya,112.084228,2.834583e+03,360.637008,275.617452,292.760948,406.131890,135.838040
SW_Aya,347.245294,1.150134e+04,1588.158444,1544.971890,1344.702942,332.042594,2235.354059
ID_Aya,92.363250,1.937413e+03,306.205275,225.322198,117.137641,202.212119,297.658705
TA_Aya,3.798334,8.555107e+01,14.739504,4.049754,12.200776,10.231536,12.421246
EN_Aya,53.754913,3.607169e+02,69.141747,93.205527,80.995250,97.275513,85.909020
ZH_Qwen3,46.980806,2.175599e+06,146.704354,119.462250,122.105214,176.318815,63.072371
SW_Qwen3,64.534645,4.380327e+06,380.075948,433.095598,258.430765,69.236501,372.747064
ID_Qwen3,16.699008,4.557271e+06,116.218561,72.677371,21.817674,43.733264,127.139610
TA_Qwen3,2.741605,2.216887e+05,15.513642,3.063271,9.956398,9.944748,13.166703
EN_Qwen3,33.428698,7.780285e+05,43.983318,64.369847,52.554869,65.558487,59.187938

Display df std

         UQ TaCQ-SINQ TaCQ-EN TaCQ-TA TaCQ-ID TaCQ-SW TaCQ-ZH
ZH_Llama                133.0   30.47    7.06   284.0    2.90
SW_Llama                137.7   45.49    4.65    0.98   31.15
ID_Llama                149.1   10.45    0.48   15.13   69.98
TA_Llama                28.76    0.02    3.24    0.27    0.01
EN_Llama                 3.12    9.28    4.39    4.12    4.08
ZH_Aya                  12.84    5.15   15.79    4.07    0.39
SW_Aya                  233.9   52.02   161.9    8.99   306.7
ID_Aya                   4.41    9.13    2.48    2.53   17.78
TA_Aya                   1.43    0.01    0.36    0.19    0.98
EN_Aya                   0.22    1.18    0.47    1.53    1.51
ZH_Qwen3                 3.32    2.31    4.75   10.10    0.75
SW_Qwen3                10.56   144.2   23.81    1.53   15.01
ID_Qwen3                 3.52   14.03    0.17    0.60    5.78
TA_Qwen3                 0.67    0.01    0.82    0.50    1.54
EN_Qwen3                 0.32    0.46    0.53    0.46    0.91

Writing to pdf ...

##### Stats: aggresive

In [ ]:
def perplexity_aggresive_target_not(eval_languages, runs, base_model, quantization_technique, bit_width, eval_dataset, custom_title="", filter_result='', hf_evaluate=False, compare_std=False, gmean_aggregate=False):
  language_sort = {
      # Flores Plus
      "eng_Latn": 0, "fra_Latn": 1, "hin_Deva": 2, "npi_Deva": 3, "tam_Taml": 6, "tel_Telu": 7, "ind_Latn": 8, "zsm_Latn": 9, "swh_Latn": 10, "yor_Latn": 11, "cmn_Hans": 12, "jpn_Jpan": 13, "kor_Hang": 14, "arb_Arab" : 15,\
      # Wikipedia
      "en": 0, "fr": 1, "hi": 2, "ne": 3, "ta": 6, "te": 7, "id": 8, "ms": 9, "sw": 10, "yo": 11, "zh": 12, "ja": 13, "ko": 14, "ar": 15,\
      # INCLUDE
      "french": 1, "hindi": 2, "nepali": 3, "albanian": 4, "tamil": 6, "telugu": 7, "indonesian": 8, "malay": 9, "chinese": 12, "japanese": 13, "korean": 14, "arabic": 15,\
      # Global MMLU Lite
      "en": 0, "fr": 1, "hi": 2, "bn": 5, "id": 8, "sw": 10, "yo": 11, "zh": 12, "ja": 13, "ko": 14, "ar": 15,
  }
  flores_plus_add = ["afr_Latn", "dan_Latn", "deu_Latn", "eng_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"]
  for index, lang in enumerate(flores_plus_add):
    language_sort[lang] = 0 + index / 100
  flores_plus_add = ["kan_Knda", "mal_Mlym", "tam_Taml", "tel_Telu"]
  for index, lang in enumerate(flores_plus_add):
    language_sort[lang] = 6 + index / 100
  #flores_plus_add = ["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "ind_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"]
  flores_plus_add = ["ind_Latn", "zsm_Latn", "bjn_Latn", "min_Latn", "ace_Latn", "ban_Latn", "bug_Latn", "jav_Latn", "sun_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "fil_Latn", "war_Latn"]
  for index, lang in enumerate(flores_plus_add):
    language_sort[lang] = 8 + index / 100
  flores_plus_add = ["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "swh_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"]
  for index, lang in enumerate(flores_plus_add):
    language_sort[lang] = 10 + index / 100
  flores_plus_add = ["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant", "cmn_Hans"]
  for index, lang in enumerate(flores_plus_add):
    language_sort[lang] = 12 + index / 100
  eval_languages = list(sorted(eval_languages, key=lambda x: language_sort.get(x, 100)))

  calib_mapper = {
      "English": "eng_Latn" if eval_dataset.lower() == "floresplus" else "en",
      "Indonesian": "ind_Latn" if eval_dataset.lower() == "floresplus" else "id",
      "Tamil": "tam_Taml" if eval_dataset.lower() == "floresplus" else "ta",
      "Swahili": "swh_Latn" if eval_dataset.lower() == "floresplus" else "sw",
      "Chinese": "cmn_Hans" if eval_dataset.lower() == "floresplus" else "zh",
  }
  reverse_calib_mapper = {value: key for key, value in calib_mapper.items()}

  columns = ["Base Model", "Quantization Technique", "Bit Width", "Calibration Language"]
  columns.extend(eval_languages)
  custom_sort = {'Unquantized': 0, 'English': 1, 'Tamil': 2, 'Indonesian': 3, 'Swahili': 4, 'Chinese': 5,\
                 'Unquantized': 0, 'gptq': 1, 'slimllm': 2, 'tacq': 3,\
                 '32-bit': 0, '2-bit': 1, '3-bit': 2, '4-bit': 3, '8-bit': 4}

  data_acc = []
  data_nancount = []

  unquantized_data_acc = []


  # Iterate over the runs and print details
  for run in runs:
      config = run.config
      summary = run.summary

      if config["calibration_language"] == "WuuChinese":
        continue

      run_data_acc = []
      run_data_nancount = []
      run_data_acc.extend([run.config["base_model"], config["quantization_technique"], config["bit_width"], config["calibration_language"]])
      run_data_nancount.extend([run.config["base_model"], config["quantization_technique"], config["bit_width"], config["calibration_language"]])
      if not hf_evaluate:
        for lang in eval_languages:
          if lang in ["zh", "Chinese", "cmn_Hans", "ja", "Japanese", "jpn_Jpan"]:
            acc = run.summary.get(f"{eval_dataset.lower()}_byte_acc_{lang}", None)
            nancount = run.summary.get(f"{eval_dataset.lower()}_count_nan_count_{lang}", 0)
            if acc:
              # acc = math.pow(acc, 1/3)
              pass
            run_data_acc.append(acc)
            run_data_nancount.append(nancount)
          else:
            run_data_acc.append(run.summary.get(f"{eval_dataset.lower()}_word_acc_{lang}", None))
            run_data_nancount.append(run.summary.get(f"{eval_dataset.lower()}_nan_count_{lang}", 0))
      elif hf_evaluate:
        for lang in eval_languages:
          if gmean_aggregate:
            run_data_acc.append(run.summary.get(f"{eval_dataset.lower()}_gmean_perplexity_{lang}", None))
          else:
            run_data_acc.append(run.summary.get(f"{eval_dataset.lower()}_token_perplexity_{lang}", None))
          run_data_nancount.append(run.summary.get(f"{eval_dataset.lower()}_nancount_{lang}", 0))

      if config["quantization_technique"] == "Unquantized":
        unquantized_data_acc.append(run_data_acc)
        data_nancount.append(run_data_nancount)
      else:
        data_acc.append(run_data_acc)
        data_nancount.append(run_data_nancount)


  import numpy as np
  df_unquantized_acc = pd.DataFrame(unquantized_data_acc, columns=columns)
  df_unquantized_acc_chief_std = df_unquantized_acc.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std")

  df_acc = pd.DataFrame(data_acc, columns=columns).sort_values(by=['Quantization Technique', 'Calibration Language', 'Bit Width'], key=lambda x: x.map(custom_sort))
  df_acc_std = df_acc.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std", ddof=0).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_acc = df_acc.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("mean").sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))

  df_acc[df_acc.columns[4:]] = df_acc[df_acc.columns[4:]].astype(float)
  df_unquantized_acc[df_unquantized_acc.columns[4:]] = df_unquantized_acc[df_unquantized_acc.columns[4:]].astype(float)

  pd.set_option('display.float_format','{:.1f}'.format)
  # display(df_unquantized_acc)

  # # Perplexity related, change order of PPL
  # df_acc.iloc[:, 5:] = df_acc.iloc[:, 5:].apply(np.log10)
  # df_unquantized_acc.iloc[:, 5:] = df_unquantized_acc.iloc[:, 5:].apply(np.log10)

  calibration_languages = df_acc["Calibration Language"].unique()
  quants = df_acc["Quantization Technique"].unique()
  base_models = df_acc["Base Model"].unique()
  bits = df_acc["Bit Width"].unique()

  flag = True
  df = pd.DataFrame(data=[], columns=["Base Model", "Quantization Technique", "Bit Width", "Calibration Language", "Target", "Mean Non Target",
                                      "Direct over Unquantized", "Cross over Unquantized", "Direct over Default", "Cross over Default", "Direct over Cross", "Cross over Direct"])
  for quant in quants:
    for bit in bits:
      for base_model in base_models:
        df_filter_uq = df_unquantized_acc[df_unquantized_acc["Base Model"] == base_model]
        df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
        mean_ppl = df_filter.iloc[:, 4:].prod(axis=0)
        default_ppl = df_filter[df_filter["Calibration Language"] == "English"].iloc[0, 4:]
        count_ppl = df_filter.iloc[:, 4:].count(axis=0)
        df_filter = df_filter.reset_index(drop=True)
        if (quant, base_model) == ("slimllm", "CohereLabs/aya-expanse-8b"):
          mean_ppl = mean_ppl.drop(calib_mapper["Tamil"], axis=0)
          default_ppl = default_ppl.drop(calib_mapper["Tamil"], axis=0)
          count_ppl = count_ppl.drop(calib_mapper["Tamil"], axis=0)
          df_filter_uq = df_filter_uq.drop(calib_mapper["Tamil"], axis=1)

        df_filter.loc[:, "Target"] = pd.Series([df_filter.loc[i, calib_mapper[calib]] for i, calib in enumerate(df_filter["Calibration Language"].unique())])
        df_filter.loc[:, "Mean Non Target"] = (mean_ppl.values / df_filter["Target"].values) ** (1/(count_ppl.values - 1))
        # df_filter.loc[:, "Power Ratio"] = (10 ** df_filter["Mean Non Target"].values / 10 ** df_filter["Target"].values)

        # [0, x:] index is transforming from 2D (df) to 1D array (series)
        # This will broke if Unquantized have more than 1 instance
        df_filter.loc[:, "Direct over Unquantized"] = (df_filter["Target"].values / df_filter_uq.iloc[0, 4:].values) * 100
        df_filter.loc[:, "Cross over Unquantized"] = (df_filter["Mean Non Target"].values / df_filter_uq.iloc[0, 4:].values) * 100
        df_filter.loc[:, "Direct over Default"] = ((default_ppl.values - df_filter["Target"].values) / default_ppl.values) *100
        df_filter.loc[:, "Cross over Default"] = ((default_ppl.values - df_filter["Mean Non Target"].values) / default_ppl.values) * 100
        # df_filter.loc[:, "Direct over Cross"] = (df_filter["Target"].values / df_filter["Mean Non Target"].values) * 100
        df_filter.loc[:, "Direct over Cross"] = (df_filter["Target"].values / df_filter["Mean Non Target"].values)
        df_filter.loc[:, "Cross over Direct"] = (df_filter["Mean Non Target"].values / df_filter["Target"].values)
        # df_filter.drop(df_filter.columns[5:].drop(["Target", "Mean Non Target"]), axis=1)
        # if flag:
        #   print(quant, bit, base_model)
        #   display(df_filter["Target"])
        #   display(default_ppl)
        #   display(df_filter.loc[:, "Direct over Default"])
        #   flag = False
        df = pd.concat([df, df_filter], axis=0)
        print(f"Finished processing {base_model}, {quant}, {bit}")

  # Sort align with the tabular data
  custom_sort = {'Unquantized': 0, 'English': 1, 'Tamil': 2, 'Indonesian': 3, 'Swahili': 4, 'Chinese': 5,\
                  'Unquantized': 0, 'gptq': 1, 'slimllm': 2, 'tacq': 3,\
                  '32-bit': 0, '8-bit': 1, '4-bit': 2, '3-bit': 3, '2-bit': 4,\
                  'Qwen/Qwen3-8B': 0, 'CohereLabs/aya-expanse-8b': 1, 'meta-llama/Llama-3.1-8B-Instruct': 2,}
  df = df.sort_values(by=['Quantization Technique', 'Bit Width', 'Base Model', 'Calibration Language'], key=lambda x: x.map(custom_sort))

  pd.set_option('display.float_format','{:.3f}'.format)
  # pd.set_option('display.float_format','{:.1e}'.format)
  pd.set_option('display.max_rows', 500)
  if filter_result:
    display(df.loc[df['Calibration Language'] == filter_result, :])
  else:
    pd.set_option('display.float_format','{:.3f}'.format)
    display(df_unquantized_acc)
    pd.set_option('display.float_format','{:.3f}'.format)
    # pd.set_option('display.float_format','{:.1e}'.format)
    display(df)

  # for calib in calibration_languages:
  #   print(f"{compare_std=}: {calib}")
  #   display(df["Cross over Direct"][df["Calibration Language"] == calib])
  #   display(df["Cross over Direct"][df["Calibration Language"] == calib].describe())

  print("Coefficient of Variations")
  df_acc = df_acc.sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort)).reset_index(drop=True)
  df_acc_std = df_acc_std.sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort)).reset_index(drop=True)
  assert len(df_acc) == len(df_acc_std), "lenght of df_acc and df_acc_std is different"
  cov_df = df_acc.copy()
  cov_df.iloc[:, 4:] = (df_acc_std.iloc[:, 4:] / df_acc.iloc[:, 4:])
  display(cov_df)
  display(cov_df.describe())

  for eval_lang in eval_languages:
    calib_lang = reverse_calib_mapper.get(eval_lang, eval_lang)
    print(f"{eval_lang}: direct statistics")
    display(cov_df[cov_df["Calibration Language"] == calib_lang][eval_lang].describe())
    print(f"{eval_lang}: cross statistics")
    display(cov_df[cov_df["Calibration Language"] != calib_lang][eval_lang].describe())

  display(df["Cross over Direct"])
  display(df["Cross over Direct"].describe())
  if compare_std:
    display(df["Target"].describe())
    display(df["Mean Non Target"].describe())

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [3]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"config.bit_width": f"{bit_width}-bit"},
                            {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            {"config.base_model": "Qwen/Qwen3-8B"},
                            {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            {"$not": {"$and": [{"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}, {"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}]}}
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                              {"config.base_model": "Qwen/Qwen3-8B"},
                            # {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                          ]}
                      ]}
                  )

  eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
  # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
  # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
  # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
  # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
  # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

  # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
  perplexity_aggresive_target_not(eval_languages, runs, "", quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", hf_evaluate=True, gmean_aggregate=True)
  perplexity_aggresive_target_not(eval_languages, runs, "", quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", hf_evaluate=True, gmean_aggregate=True, compare_std=True)

/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:153: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_filter], axis=0)
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]

Finished processing Qwen/Qwen3-8B, gptq, 3-bit
Finished processing Qwen/Qwen3-8B, slimllm, 3-bit
Finished processing Qwen/Qwen3-8B, tacq, 3-bit

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.429,2.742,16.699,64.535,46.981

,Base Model,Quantization Technique,Bit Width,Calibration Language,Target,Mean Non Target,Direct over Unquantized,Cross over Unquantized,Direct over Default,Cross over Default,Direct over Cross,Cross over Direct,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,gptq,3-bit,English,40.525,42.644,121.228,127.568,0.000,-5.230,0.950,1.052,40.525,4.277,24.871,162.378,63.734
1,Qwen/Qwen3-8B,gptq,3-bit,Tamil,2.924,3.988,106.669,145.472,31.629,6.758,0.733,1.364,42.631,2.924,23.044,141.888,64.155
2,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,19.075,23.721,114.226,142.052,23.305,4.622,0.804,1.244,42.928,3.789,19.075,136.644,62.711
3,Qwen/Qwen3-8B,gptq,3-bit,Swahili,79.112,150.236,122.589,232.799,51.279,7.477,0.527,1.899,44.148,3.725,22.242,79.112,65.088
4,Qwen/Qwen3-8B,gptq,3-bit,Chinese,55.975,63.917,119.144,136.048,12.174,-0.287,0.876,1.142,40.932,4.191,24.839,161.822,55.975
0,Qwen/Qwen3-8B,slimllm,3-bit,English,38.188,44.063,114.239,131.811,0.000,-15.382,0.867,1.154,38.188,4.949,26.285,164.319,64.713
1,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,2.907,4.329,106.049,157.890,41.252,12.534,0.672,1.489,46.081,2.907,23.784,145.458,63.479
2,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,18.984,25.019,113.683,149.823,27.777,4.817,0.759,1.318,41.845,4.010,18.984,137.723,64.820
3,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,74.108,155.937,114.834,241.633,54.900,5.101,0.475,2.104,44.450,3.972,22.584,74.108,68.374
4,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,55.553,65.321,118.246,139.038,14.155,-0.940,0.850,1.176,43.979,4.455,27.751,179.624,55.553
0,Qwen/Qwen3-8B,tacq,3-bit,English,34.863,37.093,104.292,110.961,0.000,-6.395,0.940,1.064,34.863,3.796,21.207,118.216,53.221
1,Qwen/Qwen3-8B,tacq,3-bit,Tamil,2.791,3.537,101.818,129.012,26.457,6.815,0.789,1.267,37.812,2.791,19.529,104.767,54.119
2,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,17.453,20.238,104.517,121.192,17.700,4.569,0.862,1.160,36.722,3.444,17.453,103.912,53.635
3,Qwen/Qwen3-8B,tacq,3-bit,Swahili,65.999,110.401,102.269,171.073,44.171,6.610,0.598,1.673,37.238,3.319,19.180,65.999,53.882
4,Qwen/Qwen3-8B,tacq,3-bit,Chinese,48.014,53.713,102.200,114.330,9.783,-0.925,0.894,1.119,36.612,3.607,21.118,115.434,48.014

Coefficient of Variations

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,gptq,English,3-bit,0.008,0.009,0.024,0.017,0.012
1,Qwen/Qwen3-8B,gptq,Tamil,3-bit,0.011,0.003,0.013,0.012,0.019
2,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,0.009,0.026,0.004,0.035,0.007
3,Qwen/Qwen3-8B,gptq,Swahili,3-bit,0.023,0.010,0.019,0.014,0.014
4,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.006,0.024,0.003,0.073,0.012
5,Qwen/Qwen3-8B,slimllm,English,3-bit,0.007,0.018,0.009,0.033,0.024
6,Qwen/Qwen3-8B,slimllm,Tamil,3-bit,0.029,0.002,0.022,0.052,0.015
7,Qwen/Qwen3-8B,slimllm,Indonesian,3-bit,0.016,0.009,0.002,0.024,0.011
8,Qwen/Qwen3-8B,slimllm,Swahili,3-bit,0.020,0.006,0.015,0.010,0.013
9,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.024,0.045,0.039,0.046,0.015
10,Qwen/Qwen3-8B,tacq,English,3-bit,0.004,0.010,0.005,0.023,0.006
11,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.021,0.002,0.007,0.012,0.006
12,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.013,0.004,0.002,0.050,0.016
13,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.000,0.007,0.002,0.007,0.008
14,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.010,0.011,0.008,0.020,0.004

       eng_Latn  tam_Taml  ind_Latn  swh_Latn  cmn_Hans
count    15.000    15.000    15.000    15.000    15.000
mean      0.013     0.012     0.012     0.029     0.012
std       0.008     0.012     0.011     0.019     0.005
min       0.000     0.002     0.002     0.007     0.004
25%       0.007     0.005     0.003     0.013     0.008
50%       0.011     0.009     0.008     0.023     0.012
75%       0.020     0.014     0.017     0.040     0.015
max       0.029     0.045     0.039     0.073     0.024

eng_Latn: direct statistics

count   3.000
mean    0.006
std     0.002
min     0.004
25%     0.006
50%     0.007
75%     0.007
max     0.008
Name: eng_Latn, dtype: float64

eng_Latn: cross statistics

count   12.000
mean     0.015
std      0.008
min      0.000
25%      0.010
50%      0.015
75%      0.021
max      0.029
Name: eng_Latn, dtype: float64

tam_Taml: direct statistics

count   3.000
mean    0.002
std     0.001
min     0.002
25%     0.002
50%     0.002
75%     0.002
max     0.003
Name: tam_Taml, dtype: float64

tam_Taml: cross statistics

count   12.000
mean     0.015
std      0.012
min      0.004
25%      0.008
50%      0.010
75%      0.019
max      0.045
Name: tam_Taml, dtype: float64

ind_Latn: direct statistics

count   3.000
mean    0.003
std     0.001
min     0.002
25%     0.002
50%     0.002
75%     0.003
max     0.004
Name: ind_Latn, dtype: float64

ind_Latn: cross statistics

count   12.000
mean     0.014
std      0.011
min      0.002
25%      0.007
50%      0.011
75%      0.020
max      0.039
Name: ind_Latn, dtype: float64

swh_Latn: direct statistics

count   3.000
mean    0.010
std     0.004
min     0.007
25%     0.008
50%     0.010
75%     0.012
max     0.014
Name: swh_Latn, dtype: float64

swh_Latn: cross statistics

count   12.000
mean     0.033
std      0.019
min      0.012
25%      0.019
50%      0.029
75%      0.047
max      0.073
Name: swh_Latn, dtype: float64

cmn_Hans: direct statistics

count   3.000
mean    0.010
std     0.006
min     0.004
25%     0.008
50%     0.012
75%     0.014
max     0.015
Name: cmn_Hans, dtype: float64

cmn_Hans: cross statistics

count   12.000
mean     0.013
std      0.005
min      0.006
25%      0.008
50%      0.013
75%      0.015
max      0.024
Name: cmn_Hans, dtype: float64

0   1.052
1   1.364
2   1.244
3   1.899
4   1.142
0   1.154
1   1.489
2   1.318
3   2.104
4   1.176
0   1.064
1   1.267
2   1.160
3   1.673
4   1.119
Name: Cross over Direct, dtype: float64

count   15.000
mean     1.348
std      0.315
min      1.052
25%      1.148
50%      1.244
75%      1.426
max      2.104
Name: Cross over Direct, dtype: float64

Finished processing Qwen/Qwen3-8B, gptq, 3-bit
Finished processing Qwen/Qwen3-8B, slimllm, 3-bit
Finished processing Qwen/Qwen3-8B, tacq, 3-bit

/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:153: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_filter], axis=0)
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.429,2.742,16.699,64.535,46.981

,Base Model,Quantization Technique,Bit Width,Calibration Language,Target,Mean Non Target,Direct over Unquantized,Cross over Unquantized,Direct over Default,Cross over Default,Direct over Cross,Cross over Direct,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,gptq,3-bit,English,0.317,0.464,0.948,1.387,0.000,-46.276,0.684,1.463,0.317,0.040,0.593,2.804,0.762
1,Qwen/Qwen3-8B,gptq,3-bit,Tamil,0.009,0.063,0.337,2.287,76.796,-57.384,0.147,6.783,0.470,0.009,0.310,1.705,1.200
2,Qwen/Qwen3-8B,gptq,3-bit,Indonesian,0.077,0.270,0.464,1.616,86.930,54.468,0.287,3.484,0.386,0.099,0.077,4.758,0.439
3,Qwen/Qwen3-8B,gptq,3-bit,Swahili,1.137,4.042,1.761,6.264,59.467,-44.158,0.281,3.557,1.014,0.039,0.416,1.137,0.916
4,Qwen/Qwen3-8B,gptq,3-bit,Chinese,0.699,0.779,1.489,1.658,8.282,-2.130,0.898,1.114,0.252,0.100,0.069,11.737,0.699
0,Qwen/Qwen3-8B,slimllm,3-bit,English,0.270,0.959,0.806,2.870,0.000,-255.855,0.281,3.559,0.270,0.088,0.226,5.456,1.569
1,Qwen/Qwen3-8B,slimllm,3-bit,Tamil,0.005,0.061,0.184,2.234,94.283,30.435,0.082,12.168,1.340,0.005,0.530,7.634,0.968
2,Qwen/Qwen3-8B,slimllm,3-bit,Indonesian,0.032,0.459,0.192,2.746,85.841,-102.837,0.070,14.326,0.683,0.035,0.032,3.363,0.703
3,Qwen/Qwen3-8B,slimllm,3-bit,Swahili,0.710,5.831,1.101,9.036,86.983,-6.870,0.122,8.210,0.871,0.023,0.345,0.710,0.920
4,Qwen/Qwen3-8B,slimllm,3-bit,Chinese,0.817,0.996,1.738,2.119,47.946,36.549,0.820,1.219,1.063,0.200,1.072,8.254,0.817
0,Qwen/Qwen3-8B,tacq,3-bit,English,0.152,0.137,0.454,0.410,0.000,9.671,1.107,0.903,0.152,0.039,0.103,2.746,0.322
1,Qwen/Qwen3-8B,tacq,3-bit,Tamil,0.004,0.026,0.153,0.958,89.343,33.481,0.160,6.242,0.787,0.004,0.144,1.246,0.341
2,Qwen/Qwen3-8B,tacq,3-bit,Indonesian,0.038,0.098,0.225,0.589,63.735,4.907,0.381,2.622,0.473,0.012,0.038,5.156,0.842
3,Qwen/Qwen3-8B,tacq,3-bit,Swahili,0.485,2.517,0.751,3.900,82.350,8.325,0.193,5.194,0.003,0.025,0.039,0.485,0.440
4,Qwen/Qwen3-8B,tacq,3-bit,Chinese,0.175,0.449,0.372,0.957,45.775,-39.381,0.389,2.570,0.377,0.039,0.161,2.276,0.175

Coefficient of Variations

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,gptq,English,3-bit,0.008,0.009,0.024,0.017,0.012
1,Qwen/Qwen3-8B,gptq,Tamil,3-bit,0.011,0.003,0.013,0.012,0.019
2,Qwen/Qwen3-8B,gptq,Indonesian,3-bit,0.009,0.026,0.004,0.035,0.007
3,Qwen/Qwen3-8B,gptq,Swahili,3-bit,0.023,0.010,0.019,0.014,0.014
4,Qwen/Qwen3-8B,gptq,Chinese,3-bit,0.006,0.024,0.003,0.073,0.012
5,Qwen/Qwen3-8B,slimllm,English,3-bit,0.007,0.018,0.009,0.033,0.024
6,Qwen/Qwen3-8B,slimllm,Tamil,3-bit,0.029,0.002,0.022,0.052,0.015
7,Qwen/Qwen3-8B,slimllm,Indonesian,3-bit,0.016,0.009,0.002,0.024,0.011
8,Qwen/Qwen3-8B,slimllm,Swahili,3-bit,0.020,0.006,0.015,0.010,0.013
9,Qwen/Qwen3-8B,slimllm,Chinese,3-bit,0.024,0.045,0.039,0.046,0.015
10,Qwen/Qwen3-8B,tacq,English,3-bit,0.004,0.010,0.005,0.023,0.006
11,Qwen/Qwen3-8B,tacq,Tamil,3-bit,0.021,0.002,0.007,0.012,0.006
12,Qwen/Qwen3-8B,tacq,Indonesian,3-bit,0.013,0.004,0.002,0.050,0.016
13,Qwen/Qwen3-8B,tacq,Swahili,3-bit,0.000,0.007,0.002,0.007,0.008
14,Qwen/Qwen3-8B,tacq,Chinese,3-bit,0.010,0.011,0.008,0.020,0.004

       eng_Latn  tam_Taml  ind_Latn  swh_Latn  cmn_Hans
count    15.000    15.000    15.000    15.000    15.000
mean      0.013     0.012     0.012     0.029     0.012
std       0.008     0.012     0.011     0.019     0.005
min       0.000     0.002     0.002     0.007     0.004
25%       0.007     0.005     0.003     0.013     0.008
50%       0.011     0.009     0.008     0.023     0.012
75%       0.020     0.014     0.017     0.040     0.015
max       0.029     0.045     0.039     0.073     0.024

eng_Latn: direct statistics

count   3.000
mean    0.006
std     0.002
min     0.004
25%     0.006
50%     0.007
75%     0.007
max     0.008
Name: eng_Latn, dtype: float64

eng_Latn: cross statistics

count   12.000
mean     0.015
std      0.008
min      0.000
25%      0.010
50%      0.015
75%      0.021
max      0.029
Name: eng_Latn, dtype: float64

tam_Taml: direct statistics

count   3.000
mean    0.002
std     0.001
min     0.002
25%     0.002
50%     0.002
75%     0.002
max     0.003
Name: tam_Taml, dtype: float64

tam_Taml: cross statistics

count   12.000
mean     0.015
std      0.012
min      0.004
25%      0.008
50%      0.010
75%      0.019
max      0.045
Name: tam_Taml, dtype: float64

ind_Latn: direct statistics

count   3.000
mean    0.003
std     0.001
min     0.002
25%     0.002
50%     0.002
75%     0.003
max     0.004
Name: ind_Latn, dtype: float64

ind_Latn: cross statistics

count   12.000
mean     0.014
std      0.011
min      0.002
25%      0.007
50%      0.011
75%      0.020
max      0.039
Name: ind_Latn, dtype: float64

swh_Latn: direct statistics

count   3.000
mean    0.010
std     0.004
min     0.007
25%     0.008
50%     0.010
75%     0.012
max     0.014
Name: swh_Latn, dtype: float64

swh_Latn: cross statistics

count   12.000
mean     0.033
std      0.019
min      0.012
25%      0.019
50%      0.029
75%      0.047
max      0.073
Name: swh_Latn, dtype: float64

cmn_Hans: direct statistics

count   3.000
mean    0.010
std     0.006
min     0.004
25%     0.008
50%     0.012
75%     0.014
max     0.015
Name: cmn_Hans, dtype: float64

cmn_Hans: cross statistics

count   12.000
mean     0.013
std      0.005
min      0.006
25%      0.008
50%      0.013
75%      0.015
max      0.024
Name: cmn_Hans, dtype: float64

0    1.463
1    6.783
2    3.484
3    3.557
4    1.114
0    3.559
1   12.168
2   14.326
3    8.210
4    1.219
0    0.903
1    6.242
2    2.622
3    5.194
4    2.570
Name: Cross over Direct, dtype: float64

count   15.000
mean     4.894
std      4.053
min      0.903
25%      2.017
50%      3.557
75%      6.512
max     14.326
Name: Cross over Direct, dtype: float64

count   15.000
mean     0.328
std      0.359
min      0.004
25%      0.035
50%      0.175
75%      0.592
max      1.137
Name: Target, dtype: float64

count   15.000
mean     1.143
std      1.697
min      0.026
25%      0.118
50%      0.459
75%      0.977
max      5.831
Name: Mean Non Target, dtype: float64

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"config.bit_width": f"{bit_width}-bit"},
                            {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            # {"config.base_model": "Qwen/Qwen3-8B"},
                            {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                            {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            {"$not": {"$and": [{"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}, {"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}]}}
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                              # {"config.base_model": "Qwen/Qwen3-8B"},
                            {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                          ]}
                      ]}
                  )

  eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
  # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
  # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
  # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
  # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
  # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

  # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
  perplexity_aggresive_target_not(eval_languages, runs, "", quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", hf_evaluate=True, gmean_aggregate=True)
  perplexity_aggresive_target_not(eval_languages, runs, "", quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", hf_evaluate=True, gmean_aggregate=True, compare_std=True)

Finished processing CohereLabs/aya-expanse-8b, gptq, 2-bit
Finished processing Qwen/Qwen3-8B, gptq, 2-bit
Finished processing CohereLabs/aya-expanse-8b, slimllm, 2-bit
Finished processing Qwen/Qwen3-8B, slimllm, 2-bit
Finished processing CohereLabs/aya-expanse-8b, tacq, 2-bit
Finished processing Qwen/Qwen3-8B, tacq, 2-bit

/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:153: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_filter], axis=0)
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.429,2.742,16.699,64.535,46.981
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.755,3.798,92.363,347.245,112.084

,Base Model,Quantization Technique,Bit Width,Calibration Language,Target,Mean Non Target,Direct over Unquantized,Cross over Unquantized,Direct over Default,Cross over Default,Direct over Cross,Cross over Direct,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,gptq,2-bit,English,12827.902,38022.199,38373.920,113741.192,0.000,-196.402,0.337,2.964,12827.902,45940.807,39236.778,40398.302,39491.466
1,Qwen/Qwen3-8B,gptq,2-bit,Tamil,7.469,33666.480,272.430,1227984.338,99.984,26.718,0.000,4507.526,43858.254,7.469,46203.200,46825.504,34007.537
2,Qwen/Qwen3-8B,gptq,2-bit,Indonesian,1683.806,41260.315,10083.272,247082.435,95.709,-5.157,0.041,24.504,35069.945,32266.297,1683.806,34796.007,42150.094
3,Qwen/Qwen3-8B,gptq,2-bit,Swahili,1466.964,40627.737,2273.142,62954.924,96.369,-0.568,0.036,27.695,44051.236,37346.013,41954.948,1466.964,25431.656
4,Qwen/Qwen3-8B,gptq,2-bit,Chinese,17781.025,34638.805,37847.424,73729.696,54.975,12.288,0.513,1.948,30846.395,23205.924,38104.965,41391.916,17781.025
0,CohereLabs/aya-expanse-8b,gptq,2-bit,English,241.836,754.221,449.887,1403.073,0.000,-211.873,0.321,3.119,241.836,22325.499,6090.955,22225.968,19168.145
1,CohereLabs/aya-expanse-8b,gptq,2-bit,Tamil,6.436,4939.166,169.450,130035.052,99.971,77.877,0.001,767.394,745.679,6.436,6473.672,21938.559,9278.961
2,CohereLabs/aya-expanse-8b,gptq,2-bit,Indonesian,545.812,5693.192,590.940,6163.915,91.039,6.530,0.096,10.431,522.582,4200.198,545.812,14221.137,9950.510
3,CohereLabs/aya-expanse-8b,gptq,2-bit,Swahili,1591.608,19500.949,458.353,5615.900,92.839,12.261,0.082,12.252,824.976,1501.481,4321.038,1591.608,14767.553
4,CohereLabs/aya-expanse-8b,gptq,2-bit,Chinese,1029.857,12714.765,918.824,11343.938,94.627,33.667,0.081,12.346,1006.575,4226.914,6165.939,20855.464,1029.857
0,Qwen/Qwen3-8B,slimllm,2-bit,English,151.575,3039.980,453.426,9093.923,0.000,-1905.600,0.050,20.056,151.575,14768.033,2493.904,6726.278,667418.912
1,Qwen/Qwen3-8B,slimllm,2-bit,Tamil,4.443,12923.369,162.056,471379.682,99.970,12.491,0.000,2908.754,6890.434,4.443,11464.606,6525.812,60166.327
2,Qwen/Qwen3-8B,slimllm,2-bit,Indonesian,123.248,4402.051,738.057,26361.152,95.058,-76.512,0.028,35.717,1077.302,12007.141,123.248,2713.585,411364.223
3,Qwen/Qwen3-8B,slimllm,2-bit,Swahili,539.807,6918.330,836.460,10720.334,91.975,-2.855,0.078,12.816,2003.619,6139.446,701.292,539.807,627831.336
4,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,360.020,319120.996,766.314,679258.244,99.946,52.186,0.001,886.397,5742.270,25621.911,18727.617,19233.229,360.020
0,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,136.696,746.294,254.296,1388.327,0.000,-445.950,0.183,5.460,136.696,411021.091,47666.033,9978.332,7409755.211
1,CohereLabs/aya-expanse-8b,slimllm,2-bit,Indonesian,232.826,28897.988,252.076,31287.322,99.512,39.374,0.008,124.119,268.801,449010.693,232.826,5561.333,1631136.553
2,CohereLabs/aya-expanse-8b,slimllm,2-bit,Swahili,418.917,14128.558,120.640,4068.754,95.802,-41.592,0.030,33.726,334.556,607135.151,1044.489,418.917,1004870.877
3,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,274.084,2298625.112,244.534,2050801.568,99.996,68.978,0.000,8386.566,4622.002,290134.141,484718.873,50822.574,274.084
0,Qwen/Qwen3-8B,tacq,2-bit,English,43.983,60.192,131.574,180.061,0.000,-36.852,0.731,1.369,43.983,15.514,116.219,380.076,146.704
1,Qwen/Qwen3-8B,tacq,2-bit,Tamil,3.063,11.925,111.733,434.978,80.254,23.130,0.257,3.893,64.370,3.063,72.677,433.096,119.462
2,Qwen/Qwen3-8B,tacq,2-bit,Indonesian,21.818,82.783,130.653,495.737,81.227,28.769,0.264,3.794,52.555,9.956,21.818,258.431,122.105
3,Qwen/Qwen3-8B,tacq,2-bit,Swahili,69.237,354.857,107.286,549.870,81.784,6.635,0.195,5.125,65.558,9.945,43.733,69.237,176.319
4,Qwen/Qwen3-8B,tacq,2-bit,Chinese,63.072,139.372,134.251,296.658,57.007,4.998,0.453,2.210,59.188,13.167,127.140,372.747,63.072
0,CohereLabs/aya-expanse-8b,tacq,2-bit,English,69.142,89.122,128.624,165.794,0.000,-28.898,0.776,1.289,69.142,14.740,306.205,1588.158,360.637
1,CohereLabs/aya-expanse-8b,tacq,2-bit,Tamil,4.050,12.295,106.619,323.706,72.524,16.582,0.329,3.036,93.206,4.050,225.322,1544.972,275.617
2,CohereLabs/aya-expanse-8b,tacq,2-bit,Indonesian,117.138,253.855,126.823,274.844,61.745,17.096,0.461,2.167,80.995,12.201,117.138,1344.703,292.761
3,CohereLabs/aya-expanse-8b,tacq,2-bit,Swahili,332.043,1647.960,95.622,474.581,79.093,-3.765,0.201,4.963,97.276,10.232,202.212,332.043,406.132
4,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,135.838,329.715,121.193,294.168,62.334,8.574,0.412,2.427,85.909,12.421,297.659,2235.354,135.838

Coefficient of Variations

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,gptq,English,2-bit,0.021,0.080,0.015,0.038,0.109
1,Qwen/Qwen3-8B,gptq,Tamil,2-bit,0.072,0.056,0.128,0.001,0.372
2,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,0.042,0.109,0.275,0.093,0.043
3,Qwen/Qwen3-8B,gptq,Swahili,2-bit,0.036,0.041,0.051,0.081,0.008
4,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.016,0.078,0.120,0.150,0.086
5,Qwen/Qwen3-8B,slimllm,English,2-bit,0.100,0.633,0.174,0.136,0.392
6,Qwen/Qwen3-8B,slimllm,Tamil,2-bit,0.375,0.024,0.190,0.206,0.383
7,Qwen/Qwen3-8B,slimllm,Indonesian,2-bit,0.530,0.926,0.520,0.453,0.331
8,Qwen/Qwen3-8B,slimllm,Swahili,2-bit,0.406,0.660,0.091,0.283,0.895
9,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.395,0.625,0.277,0.315,0.125
10,Qwen/Qwen3-8B,tacq,English,2-bit,0.007,0.043,0.030,0.028,0.023
11,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.007,0.003,0.193,0.333,0.019
12,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.010,0.082,0.008,0.092,0.039
13,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.007,0.050,0.014,0.022,0.057
14,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.015,0.117,0.045,0.040,0.012
15,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.026,0.301,0.129,0.057,0.081
16,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,0.082,0.038,0.070,0.093,0.140
17,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,0.049,0.241,0.067,0.081,0.087
18,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,0.098,0.384,0.138,0.021,0.080
19,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.075,0.269,0.121,0.112,0.018
20,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.063,0.689,0.340,0.212,0.162
21,CohereLabs/aya-expanse-8b,slimllm,Indonesian,2-bit,0.084,0.719,0.047,0.205,0.256
22,CohereLabs/aya-expanse-8b,slimllm,Swahili,2-bit,0.350,1.365,0.390,0.090,0.645
23,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.765,0.926,0.096,0.519,0.051
24,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.003,0.097,0.014,0.147,0.036
25,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,0.013,0.003,0.041,0.034,0.019
26,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.006,0.030,0.021,0.120,0.054
27,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,0.016,0.019,0.013,0.027,0.010
28,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.018,0.079,0.060,0.137,0.003

       eng_Latn  tam_Taml  ind_Latn  swh_Latn  cmn_Hans
count    29.000    29.000    29.000    29.000    29.000
mean      0.127     0.300     0.127     0.142     0.156
std       0.192     0.360     0.127     0.130     0.210
min       0.003     0.003     0.008     0.001     0.003
25%       0.015     0.043     0.041     0.040     0.023
50%       0.042     0.097     0.091     0.093     0.080
75%       0.098     0.625     0.174     0.205     0.162
max       0.765     1.365     0.520     0.519     0.895

eng_Latn: direct statistics

count   6.000
mean    0.037
std     0.038
min     0.003
25%     0.011
50%     0.024
75%     0.054
max     0.100
Name: eng_Latn, dtype: float64

eng_Latn: cross statistics

count   23.000
mean     0.151
std      0.210
min      0.006
25%      0.016
50%      0.049
75%      0.224
max      0.765
Name: eng_Latn, dtype: float64

tam_Taml: direct statistics

count   5.000
mean    0.025
std     0.023
min     0.003
25%     0.003
50%     0.024
75%     0.038
max     0.056
Name: tam_Taml, dtype: float64

tam_Taml: cross statistics

count   24.000
mean     0.357
std      0.372
min      0.019
25%      0.079
50%      0.179
75%      0.640
max      1.365
Name: tam_Taml, dtype: float64

ind_Latn: direct statistics

count   6.000
mean    0.156
std     0.203
min     0.008
25%     0.028
50%     0.057
75%     0.223
max     0.520
Name: ind_Latn, dtype: float64

ind_Latn: cross statistics

count   23.000
mean     0.119
std      0.104
min      0.013
25%      0.043
50%      0.096
75%      0.156
max      0.390
Name: ind_Latn, dtype: float64

swh_Latn: direct statistics

count   6.000
mean    0.087
std     0.101
min     0.021
25%     0.023
50%     0.054
75%     0.088
max     0.283
Name: swh_Latn, dtype: float64

swh_Latn: cross statistics

count   23.000
mean     0.157
std      0.135
min      0.001
25%      0.069
50%      0.120
75%      0.206
max      0.519
Name: swh_Latn, dtype: float64

cmn_Hans: direct statistics

count   6.000
mean    0.049
std     0.048
min     0.003
25%     0.014
50%     0.035
75%     0.077
max     0.125
Name: cmn_Hans, dtype: float64

cmn_Hans: cross statistics

count   23.000
mean     0.184
std      0.228
min      0.008
25%      0.037
50%      0.081
75%      0.293
max      0.895
Name: cmn_Hans, dtype: float64

0      2.964
1   4507.526
2     24.504
3     27.695
4      1.948
0      3.119
1    767.394
2     10.431
3     12.252
4     12.346
0     20.056
1   2908.754
2     35.717
3     12.816
4    886.397
0      5.460
1    124.119
2     33.726
3   8386.566
0      1.369
1      3.893
2      3.794
3      5.125
4      2.210
0      1.289
1      3.036
2      2.167
3      4.963
4      2.427
Name: Cross over Direct, dtype: float64

count     29.000
mean     614.278
std     1788.508
min        1.289
25%        3.036
50%       10.431
75%       33.726
max     8386.566
Name: Cross over Direct, dtype: float64

Finished processing CohereLabs/aya-expanse-8b, gptq, 2-bit
Finished processing Qwen/Qwen3-8B, gptq, 2-bit
Finished processing CohereLabs/aya-expanse-8b, slimllm, 2-bit
Finished processing Qwen/Qwen3-8B, slimllm, 2-bit
Finished processing CohereLabs/aya-expanse-8b, tacq, 2-bit
Finished processing Qwen/Qwen3-8B, tacq, 2-bit

/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:153: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_filter], axis=0)
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
/tmp/ipykernel_8238/3810827973.py:122: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.429,2.742,16.699,64.535,46.981
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.755,3.798,92.363,347.245,112.084

,Base Model,Quantization Technique,Bit Width,Calibration Language,Target,Mean Non Target,Direct over Unquantized,Cross over Unquantized,Direct over Default,Cross over Default,Direct over Cross,Cross over Direct,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,gptq,2-bit,English,269.192,1379.778,805.271,4127.524,0.000,-412.563,0.195,5.126,269.192,3672.782,607.573,1545.126,4322.025
1,Qwen/Qwen3-8B,gptq,2-bit,Tamil,0.418,2447.045,15.233,89255.924,99.989,33.374,0.000,5859.364,3137.502,0.418,5893.247,41.811,12652.174
2,Qwen/Qwen3-8B,gptq,2-bit,Indonesian,463.525,2433.128,2775.761,14570.493,23.709,-300.467,0.191,5.249,1463.765,3505.412,463.525,3225.379,1814.626
3,Qwen/Qwen3-8B,gptq,2-bit,Swahili,119.319,1066.372,184.891,1652.403,92.278,30.985,0.112,8.937,1602.263,1535.748,2132.437,119.319,214.563
4,Qwen/Qwen3-8B,gptq,2-bit,Chinese,1521.219,2148.070,3237.958,4572.229,64.803,50.299,0.708,1.412,492.546,1813.484,4590.186,6205.822,1521.219
0,CohereLabs/aya-expanse-8b,gptq,2-bit,English,6.347,55.452,11.808,103.157,0.000,-773.628,0.114,8.736,6.347,6727.004,785.552,1277.196,1543.522
1,CohereLabs/aya-expanse-8b,gptq,2-bit,Tamil,0.242,1453.431,6.384,38264.953,99.996,78.394,0.000,5994.001,60.776,0.242,453.404,2050.240,1302.353
2,CohereLabs/aya-expanse-8b,gptq,2-bit,Indonesian,36.466,631.875,39.481,684.119,95.358,19.563,0.058,17.328,25.456,1013.399,36.466,1152.199,866.080
3,CohereLabs/aya-expanse-8b,gptq,2-bit,Swahili,33.017,1630.066,9.508,469.428,97.415,-27.629,0.020,49.370,80.774,576.595,597.969,33.017,1180.853
4,CohereLabs/aya-expanse-8b,gptq,2-bit,Chinese,18.945,1197.427,16.903,1068.328,98.773,22.422,0.016,63.205,75.661,1135.284,748.489,2340.086,18.945
0,Qwen/Qwen3-8B,slimllm,2-bit,English,15.200,1283.833,45.469,3840.511,0.000,-8346.429,0.012,84.464,15.200,9351.708,434.530,915.581,261392.184
1,Qwen/Qwen3-8B,slimllm,2-bit,Tamil,0.105,9064.275,3.826,330619.296,99.999,3.074,0.000,86417.678,2585.159,0.105,2181.572,1344.498,23070.095
2,Qwen/Qwen3-8B,slimllm,2-bit,Indonesian,64.114,748.198,383.940,4480.493,85.245,-72.185,0.086,11.670,570.476,11122.034,64.114,1229.940,136201.928
3,Qwen/Qwen3-8B,slimllm,2-bit,Swahili,152.853,1739.756,236.854,2695.848,83.305,-90.017,0.088,11.382,812.772,4051.682,63.687,152.853,562039.371
4,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,44.891,146579.419,95.552,311998.520,99.983,43.924,0.000,3265.238,2266.422,16018.500,5190.682,6050.794,44.891
0,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,8.647,210.964,16.086,392.455,0.000,-2339.708,0.041,24.397,8.647,283221.794,16191.599,2119.860,1202363.339
1,CohereLabs/aya-expanse-8b,slimllm,2-bit,Indonesian,10.858,6745.919,11.756,7303.683,99.933,58.337,0.002,621.285,22.656,322783.452,10.858,1141.379,416931.508
2,CohereLabs/aya-expanse-8b,slimllm,2-bit,Swahili,37.524,3996.111,10.806,1150.804,98.230,-88.508,0.009,106.496,117.248,828733.377,407.497,37.524,648186.967
3,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,13.882,687490.834,12.385,613369.824,99.999,42.822,0.000,49523.481,3534.650,268700.417,46527.415,26373.981,13.882
0,Qwen/Qwen3-8B,tacq,2-bit,English,0.324,0.566,0.968,1.693,0.000,-74.958,0.572,1.750,0.324,0.665,3.516,10.556,3.317
1,Qwen/Qwen3-8B,tacq,2-bit,Tamil,0.010,0.805,0.381,29.359,98.428,-20.984,0.013,76.982,0.462,0.010,14.028,144.154,2.312
2,Qwen/Qwen3-8B,tacq,2-bit,Indonesian,0.168,3.621,1.004,21.684,95.229,-2.994,0.046,21.588,0.535,0.818,0.168,23.810,4.750
3,Qwen/Qwen3-8B,tacq,2-bit,Swahili,1.532,27.157,2.375,42.081,85.484,-157.254,0.056,17.722,0.458,0.499,0.603,1.532,10.103
4,Qwen/Qwen3-8B,tacq,2-bit,Chinese,0.753,4.380,1.602,9.323,77.311,-32.043,0.172,5.820,0.908,1.544,5.781,15.010,0.753
0,CohereLabs/aya-expanse-8b,tacq,2-bit,English,0.218,1.066,0.406,1.982,0.000,-388.370,0.205,4.884,0.218,1.434,4.412,233.932,12.842
1,CohereLabs/aya-expanse-8b,tacq,2-bit,Tamil,0.013,0.559,0.337,14.711,99.107,61.033,0.023,43.654,1.177,0.013,9.131,52.023,5.145
2,CohereLabs/aya-expanse-8b,tacq,2-bit,Indonesian,2.482,6.526,2.687,7.066,43.743,-47.916,0.380,2.629,0.472,0.360,2.482,161.907,15.791
3,CohereLabs/aya-expanse-8b,tacq,2-bit,Swahili,8.992,156.790,2.589,45.153,96.156,32.976,0.057,17.437,1.532,0.193,2.532,8.992,4.074
4,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,0.387,8.075,0.346,7.204,96.983,37.123,0.048,20.843,1.514,0.978,17.780,306.710,0.387

Coefficient of Variations

,Base Model,Quantization Technique,Calibration Language,Bit Width,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,gptq,English,2-bit,0.021,0.080,0.015,0.038,0.109
1,Qwen/Qwen3-8B,gptq,Tamil,2-bit,0.072,0.056,0.128,0.001,0.372
2,Qwen/Qwen3-8B,gptq,Indonesian,2-bit,0.042,0.109,0.275,0.093,0.043
3,Qwen/Qwen3-8B,gptq,Swahili,2-bit,0.036,0.041,0.051,0.081,0.008
4,Qwen/Qwen3-8B,gptq,Chinese,2-bit,0.016,0.078,0.120,0.150,0.086
5,Qwen/Qwen3-8B,slimllm,English,2-bit,0.100,0.633,0.174,0.136,0.392
6,Qwen/Qwen3-8B,slimllm,Tamil,2-bit,0.375,0.024,0.190,0.206,0.383
7,Qwen/Qwen3-8B,slimllm,Indonesian,2-bit,0.530,0.926,0.520,0.453,0.331
8,Qwen/Qwen3-8B,slimllm,Swahili,2-bit,0.406,0.660,0.091,0.283,0.895
9,Qwen/Qwen3-8B,slimllm,Chinese,2-bit,0.395,0.625,0.277,0.315,0.125
10,Qwen/Qwen3-8B,tacq,English,2-bit,0.007,0.043,0.030,0.028,0.023
11,Qwen/Qwen3-8B,tacq,Tamil,2-bit,0.007,0.003,0.193,0.333,0.019
12,Qwen/Qwen3-8B,tacq,Indonesian,2-bit,0.010,0.082,0.008,0.092,0.039
13,Qwen/Qwen3-8B,tacq,Swahili,2-bit,0.007,0.050,0.014,0.022,0.057
14,Qwen/Qwen3-8B,tacq,Chinese,2-bit,0.015,0.117,0.045,0.040,0.012
15,CohereLabs/aya-expanse-8b,gptq,English,2-bit,0.026,0.301,0.129,0.057,0.081
16,CohereLabs/aya-expanse-8b,gptq,Tamil,2-bit,0.082,0.038,0.070,0.093,0.140
17,CohereLabs/aya-expanse-8b,gptq,Indonesian,2-bit,0.049,0.241,0.067,0.081,0.087
18,CohereLabs/aya-expanse-8b,gptq,Swahili,2-bit,0.098,0.384,0.138,0.021,0.080
19,CohereLabs/aya-expanse-8b,gptq,Chinese,2-bit,0.075,0.269,0.121,0.112,0.018
20,CohereLabs/aya-expanse-8b,slimllm,English,2-bit,0.063,0.689,0.340,0.212,0.162
21,CohereLabs/aya-expanse-8b,slimllm,Indonesian,2-bit,0.084,0.719,0.047,0.205,0.256
22,CohereLabs/aya-expanse-8b,slimllm,Swahili,2-bit,0.350,1.365,0.390,0.090,0.645
23,CohereLabs/aya-expanse-8b,slimllm,Chinese,2-bit,0.765,0.926,0.096,0.519,0.051
24,CohereLabs/aya-expanse-8b,tacq,English,2-bit,0.003,0.097,0.014,0.147,0.036
25,CohereLabs/aya-expanse-8b,tacq,Tamil,2-bit,0.013,0.003,0.041,0.034,0.019
26,CohereLabs/aya-expanse-8b,tacq,Indonesian,2-bit,0.006,0.030,0.021,0.120,0.054
27,CohereLabs/aya-expanse-8b,tacq,Swahili,2-bit,0.016,0.019,0.013,0.027,0.010
28,CohereLabs/aya-expanse-8b,tacq,Chinese,2-bit,0.018,0.079,0.060,0.137,0.003

       eng_Latn  tam_Taml  ind_Latn  swh_Latn  cmn_Hans
count    29.000    29.000    29.000    29.000    29.000
mean      0.127     0.300     0.127     0.142     0.156
std       0.192     0.360     0.127     0.130     0.210
min       0.003     0.003     0.008     0.001     0.003
25%       0.015     0.043     0.041     0.040     0.023
50%       0.042     0.097     0.091     0.093     0.080
75%       0.098     0.625     0.174     0.205     0.162
max       0.765     1.365     0.520     0.519     0.895

eng_Latn: direct statistics

count   6.000
mean    0.037
std     0.038
min     0.003
25%     0.011
50%     0.024
75%     0.054
max     0.100
Name: eng_Latn, dtype: float64

eng_Latn: cross statistics

count   23.000
mean     0.151
std      0.210
min      0.006
25%      0.016
50%      0.049
75%      0.224
max      0.765
Name: eng_Latn, dtype: float64

tam_Taml: direct statistics

count   5.000
mean    0.025
std     0.023
min     0.003
25%     0.003
50%     0.024
75%     0.038
max     0.056
Name: tam_Taml, dtype: float64

tam_Taml: cross statistics

count   24.000
mean     0.357
std      0.372
min      0.019
25%      0.079
50%      0.179
75%      0.640
max      1.365
Name: tam_Taml, dtype: float64

ind_Latn: direct statistics

count   6.000
mean    0.156
std     0.203
min     0.008
25%     0.028
50%     0.057
75%     0.223
max     0.520
Name: ind_Latn, dtype: float64

ind_Latn: cross statistics

count   23.000
mean     0.119
std      0.104
min      0.013
25%      0.043
50%      0.096
75%      0.156
max      0.390
Name: ind_Latn, dtype: float64

swh_Latn: direct statistics

count   6.000
mean    0.087
std     0.101
min     0.021
25%     0.023
50%     0.054
75%     0.088
max     0.283
Name: swh_Latn, dtype: float64

swh_Latn: cross statistics

count   23.000
mean     0.157
std      0.135
min      0.001
25%      0.069
50%      0.120
75%      0.206
max      0.519
Name: swh_Latn, dtype: float64

cmn_Hans: direct statistics

count   6.000
mean    0.049
std     0.048
min     0.003
25%     0.014
50%     0.035
75%     0.077
max     0.125
Name: cmn_Hans, dtype: float64

cmn_Hans: cross statistics

count   23.000
mean     0.184
std      0.228
min      0.008
25%      0.037
50%      0.081
75%      0.293
max      0.895
Name: cmn_Hans, dtype: float64

0       5.126
1    5859.364
2       5.249
3       8.937
4       1.412
0       8.736
1    5994.001
2      17.328
3      49.370
4      63.205
0      84.464
1   86417.678
2      11.670
3      11.382
4    3265.238
0      24.397
1     621.285
2     106.496
3   49523.481
0       1.750
1      76.982
2      21.588
3      17.722
4       5.820
0       4.884
1      43.654
2       2.629
3      17.437
4      20.843
Name: Cross over Direct, dtype: float64

count      29.000
mean     5251.453
std     18128.686
min         1.412
25%         8.736
50%        20.843
75%        84.464
max     86417.678
Name: Cross over Direct, dtype: float64

count     29.000
mean      97.643
std      291.155
min        0.010
25%        0.387
50%        8.992
75%       37.524
max     1521.219
Name: Target, dtype: float64

count       29.000
mean     30086.603
std     129291.113
min          0.559
25%          8.075
50%       1066.372
75%       2148.070
max     687490.834
Name: Mean Non Target, dtype: float64

##### Stats pool model

In [ ]:
def perplexity_aggresive_target_not_pool_model(eval_languages, runs, base_model, quantization_technique, bit_width, eval_dataset, custom_title="", filter_result='', hf_evaluate=False, compare_std=False, gmean_aggregate=False):
  language_sort = {
      # Flores Plus
      "eng_Latn": 0, "fra_Latn": 1, "hin_Deva": 2, "npi_Deva": 3, "tam_Taml": 6, "tel_Telu": 7, "ind_Latn": 8, "zsm_Latn": 9, "swh_Latn": 10, "yor_Latn": 11, "cmn_Hans": 12, "jpn_Jpan": 13, "kor_Hang": 14, "arb_Arab" : 15,\
      # Wikipedia
      "en": 0, "fr": 1, "hi": 2, "ne": 3, "ta": 6, "te": 7, "id": 8, "ms": 9, "sw": 10, "yo": 11, "zh": 12, "ja": 13, "ko": 14, "ar": 15,\
      # INCLUDE
      "french": 1, "hindi": 2, "nepali": 3, "albanian": 4, "tamil": 6, "telugu": 7, "indonesian": 8, "malay": 9, "chinese": 12, "japanese": 13, "korean": 14, "arabic": 15,\
      # Global MMLU Lite
      "en": 0, "fr": 1, "hi": 2, "bn": 5, "id": 8, "sw": 10, "yo": 11, "zh": 12, "ja": 13, "ko": 14, "ar": 15,
  }
  flores_plus_add = ["afr_Latn", "dan_Latn", "deu_Latn", "eng_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"]
  for index, lang in enumerate(flores_plus_add):
    language_sort[lang] = 0 + index / 100
  flores_plus_add = ["kan_Knda", "mal_Mlym", "tam_Taml", "tel_Telu"]
  for index, lang in enumerate(flores_plus_add):
    language_sort[lang] = 6 + index / 100
  #flores_plus_add = ["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "ind_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"]
  flores_plus_add = ["ind_Latn", "zsm_Latn", "bjn_Latn", "min_Latn", "ace_Latn", "ban_Latn", "bug_Latn", "jav_Latn", "sun_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "fil_Latn", "war_Latn"]
  for index, lang in enumerate(flores_plus_add):
    language_sort[lang] = 8 + index / 100
  flores_plus_add = ["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "swh_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"]
  for index, lang in enumerate(flores_plus_add):
    language_sort[lang] = 10 + index / 100
  flores_plus_add = ["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant", "cmn_Hans"]
  for index, lang in enumerate(flores_plus_add):
    language_sort[lang] = 12 + index / 100
  eval_languages = list(sorted(eval_languages, key=lambda x: language_sort.get(x, 100)))

  calib_mapper = {
      "English": "eng_Latn" if eval_dataset.lower() == "floresplus" else "en",
      "Indonesian": "ind_Latn" if eval_dataset.lower() == "floresplus" else "id",
      "Tamil": "tam_Taml" if eval_dataset.lower() == "floresplus" else "ta",
      "Swahili": "swh_Latn" if eval_dataset.lower() == "floresplus" else "sw",
      "Chinese": "cmn_Hans" if eval_dataset.lower() == "floresplus" else "zh",
  }

  columns = ["Base Model", "Quantization Technique", "Bit Width", "Calibration Language"]
  columns.extend(eval_languages)
  custom_sort = {'Unquantized': 0, 'English': 1, 'Tamil': 2, 'Indonesian': 3, 'Swahili': 4, 'Chinese': 5,\
                 'Unquantized': 0, 'gptq': 1, 'slimllm': 2, 'tacq': 3,\
                 '32-bit': 0, '2-bit': 1, '3-bit': 2, '4-bit': 3, '8-bit': 4}

  data_acc = []
  data_nancount = []

  unquantized_data_acc = []


  # Iterate over the runs and print details
  for run in runs:
      config = run.config
      summary = run.summary

      if config["calibration_language"] == "WuuChinese":
        continue

      run_data_acc = []
      run_data_nancount = []
      run_data_acc.extend([run.config["base_model"], config["quantization_technique"], config["bit_width"], config["calibration_language"]])
      run_data_nancount.extend([run.config["base_model"], config["quantization_technique"], config["bit_width"], config["calibration_language"]])
      if not hf_evaluate:
        for lang in eval_languages:
          if lang in ["zh", "Chinese", "cmn_Hans", "ja", "Japanese", "jpn_Jpan"]:
            acc = run.summary.get(f"{eval_dataset.lower()}_byte_acc_{lang}", None)
            nancount = run.summary.get(f"{eval_dataset.lower()}_count_nan_count_{lang}", 0)
            if acc:
              # acc = math.pow(acc, 1/3)
              pass
            run_data_acc.append(acc)
            run_data_nancount.append(nancount)
          else:
            run_data_acc.append(run.summary.get(f"{eval_dataset.lower()}_word_acc_{lang}", None))
            run_data_nancount.append(run.summary.get(f"{eval_dataset.lower()}_nan_count_{lang}", 0))
      elif hf_evaluate:
        for lang in eval_languages:
          if gmean_aggregate:
            run_data_acc.append(run.summary.get(f"{eval_dataset.lower()}_gmean_perplexity_{lang}", None))
          else:
            run_data_acc.append(run.summary.get(f"{eval_dataset.lower()}_token_perplexity_{lang}", None))
          run_data_nancount.append(run.summary.get(f"{eval_dataset.lower()}_nancount_{lang}", 0))

      if config["quantization_technique"] == "Unquantized":
        unquantized_data_acc.append(run_data_acc)
        data_nancount.append(run_data_nancount)
      else:
        data_acc.append(run_data_acc)
        data_nancount.append(run_data_nancount)


  import numpy as np
  df_unquantized_acc = pd.DataFrame(unquantized_data_acc, columns=columns)
  df_unquantized_acc_chief_std = df_unquantized_acc.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std")

  df_acc = pd.DataFrame(data_acc, columns=columns).sort_values(by=['Quantization Technique', 'Calibration Language', 'Bit Width'], key=lambda x: x.map(custom_sort))
  df_acc_std = df_acc.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("std", ddof=0).sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  df_acc = df_acc.groupby(['Base Model', 'Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("mean").sort_values(by=['Base Model', 'Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))

  df_acc[df_acc.columns[4:]] = df_acc[df_acc.columns[4:]].astype(float)
  df_unquantized_acc[df_unquantized_acc.columns[4:]] = df_unquantized_acc[df_unquantized_acc.columns[4:]].astype(float)

  pd.set_option('display.float_format','{:.1f}'.format)
  # display(df_unquantized_acc)

  # # Perplexity related, change order of PPL
  # df_acc.iloc[:, 5:] = df_acc.iloc[:, 5:].apply(np.log10)
  # df_unquantized_acc.iloc[:, 5:] = df_unquantized_acc.iloc[:, 5:].apply(np.log10)

  calibration_languages = df_acc["Calibration Language"].unique()
  quants = df_acc["Quantization Technique"].unique()
  base_models = df_acc["Base Model"].unique()
  bits = df_acc["Bit Width"].unique()

  flag = True
  df = pd.DataFrame(data=[], columns=["Base Model", "Quantization Technique", "Bit Width", "Calibration Language", "Target", "Mean Non Target",
                                      "Direct over Unquantized", "Cross over Unquantized", "Direct over Default", "Cross over Default", "Direct over Cross", "Cross over Direct"])
  for quant in quants:
    for bit in bits:
      for base_model in base_models:
        df_filter_uq = df_unquantized_acc[df_unquantized_acc["Base Model"] == base_model]
        df_filter = df_acc_std.loc[df_acc_std["Quantization Technique"] == quant][df_acc_std["Bit Width"] == bit][df_acc_std["Base Model"] == base_model] if compare_std else df_acc.loc[df_acc["Quantization Technique"] == quant][df_acc["Bit Width"] == bit][df_acc["Base Model"] == base_model]
        mean_ppl = df_filter.iloc[:, 4:].prod(axis=0)
        default_ppl = df_filter[df_filter["Calibration Language"] == "English"].iloc[0, 4:]
        count_ppl = df_filter.iloc[:, 4:].count(axis=0)
        df_filter = df_filter.reset_index(drop=True)
        if (quant, base_model) == ("slimllm", "CohereLabs/aya-expanse-8b"):
          mean_ppl = mean_ppl.drop(calib_mapper["Tamil"], axis=0)
          default_ppl = default_ppl.drop(calib_mapper["Tamil"], axis=0)
          count_ppl = count_ppl.drop(calib_mapper["Tamil"], axis=0)
          df_filter_uq = df_filter_uq.drop(calib_mapper["Tamil"], axis=1)

        df_filter.loc[:, "Target"] = pd.Series([df_filter.loc[i, calib_mapper[calib]] for i, calib in enumerate(df_filter["Calibration Language"].unique())])
        df_filter.loc[:, "Mean Non Target"] = (mean_ppl.values / df_filter["Target"].values) ** (1/(count_ppl.values - 1))
        # df_filter.loc[:, "Power Ratio"] = (10 ** df_filter["Mean Non Target"].values / 10 ** df_filter["Target"].values)

        # [0, x:] index is transforming from 2D (df) to 1D array (series)
        # This will broke if Unquantized have more than 1 instance
        df_filter.loc[:, "Direct over Unquantized"] = (df_filter["Target"].values / df_filter_uq.iloc[0, 4:].values) * 100
        df_filter.loc[:, "Cross over Unquantized"] = (df_filter["Mean Non Target"].values / df_filter_uq.iloc[0, 4:].values) * 100
        df_filter.loc[:, "Direct over Default"] = ((default_ppl.values - df_filter["Target"].values) / default_ppl.values) *100
        df_filter.loc[:, "Cross over Default"] = ((default_ppl.values - df_filter["Mean Non Target"].values) / default_ppl.values) * 100
        # df_filter.loc[:, "Direct over Cross"] = (df_filter["Target"].values / df_filter["Mean Non Target"].values) * 100
        df_filter.loc[:, "Direct over Cross"] = (df_filter["Target"].values / df_filter["Mean Non Target"].values)
        df_filter.loc[:, "Cross over Direct"] = (df_filter["Mean Non Target"].values / df_filter["Target"].values)
        # df_filter.drop(df_filter.columns[5:].drop(["Target", "Mean Non Target"]), axis=1)
        # if flag:
        #   print(quant, bit, base_model)
        #   display(df_filter["Target"])
        #   display(default_ppl)
        #   display(df_filter.loc[:, "Direct over Default"])
        #   flag = False
        df = pd.concat([df, df_filter], axis=0)
        print(f"Finished processing {base_model}, {quant}, {bit}")

  # Sort align with the tabular data
  custom_sort = {'Unquantized': 0, 'English': 1, 'Tamil': 2, 'Indonesian': 3, 'Swahili': 4, 'Chinese': 5,\
                  'Unquantized': 0, 'gptq': 1, 'slimllm': 2, 'tacq': 3,\
                  '32-bit': 0, '8-bit': 1, '4-bit': 2, '3-bit': 3, '2-bit': 4,\
                  'Qwen/Qwen3-8B': 0, 'CohereLabs/aya-expanse-8b': 1, 'meta-llama/Llama-3.1-8B-Instruct': 2,}
  df = df.sort_values(by=['Quantization Technique', 'Bit Width', 'Base Model', 'Calibration Language'], key=lambda x: x.map(custom_sort))

  pd.set_option('display.float_format','{:.3f}'.format)
  # pd.set_option('display.float_format','{:.1e}'.format)
  pd.set_option('display.max_rows', 500)
  if filter_result:
    display(df.loc[df['Calibration Language'] == filter_result, :])
  else:
    pd.set_option('display.float_format','{:.3f}'.format)
    display(df_unquantized_acc)
    pd.set_option('display.float_format','{:.3f}'.format)
    # pd.set_option('display.float_format','{:.1e}'.format)
    display(df)

  # for calib in calibration_languages:
  #   print(f"{compare_std=}: {calib}")
  #   display(df["Cross over Direct"][df["Calibration Language"] == calib])
  #   display(df["Cross over Direct"][df["Calibration Language"] == calib].describe())

  print("Coefficient of Variations")
  cov_std = df_acc_std.drop("Base Model", axis=1).groupby(['Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("mean").sort_values(by=['Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  cov_acc = df_acc.drop("Base Model", axis=1).groupby(['Quantization Technique', 'Calibration Language', 'Bit Width'], as_index=False).agg("mean").sort_values(by=['Quantization Technique', 'Calibration Language'], key=lambda x: x.map(custom_sort))
  cov = (cov_std.iloc[:, 3:] / cov_acc.iloc[:, 3:]).rename(df_acc["Quantization Technique"] + '-' + df_acc["Calibration Language"])
  display(cov)
  display(cov.describe())

  display(df["Cross over Direct"])
  display(df["Cross over Direct"].describe())
  if compare_std:
    display(df["Target"].describe())
    display(df["Mean Non Target"].describe())

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialize the W&B API
api = Api()

# eval_languages = ["arb_Arab", "eng_Latn", "cmn_Hans", "hin_Deva", "fra_Latn", "jpn_Jpan", "zsm_Latn", "kor_Hang", "tam_Taml", "ind_Latn", "swh_Latn", "tel_Telu", "npi_Deva", "yor_Latn"]
quantization_technique = "ALL"
bit_width = 8
evaluation_dataset = "floresplus"
# base_model = "Qwen/Qwen3-8B"
base_model = "All"

# for base_model in ["Qwen/Qwen3-8B", "meta-llama/Llama-3.1-8B-Instruct", "CohereLabs/aya-expanse-8b"]:
for bit_width in [2]:
  runs = api.runs(path=f"{ENTITY}/{PROJECT}",
                  filters={"$or": [
                          { "$and": [
                            # {"config.quantization_technique": quantization_technique.lower()},
                            {"config.bit_width": f"{bit_width}-bit"},
                            {"config.num_calibration_samples": 128},
                            # {"config.evaluation_dataset": evaluation_dataset},
                            {"$or": [
                              {"config.evaluation_dataset": f"floresplus-evaluate"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-1000"},
                              {"config.evaluation_dataset": f"floresplus-evaluate-2000"},
                            ]},
                            # {"config.base_model": "Qwen/Qwen3-8B"},
                            {"config.enable_thinking": False},
                            {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                            {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                            {"$not": {"$and": [{"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}, {"config.quantization_technique": "slimllm"}, {"config.calibration_language": "Tamil"}]}}
                          ]
                          },
                          { "$and" : [
                              {"config.quantization_technique": "Unquantized"},
                              # {"config.evaluation_dataset": evaluation_dataset},
                              {"config.evaluation_dataset": f"{evaluation_dataset}-evaluate"},
                              # {"config.base_model": "Qwen/Qwen3-8B"},
                            {"$not":  {"config.base_model": "meta-llama/Llama-3.1-8B-Instruct"}},
                            # {"$not":  {"config.base_model": "CohereLabs/aya-expanse-8b"}},
                              {"config.enable_thinking": False},
                              {"config.output_type": "perplexity"},
                            {"created_at": {"$gt": '2026-01-15'}},
                            {"created_at": {"$lt": '2026-07-01'}},
                          ]}
                      ]}
                  )

  eval_languages = ["eng_Latn", "cmn_Hans", "tam_Taml", "ind_Latn", "swh_Latn"]
  # eval_languages.extend(["afr_Latn", "dan_Latn", "deu_Latn", "fao_Latn", "isl_Latn", "lim_Latn", "ltz_Latn", "nld_Latn", "nno_Latn", "nob_Latn", "swe_Latn", "tpi_Latn", "ydd_Hebr"])
  # eval_languages.extend(["kan_Knda", "mal_Mlym", "tel_Telu"])
  # eval_languages.extend(["ace_Latn", "ban_Latn", "bjn_Latn", "bug_Latn", "ceb_Latn", "fij_Latn", "ilo_Latn", "jav_Latn", "min_Latn", "plt_Latn", "mri_Latn", "pag_Latn", "smo_Latn", "sun_Latn", "fil_Latn", "war_Latn", "zsm_Latn"])
  # eval_languages.extend(["bem_Latn", "cjk_Latn", "ibo_Latn", "kam_Latn", "kik_Latn", "kin_Latn", "kmb_Latn", "ktu_Latn", "lin_Latn", "lua_Latn", "lug_Latn", "nso_Latn", "nya_Latn", "run_Latn", "sna_Latn", "sot_Latn", "ssw_Latn", "tsn_Latn", "tso_Latn", "tum_Latn", "umb_Latn", "xho_Latn", "yor_Latn", "zul_Latn"])
  # eval_languages.extend(["bod_Tibt", "dzo_Tibt", "kac_Latn", "lus_Latn", "mni_Beng", "mya_Mymr", "yue_Hant"])

  # perplexity_heatmap_deliver_vertical(eval_languages, runs, ["Qwen/Qwen3-8B", "CohereLabs/aya-expanse-8b", "meta-llama/Llama-3.1-8B-Instruct"], quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", display_mean=False, compile=False, show_subline=True, hf_evaluate=True, zscore_threshold=1/2, gmean_aggregate=False)
  perplexity_aggresive_target_not_pool_model(eval_languages, runs, "", quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", hf_evaluate=True, gmean_aggregate=True)
  # perplexity_aggresive_target_not(eval_languages, runs, "", quantization_technique, bit_width, evaluation_dataset, custom_title="All-PPL", hf_evaluate=True, gmean_aggregate=True, compare_std=True)

Finished processing CohereLabs/aya-expanse-8b, gptq, 2-bit
Finished processing Qwen/Qwen3-8B, gptq, 2-bit
Finished processing CohereLabs/aya-expanse-8b, slimllm, 2-bit
Finished processing Qwen/Qwen3-8B, slimllm, 2-bit
Finished processing CohereLabs/aya-expanse-8b, tacq, 2-bit
Finished processing Qwen/Qwen3-8B, tacq, 2-bit

/tmp/ipykernel_12153/1680869954.py:121: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

/tmp/ipykernel_12153/1680869954.py:121: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

/tmp/ipykernel_12153/1680869954.py:152: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/tmp/ipykernel_12153/1680869954.py:121: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

/tmp/ipykernel_12153/1680869954.py:121: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

/tmp/ipykernel_12153/1680869954.py:121: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

/tmp/ipykernel_12153/1680869954.py:121: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

/tmp/ipykernel_12153/1680869954.py:121: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

/tmp/ipykernel_12153/1680869954.py:121: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

/tmp/ipykernel_12153/1680869954.py:121: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

/tmp/ipykernel_12153/1680869954.py:121: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

/tmp/ipykernel_12153/1680869954.py:121: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

/tmp/ipykernel_12153/1680869954.py:121: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

,Base Model,Quantization Technique,Bit Width,Calibration Language,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,Unquantized,32-bit,Unquantized,33.429,2.742,16.699,64.535,46.981
1,CohereLabs/aya-expanse-8b,Unquantized,32-bit,Unquantized,53.755,3.798,92.363,347.245,112.084

,Base Model,Quantization Technique,Bit Width,Calibration Language,Target,Mean Non Target,Direct over Unquantized,Cross over Unquantized,Direct over Default,Cross over Default,Direct over Cross,Cross over Direct,eng_Latn,tam_Taml,ind_Latn,swh_Latn,cmn_Hans
0,Qwen/Qwen3-8B,gptq,2-bit,English,12827.902,38022.199,38373.920,113741.192,0.000,-196.402,0.337,2.964,12827.902,45940.807,39236.778,40398.302,39491.466
1,Qwen/Qwen3-8B,gptq,2-bit,Tamil,7.469,33666.480,272.430,1227984.338,99.984,26.718,0.000,4507.526,43858.254,7.469,46203.200,46825.504,34007.537
2,Qwen/Qwen3-8B,gptq,2-bit,Indonesian,1683.806,41260.315,10083.272,247082.435,95.709,-5.157,0.041,24.504,35069.945,32266.297,1683.806,34796.007,42150.094
3,Qwen/Qwen3-8B,gptq,2-bit,Swahili,1466.964,40627.737,2273.142,62954.924,96.369,-0.568,0.036,27.695,44051.236,37346.013,41954.948,1466.964,25431.656
4,Qwen/Qwen3-8B,gptq,2-bit,Chinese,17781.025,34638.805,37847.424,73729.696,54.975,12.288,0.513,1.948,30846.395,23205.924,38104.965,41391.916,17781.025
0,CohereLabs/aya-expanse-8b,gptq,2-bit,English,241.836,754.221,449.887,1403.073,0.000,-211.873,0.321,3.119,241.836,22325.499,6090.955,22225.968,19168.145
1,CohereLabs/aya-expanse-8b,gptq,2-bit,Tamil,6.436,4939.166,169.450,130035.052,99.971,77.877,0.001,767.394,745.679,6.436,6473.672,21938.559,9278.961
2,CohereLabs/aya-expanse-8b,gptq,2-bit,Indonesian,545.812,5693.192,590.940,6163.915,91.039,6.530,0.096,10.431,522.582,4200.198,545.812,14221.137,9950.510
3,CohereLabs/aya-expanse-8b,gptq,2-bit,Swahili,1591.608,19500.949,458.353,5615.900,92.839,12.261,0.082,12.252,824.976,1501.481,4321.038,1591.608,14767.553
4,CohereLabs/aya-expanse-8b,gptq,2-bit,Chinese,1029.857,12714.765,918.824,11343.938,94.627,33.667,0.081,12.346,1006.575,4226.914,6165.939,20855.464,1029.857
0,Qwen/Qwen3-8B,slimllm,2-bit,English,151.575,3039.980,453.426,9093.923,0.000,-1905.600,0.050,20.056,151.575,14768.033,2493.904,6726.278,667418.912
1,Qwen/Qwen3-8B,slimllm,2-bit,Tamil,4.443,12923.369,162.056,471379.682,99.970,12.491,0.000,2908.754,6890.434,4.443,11464.606,6525.812,60166.327
2,Qwen/Qwen3-8B,slimllm,2-bit,Indonesian,123.248,4402.051,738.057,26361.152,95.058,-76.512,0.028,35.717,1077.302,12007.141,123.248,2713.585,411364.223
3,Qwen/Qwen3-8B,slimllm,2-bit,Swahili,539.807,6918.330,836.460,10720.334,91.975,-2.855,0.078,12.816,2003.619,6139.446,701.292,539.807,627831.336
4,Qwen/Qwen3-8B,slimllm,2-bit,Chinese,360.020,319120.996,766.314,679258.244,99.946,52.186,0.001,886.397,5742.270,25621.911,18727.617,19233.229,360.020
0,CohereLabs/aya-expanse-8b,slimllm,2-bit,English,136.696,746.294,254.296,1388.327,0.000,-445.950,0.183,5.460,136.696,411021.091,47666.033,9978.332,7409755.211
1,CohereLabs/aya-expanse-8b,slimllm,2-bit,Indonesian,232.826,28897.988,252.076,31287.322,99.512,39.374,0.008,124.119,268.801,449010.693,232.826,5561.333,1631136.553
2,CohereLabs/aya-expanse-8b,slimllm,2-bit,Swahili,418.917,14128.558,120.640,4068.754,95.802,-41.592,0.030,33.726,334.556,607135.151,1044.489,418.917,1004870.877
3,CohereLabs/aya-expanse-8b,slimllm,2-bit,Chinese,274.084,2298625.112,244.534,2050801.568,99.996,68.978,0.000,8386.566,4622.002,290134.141,484718.873,50822.574,274.084
0,Qwen/Qwen3-8B,tacq,2-bit,English,43.983,60.192,131.574,180.061,0.000,-36.852,0.731,1.369,43.983,15.514,116.219,380.076,146.704
1,Qwen/Qwen3-8B,tacq,2-bit,Tamil,3.063,11.925,111.733,434.978,80.254,23.130,0.257,3.893,64.370,3.063,72.677,433.096,119.462
2,Qwen/Qwen3-8B,tacq,2-bit,Indonesian,21.818,82.783,130.653,495.737,81.227,28.769,0.264,3.794,52.555,9.956,21.818,258.431,122.105
3,Qwen/Qwen3-8B,tacq,2-bit,Swahili,69.237,354.857,107.286,549.870,81.784,6.635,0.195,5.125,65.558,9.945,43.733,69.237,176.319
4,Qwen/Qwen3-8B,tacq,2-bit,Chinese,63.072,139.372,134.251,296.658,57.007,4.998,0.453,2.210,59.188,13.167,127.140,372.747,63.072
0,CohereLabs/aya-expanse-8b,tacq,2-bit,English,69.142,89.122,128.624,165.794,0.000,-28.898,0.776,1.289,69.142,14.740,306.205,1588.158,360.637
1,CohereLabs/aya-expanse-8b,tacq,2-bit,Tamil,4.050,12.295,106.619,323.706,72.524,16.582,0.329,3.036,93.206,4.050,225.322,1544.972,275.617
2,CohereLabs/aya-expanse-8b,tacq,2-bit,Indonesian,117.138,253.855,126.823,274.844,61.745,17.096,0.461,2.167,80.995,12.201,117.138,1344.703,292.761
3,CohereLabs/aya-expanse-8b,tacq,2-bit,Swahili,332.043,1647.960,95.622,474.581,79.093,-3.765,0.201,4.963,97.276,10.232,202.212,332.043,406.132
4,CohereLabs/aya-expanse-8b,tacq,2-bit,Chinese,135.838,329.715,121.193,294.168,62.334,8.574,0.412,2.427,85.909,12.421,297.659,2235.354,135.838

Coefficient of Variations

                    eng_Latn  tam_Taml  ind_Latn  swh_Latn  cmn_Hans
gptq-English           0.021     0.152     0.031     0.045     0.100
gptq-Tamil             0.072     0.047     0.120     0.030     0.322
gptq-Indonesian        0.042     0.124     0.224     0.089     0.051
gptq-Swahili           0.038     0.054     0.059     0.050     0.035
gptq-Chinese           0.018     0.107     0.121     0.137     0.082
slimllm-English        0.083     0.687     0.331     0.182     0.181
tacq-Chinese           0.375     0.024     0.190     0.206     0.383
slimllm-Indonesian     0.441     0.724     0.211     0.287     0.271
slimllm-Swahili        0.398     1.358     0.270     0.199     0.741
slimllm-Chinese        0.560     0.902     0.103     0.463     0.093
tacq-Indonesian        0.005     0.069     0.019     0.124     0.032
gptq-Chinese           0.010     0.003     0.078     0.099     0.019
tacq-Swahili           0.008     0.053     0.019     0.116     0.050
tacq-Tamil             0.012     0.034     0.013     0.026     0.024
tacq-English           0.017     0.099     0.055     0.123     0.006

       eng_Latn  tam_Taml  ind_Latn  swh_Latn  cmn_Hans
count    15.000    15.000    15.000    15.000    15.000
mean      0.140     0.296     0.123     0.145     0.159
std       0.194     0.415     0.100     0.114     0.200
min       0.005     0.003     0.013     0.026     0.006
25%       0.014     0.050     0.043     0.070     0.033
50%       0.038     0.099     0.103     0.123     0.082
75%       0.229     0.420     0.200     0.190     0.226
max       0.560     1.358     0.331     0.463     0.741

0      2.964
1   4507.526
2     24.504
3     27.695
4      1.948
0      3.119
1    767.394
2     10.431
3     12.252
4     12.346
0     20.056
1   2908.754
2     35.717
3     12.816
4    886.397
0      5.460
1    124.119
2     33.726
3   8386.566
0      1.369
1      3.893
2      3.794
3      5.125
4      2.210
0      1.289
1      3.036
2      2.167
3      4.963
4      2.427
Name: Cross over Direct, dtype: float64

count     29.000
mean     614.278
std     1788.508
min        1.289
25%        3.036
50%       10.431
75%       33.726
max     8386.566
Name: Cross over Direct, dtype: float64